name: Setup Node
description: Sets up Node.js with a specific version

inputs:
  node_version:
    description: 'The version of Node.js to install'
    required: false
    default: '22.x'

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'
        cache-dependency-path: 'website/package-lock.json'
