name: Install Python Dependencies
description: Install Python dependencies with caching

runs:
  using: "composite"
  steps:
    - name: Cache pip packages
      id: pip-cache
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ runner.os }}-pip-${{ hashFiles('**/base.txt', '**/local.txt', '**/requirements.txt') }}

    - name: Install Python dependencies
      if: steps.pip-cache.outputs.cache-hit != 'true'
      run: |
        cd website
        make pip-install
      shell: bash
