# Generated by Django 5.2.13 on 2026-06-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtaillinkchecker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="running",
                max_length=20,
            ),
        ),
    ]
