# Generated by Django 5.2.13 on 2026-06-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtaillinkchecker", "0002_scan_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanlink",
            name="url",
            field=models.URLField(max_length=1000),
        ),
    ]
