name: Install NPM Dependencies
description: Install NPM dependencies with caching

runs:
  using: "composite"
  steps:
    - name: Cache node modules
      id: node-cache
      uses: actions/cache@v3
      with:
        path: |
          website/node_modules
          ~/.cache/Cypress
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install Node dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: |
        cd website
        make npm-install
