# Generated by Django 5.1.3 on 2025-01-31 18:45

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_alter_page_search_description"),
        ("wagtaildocs", "0014_alter_document_file_size"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("no_index", models.BooleanField(default=False)),
                (
                    "navigation_category",
                    models.TextField(
                        choices=[
                            ("NONE", "None"),
                            ("ABOUT", "About the Court"),
                            ("RULES", "Rules & Guidance"),
                            ("ORDERS", "Orders & Opinions"),
                            ("eFILING", "eFiling & Case Maintenance"),
                        ],
                        default="NONE",
                        max_length=45,
                    ),
                ),
                (
                    "redirectLink",
                    models.CharField(
                        blank=True, help_text="Insert link here.", max_length=250
                    ),
                ),
                (
                    "menu_item_name",
                    models.CharField(
                        default="*NOT SET*",
                        help_text="Enter the name of the page for the navigation bar link.",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Insert text here."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ExternalRedirectPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("no_index", models.BooleanField(default=False)),
                (
                    "navigation_category",
                    models.TextField(
                        choices=[
                            ("NONE", "None"),
                            ("ABOUT", "About the Court"),
                            ("RULES", "Rules & Guidance"),
                            ("ORDERS", "Orders & Opinions"),
                            ("eFILING", "eFiling & Case Maintenance"),
                        ],
                        default="NONE",
                        max_length=45,
                    ),
                ),
                (
                    "redirectLink",
                    models.CharField(
                        blank=True, help_text="Insert link here.", max_length=250
                    ),
                ),
                (
                    "menu_item_name",
                    models.CharField(
                        default="*NOT SET*",
                        help_text="Enter the name of the page for the navigation bar link.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technicalQuestions",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Content for technical questions."
                    ),
                ),
                (
                    "otherQuestions",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Content for other questions."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GoogleAnalyticsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_id",
                    models.CharField(
                        default="G-3T6ZS0FHZ8",
                        help_text="Google Analytics Measurement ID (e.g., G-1234567890)",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("no_index", models.BooleanField(default=False)),
                (
                    "navigation_category",
                    models.TextField(
                        choices=[
                            ("NONE", "None"),
                            ("ABOUT", "About the Court"),
                            ("RULES", "Rules & Guidance"),
                            ("ORDERS", "Orders & Opinions"),
                            ("eFILING", "eFiling & Case Maintenance"),
                        ],
                        default="NONE",
                        max_length=45,
                    ),
                ),
                (
                    "redirectLink",
                    models.CharField(
                        blank=True, help_text="Insert link here.", max_length=250
                    ),
                ),
                (
                    "menu_item_name",
                    models.CharField(
                        default="*NOT SET*",
                        help_text="Enter the name of the page for the navigation bar link.",
                        max_length=255,
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Introduction text for the homepage."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SimpleCardGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_label",
                    models.CharField(
                        blank=True,
                        help_text="Label for this group of cards (e.g., 'Section 1: Featured Cards').",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaseRelatedFormsPage",
            fields=[
                (
                    "standardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.standardpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.standardpage",),
        ),
        migrations.CreateModel(
            name="DawsonPage",
            fields=[
                (
                    "standardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.standardpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.standardpage",),
        ),
        migrations.CreateModel(
            name="PamphletsPage",
            fields=[
                (
                    "standardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.standardpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.standardpage",),
        ),
        migrations.CreateModel(
            name="RemoteProceedingsPage",
            fields=[
                (
                    "standardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.standardpage",
                    ),
                ),
                ("faq_title", models.CharField(max_length=255)),
                ("additional_info", wagtail.fields.RichTextField(blank=True)),
                ("example_title", models.CharField(max_length=255)),
                ("example_body", wagtail.fields.RichTextField(blank=True)),
                ("feedback_form", models.CharField(blank=True, max_length=1000)),
            ],
            options={
                "abstract": False,
            },
            bases=("home.standardpage",),
        ),
        migrations.CreateModel(
            name="HomePageEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", wagtail.fields.RichTextField(blank=True)),
                (
                    "homepage",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="home.homepage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimpleCards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_title",
                    models.CharField(
                        blank="True",
                        help_text="The title to appear at the top of the card",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "card_icon",
                    models.CharField(
                        blank="True",
                        help_text='Icon Name - see https://tabler.io/icons and enter the name of the icon (i.e. "accessible")',
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "parent_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="home.simplecardgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RelatedPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "related_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="home.standardpage",
                    ),
                ),
                (
                    "card",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_pages",
                        to="home.simplecards",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseRelatedFormsEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("formName", models.CharField(max_length=255)),
                ("number", models.CharField(blank=True, max_length=255)),
                ("formNameNote", models.CharField(blank=True, max_length=255)),
                ("eligibleForEFilingByPetitioners", models.CharField(max_length=255)),
                ("eligibleForEFilingByPractitioners", models.CharField(max_length=255)),
                (
                    "pdf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                    ),
                ),
                (
                    "parentpage",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="home.caserelatedformspage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CitationStyleManualPage",
            fields=[
                (
                    "standardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.standardpage",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.standardpage",),
        ),
        migrations.AddField(
            model_name="simplecardgroup",
            name="parent_page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_groups",
                to="home.dawsonpage",
            ),
        ),
        migrations.CreateModel(
            name="PhotoDedication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the title for the dedication", max_length=255
                    ),
                ),
                (
                    "paragraph_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Add the main paragraph text for the dedication section",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Upload an image to display with this dedication",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "card",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_dedication",
                        to="home.dawsonpage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FancyCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank="True",
                        help_text="The URL to link to when the photo is clicked.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank="True",
                        help_text="The text to appear next to the image in the light blue card.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Upload an image to display with in dark blue card.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "parent_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fancy_card",
                        to="home.dawsonpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PamphletEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=255)),
                ("date_range", models.CharField(max_length=255)),
                ("citation", wagtail.fields.RichTextField(blank=True)),
                ("volume_number", models.FloatField(default=0)),
                (
                    "pdf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                    ),
                ),
                (
                    "parentpage",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="home.pamphletspage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RemoteProceedingsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                    ),
                ),
                (
                    "parentpage",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info",
                        to="home.remoteproceedingspage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RemoteProceedingsFAQLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=1000)),
                (
                    "parentpage",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq_links",
                        to="home.remoteproceedingspage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RemoteProceedingsExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("speaker_title", models.CharField(max_length=255)),
                ("speaker_url", models.CharField(max_length=1000)),
                ("gallery_title", models.CharField(max_length=255)),
                ("gallery_url", models.CharField(max_length=1000)),
                (
                    "parentpage",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="home.remoteproceedingspage",
                    ),
                ),
            ],
        ),
    ]
