# Generated by Django 5.1.3 on 2025-01-21 22:26

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_alter_page_search_description"),
        ("wagtaildocs", "0014_alter_document_file_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("no_index", models.BooleanField(default=False)),
                (
                    "navigation_category",
                    models.TextField(
                        choices=[
                            ("NONE", "None"),
                            ("ABOUT", "About the Court"),
                            ("RULES", "Rules & Guidance"),
                            ("ORDERS", "Orders & Opinions"),
                            ("eFILING", "eFiling & Case Maintenance"),
                        ],
                        default="NONE",
                        max_length=45,
                    ),
                ),
                (
                    "redirectLink",
                    models.CharField(
                        blank=True, help_text="Insert link here.", max_length=250
                    ),
                ),
                (
                    "menu_item_name",
                    models.CharField(
                        default="*NOT SET*",
                        help_text="Enter the name of the page for the navigation bar link.",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Insert text here."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ExternalRedirectPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("no_index", models.BooleanField(default=False)),
                (
                    "navigation_category",
                    models.TextField(
                        choices=[
                            ("NONE", "None"),
                            ("ABOUT", "About the Court"),
                            ("RULES", "Rules & Guidance"),
                            ("ORDERS", "Orders & Opinions"),
                            ("eFILING", "eFiling & Case Maintenance"),
                        ],
                        default="NONE",
                        max_length=45,
                    ),
                ),
                (
                    "redirectLink",
                    models.CharField(
                        blank=True, help_text="Insert link here.", max_length=250
                    ),
                ),
                (
                    "menu_item_name",
                    models.CharField(
                        default="*NOT SET*",
                        help_text="Enter the name of the page for the navigation bar link.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technicalQuestions",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Content for technical questions."
                    ),
                ),
                (
                    "otherQuestions",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Content for other questions."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GoogleAnalyticsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_id",
                    models.CharField(
                        default="G-3T6ZS0FHZ8",
                        help_text="Google Analytics Measurement ID (e.g., G-1234567890)",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("no_index", models.BooleanField(default=False)),
                (
                    "navigation_category",
                    models.TextField(
                        choices=[
                            ("NONE", "None"),
                            ("ABOUT", "About the Court"),
                            ("RULES", "Rules & Guidance"),
                            ("ORDERS", "Orders & Opinions"),
                            ("eFILING", "eFiling & Case Maintenance"),
                        ],
                        default="NONE",
                        max_length=45,
                    ),
                ),
                (
                    "redirectLink",
                    models.CharField(
                        blank=True, help_text="Insert link here.", max_length=250
                    ),
                ),
                (
                    "menu_item_name",
                    models.CharField(
                        default="*NOT SET*",
                        help_text="Enter the name of the page for the navigation bar link.",
                        max_length=255,
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Introduction text for the homepage."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="CaseRelatedFormsPage",
            fields=[
                (
                    "standardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.standardpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.standardpage",),
        ),
        migrations.CreateModel(
            name="DawsonPage",
            fields=[
                (
                    "standardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.standardpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.standardpage",),
        ),
        migrations.CreateModel(
            name="HomePageEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", wagtail.fields.RichTextField(blank=True)),
                (
                    "homepage",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="home.homepage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseRelatedFormsEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("formName", models.CharField(max_length=255)),
                ("number", models.CharField(blank=True, max_length=255)),
                ("formNameNote", models.CharField(blank=True, max_length=255)),
                ("eligibleForEFilingByPetitioners", models.CharField(max_length=255)),
                ("eligibleForEFilingByPractitioners", models.CharField(max_length=255)),
                (
                    "pdf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                    ),
                ),
                (
                    "parentpage",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="home.caserelatedformspage",
                    ),
                ),
            ],
        ),
    ]
