# Generated by Django 5.1.3 on 2025-01-28 20:22

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_citationstylemanualpage"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoDedication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the title for the dedication", max_length=255
                    ),
                ),
                (
                    "paragraph_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Add the main paragraph text for the dedication section",
                    ),
                ),
                (
                    "card",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_dedication",
                        to="home.dawsonpage",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Upload an image to display with this dedication",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimpleCardGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_label",
                    models.CharField(
                        help_text="Label for this group of cards (e.g., 'Section 1: Featured Cards').",
                        max_length=255,
                    ),
                ),
                (
                    "parent_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_groups",
                        to="home.dawsonpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SimpleCards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_title",
                    models.CharField(
                        blank="True",
                        help_text="The title to appear at the top of the card",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "card_icon",
                    models.CharField(
                        blank="True",
                        help_text='Icon Name - see https://tabler.io/icons and enter the name of the icon (i.e. "accessible")',
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "parent_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="home.simplecardgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RelatedPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "related_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="home.standardpage",
                    ),
                ),
                (
                    "card",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_pages",
                        to="home.simplecards",
                    ),
                ),
            ],
        ),
    ]
