# Generated by Django 5.1.3 on 2025-01-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pamphletspage_pamphletentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pamphletentry',
            name='order',
        ),
        migrations.AddField(
            model_name='pamphletentry',
            name='volume_number',
            field=models.FloatField(default=0),
        ),
    ]
