# Generated by Django 5.1.3 on 2025-01-30 03:05

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_photodedication_simplecardgroup_simplecards_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FancyCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank="True",
                        help_text="The URL to link to when the photo is clicked.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank="True",
                        help_text="The text to appear next to the image in the light blue card.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "parent_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fancy_card",
                        to="home.dawsonpage",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Upload an image to display with in dark blue card.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
