# Generated by Django 5.1.3 on 2025-01-30 22:24

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_pamphletspage_pamphletentry"),
        ("wagtaildocs", "0014_alter_document_file_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteProceedingsPage",
            fields=[
                (
                    "standardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.standardpage",
                    ),
                ),
                ("faq_title", models.CharField(max_length=255)),
                ("additional_info", wagtail.fields.RichTextField(blank=True)),
                ("example_title", models.CharField(max_length=255)),
                ("example_body", wagtail.fields.RichTextField(blank=True)),
                ("feedback_form", models.CharField(blank=True, max_length=1000)),
            ],
            options={
                "abstract": False,
            },
            bases=("home.standardpage",),
        ),
        migrations.CreateModel(
            name="RemoteProceedingsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                    ),
                ),
                (
                    "parentpage",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info",
                        to="home.remoteproceedingspage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RemoteProceedingsFAQLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=1000)),
                (
                    "parentpage",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq_links",
                        to="home.remoteproceedingspage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RemoteProceedingsExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("speaker_title", models.CharField(max_length=255)),
                ("speaker_url", models.CharField(max_length=1000)),
                ("gallery_title", models.CharField(max_length=255)),
                ("gallery_url", models.CharField(max_length=1000)),
                (
                    "parentpage",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="home.remoteproceedingspage",
                    ),
                ),
            ],
        ),
    ]
