# Generated by Django 5.1.3 on 2025-02-06 21:49

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_administrativeorderspage_pdfs"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_title",
                    models.CharField(
                        blank="True",
                        help_text="The title to appear at the top of the card",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "card_icon",
                    models.CharField(
                        blank="True",
                        help_text='Icon Name - see https://fontawesome.com/icons/ and enter the name of the icon (i.e. "accessible")',
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "parent_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="home.simplecardgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="relatedpage",
            name="card",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_pages",
                to="home.simplecard",
            ),
        ),
        migrations.DeleteModel(
            name="SimpleCards",
        ),
    ]
