# Generated by Django 5.1.3 on 2025-02-06 22:37

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_bluenavigationbar_remoteproceedingspage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remoteproceedingsfaqlinks",
            name="parentpage",
        ),
        migrations.RemoveField(
            model_name="remoteproceedingsinfo",
            name="parentpage",
        ),
        migrations.RemoveField(
            model_name="remoteproceedingsinfo",
            name="pdf",
        ),
        migrations.RemoveField(
            model_name="remoteproceedingspage",
            name="standardpage_ptr",
        ),
        migrations.AlterField(
            model_name="bluenavigationbarlink",
            name="icon",
            field=models.CharField(
                choices=[
                    ("", "None"),
                    ("ti ti-info-circle", "Info"),
                    ("ti ti-file-type-pdf", "Pdf"),
                    ("ti ti-book-2", "Book 2"),
                    ("ti ti-building-bank", "Building Bank"),
                    ("ti ti-hammer", "Hammer"),
                    ("ti ti-scale", "Scale"),
                    ("ti ti-calendar-month", "Calendar Month"),
                    ("ti ti-file", "File"),
                    ("ti ti-info-circle-filled", "Info Circle Filled"),
                    ("ti ti-chevron-right", "Chevron Right"),
                    ("ti ti-video-filled", "Video"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("h3", 0),
                    ("h4", 0),
                    ("paragraph", 1),
                    ("hr", 2),
                    ("image", 3),
                    ("links", 10),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.BooleanBlock", (), {}),
                    3: ("wagtail.images.blocks.ImageBlock", [], {}),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ti ti-file-type-pdf", "PDF"),
                                ("ti ti-info-circle-filled", "Info"),
                                ("ti ti-link", "Link"),
                            ]
                        },
                    ),
                    6: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("icon", 5), ("document", 6), ("url", 7)]],
                        {},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 4), ("links", 9)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.DeleteModel(
            name="RemoteProceedingsExample",
        ),
        migrations.DeleteModel(
            name="RemoteProceedingsFAQLinks",
        ),
        migrations.DeleteModel(
            name="RemoteProceedingsInfo",
        ),
        migrations.DeleteModel(
            name="RemoteProceedingsPage",
        ),
    ]
