# Generated by Django 5.1.3 on 2024-12-27 18:31

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_demopage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testpage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="body",
        ),
        migrations.AddField(
            model_name="homepage",
            name="intro",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Introduction text for the homepage."
            ),
        ),
        migrations.CreateModel(
            name="HomePageEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", wagtail.fields.RichTextField(blank=True)),
                (
                    "homepage",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="home.homepage",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DemoPage",
        ),
        migrations.DeleteModel(
            name="TestPage",
        ),
    ]
