# Generated by Django 5.1.3 on 2025-02-04 22:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_remoteproceedingspage_remoteproceedingsinfo_and_more"),
        ("wagtailcore", "0098_alter_page_search_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnhancedStandardPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("no_index", models.BooleanField(default=False)),
                (
                    "navigation_category",
                    models.TextField(
                        choices=[
                            ("NONE", "None"),
                            ("ABOUT", "About the Court"),
                            ("RULES", "Rules & Guidance"),
                            ("ORDERS", "Orders & Opinions"),
                            ("eFILING", "eFiling & Case Maintenance"),
                        ],
                        default="NONE",
                        max_length=45,
                    ),
                ),
                (
                    "redirectLink",
                    models.CharField(
                        blank=True, help_text="Insert link here.", max_length=250
                    ),
                ),
                (
                    "menu_item_name",
                    models.CharField(
                        default="*NOT SET*",
                        help_text="Enter the name of the page for the navigation bar link.",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("paragraph", 1),
                            ("hr", 2),
                            ("image", 3),
                            ("blue_page_links_bar", 7),
                            ("links", 10),
                        ],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: ("wagtail.blocks.BooleanBlock", (), {}),
                            3: ("wagtail.images.blocks.ImageBlock", [], {}),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("ti ti-file-type-pdf", "PDF"),
                                        ("ti ti-info-circle-filled", "Info"),
                                        ("ti ti-link", "Link"),
                                    ]
                                },
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("icon", 4), ("url", 5)]],
                                {},
                            ),
                            7: ("wagtail.blocks.ListBlock", (6,), {"required": False}),
                            8: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("icon", 4),
                                        ("document", 8),
                                        ("url", 5),
                                    ]
                                ],
                                {},
                            ),
                            10: ("wagtail.blocks.ListBlock", (9,), {}),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
