# Generated by Django 5.1.3 on 2025-02-02 04:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_remoteproceedingspage_remoteproceedingsinfo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministrativeOrdersPage",
            fields=[
                (
                    "standardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.standardpage",
                    ),
                ),
                (
                    "pdf_section",
                    wagtail.fields.StreamField(
                        [("pdf_section", 6)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "blank": True,
                                    "help_text": "Optional Section Title",
                                    "null": True,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "An optional descriptive name for the PDF.",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {
                                    "help_text": "Upload or choose an existing PDF.",
                                    "required": True,
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 1), ("pdf_document", 2)]],
                                {},
                            ),
                            4: (
                                "wagtail.blocks.ListBlock",
                                (3,),
                                {
                                    "help_text": "Add one or more PDF documents (drag to reorder)."
                                },
                            ),
                            5: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("asc", "Ascending"),
                                        ("desc", "Descending"),
                                    ],
                                    "help_text": "Optional ordering",
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("section_title", 0), ("pdfs", 4), ("ordering", 5)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.standardpage",),
        ),
    ]
