# Generated by Django 5.1.3 on 2024-12-30 19:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_remove_testpage_page_ptr_remove_homepage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="otherQuestions",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Content for other questions."
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="technicalQuestions",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Content for technical questions."
            ),
        ),
    ]
