# Generated by Django 5.1.3 on 2025-02-07 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_simplecard_alter_relatedpage_card_delete_simplecards"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedirectPage",
            fields=[
                (
                    "standardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.standardpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.standardpage",),
        ),
    ]
