# Generated by Django 5.1.3 on 2024-12-30 20:19

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_homepage_otherquestions_homepage_technicalquestions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technicalQuestions",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Content for technical questions."
                    ),
                ),
                (
                    "otherQuestions",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Content for other questions."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="otherQuestions",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="technicalQuestions",
        ),
    ]
