# Generated by Django 5.1.3 on 2025-02-10 23:54

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_redirectpage"),
        ("wagtailcore", "__latest__"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationRibbon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="remoteproceedingsexample",
            name="parentpage",
        ),
        migrations.RemoveField(
            model_name="remoteproceedingsfaqlinks",
            name="parentpage",
        ),
        migrations.RemoveField(
            model_name="remoteproceedingsinfo",
            name="parentpage",
        ),
        migrations.RemoveField(
            model_name="remoteproceedingsinfo",
            name="pdf",
        ),
        migrations.RemoveField(
            model_name="remoteproceedingspage",
            name="standardpage_ptr",
        ),
        migrations.CreateModel(
            name="EnhancedStandardPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("no_index", models.BooleanField(default=False)),
                (
                    "navigation_category",
                    models.TextField(
                        choices=[
                            ("NONE", "None"),
                            ("ABOUT", "About the Court"),
                            ("RULES", "Rules & Guidance"),
                            ("ORDERS", "Orders & Opinions"),
                            ("eFILING", "eFiling & Case Maintenance"),
                        ],
                        default="NONE",
                        max_length=45,
                    ),
                ),
                (
                    "redirectLink",
                    models.CharField(
                        blank=True, help_text="Insert link here.", max_length=250
                    ),
                ),
                (
                    "menu_item_name",
                    models.CharField(
                        default="*NOT SET*",
                        help_text="Enter the name of the page for the navigation bar link.",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("h3", 0),
                            ("h4", 0),
                            ("paragraph", 1),
                            ("hr", 2),
                            ("image", 3),
                            ("links", 10),
                            ("questionanswers", 12),
                        ],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: ("wagtail.blocks.BooleanBlock", (), {}),
                            3: ("wagtail.images.blocks.ImageBlock", [], {}),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("indented", "indented"),
                                        ("unindented", "unindented"),
                                    ]
                                },
                            ),
                            5: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("ti ti-file-type-pdf", "PDF"),
                                        ("ti ti-info-circle-filled", "Info"),
                                        ("ti ti-link", "Link"),
                                    ]
                                },
                            ),
                            6: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"required": False},
                            ),
                            7: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("icon", 5),
                                        ("document", 6),
                                        ("url", 7),
                                    ]
                                ],
                                {},
                            ),
                            9: ("wagtail.blocks.ListBlock", (8,), {}),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("class", 4), ("links", 9)]],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 7), ("answer", 1)]],
                                {},
                            ),
                            12: ("wagtail.blocks.ListBlock", (11,), {}),
                        },
                    ),
                ),
                (
                    "navigation_ribbon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="home.navigationribbon",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NavigationRibbonLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("", "None"),
                            ("ti ti-info-circle", "Info"),
                            ("ti ti-file-type-pdf", "Pdf"),
                            ("ti ti-book-2", "Book 2"),
                            ("ti ti-building-bank", "Building Bank"),
                            ("ti ti-hammer", "Hammer"),
                            ("ti ti-scale", "Scale"),
                            ("ti ti-calendar-month", "Calendar Month"),
                            ("ti ti-file", "File"),
                            ("ti ti-info-circle-filled", "Info Circle Filled"),
                            ("ti ti-chevron-right", "Chevron Right"),
                            ("ti ti-video-filled", "Video"),
                        ],
                        max_length=200,
                    ),
                ),
                ("url", models.CharField(max_length=1000)),
                (
                    "navigation_ribbon",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="home.navigationribbon",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CitationStyleManualPage",
        ),
        migrations.DeleteModel(
            name="RemoteProceedingsExample",
        ),
        migrations.DeleteModel(
            name="RemoteProceedingsFAQLinks",
        ),
        migrations.DeleteModel(
            name="RemoteProceedingsInfo",
        ),
        migrations.DeleteModel(
            name="RemoteProceedingsPage",
        ),
    ]
