# Generated by Django 5.1.3 on 2025-02-10 19:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("h3", 0),
                    ("h4", 0),
                    ("paragraph", 1),
                    ("hr", 2),
                    ("image", 3),
                    ("links", 10),
                    ("questionanswers", 12),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.BooleanBlock", (), {}),
                    3: ("wagtail.images.blocks.ImageBlock", [], {}),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ti ti-file-type-pdf", "PDF"),
                                ("ti ti-info-circle-filled", "Info"),
                                ("ti ti-link", "Link"),
                            ]
                        },
                    ),
                    6: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("icon", 5), ("document", 6), ("url", 7)]],
                        {},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 4), ("links", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 7), ("answer", 1)]],
                        {},
                    ),
                    12: ("wagtail.blocks.ListBlock", (11,), {}),
                },
            ),
        ),
    ]
