# Generated by Django 5.1.3 on 2025-02-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_navigationribbon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationribbonlink",
            name="icon",
            field=models.CharField(
                choices=[
                    ("", "None"),
                    ("ti ti-info-circle", "Info"),
                    ("ti ti-file-type-pdf", "Pdf"),
                    ("ti ti-book-2", "Book 2"),
                    ("ti ti-building-bank", "Building Bank"),
                    ("ti ti-hammer", "Hammer"),
                    ("ti ti-scale", "Scale"),
                    ("ti ti-calendar-month", "Calendar Month"),
                    ("ti ti-file", "File"),
                    ("ti ti-info-circle-filled", "Info Circle Filled"),
                    ("ti ti-chevron-right", "Chevron Right"),
                    ("ti ti-video-filled", "Video"),
                    ("ti ti-user-filled", "User"),
                ],
                max_length=200,
            ),
        ),
    ]
