# Generated by Django 5.1.3 on 2025-01-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_home_page_entries"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAnalyticsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_id",
                    models.CharField(
                        default="G-3T6ZS0FHZ8",
                        help_text="Google Analytics Measurement ID (e.g., G-1234567890)",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="footer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="homepageentry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
