# Generated by Django 5.1.3 on 2025-01-03 21:31

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_home_page_meta"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseRelatedFormsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("body", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="CaseRelatedFormsEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("formName", models.CharField(max_length=255)),
                ("pdf", models.FileField(upload_to="forms/")),
                ("number", models.CharField(max_length=255)),
                ("formNameNote", models.CharField(max_length=255)),
                ("eligibleForEFilingByPetitioners", models.CharField(max_length=255)),
                ("eligibleForEFilingByPractitioners", models.CharField(max_length=255)),
                (
                    "parentpage",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="home.caserelatedformspage",
                    ),
                ),
            ],
        ),
    ]
