# Generated by Django 5.1.3 on 2025-01-02 04:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_navigationsettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NavigationSettings",
        ),
    ]
