# Generated by Django 5.1.3 on 2025-02-27 21:57

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photodedication",
            name="card",
        ),
        migrations.AddField(
            model_name="enhancedstandardpage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Description of the section"
            ),
        ),
        migrations.AddField(
            model_name="enhancedstandardpage",
            name="title_text",
            field=models.CharField(
                blank=True, help_text="Title of the section", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="enhancedstandardpage",
            name="video_url",
            field=models.URLField(blank=True, help_text="YouTube embed URL"),
        ),
        migrations.AddField(
            model_name="photodedication",
            name="dawson_page",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo_dedication",
                to="home.dawsonpage",
            ),
        ),
        migrations.AddField(
            model_name="photodedication",
            name="enhanced_standard_page",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo_dedications",
                to="home.enhancedstandardpage",
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("h2", 0),
                    ("h3", 0),
                    ("h4", 0),
                    ("paragraph", 1),
                    ("hr", 2),
                    ("image", 3),
                    ("photo_dedication", 7),
                    ("links", 14),
                    ("questionanswers", 16),
                    ("embedded_video", 19),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.BooleanBlock", (), {}),
                    3: ("wagtail.images.blocks.ImageBlock", [], {}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    5: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {
                            "help_text": "Upload an image to display with this dedication"
                        },
                    ),
                    6: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 4), ("photo", 5), ("paragraph_text", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("ti ti-info-circle", "Info"),
                                ("ti ti-file-type-pdf", "Pdf"),
                                ("ti ti-book-2", "Book 2"),
                                ("ti ti-building-bank", "Building Bank"),
                                ("ti ti-hammer", "Hammer"),
                                ("ti ti-scale", "Scale"),
                                ("ti ti-calendar-month", "Calendar Month"),
                                ("ti ti-file", "File"),
                                ("ti ti-info-circle-filled", "Info Circle Filled"),
                                ("ti ti-chevron-right", "Chevron Right"),
                                ("ti ti-video-filled", "Video"),
                                ("ti ti-user-filled", "User"),
                            ]
                        },
                    ),
                    10: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    11: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("icon", 9), ("document", 10), ("url", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 8), ("links", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 11), ("answer", 1), ("anchortag", 0)]],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    18: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 11), ("description", 17), ("video_url", 18)]],
                        {},
                    ),
                },
            ),
        ),
    ]
