# Generated by Django 5.1.3 on 2025-02-27 22:40

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_alter_enhancedstandardpage_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photodedication",
            name="card",
        ),
        migrations.AddField(
            model_name="enhancedstandardpage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Description of the section"
            ),
        ),
        migrations.AddField(
            model_name="enhancedstandardpage",
            name="title_text",
            field=models.CharField(
                blank=True, help_text="Title of the section", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="enhancedstandardpage",
            name="video_url",
            field=models.URLField(blank=True, help_text="YouTube embed URL"),
        ),
        migrations.AddField(
            model_name="photodedication",
            name="dawson_page",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo_dedication",
                to="home.dawsonpage",
            ),
        ),
        migrations.AddField(
            model_name="photodedication",
            name="enhanced_standard_page",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo_dedications",
                to="home.enhancedstandardpage",
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("h2", 0),
                    ("h3", 0),
                    ("h4", 0),
                    ("paragraph", 1),
                    ("hr", 2),
                    ("image", 3),
                    ("links", 10),
                    ("questionanswers", 12),
                    ("columns", 17),
                    ("embedded_video", 20),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.BooleanBlock", (), {}),
                    3: ("wagtail.images.blocks.ImageBlock", [], {}),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ti ti-book-2", "Book 2"),
                                ("ti ti-building-bank", "Building Bank"),
                                ("ti ti-calendar-month", "Calendar Month"),
                                ("ti ti-chevron-right", "Chevron Right"),
                                ("ti ti-file", "File"),
                                ("ti ti-hammer", "Hammer"),
                                ("ti ti-info-circle", "Info"),
                                ("ti ti-info-circle-filled", "Info Circle Filled"),
                                ("ti ti-link", "Link"),
                                ("", "None"),
                                ("ti ti-file-type-pdf", "Pdf"),
                                ("ti ti-scale", "Scale"),
                                ("ti ti-user-filled", "User"),
                                ("ti ti-video-filled", "Video"),
                            ]
                        },
                    ),
                    6: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("icon", 5), ("document", 6), ("url", 7)]],
                        {},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 4), ("links", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 7), ("answer", 1), ("anchortag", 0)]],
                        {},
                    ),
                    12: ("wagtail.blocks.ListBlock", (11,), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 7)]],
                        {},
                    ),
                    14: ("wagtail.blocks.StructBlock", [[("text", 0), ("url", 7)]], {}),
                    15: (
                        "wagtail.blocks.StreamBlock",
                        [[("h2WithAnchorTag", 13), ("clickableButton", 14)]],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: ("wagtail.blocks.StructBlock", [[("column", 16)]], {}),
                    18: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    19: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("description", 18), ("video_url", 19)]],
                        {},
                    ),
                },
            ),
        ),
    ]
