# Generated by Django 5.1.3 on 2025-01-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_standardpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardpage",
            name="navigation_category",
            field=models.TextField(
                choices=[
                    ("NONE", "None"),
                    ("ABOUT", "About the Court"),
                    ("RULES", "Rules and Guidance"),
                    ("ORDERS", "Orders and Opinions"),
                    ("eFILING", "eFiling and Case Maintenance"),
                ],
                default="NONE",
                max_length=45,
            ),
        ),
    ]
