# Generated by Django 5.1.3 on 2025-02-27 23:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_remove_photodedication_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("h2", 0),
                    ("h3", 0),
                    ("h4", 0),
                    ("paragraph", 1),
                    ("hr", 2),
                    ("image", 3),
                    ("photo_dedication", 7),
                    ("links", 14),
                    ("questionanswers", 16),
                    ("columns", 21),
                    ("embedded_video", 24),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.BooleanBlock", (), {}),
                    3: ("wagtail.images.blocks.ImageBlock", [], {}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    5: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {
                            "help_text": "Upload an image to display with this dedication"
                        },
                    ),
                    6: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 4), ("photo", 5), ("paragraph_text", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ti ti-book-2", "Book 2"),
                                ("ti ti-building-bank", "Building Bank"),
                                ("ti ti-calendar-month", "Calendar Month"),
                                ("ti ti-chevron-right", "Chevron Right"),
                                ("ti ti-file", "File"),
                                ("ti ti-hammer", "Hammer"),
                                ("ti ti-info-circle", "Info"),
                                ("ti ti-info-circle-filled", "Info Circle Filled"),
                                ("ti ti-link", "Link"),
                                ("", "None"),
                                ("ti ti-file-type-pdf", "Pdf"),
                                ("ti ti-scale", "Scale"),
                                ("ti ti-user-filled", "User"),
                                ("ti ti-video-filled", "Video"),
                            ]
                        },
                    ),
                    10: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    11: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("icon", 9), ("document", 10), ("url", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 8), ("links", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 11), ("answer", 1), ("anchortag", 0)]],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 11)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 11)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StreamBlock",
                        [[("h2WithAnchorTag", 17), ("clickableButton", 18)]],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: ("wagtail.blocks.StructBlock", [[("column", 20)]], {}),
                    22: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    23: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 11), ("description", 22), ("video_url", 23)]],
                        {},
                    ),
                },
            ),
        ),
    ]
