# Generated by Django 5.1.3 on 2025-01-06 02:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_alter_standardpage_navigation_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
