# Generated by Django 5.1.3 on 2025-01-06 02:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_standardpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Insert text here.'),
        ),
    ]
