# Generated by Django 5.1.3 on 2025-02-28 20:33

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photodedication",
            name="card",
        ),
        migrations.AddField(
            model_name="enhancedstandardpage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Description of the section"
            ),
        ),
        migrations.AddField(
            model_name="enhancedstandardpage",
            name="title_text",
            field=models.CharField(
                blank=True, help_text="Title of the section", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="enhancedstandardpage",
            name="video_url",
            field=models.URLField(blank=True, help_text="YouTube embed URL"),
        ),
        migrations.AddField(
            model_name="photodedication",
            name="dawson_page",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo_dedication",
                to="home.dawsonpage",
            ),
        ),
        migrations.AddField(
            model_name="photodedication",
            name="enhanced_standard_page",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo_dedications",
                to="home.enhancedstandardpage",
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("h2", 0),
                    ("h3", 0),
                    ("h4", 0),
                    ("paragraph", 1),
                    ("hr", 2),
                    ("image", 3),
                    ("photo_dedication", 8),
                    ("links", 16),
                    ("questionanswers", 18),
                    ("columns", 23),
                    ("embedded_video", 26),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.BooleanBlock", (), {}),
                    3: ("wagtail.images.blocks.ImageBlock", [], {}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    5: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {
                            "help_text": "Upload an image to display with this dedication"
                        },
                    ),
                    6: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Provide alternative text for the image for accessibility.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 4),
                                ("photo", 5),
                                ("paragraph_text", 6),
                                ("alt_text", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ti ti-book-2", "Book 2"),
                                ("ti ti-building-bank", "Building Bank"),
                                ("ti ti-calendar-month", "Calendar Month"),
                                ("ti ti-chevron-right", "Chevron Right"),
                                ("ti ti-file", "File"),
                                ("ti ti-hammer", "Hammer"),
                                ("ti ti-info-circle", "Info"),
                                ("ti ti-info-circle-filled", "Info Circle Filled"),
                                ("ti ti-link", "Link"),
                                ("", "None"),
                                ("ti ti-file-type-pdf", "Pdf"),
                                ("ti ti-scale", "Scale"),
                                ("ti ti-user-filled", "User"),
                                ("ti ti-video-filled", "Video"),
                            ]
                        },
                    ),
                    11: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    12: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    13: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 10),
                                ("document", 11),
                                ("url", 12),
                                ("text_only", 13),
                            ]
                        ],
                        {},
                    ),
                    15: ("wagtail.blocks.ListBlock", (14,), {}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 9), ("links", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 12), ("answer", 1), ("anchortag", 0)]],
                        {},
                    ),
                    18: ("wagtail.blocks.ListBlock", (17,), {}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 12)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 12)]],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.StreamBlock",
                        [[("h2WithAnchorTag", 19), ("clickableButton", 20)]],
                        {},
                    ),
                    22: ("wagtail.blocks.ListBlock", (21,), {}),
                    23: ("wagtail.blocks.StructBlock", [[("column", 22)]], {}),
                    24: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    25: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 12), ("description", 24), ("video_url", 25)]],
                        {},
                    ),
                },
            ),
        ),
    ]
