# Generated by Django 5.1.3 on 2025-03-03 22:49

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("h2", 0),
                    ("h3", 0),
                    ("h4", 0),
                    ("paragraph", 1),
                    ("hr", 2),
                    ("image", 3),
                    ("links", 11),
                    ("questionanswers", 13),
                    ("columns", 18),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.BooleanBlock", (), {}),
                    3: ("wagtail.images.blocks.ImageBlock", [], {}),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ti ti-book-2", "Book 2"),
                                ("ti ti-building-bank", "Building Bank"),
                                ("ti ti-calendar-month", "Calendar Month"),
                                ("ti ti-chevron-right", "Chevron Right"),
                                ("ti ti-file", "File"),
                                ("ti ti-hammer", "Hammer"),
                                ("ti ti-info-circle", "Info"),
                                ("ti ti-info-circle-filled", "Info Circle Filled"),
                                ("ti ti-link", "Link"),
                                ("", "None"),
                                ("ti ti-file-type-pdf", "Pdf"),
                                ("ti ti-scale", "Scale"),
                                ("ti ti-user-filled", "User"),
                                ("ti ti-video-filled", "Video"),
                                ("ti ti-settings-filled", "Settings"),
                                ("ti ti-briefcase-filled", "Briefcase"),
                                ("ti ti-search", "Search"),
                            ]
                        },
                    ),
                    6: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    8: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 5),
                                ("document", 6),
                                ("url", 7),
                                ("text_only", 8),
                            ]
                        ],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 4), ("links", 10)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 7), ("answer", 1), ("anchortag", 0)]],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 7)]],
                        {},
                    ),
                    15: ("wagtail.blocks.StructBlock", [[("text", 0), ("url", 7)]], {}),
                    16: (
                        "wagtail.blocks.StreamBlock",
                        [[("h2WithAnchorTag", 14), ("clickableButton", 15)]],
                        {},
                    ),
                    17: ("wagtail.blocks.ListBlock", (16,), {}),
                    18: ("wagtail.blocks.StructBlock", [[("column", 17)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="navigationribbonlink",
            name="icon",
            field=models.CharField(
                choices=[
                    ("ti ti-book-2", "Book 2"),
                    ("ti ti-building-bank", "Building Bank"),
                    ("ti ti-calendar-month", "Calendar Month"),
                    ("ti ti-chevron-right", "Chevron Right"),
                    ("ti ti-file", "File"),
                    ("ti ti-hammer", "Hammer"),
                    ("ti ti-info-circle", "Info"),
                    ("ti ti-info-circle-filled", "Info Circle Filled"),
                    ("ti ti-link", "Link"),
                    ("", "None"),
                    ("ti ti-file-type-pdf", "Pdf"),
                    ("ti ti-scale", "Scale"),
                    ("ti ti-user-filled", "User"),
                    ("ti ti-video-filled", "Video"),
                    ("ti ti-settings-filled", "Settings"),
                    ("ti ti-briefcase-filled", "Briefcase"),
                    ("ti ti-search", "Search"),
                ],
                max_length=200,
            ),
        ),
    ]
