# Generated by Django 5.1.3 on 2025-03-04 22:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_alter_enhancedstandardpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("h2", 0),
                    ("h3", 1),
                    ("h4", 2),
                    ("paragraph", 3),
                    ("hr", 4),
                    ("image", 5),
                    ("links", 14),
                    ("questionanswers", 18),
                    ("columns", 23),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Header 2"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Header 3"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Header 4"}),
                    3: ("wagtail.blocks.RichTextBlock", (), {"label": "Paragraph"}),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Horizontal Rule"},
                    ),
                    5: ("wagtail.images.blocks.ImageBlock", [], {"label": "Image"}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {}),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ti ti-book-2", "Book 2"),
                                ("ti ti-building-bank", "Building Bank"),
                                ("ti ti-calendar-month", "Calendar Month"),
                                ("ti ti-chevron-right", "Chevron Right"),
                                ("ti ti-file", "File"),
                                ("ti ti-hammer", "Hammer"),
                                ("ti ti-info-circle", "Info"),
                                ("ti ti-info-circle-filled", "Info Circle Filled"),
                                ("ti ti-link", "Link"),
                                ("", "None"),
                                ("ti ti-file-type-pdf", "Pdf"),
                                ("ti ti-scale", "Scale"),
                                ("ti ti-user-filled", "User"),
                                ("ti ti-video-filled", "Video"),
                                ("ti ti-settings-filled", "Settings"),
                                ("ti ti-briefcase-filled", "Briefcase"),
                                ("ti ti-search", "Search"),
                            ]
                        },
                    ),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    10: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    11: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 7),
                                ("icon", 8),
                                ("document", 9),
                                ("url", 10),
                                ("text_only", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 6), ("links", 13)]],
                        {},
                    ),
                    15: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("link", "Link"), ("question", "Question")],
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("question", 10),
                                ("answer", 15),
                                ("anchortag", 10),
                                ("type", 16),
                                ("value", 10),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ListBlock",
                        (17,),
                        {"label": "Question and Answer"},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("anchortag", 10)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("url", 10)]],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.StreamBlock",
                        [[("h2WithAnchorTag", 19), ("clickableButton", 20)]],
                        {},
                    ),
                    22: ("wagtail.blocks.ListBlock", (21,), {}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("column", 22)]],
                        {"label": "Columns"},
                    ),
                },
            ),
        ),
    ]
