# Generated by Django 5.1.3 on 2025-03-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_remove_photodedication_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photodedication",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Enter alternative text for the image",
                max_length=255,
            ),
        ),
    ]
