# Generated by Django 5.1.3 on 2025-03-05 17:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 0),
                    ("h3", 0),
                    ("h4", 0),
                    ("paragraph", 4),
                    ("hr", 5),
                    ("image", 6),
                    ("links", 14),
                    ("questionanswers", 16),
                    ("columns", 21),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.RichTextBlock", (), {}),
                    5: ("wagtail.blocks.BooleanBlock", (), {}),
                    6: ("wagtail.images.blocks.ImageBlock", [], {}),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ti ti-book-2", "Book 2"),
                                ("ti ti-building-bank", "Building Bank"),
                                ("ti ti-calendar-month", "Calendar Month"),
                                ("ti ti-chevron-right", "Chevron Right"),
                                ("ti ti-file", "File"),
                                ("ti ti-hammer", "Hammer"),
                                ("ti ti-info-circle", "Info"),
                                ("ti ti-info-circle-filled", "Info Circle Filled"),
                                ("ti ti-link", "Link"),
                                ("", "None"),
                                ("ti ti-file-type-pdf", "Pdf"),
                                ("ti ti-scale", "Scale"),
                                ("ti ti-user-filled", "User"),
                                ("ti ti-video-filled", "Video"),
                            ],
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    10: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    11: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 8),
                                ("document", 9),
                                ("url", 10),
                                ("text_only", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 7), ("links", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 10), ("answer", 4), ("anchortag", 0)]],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 10)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 10)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StreamBlock",
                        [[("h2WithAnchorTag", 17), ("clickableButton", 18)]],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: ("wagtail.blocks.StructBlock", [[("column", 20)]], {}),
                },
            ),
        ),
    ]
