# Generated by Django 5.1.3 on 2025-01-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_standardpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='menu_item_name',
            field=models.CharField(default='*NOT SET*', max_length=255),
        ),
    ]
