# Generated by Django 5.1.3 on 2025-01-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_standardpage_menu_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardpage",
            name="menu_item_name",
            field=models.CharField(
                default="*NOT SET*",
                help_text="Enter the name of the page for the navigation bar link.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="navigation_category",
            field=models.TextField(
                choices=[
                    ("NONE", "None"),
                    ("ABOUT", "About the Court"),
                    ("RULES", "Rules & Guidance"),
                    ("ORDERS", "Orders & Opinions"),
                    ("eFILING", "eFiling & Case Maintenance"),
                ],
                default="NONE",
                max_length=45,
            ),
        ),
    ]
