# Generated by Django 5.1.3 on 2025-03-05 23:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("hr", 8),
                    ("image", 9),
                    ("links", 17),
                    ("questionanswers", 19),
                    ("columns", 24),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    9: ("wagtail.images.blocks.ImageBlock", [], {}),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ti ti-book-2", "Book 2"),
                                ("ti ti-building-bank", "Building Bank"),
                                ("ti ti-calendar-month", "Calendar Month"),
                                ("ti ti-chevron-right", "Chevron Right"),
                                ("ti ti-file", "File"),
                                ("ti ti-hammer", "Hammer"),
                                ("ti ti-info-circle", "Info"),
                                ("ti ti-info-circle-filled", "Info Circle Filled"),
                                ("ti ti-link", "Link"),
                                ("", "None"),
                                ("ti ti-file-type-pdf", "Pdf"),
                                ("ti ti-scale", "Scale"),
                                ("ti ti-user-filled", "User"),
                                ("ti ti-video-filled", "Video"),
                                ("ti ti-settings-filled", "Settings"),
                                ("ti ti-briefcase-filled", "Briefcase"),
                                ("ti ti-search", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    14: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 11),
                                ("document", 12),
                                ("url", 13),
                                ("text_only", 14),
                            ]
                        ],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 10), ("links", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 13), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    19: ("wagtail.blocks.ListBlock", (18,), {}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 13)]],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 13)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.StreamBlock",
                        [[("h2WithAnchorTag", 20), ("clickableButton", 21)]],
                        {},
                    ),
                    23: ("wagtail.blocks.ListBlock", (22,), {}),
                    24: ("wagtail.blocks.StructBlock", [[("column", 23)]], {}),
                },
            ),
        ),
    ]
