# Generated by Django 5.1.3 on 2025-03-10 16:01

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_remove_photodedication_card_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the text snippet", max_length=255
                    ),
                ),
                (
                    "text",
                    wagtail.fields.RichTextField(help_text="HTML Rich text content"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("snippet", 8),
                    ("hr", 9),
                    ("image", 10),
                    ("photo_dedication", 15),
                    ("links", 23),
                    ("questionanswers", 25),
                    ("columns", 30),
                    ("embedded_video", 33),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    10: ("wagtail.images.blocks.ImageBlock", [], {}),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    12: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {
                            "help_text": "Upload an image to display with this dedication"
                        },
                    ),
                    13: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Provide alternative text for the image for accessibility.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 11),
                                ("photo", 12),
                                ("paragraph_text", 13),
                                ("alt_text", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ti ti-book-2", "Book 2"),
                                ("ti ti-building-bank", "Building Bank"),
                                ("ti ti-calendar-month", "Calendar Month"),
                                ("ti ti-chevron-right", "Chevron Right"),
                                ("ti ti-file", "File"),
                                ("ti ti-hammer", "Hammer"),
                                ("ti ti-info-circle", "Info"),
                                ("ti ti-info-circle-filled", "Info Circle Filled"),
                                ("ti ti-link", "Link"),
                                ("", "None"),
                                ("ti ti-file-type-pdf", "Pdf"),
                                ("ti ti-scale", "Scale"),
                                ("ti ti-user-filled", "User"),
                                ("ti ti-video-filled", "Video"),
                                ("ti ti-settings-filled", "Settings"),
                                ("ti ti-briefcase-filled", "Briefcase"),
                                ("ti ti-search", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    19: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    20: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 17),
                                ("document", 18),
                                ("url", 19),
                                ("text_only", 20),
                            ]
                        ],
                        {},
                    ),
                    22: ("wagtail.blocks.ListBlock", (21,), {}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 16), ("links", 22)]],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 19), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    25: ("wagtail.blocks.ListBlock", (24,), {}),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 19)]],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 19)]],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.StreamBlock",
                        [[("h2WithAnchorTag", 26), ("clickableButton", 27)]],
                        {},
                    ),
                    29: ("wagtail.blocks.ListBlock", (28,), {}),
                    30: ("wagtail.blocks.StructBlock", [[("column", 29)]], {}),
                    31: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    32: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 19), ("description", 31), ("video_url", 32)]],
                        {},
                    ),
                },
            ),
        ),
    ]
