# Generated by Django 5.1.3 on 2025-03-10 19:21

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_commontext_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacancyAnnouncementsPage",
            fields=[
                (
                    "standardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.standardpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.standardpage",),
        ),
        migrations.CreateModel(
            name="VacancyEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Vacancy announcement number", max_length=50
                    ),
                ),
                (
                    "position_title",
                    models.CharField(
                        help_text="Position title, series, and grade", max_length=255
                    ),
                ),
                (
                    "closing_date",
                    models.DateField(help_text="Closing date for the vacancy"),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Link to the vacancy announcement", max_length=255
                    ),
                ),
                (
                    "parentpage",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="home.vacancyannouncementspage",
                    ),
                ),
            ],
            options={
                "ordering": ["closing_date"],
            },
        ),
    ]
