# Generated by Django 5.1.3 on 2025-03-12 19:27

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_commontext_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("snippet", 8),
                    ("hr", 9),
                    ("image", 10),
                    ("table", 11),
                    ("links", 19),
                    ("questionanswers", 21),
                    ("columns", 26),
                    ("embedded_video", 29),
                    ("card", 35),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    10: ("wagtail.images.blocks.ImageBlock", [], {}),
                    11: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("ti ti-book-2", "Book 2"),
                                ("ti ti-building-bank", "Building Bank"),
                                ("ti ti-calendar-month", "Calendar Month"),
                                ("ti ti-chevron-right", "Chevron Right"),
                                ("ti ti-file", "File"),
                                ("ti ti-hammer", "Hammer"),
                                ("ti ti-info-circle", "Info"),
                                ("ti ti-info-circle-filled", "Info Circle Filled"),
                                ("ti ti-check", "Check"),
                                ("ti ti-link", "Link"),
                                ("ti ti-exclamation-mark", "Exclamation Mark"),
                                ("ti ti-file-type-pdf", "Pdf"),
                                ("ti ti-scale", "Scale"),
                                ("ti ti-user-filled", "User"),
                                ("ti ti-video-filled", "Video"),
                                ("ti ti-settings-filled", "Settings"),
                                ("ti ti-briefcase-filled", "Briefcase"),
                                ("ti ti-search", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    15: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    16: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 13),
                                ("document", 14),
                                ("url", 15),
                                ("text_only", 16),
                            ]
                        ],
                        {},
                    ),
                    18: ("wagtail.blocks.ListBlock", (17,), {}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 12), ("links", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 15), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 15)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 15)]],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.StreamBlock",
                        [[("h2WithAnchorTag", 22), ("clickableButton", 23)]],
                        {},
                    ),
                    25: ("wagtail.blocks.ListBlock", (24,), {}),
                    26: ("wagtail.blocks.StructBlock", [[("column", 25)]], {}),
                    27: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    28: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 15), ("description", 27), ("video_url", 28)]],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("ti ti-book-2", "Book 2"),
                                ("ti ti-building-bank", "Building Bank"),
                                ("ti ti-calendar-month", "Calendar Month"),
                                ("ti ti-chevron-right", "Chevron Right"),
                                ("ti ti-file", "File"),
                                ("ti ti-hammer", "Hammer"),
                                ("ti ti-info-circle", "Info"),
                                ("ti ti-info-circle-filled", "Info Circle Filled"),
                                ("ti ti-check", "Check"),
                                ("ti ti-link", "Link"),
                                ("ti ti-exclamation-mark", "Exclamation Mark"),
                                ("ti ti-file-type-pdf", "Pdf"),
                                ("ti ti-scale", "Scale"),
                                ("ti ti-user-filled", "User"),
                                ("ti ti-video-filled", "Video"),
                                ("ti ti-settings-filled", "Settings"),
                                ("ti ti-briefcase-filled", "Briefcase"),
                                ("ti ti-search", "Search"),
                            ]
                        },
                    ),
                    31: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    32: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 30),
                                ("title", 31),
                                ("description", 32),
                                ("color", 33),
                            ]
                        ],
                        {},
                    ),
                    35: ("wagtail.blocks.ListBlock", (34,), {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="navigationribbonlink",
            name="icon",
            field=models.CharField(
                choices=[
                    ("", "None"),
                    ("ti ti-book-2", "Book 2"),
                    ("ti ti-building-bank", "Building Bank"),
                    ("ti ti-calendar-month", "Calendar Month"),
                    ("ti ti-chevron-right", "Chevron Right"),
                    ("ti ti-file", "File"),
                    ("ti ti-hammer", "Hammer"),
                    ("ti ti-info-circle", "Info"),
                    ("ti ti-info-circle-filled", "Info Circle Filled"),
                    ("ti ti-check", "Check"),
                    ("ti ti-link", "Link"),
                    ("ti ti-exclamation-mark", "Exclamation Mark"),
                    ("ti ti-file-type-pdf", "Pdf"),
                    ("ti ti-scale", "Scale"),
                    ("ti ti-user-filled", "User"),
                    ("ti ti-video-filled", "Video"),
                    ("ti ti-settings-filled", "Settings"),
                    ("ti ti-briefcase-filled", "Briefcase"),
                    ("ti ti-search", "Search"),
                ],
                max_length=200,
            ),
        ),
    ]
