# Generated by Django 5.1.3 on 2025-03-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_vacancyannouncementspage_vacancyentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancyentry",
            name="url",
            field=models.URLField(
                blank=True, help_text="Link to the vacancy announcement", max_length=255
            ),
        ),
    ]
