# Generated by Django 5.1.3 on 2025-01-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_caserelatedformspage_caserelatedformsentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caserelatedformsentry",
            name="formNameNote",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="caserelatedformsentry",
            name="number",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
