# Generated by Django 5.1.3 on 2025-01-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0022_alter_caserelatedformsentry_formnamenote_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caserelatedformsentry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
