# Generated by Django 5.1.3 on 2025-01-14 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0023_alter_caserelatedformsentry_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caserelatedformspage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="CaseRelatedFormsEntry",
        ),
        migrations.DeleteModel(
            name="CaseRelatedFormsPage",
        ),
    ]
