# Generated by Django 5.1.3 on 2025-03-17 21:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0023_dawsonfaqspageimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DawsonFaqsPageImage",
        ),
    ]
