# Generated by Django 5.1.3 on 2025-03-17 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0024_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatedpage",
            name="related_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.enhancedstandardpage",
            ),
        ),
    ]
