# Generated by Django 5.1.3 on 2025-01-14 20:34

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0024_remove_caserelatedformspage_page_ptr_and_more"),
        ("wagtaildocs", "0014_alter_document_file_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseRelatedFormsPage",
            fields=[
                (
                    "standardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.standardpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.standardpage",),
        ),
        migrations.CreateModel(
            name="CaseRelatedFormsEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("formName", models.CharField(max_length=255)),
                ("number", models.CharField(blank=True, max_length=255)),
                ("formNameNote", models.CharField(blank=True, max_length=255)),
                ("eligibleForEFilingByPetitioners", models.CharField(max_length=255)),
                ("eligibleForEFilingByPractitioners", models.CharField(max_length=255)),
                (
                    "pdf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                    ),
                ),
                (
                    "parentpage",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="home.caserelatedformspage",
                    ),
                ),
            ],
        ),
    ]
