# Generated by Django 5.1.3 on 2025-03-19 18:07

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_relatedpage_display_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu_items",
                    wagtail.fields.StreamField(
                        [("section", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Top level navigation title",
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Unique identifier for this section",
                                    "required": True,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Display text for the navigation link",
                                    "required": True,
                                },
                            ),
                            3: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Select a page to link to",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Or enter an external URL",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 2), ("page", 3), ("external_url", 4)]],
                                {},
                            ),
                            6: ("wagtail.blocks.ListBlock", (5,), {}),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("key", 1), ("sub_links", 6)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation Menu",
            },
        ),
    ]
