# Generated by Django 5.1.3 on 2025-03-19 23:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_relatedpage_display_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enhancedstandardpage",
            name="description",
        ),
        migrations.RemoveField(
            model_name="enhancedstandardpage",
            name="title_text",
        ),
        migrations.RemoveField(
            model_name="enhancedstandardpage",
            name="video_url",
        ),
    ]
