# Generated by Django 5.1.3 on 2025-03-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_relatedpage_display_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("video_file", models.FileField(upload_to="videos/")),
            ],
        ),
    ]
