# Generated by Django 5.1.3 on 2025-03-18 19:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_relatedpage_display_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("snippet", 8),
                    ("hr", 9),
                    ("image", 10),
                    ("table", 11),
                    ("links", 19),
                    ("questionanswers", 21),
                    ("columns", 29),
                    ("embedded_video", 32),
                    ("card", 38),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    10: ("wagtail.images.blocks.ImageBlock", [], {}),
                    11: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("ti ti-book-2", "Book 2"),
                                ("ti ti-building-bank", "Building Bank"),
                                ("ti ti-calendar-month", "Calendar Month"),
                                ("ti ti-chevron-right", "Chevron Right"),
                                ("ti ti-file", "File"),
                                ("ti ti-hammer", "Hammer"),
                                ("ti ti-info-circle", "Info"),
                                ("ti ti-info-circle-filled", "Info Circle Filled"),
                                ("ti ti-check", "Check"),
                                ("ti ti-link", "Link"),
                                ("ti ti-exclamation-mark", "Exclamation Mark"),
                                ("ti ti-file-type-pdf", "Pdf"),
                                ("ti ti-scale", "Scale"),
                                ("ti ti-user-filled", "User"),
                                ("ti ti-video-filled", "Video"),
                                ("ti ti-settings-filled", "Settings"),
                                ("ti ti-briefcase-filled", "Briefcase"),
                                ("ti ti-search", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    15: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    16: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 13),
                                ("document", 14),
                                ("url", 15),
                                ("text_only", 16),
                            ]
                        ],
                        {},
                    ),
                    18: ("wagtail.blocks.ListBlock", (17,), {}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 12), ("links", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 15), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.ListBlock",
                        (20,),
                        {
                            "help_text": "Add a question and answer with anchor tag for linking",
                            "label": "Question and Answer",
                        },
                    ),
                    22: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 15)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 15)]],
                        {"label": "Clickable Button"},
                    ),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 25), ("links", 18)]],
                        {"label": "Links"},
                    ),
                    27: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 4),
                                ("h3", 5),
                                ("hr", 22),
                                ("h2WithAnchorTag", 23),
                                ("clickableButton", 24),
                                ("links", 26),
                            ]
                        ],
                        {},
                    ),
                    28: ("wagtail.blocks.ListBlock", (27,), {}),
                    29: ("wagtail.blocks.StructBlock", [[("column", 28)]], {}),
                    30: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    31: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 15), ("description", 30), ("video_url", 31)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("ti ti-book-2", "Book 2"),
                                ("ti ti-building-bank", "Building Bank"),
                                ("ti ti-calendar-month", "Calendar Month"),
                                ("ti ti-chevron-right", "Chevron Right"),
                                ("ti ti-file", "File"),
                                ("ti ti-hammer", "Hammer"),
                                ("ti ti-info-circle", "Info"),
                                ("ti ti-info-circle-filled", "Info Circle Filled"),
                                ("ti ti-check", "Check"),
                                ("ti ti-link", "Link"),
                                ("ti ti-exclamation-mark", "Exclamation Mark"),
                                ("ti ti-file-type-pdf", "Pdf"),
                                ("ti ti-scale", "Scale"),
                                ("ti ti-user-filled", "User"),
                                ("ti ti-video-filled", "Video"),
                                ("ti ti-settings-filled", "Settings"),
                                ("ti ti-briefcase-filled", "Briefcase"),
                                ("ti ti-search", "Search"),
                            ]
                        },
                    ),
                    34: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    35: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    36: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 33),
                                ("title", 34),
                                ("description", 35),
                                ("color", 36),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    38: ("wagtail.blocks.ListBlock", (37,), {"label": "Card Set"}),
                },
            ),
        ),
    ]
