# Generated by Django 5.1.7 on 2025-03-21 14:32

import django.db.models.deletion
import wagtail.fields
import wagtail.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_relatedpage_display_title_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enhancedstandardpage",
            name="menu_item_name",
        ),
        migrations.RemoveField(
            model_name="enhancedstandardpage",
            name="navigation_category",
        ),
        migrations.RemoveField(
            model_name="enhancedstandardpage",
            name="no_index",
        ),
        migrations.RemoveField(
            model_name="enhancedstandardpage",
            name="redirectLink",
        ),
        migrations.RemoveField(
            model_name="externalredirectpage",
            name="menu_item_name",
        ),
        migrations.RemoveField(
            model_name="externalredirectpage",
            name="navigation_category",
        ),
        migrations.RemoveField(
            model_name="externalredirectpage",
            name="no_index",
        ),
        migrations.RemoveField(
            model_name="externalredirectpage",
            name="redirectLink",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="menu_item_name",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="navigation_category",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="no_index",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="redirectLink",
        ),
        migrations.RemoveField(
            model_name="standardpage",
            name="menu_item_name",
        ),
        migrations.RemoveField(
            model_name="standardpage",
            name="navigation_category",
        ),
        migrations.RemoveField(
            model_name="standardpage",
            name="no_index",
        ),
        migrations.RemoveField(
            model_name="standardpage",
            name="redirectLink",
        ),
        migrations.CreateModel(
            name="NavigationMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "live",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="live"
                    ),
                ),
                (
                    "has_unpublished_changes",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="has unpublished changes",
                    ),
                ),
                (
                    "first_published_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="first published at",
                    ),
                ),
                (
                    "last_published_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="last published at"
                    ),
                ),
                (
                    "go_live_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="go live date/time"
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expiry date/time"
                    ),
                ),
                (
                    "expired",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="expired"
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="locked"
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="locked at"
                    ),
                ),
                (
                    "menu_items",
                    wagtail.fields.StreamField(
                        [("section", 6)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Top level navigation title",
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Display text for the navigation link",
                                    "required": True,
                                },
                            ),
                            2: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Select a page to link to",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Or enter an external URL",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 1), ("page", 2), ("external_url", 3)]],
                                {},
                            ),
                            5: ("wagtail.blocks.ListBlock", (4,), {}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("sub_links", 5)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="locked by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation Menu",
                "verbose_name_plural": "Navigation Menus",
            },
            bases=(wagtail.models.PreviewableMixin, models.Model),
        ),
    ]
