# Generated by Django 5.1.3 on 2025-01-15 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_caserelatedformspage_caserelatedformsentry'),
        ('wagtailcore', '0096_alter_page_search_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRedirectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('no_index', models.BooleanField(default=False)),
                ('navigation_category', models.TextField(choices=[('NONE', 'None'), ('ABOUT', 'About the Court'), ('RULES', 'Rules & Guidance'), ('ORDERS', 'Orders & Opinions'), ('eFILING', 'eFiling & Case Maintenance')], default='NONE', max_length=45)),
                ('menu_item_name', models.CharField(default='*NOT SET*', help_text='Enter the name of the page for the navigation bar link.', max_length=255)),
                ('link', models.CharField(help_text='Insert link here.', max_length=250)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
