# Generated by Django 5.1.3 on 2025-03-19 21:30

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_relatedpage_display_title_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgeIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="JudgeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("middle_initial", models.CharField(blank=True, max_length=3)),
                ("last_name", models.CharField(max_length=255)),
                ("suffix", models.CharField(blank=True, max_length=3)),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional full name to display (e.g., 'John A. Smith')",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Judge", "Judge"),
                            ("Senior Judge", "Senior Judge"),
                            ("Special Trial Judge", "Special Trial Judge"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "chambders_telephone",
                    models.CharField(
                        blank=True, help_text="Chambers Telephone Number", max_length=20
                    ),
                ),
                ("bio", wagtail.fields.RichTextField(blank=True)),
            ],
        ),
    ]
