# Generated by Django 5.1.3 on 2025-01-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_externalredirectpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalredirectpage',
            old_name='link',
            new_name='redirectLink',
        ),
    ]
