# Generated by Django 5.1.3 on 2025-01-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0026_dawsonpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="menu_item_name",
            field=models.CharField(
                default="*NOT SET*",
                help_text="Enter the name of the page for the navigation bar link.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="navigation_category",
            field=models.TextField(
                choices=[
                    ("NONE", "None"),
                    ("ABOUT", "About the Court"),
                    ("RULES", "Rules & Guidance"),
                    ("ORDERS", "Orders & Opinions"),
                    ("eFILING", "eFiling & Case Maintenance"),
                ],
                default="NONE",
                max_length=45,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="no_index",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="homepage",
            name="redirectLink",
            field=models.CharField(
                blank=True, help_text="Insert link here.", max_length=250
            ),
        ),
    ]
