# Generated by Django 5.1.7 on 2025-03-21 18:45

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0026_remove_enhancedstandardpage_menu_item_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgeCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this collection (e.g., 'Featured Judges', 'Tax Court Judges')",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JudgeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("middle_initial", models.CharField(blank=True, max_length=3)),
                ("last_name", models.CharField(max_length=255)),
                ("suffix", models.CharField(blank=True, max_length=3)),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional full name to display (e.g., 'John A. Smith')",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Judge", "Judge"),
                            ("Senior Judge", "Senior Judge"),
                            ("Special Trial Judge", "Special Trial Judge"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "chambders_telephone",
                    models.CharField(
                        blank=True, help_text="Chambers Telephone Number", max_length=20
                    ),
                ),
                ("bio", wagtail.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="JudgeIndex",
            fields=[
                (
                    "enhancedstandardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.enhancedstandardpage",
                    ),
                ),
                (
                    "judge_collections",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select judge collections to display on this page",
                        related_name="judge_index_pages",
                        to="home.judgecollection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Judges Index Page",
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "home.enhancedstandardpage",
            ),
        ),
        migrations.AddField(
            model_name="judgecollection",
            name="judges",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select judges to include in this collection",
                related_name="collections",
                to="home.judgeprofile",
            ),
        ),
    ]
