# Generated by Django 5.1.3 on 2025-01-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_rename_link_externalredirectpage_redirectlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='redirectLink',
            field=models.CharField(blank=True, help_text='Insert link here.', max_length=250),
        ),
        migrations.AlterField(
            model_name='externalredirectpage',
            name='redirectLink',
            field=models.CharField(blank=True, help_text='Insert link here.', max_length=250),
        ),
    ]
