# Generated by Django 5.1.3 on 2025-03-21 21:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0027_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Video",
        ),
    ]
