# Generated by Django 5.1.3 on 2025-03-24 20:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0027_alter_enhancedstandardpage_body_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnhancedRawHTMLPage",
            fields=[
                (
                    "enhancedstandardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.enhancedstandardpage",
                    ),
                ),
                (
                    "raw_html_body",
                    wagtail.fields.StreamField(
                        [
                            ("raw_html", 0),
                            ("paragraph", 1),
                            ("h2", 2),
                            ("h3", 3),
                            ("image", 4),
                            ("questionanswers", 10),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {"label": "Raw HTML"},
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"label": "Rich Text"},
                            ),
                            2: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                            3: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"required": False},
                            ),
                            7: ("wagtail.blocks.RawHTMLBlock", (), {"required": False}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("rich_text", 6), ("html_block", 7)]],
                                {"required": False},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 5), ("answer", 8), ("anchortag", 5)]],
                                {},
                            ),
                            10: (
                                "wagtail.blocks.ListBlock",
                                (9,),
                                {
                                    "help_text": "Add a question and answer with anchor tag for linking",
                                    "label": "Question and Answer",
                                },
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Enhanced Raw HTML Page",
            },
            bases=("home.enhancedstandardpage",),
        ),
    ]
