# Generated by Django 5.1.7 on 2025-03-25 19:40

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0028_judgecollection_judgeindex_judgeprofile_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Directory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the directory (e.g., 'Contact Directory')",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DirectoryIndex",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("columns", 15)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                            2: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Add Horizontal Rule.",
                                    "label": "Horizontal Rule",
                                },
                            ),
                            3: ("wagtail.blocks.CharBlock", (), {}),
                            4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 3), ("anchortag", 4)]],
                                {
                                    "help_text": "Heading 2 with optional anchor tag for linking",
                                    "label": "Heading 2 with Anchor Tag",
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 3), ("url", 4)]],
                                {"label": "Clickable Button"},
                            ),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("indented", "Indented"),
                                        ("unindented", "Unindented"),
                                    ]
                                },
                            ),
                            8: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("", "None"),
                                        ("fa-solid fa-book", "Book"),
                                        (
                                            "fa-solid fa-building-columns",
                                            "Building Bank",
                                        ),
                                        ("fa-solid fa-calendar", "Calendar Month"),
                                        ("fa-solid fa-chevron-right", "Chevron Right"),
                                        ("fa-solid fa-file", "File"),
                                        ("fa-solid fa-gavel", "Hammer"),
                                        ("fa-solid fa-circle-info", "Info"),
                                        ("fa-solid fa-check", "Check"),
                                        ("fa-solid fa-link", "Link"),
                                        ("fa-solid fa-exclamation", "Exclamation Mark"),
                                        ("fa-solid fa-file-pdf", "Pdf"),
                                        ("fa-solid fa-scale-balanced", "Scale"),
                                        ("fa-solid fa-user", "User"),
                                        ("fa-solid fa-video", "Video"),
                                        ("fa-solid fa-gear", "Settings"),
                                        ("fa-solid fa-briefcase", "Briefcase"),
                                        ("fa-solid fa-magnifying-glass", "Search"),
                                    ],
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"required": False},
                            ),
                            10: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"required": False},
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 3),
                                        ("icon", 8),
                                        ("document", 9),
                                        ("url", 4),
                                        ("text_only", 10),
                                    ]
                                ],
                                {},
                            ),
                            12: ("wagtail.blocks.ListBlock", (11,), {}),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("class", 7), ("links", 12)]],
                                {"label": "Links"},
                            ),
                            14: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (),
                                {
                                    "help_text": "Directory Entry snippet",
                                    "label": "Directory Entry",
                                    "required": False,
                                    "target_model": "home.Directory",
                                },
                            ),
                            15: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("h2", 0),
                                        ("h3", 1),
                                        ("hr", 2),
                                        ("h2WithAnchorTag", 5),
                                        ("clickableButton", 6),
                                        ("links", 13),
                                        ("judgeCollection", 14),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Add judge profiles or collections to display on this page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="DirectoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(help_text="Title", max_length=255)),
                (
                    "detail",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Additional details"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=20
                    ),
                ),
                (
                    "directory",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="home.directory",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
