# Generated by Django 5.1.3 on 2025-01-20 22:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0028_rename_dawsonpage_dawsonefilingpage_dawsoncard_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DawsonEFilingPage",
            new_name="DawsonPage",
        ),
    ]
