# Generated by Django 5.1.7 on 2025-03-31 18:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0028_judgecollection_judgeindex_judgeprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnhancedRawHTMLPage",
            fields=[
                (
                    "enhancedstandardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.enhancedstandardpage",
                    ),
                ),
                (
                    "raw_html_body",
                    wagtail.fields.StreamField(
                        [("raw_html", 0), ("questionanswers", 6)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {"label": "Raw HTML"},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"required": False},
                            ),
                            3: ("wagtail.blocks.RawHTMLBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("rich_text", 2), ("html_block", 3)]],
                                {"required": False},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 1), ("answer", 4), ("anchortag", 1)]],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.ListBlock",
                                (5,),
                                {
                                    "help_text": "Add a question and answer with anchor tag for linking",
                                    "label": "Question and Answer",
                                },
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Enhanced Raw HTML Page",
            },
            bases=("home.enhancedstandardpage",),
        ),
    ]
