# Generated by Django 5.1.7 on 2025-03-31 16:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0028_judgecollection_judgeindex_judgeprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationmenu",
            name="menu_items",
            field=wagtail.fields.StreamField(
                [("section", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Top level navigation title", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Or enter an external URL", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Display text for the navigation link",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 2), ("page", 3), ("external_url", 1)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("external_url", 1), ("sub_links", 5)]],
                        {},
                    ),
                },
            ),
        ),
    ]
