# Generated by Django 5.1.7 on 2025-03-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0029_directory_directoryindex_directoryentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directoryentry",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="directoryentry",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
