# Generated by Django 5.1.3 on 2025-01-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_rename_dawsonefilingpage_dawsonpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dawsoncard',
            name='card_icon',
            field=models.CharField(help_text='Icon Name - see https://tabler.io/icons and enter the name of the icon (i.e. "accessible")', max_length=200, null=True),
        ),
    ]
