# Generated by Django 5.1.3 on 2025-01-23 16:17

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_dawsoncard_card_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleCardGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_label', models.CharField(help_text="Label for this group of cards (e.g., 'Section 1: Featured Cards').", max_length=255)),
                ('parent_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_groups', to='home.dawsonpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(help_text='The title to appear at the top of the card', max_length=255, null=True)),
                ('card_icon', models.CharField(help_text='Icon Name - see https://tabler.io/icons and enter the name of the icon (i.e. "accessible")', max_length=200, null=True)),
                ('parent_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='home.simplecardgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='relatedpage',
            name='card',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_pages', to='home.simplecards'),
        ),
        migrations.DeleteModel(
            name='DawsonCard',
        ),
    ]
