# Generated by Django 5.1.7 on 2025-03-26 14:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0030_alter_directoryentry_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directoryindex",
            name="body",
            field=wagtail.fields.StreamField(
                [("Entries", 16)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {}),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("anchortag", 4)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("url", 4)]],
                        {"label": "Clickable Button"},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    10: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("icon", 8),
                                ("document", 9),
                                ("url", 4),
                                ("text_only", 10),
                            ]
                        ],
                        {},
                    ),
                    12: ("wagtail.blocks.ListBlock", (11,), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 7), ("links", 12)]],
                        {"label": "Links"},
                    ),
                    14: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (),
                        {
                            "help_text": "Optionally pick a JudgeCollection snippet",
                            "label": "Judge Collection",
                            "required": False,
                            "target_model": "home.JudgeCollection",
                        },
                    ),
                    15: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (),
                        {
                            "label": "Directory",
                            "required": False,
                            "target_model": "home.Directory",
                        },
                    ),
                    16: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 0),
                                ("h3", 1),
                                ("hr", 2),
                                ("h2WithAnchorTag", 5),
                                ("clickableButton", 6),
                                ("links", 13),
                                ("JudgeCollection", 14),
                                ("Directory", 15),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Add directory entries or judge profiles",
            ),
        ),
    ]
