# Generated by Django 5.1.3 on 2025-01-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_simplecardgroup_simplecards_alter_relatedpage_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplecards',
            name='card_icon',
            field=models.CharField(blank='True', help_text='Icon Name - see https://tabler.io/icons and enter the name of the icon (i.e. "accessible")', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='simplecards',
            name='card_title',
            field=models.CharField(blank='True', help_text='The title to appear at the top of the card', max_length=255, null=True),
        ),
    ]
