# Generated by Django 5.1.3 on 2025-01-23 17:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_simplecards_card_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dawsonpage',
            name='dawson_dedication',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
