# Generated by Django 5.1.7 on 2025-04-03 03:35

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0032_directoryindex_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgesRecruiting",
            fields=[
                (
                    "enhancedstandardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.enhancedstandardpage",
                    ),
                ),
                (
                    "judges_recruiting",
                    wagtail.fields.StreamField(
                        [("judges_recruiting_block", 4)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {"blank": True}),
                            1: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {
                                    "help_text": "Start displaying from this date",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {
                                    "help_text": "Stop displaying after this date",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("judge_name", 0),
                                        ("description", 0),
                                        ("apply_to_email", 0),
                                        ("display_from", 1),
                                        ("display_to", 2),
                                    ]
                                ],
                                {},
                            ),
                            4: ("wagtail.blocks.ListBlock", (3,), {}),
                        },
                        help_text="Add judges recruiting details",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.enhancedstandardpage",),
        ),
    ]
