# Generated by Django 5.1.7 on 2025-04-02 14:48

import django.db.models.deletion
import wagtail.contrib.routable_page.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0032_directoryindex_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PressRelease",
            fields=[
                (
                    "enhancedstandardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.enhancedstandardpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "home.enhancedstandardpage",
            ),
        ),
    ]
