# Generated by Django 5.1.7 on 2025-04-04 16:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0032_directoryindex_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgesRecruiting",
            fields=[
                (
                    "enhancedstandardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.enhancedstandardpage",
                    ),
                ),
                (
                    "judges_recruiting",
                    wagtail.fields.StreamField(
                        [("message", 0), ("judge", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Default message to display when no judges are recruiting.",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("home.JudgeProfile",),
                                {"required": False},
                            ),
                            2: ("wagtail.blocks.RichTextBlock", (), {"blank": True}),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter a valid email.",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {
                                    "help_text": "Start displaying from this date",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {
                                    "help_text": "Stop displaying after this date",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("judge_name", 1),
                                        ("description", 2),
                                        ("apply_to_email", 3),
                                        ("display_from", 4),
                                        ("display_to", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: ("wagtail.blocks.ListBlock", (6,), {}),
                        },
                        help_text="Add judges recruiting details",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.enhancedstandardpage",),
        ),
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("snippet", 8),
                    ("hr", 9),
                    ("image", 10),
                    ("table", 11),
                    ("links", 19),
                    ("questionanswers", 21),
                    ("columns", 29),
                    ("embedded_video", 32),
                    ("card", 38),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    10: ("wagtail.images.blocks.ImageBlock", [], {}),
                    11: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    15: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    16: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 13),
                                ("document", 14),
                                ("video", 14),
                                ("url", 15),
                                ("text_only", 16),
                            ]
                        ],
                        {},
                    ),
                    18: ("wagtail.blocks.ListBlock", (17,), {}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 12), ("links", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 15), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.ListBlock",
                        (20,),
                        {
                            "help_text": "Add a question and answer with anchor tag for linking",
                            "label": "Question and Answer",
                        },
                    ),
                    22: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 15)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 15)]],
                        {"label": "Clickable Button"},
                    ),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 25), ("links", 18)]],
                        {"label": "Links"},
                    ),
                    27: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 4),
                                ("h3", 5),
                                ("hr", 22),
                                ("h2WithAnchorTag", 23),
                                ("clickableButton", 24),
                                ("links", 26),
                            ]
                        ],
                        {},
                    ),
                    28: ("wagtail.blocks.ListBlock", (27,), {}),
                    29: ("wagtail.blocks.StructBlock", [[("column", 28)]], {}),
                    30: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    31: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 15), ("description", 30), ("video_url", 31)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ]
                        },
                    ),
                    34: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    35: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    36: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 33),
                                ("title", 34),
                                ("description", 35),
                                ("color", 36),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    38: ("wagtail.blocks.ListBlock", (37,), {"label": "Card Set"}),
                },
            ),
        ),
    ]
