# Generated by Django 5.1.7 on 2025-04-08 14:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0033_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgesRecruiting",
            fields=[
                (
                    "enhancedstandardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.enhancedstandardpage",
                    ),
                ),
                (
                    "judges_recruiting",
                    wagtail.fields.StreamField(
                        [("message", 0), ("judge", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Default message to display when no judges are recruiting.",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("home.JudgeProfile",),
                                {"required": False},
                            ),
                            2: ("wagtail.blocks.RichTextBlock", (), {"blank": True}),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter a valid email.",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {
                                    "help_text": "Start displaying from this date",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {
                                    "help_text": "Stop displaying after this date",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("judge_name", 1),
                                        ("description", 2),
                                        ("apply_to_email", 3),
                                        ("display_from", 4),
                                        ("display_to", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: ("wagtail.blocks.ListBlock", (6,), {}),
                        },
                        help_text="Add judges recruiting details",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.enhancedstandardpage",),
        ),
        migrations.AlterModelOptions(
            name="judgeprofile",
            options={"ordering": ["last_name"]},
        ),
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("snippet", 8),
                    ("hr", 9),
                    ("image", 10),
                    ("table", 11),
                    ("list", 20),
                    ("links", 28),
                    ("questionanswers", 30),
                    ("columns", 38),
                    ("embedded_video", 40),
                    ("card", 46),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    10: ("wagtail.images.blocks.ImageBlock", [], {}),
                    11: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                            ],
                            "required": False,
                        },
                    ),
                    13: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 13), ("image", 10)]],
                        {},
                    ),
                    15: ("wagtail.blocks.ListBlock", (14,), {"default": []}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 12), ("items", 15)]],
                        {"required": False},
                    ),
                    17: ("wagtail.blocks.ListBlock", (16,), {"default": []}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 13), ("image", 10), ("nested_list", 17)]],
                        {"required": False},
                    ),
                    19: ("wagtail.blocks.ListBlock", (18,), {"default": []}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 12), ("items", 19)]],
                        {"label": "Nested List"},
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    24: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    25: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 22),
                                ("document", 23),
                                ("video", 23),
                                ("url", 24),
                                ("text_only", 25),
                            ]
                        ],
                        {},
                    ),
                    27: ("wagtail.blocks.ListBlock", (26,), {}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 21), ("links", 27)]],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 24), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.ListBlock",
                        (29,),
                        {
                            "help_text": "Add a question and answer with anchor tag for linking",
                            "label": "Question and Answer",
                        },
                    ),
                    31: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 24)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 24)]],
                        {"label": "Clickable Button"},
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 34), ("links", 27)]],
                        {"label": "Links"},
                    ),
                    36: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 4),
                                ("h3", 5),
                                ("hr", 31),
                                ("h2WithAnchorTag", 32),
                                ("clickableButton", 33),
                                ("links", 35),
                            ]
                        ],
                        {},
                    ),
                    37: ("wagtail.blocks.ListBlock", (36,), {}),
                    38: ("wagtail.blocks.StructBlock", [[("column", 37)]], {}),
                    39: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 24), ("description", 13), ("video_url", 39)]],
                        {},
                    ),
                    41: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ]
                        },
                    ),
                    42: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    43: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 41),
                                ("title", 42),
                                ("description", 43),
                                ("color", 44),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    46: ("wagtail.blocks.ListBlock", (45,), {"label": "Card Set"}),
                },
            ),
        ),
    ]
