# Generated by Django 5.1.3 on 2025-01-23 18:41

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_dawsonpage_dawson_dedication'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dawsonpage',
            name='dawson_dedication',
        ),
        migrations.CreateModel(
            name='PhotoDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title for the dedication', max_length=255)),
                ('paragraph_text', wagtail.fields.RichTextField(blank=True, help_text='Add the main paragraph text for the dedication section')),
                ('card', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_dedication', to='home.dawsonpage')),
                ('photo', models.ForeignKey(blank=True, help_text='Upload an image to display with this dedication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
    ]
