# Generated by Django 5.1.7 on 2025-04-08 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0034_judgesrecruiting_alter_judgeprofile_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVUploadPage",
            fields=[
                (
                    "enhancedstandardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.enhancedstandardpage",
                    ),
                ),
                ("csv_file", models.FileField(upload_to="csv_files/")),
            ],
            options={
                "abstract": False,
            },
            bases=("home.enhancedstandardpage",),
        ),
    ]
