# Generated by Django 5.1.7 on 2025-04-08 16:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0035_csvuploadpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("snippet", 8),
                    ("hr", 9),
                    ("image", 10),
                    ("table", 11),
                    ("list", 28),
                    ("links", 36),
                    ("questionanswers", 38),
                    ("columns", 46),
                    ("embedded_video", 48),
                    ("card", 54),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    10: ("wagtail.images.blocks.ImageBlock", [], {}),
                    11: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                            ],
                            "required": False,
                        },
                    ),
                    13: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 13), ("image", 10)]],
                        {"required": False},
                    ),
                    15: ("wagtail.blocks.ListBlock", (14,), {"default": []}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 12), ("items", 15)]],
                        {"required": False},
                    ),
                    17: ("wagtail.blocks.ListBlock", (16,), {"default": []}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 13), ("image", 10), ("nested_list", 17)]],
                        {"required": False},
                    ),
                    19: ("wagtail.blocks.ListBlock", (18,), {"default": []}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 12), ("items", 19)]],
                        {"required": False},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {"default": []}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 13), ("image", 10), ("nested_list", 21)]],
                        {"required": False},
                    ),
                    23: ("wagtail.blocks.ListBlock", (22,), {"default": []}),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 12), ("items", 23)]],
                        {"required": False},
                    ),
                    25: ("wagtail.blocks.ListBlock", (24,), {"default": []}),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 13), ("image", 10), ("nested_list", 25)]],
                        {"required": False},
                    ),
                    27: ("wagtail.blocks.ListBlock", (26,), {"default": []}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 12), ("items", 27)]],
                        {"required": False},
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    32: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    33: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 30),
                                ("document", 31),
                                ("video", 31),
                                ("url", 32),
                                ("text_only", 33),
                            ]
                        ],
                        {},
                    ),
                    35: ("wagtail.blocks.ListBlock", (34,), {}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 29), ("links", 35)]],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 32), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.ListBlock",
                        (37,),
                        {
                            "help_text": "Add a question and answer with anchor tag for linking",
                            "label": "Question and Answer",
                        },
                    ),
                    39: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 32)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 32)]],
                        {"label": "Clickable Button"},
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 42), ("links", 35)]],
                        {"label": "Links"},
                    ),
                    44: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 4),
                                ("h3", 5),
                                ("hr", 39),
                                ("h2WithAnchorTag", 40),
                                ("clickableButton", 41),
                                ("links", 43),
                            ]
                        ],
                        {},
                    ),
                    45: ("wagtail.blocks.ListBlock", (44,), {}),
                    46: ("wagtail.blocks.StructBlock", [[("column", 45)]], {}),
                    47: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 32), ("description", 13), ("video_url", 47)]],
                        {},
                    ),
                    49: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ]
                        },
                    ),
                    50: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    51: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    52: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 49),
                                ("title", 50),
                                ("description", 51),
                                ("color", 52),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    54: ("wagtail.blocks.ListBlock", (53,), {"label": "Card Set"}),
                },
            ),
        ),
    ]
