# Generated by Django 5.1.7 on 2025-04-10 20:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0036_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("snippet", 8),
                    ("hr", 9),
                    ("alert", 11),
                    ("image", 12),
                    ("table", 13),
                    ("unstyled_table", 13),
                    ("list", 30),
                    ("links", 38),
                    ("questionanswers", 40),
                    ("columns", 48),
                    ("embedded_video", 50),
                    ("card", 56),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success")]},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("alert_type", 10), ("content", 7)]],
                        {},
                    ),
                    12: ("wagtail.images.blocks.ImageBlock", [], {}),
                    13: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                            ],
                            "required": False,
                        },
                    ),
                    15: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 15), ("image", 12)]],
                        {"required": False},
                    ),
                    17: ("wagtail.blocks.ListBlock", (16,), {"default": []}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 14), ("items", 17)]],
                        {"required": False},
                    ),
                    19: ("wagtail.blocks.ListBlock", (18,), {"default": []}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 15), ("image", 12), ("nested_list", 19)]],
                        {"required": False},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {"default": []}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 14), ("items", 21)]],
                        {"required": False},
                    ),
                    23: ("wagtail.blocks.ListBlock", (22,), {"default": []}),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 15), ("image", 12), ("nested_list", 23)]],
                        {"required": False},
                    ),
                    25: ("wagtail.blocks.ListBlock", (24,), {"default": []}),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 14), ("items", 25)]],
                        {"required": False},
                    ),
                    27: ("wagtail.blocks.ListBlock", (26,), {"default": []}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 15), ("image", 12), ("nested_list", 27)]],
                        {"required": False},
                    ),
                    29: ("wagtail.blocks.ListBlock", (28,), {"default": []}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 14), ("items", 29)]],
                        {"required": False},
                    ),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    32: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    34: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    35: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 32),
                                ("document", 33),
                                ("video", 33),
                                ("url", 34),
                                ("text_only", 35),
                            ]
                        ],
                        {},
                    ),
                    37: ("wagtail.blocks.ListBlock", (36,), {}),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 31), ("links", 37)]],
                        {},
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 34), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    40: (
                        "wagtail.blocks.ListBlock",
                        (39,),
                        {
                            "help_text": "Add a question and answer with anchor tag for linking",
                            "label": "Question and Answer",
                        },
                    ),
                    41: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 34)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 34)]],
                        {"label": "Clickable Button"},
                    ),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 44), ("links", 37)]],
                        {"label": "Links"},
                    ),
                    46: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 4),
                                ("h3", 5),
                                ("hr", 41),
                                ("h2WithAnchorTag", 42),
                                ("clickableButton", 43),
                                ("links", 45),
                            ]
                        ],
                        {},
                    ),
                    47: ("wagtail.blocks.ListBlock", (46,), {}),
                    48: ("wagtail.blocks.StructBlock", [[("column", 47)]], {}),
                    49: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 34), ("description", 15), ("video_url", 49)]],
                        {},
                    ),
                    51: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ]
                        },
                    ),
                    52: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    53: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    54: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 51),
                                ("title", 52),
                                ("description", 53),
                                ("color", 54),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    56: ("wagtail.blocks.ListBlock", (55,), {"label": "Card Set"}),
                },
            ),
        ),
    ]
