# Generated by Django 5.1.7 on 2025-04-08 21:54

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0036_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="PressReleasePage",
            fields=[
                (
                    "enhancedstandardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.enhancedstandardpage",
                    ),
                ),
                (
                    "press_release_body",
                    wagtail.fields.StreamField(
                        [("button", 3), ("press_releases", 9)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Button text", "required": True},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Button link  (Can be relative or absolute)",
                                    "required": True,
                                },
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("primary", "Primary")],
                                    "help_text": "Choose the button style",
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("href", 1), ("style", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.DateBlock", (), {"required": False}),
                            5: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            6: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"required": False},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("description", 5), ("file", 6)]],
                                {"required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("release_date", 4), ("details", 7)]],
                                {},
                            ),
                            9: ("wagtail.blocks.ListBlock", (8,), {}),
                        },
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Press Release Page",
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "home.enhancedstandardpage",
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("snippet", 8),
                    ("button", 12),
                    ("hr", 13),
                    ("image", 14),
                    ("table", 15),
                    ("list", 32),
                    ("links", 40),
                    ("questionanswers", 42),
                    ("columns", 50),
                    ("embedded_video", 52),
                    ("card", 58),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "required": True},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button link  (Can be relative or absolute)",
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary")],
                            "help_text": "Choose the button style",
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 9), ("href", 10), ("style", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    14: ("wagtail.images.blocks.ImageBlock", [], {}),
                    15: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                            ],
                            "required": False,
                        },
                    ),
                    17: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 17), ("image", 14)]],
                        {"required": False},
                    ),
                    19: ("wagtail.blocks.ListBlock", (18,), {"default": []}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 16), ("items", 19)]],
                        {"required": False},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {"default": []}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 17), ("image", 14), ("nested_list", 21)]],
                        {"required": False},
                    ),
                    23: ("wagtail.blocks.ListBlock", (22,), {"default": []}),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 16), ("items", 23)]],
                        {"required": False},
                    ),
                    25: ("wagtail.blocks.ListBlock", (24,), {"default": []}),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 17), ("image", 14), ("nested_list", 25)]],
                        {"required": False},
                    ),
                    27: ("wagtail.blocks.ListBlock", (26,), {"default": []}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 16), ("items", 27)]],
                        {"required": False},
                    ),
                    29: ("wagtail.blocks.ListBlock", (28,), {"default": []}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 17), ("image", 14), ("nested_list", 29)]],
                        {"required": False},
                    ),
                    31: ("wagtail.blocks.ListBlock", (30,), {"default": []}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 16), ("items", 31)]],
                        {"required": False},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    36: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    37: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 34),
                                ("document", 35),
                                ("video", 35),
                                ("url", 36),
                                ("text_only", 37),
                            ]
                        ],
                        {},
                    ),
                    39: ("wagtail.blocks.ListBlock", (38,), {}),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 33), ("links", 39)]],
                        {},
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 36), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    42: (
                        "wagtail.blocks.ListBlock",
                        (41,),
                        {
                            "help_text": "Add a question and answer with anchor tag for linking",
                            "label": "Question and Answer",
                        },
                    ),
                    43: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 36)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 36)]],
                        {"label": "Clickable Button"},
                    ),
                    46: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 46), ("links", 39)]],
                        {"label": "Links"},
                    ),
                    48: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 4),
                                ("h3", 5),
                                ("hr", 43),
                                ("h2WithAnchorTag", 44),
                                ("clickableButton", 45),
                                ("links", 47),
                            ]
                        ],
                        {},
                    ),
                    49: ("wagtail.blocks.ListBlock", (48,), {}),
                    50: ("wagtail.blocks.StructBlock", [[("column", 49)]], {}),
                    51: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 36), ("description", 17), ("video_url", 51)]],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ]
                        },
                    ),
                    54: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    55: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    56: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 53),
                                ("title", 54),
                                ("description", 55),
                                ("color", 56),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    58: ("wagtail.blocks.ListBlock", (57,), {"label": "Card Set"}),
                },
            ),
        ),
    ]
