# Generated by Django 5.1.7 on 2025-04-11 21:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0038_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseNotes",
            fields=[
                (
                    "enhancedstandardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.enhancedstandardpage",
                    ),
                ),
                (
                    "paragraph",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Introduction or description for the release notes",
                    ),
                ),
                (
                    "release_entries",
                    wagtail.fields.StreamField(
                        [("release_entry", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {"help_text": "Date of the release", "required": True},
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Description or details of the release",
                                    "required": True,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("release_date", 0), ("description", 1)]],
                                {},
                            ),
                        },
                        help_text="List of release entries with date and description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Release Notes",
                "verbose_name_plural": "Release Notes",
            },
            bases=("home.enhancedstandardpage",),
        ),
    ]
