# Generated by Django 5.1.7 on 2025-04-14 17:34

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0038_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseNotes",
            fields=[
                (
                    "enhancedstandardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.enhancedstandardpage",
                    ),
                ),
                (
                    "paragraph",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Introduction or description for the release notes",
                    ),
                ),
                (
                    "release_entries",
                    wagtail.fields.StreamField(
                        [("release_entry", 20)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {"help_text": "Date of the release", "required": True},
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Description or details of the release",
                                    "required": True,
                                },
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("ordered", "Ordered List"),
                                        ("unordered", "Unordered List"),
                                    ],
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"required": False},
                            ),
                            4: ("wagtail.images.blocks.ImageBlock", [], {}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 3), ("image", 4)]],
                                {"required": False},
                            ),
                            6: ("wagtail.blocks.ListBlock", (5,), {"default": []}),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("list_type", 2), ("items", 6)]],
                                {"required": False},
                            ),
                            8: ("wagtail.blocks.ListBlock", (7,), {"default": []}),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 3), ("image", 4), ("nested_list", 8)]],
                                {"required": False},
                            ),
                            10: ("wagtail.blocks.ListBlock", (9,), {"default": []}),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("list_type", 2), ("items", 10)]],
                                {"required": False},
                            ),
                            12: ("wagtail.blocks.ListBlock", (11,), {"default": []}),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 3), ("image", 4), ("nested_list", 12)]],
                                {"required": False},
                            ),
                            14: ("wagtail.blocks.ListBlock", (13,), {"default": []}),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("list_type", 2), ("items", 14)]],
                                {"required": False},
                            ),
                            16: ("wagtail.blocks.ListBlock", (15,), {"default": []}),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 3), ("image", 4), ("nested_list", 16)]],
                                {"required": False},
                            ),
                            18: ("wagtail.blocks.ListBlock", (17,), {"default": []}),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [[("list_type", 2), ("items", 18)]],
                                {"required": False},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("release_date", 0),
                                        ("description", 1),
                                        ("list", 19),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="List of release entries with date and description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Release Notes",
                "verbose_name_plural": "Release Notes",
            },
            bases=("home.enhancedstandardpage",),
        ),
    ]
