# Generated by Django 5.1.7 on 2025-04-15 14:26

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0039_releasenotes"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternshipPrograms",
            fields=[
                (
                    "enhancedstandardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.enhancedstandardpage",
                    ),
                ),
                (
                    "internship_programs",
                    wagtail.fields.StreamField(
                        [("h2", 0), ("paragraph", 1), ("internship", 9)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"required": False},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title"},
                            ),
                            4: (
                                "wagtail.blocks.StreamBlock",
                                [[("h2", 3), ("paragraph", 1)]],
                                {"required": False},
                            ),
                            5: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "A simple paragraph of text.",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {
                                    "help_text": "Start displaying this internship",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {
                                    "help_text": "Closing date for this internship",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Link to external internship posting",
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("description", 2),
                                        ("section", 4),
                                        ("paragraph", 5),
                                        ("display_from", 6),
                                        ("closing_date", 7),
                                        ("external_link", 8),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Internship Programs Details",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.enhancedstandardpage",),
        ),
    ]
