# Generated by Django 5.1.7 on 2025-04-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0040_internshipprograms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simplecard",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="relatedpage",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="Optional URL to link to when the card is clicked.",
                max_length=255,
                null=True,
            ),
        ),
    ]
