# Generated by Django 5.1.7 on 2025-04-15 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0040_internshipprograms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simplecard",
            options={"ordering": ["id"]},
        ),
    ]
