# Generated by Django 5.1.7 on 2025-04-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0042_placesoftrialpage_alter_directoryindex_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepageentry",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
