# Generated by Django 5.1.7 on 2025-04-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0044_alter_directoryindex_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgecollection",
            name="name",
            field=models.CharField(
                help_text="Name of this collection (e.g., 'Featured Judges', 'Tax Court Judges')",
                max_length=255,
                unique=True,
            ),
        ),
    ]
