# Generated by Django 5.1.7 on 2025-05-01 19:32

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0045_alter_judgecollection_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepageentry",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepageentry",
            name="persist_to_press_releases",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="homepageentry",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="homepageentry",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="homepageentry",
            name="title",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
