# Generated by Django 5.1.7 on 2025-05-02 12:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0046_alter_enhancedstandardpage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepageentry",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepageentry",
            name="persist_to_press_releases",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="homepageentry",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="homepageentry",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="homepageentry",
            name="title",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
