# Generated by Django 5.1.7 on 2025-05-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0047_homepageentry_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepageentry",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="homepageentry",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
