# Generated by Django 5.1.7 on 2025-05-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0047_homepageentry_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepageentry",
            name="order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
