# Generated by Django 5.1.7 on 2025-05-06 22:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0048_homepageentry_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepageentry",
            options={"ordering": ["order"]},
        ),
    ]
