# Generated by Django 5.1.7 on 2025-05-15 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0049_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgecollectionorderable",
            name="judge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_orderables",
                to="home.judgeprofile",
            ),
        ),
    ]
