# Generated by Django 5.1.7 on 2025-05-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0049_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepageentry",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="homepageentry",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
