# Generated by Django 5.1.7 on 2025-05-15 19:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0049_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directoryindex",
            name="body",
            field=wagtail.fields.StreamField(
                [("directory", 18)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {}),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("anchortag", 4)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("url", 4)]],
                        {"label": "Clickable Button"},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    10: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("icon", 8),
                                ("document", 9),
                                ("video", 9),
                                ("anchor", 4),
                                ("url", 4),
                                ("text_only", 10),
                            ]
                        ],
                        {},
                    ),
                    12: ("wagtail.blocks.ListBlock", (11,), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 7), ("links", 12)]],
                        {"label": "Links"},
                    ),
                    14: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (),
                        {
                            "help_text": "Optionally pick a JudgeCollection snippet",
                            "label": "Judge Collection",
                            "required": False,
                            "target_model": "home.JudgeCollection",
                        },
                    ),
                    15: ("wagtail.blocks.RichTextBlock", (), {}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("description", 15), ("phone_number", 3)]],
                        {},
                    ),
                    17: ("wagtail.blocks.ListBlock", (16,), {}),
                    18: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 0),
                                ("h3", 1),
                                ("hr", 2),
                                ("h2WithAnchorTag", 5),
                                ("clickableButton", 6),
                                ("links", 13),
                                ("JudgeCollection", 14),
                                ("DirectoryEntry", 17),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Directory entries or judge profiles",
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("snippet", 8),
                    ("button", 12),
                    ("hr", 13),
                    ("iframe", 17),
                    ("alert", 19),
                    ("image", 20),
                    ("photo_dedication", 25),
                    ("table", 26),
                    ("unstyled_table", 26),
                    ("list", 43),
                    ("links", 50),
                    ("questionanswers", 52),
                    ("columns", 60),
                    ("embedded_video", 62),
                    ("card", 67),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "required": True},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button link  (Can be relative or absolute)",
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary")],
                            "help_text": "Choose the button style",
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 9), ("href", 10), ("style", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    14: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    15: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    16: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("src", 14),
                                ("width", 15),
                                ("height", 15),
                                ("class", 16),
                                ("loading", 16),
                                ("data_delay", 16),
                                ("name", 16),
                                ("title", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success")]},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("alert_type", 18), ("content", 7)]],
                        {},
                    ),
                    20: ("wagtail.images.blocks.ImageBlock", [], {}),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    22: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {
                            "help_text": "Upload an image to display with this dedication"
                        },
                    ),
                    23: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Provide alternative text for the image for accessibility.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 21),
                                ("photo", 22),
                                ("paragraph_text", 23),
                                ("alt_text", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                            ],
                            "required": False,
                        },
                    ),
                    28: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 28), ("image", 20)]],
                        {"required": False},
                    ),
                    30: ("wagtail.blocks.ListBlock", (29,), {"default": []}),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 27), ("items", 30)]],
                        {"required": False},
                    ),
                    32: ("wagtail.blocks.ListBlock", (31,), {"default": []}),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 28), ("image", 20), ("nested_list", 32)]],
                        {"required": False},
                    ),
                    34: ("wagtail.blocks.ListBlock", (33,), {"default": []}),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 27), ("items", 34)]],
                        {"required": False},
                    ),
                    36: ("wagtail.blocks.ListBlock", (35,), {"default": []}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 28), ("image", 20), ("nested_list", 36)]],
                        {"required": False},
                    ),
                    38: ("wagtail.blocks.ListBlock", (37,), {"default": []}),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 27), ("items", 38)]],
                        {"required": False},
                    ),
                    40: ("wagtail.blocks.ListBlock", (39,), {"default": []}),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 28), ("image", 20), ("nested_list", 40)]],
                        {"required": False},
                    ),
                    42: ("wagtail.blocks.ListBlock", (41,), {"default": []}),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 27), ("items", 42)]],
                        {"required": False},
                    ),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ]
                        },
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    46: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    47: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 45),
                                ("document", 46),
                                ("video", 46),
                                ("anchor", 16),
                                ("url", 16),
                                ("text_only", 47),
                            ]
                        ],
                        {},
                    ),
                    49: ("wagtail.blocks.ListBlock", (48,), {}),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 44), ("links", 49)]],
                        {},
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 16), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    52: (
                        "wagtail.blocks.ListBlock",
                        (51,),
                        {
                            "help_text": "Add a question and answer with anchor tag for linking",
                            "label": "Question and Answer",
                        },
                    ),
                    53: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 16)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 16)]],
                        {"label": "Clickable Button"},
                    ),
                    56: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 56), ("links", 49)]],
                        {"label": "Links"},
                    ),
                    58: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 4),
                                ("h3", 5),
                                ("hr", 53),
                                ("h2WithAnchorTag", 54),
                                ("clickableButton", 55),
                                ("links", 57),
                            ]
                        ],
                        {},
                    ),
                    59: ("wagtail.blocks.ListBlock", (58,), {}),
                    60: ("wagtail.blocks.StructBlock", [[("column", 59)]], {}),
                    61: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 16), ("description", 28), ("video_url", 61)]],
                        {},
                    ),
                    63: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ]
                        },
                    ),
                    64: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    65: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 63),
                                ("title", 15),
                                ("description", 64),
                                ("color", 65),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    67: ("wagtail.blocks.ListBlock", (66,), {"label": "Card Set"}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="judgeindex",
            name="body",
            field=wagtail.fields.StreamField(
                [("columns", 17)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {}),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("anchortag", 4)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("url", 4)]],
                        {"label": "Clickable Button"},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    10: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("icon", 8),
                                ("document", 9),
                                ("video", 9),
                                ("anchor", 4),
                                ("url", 4),
                                ("text_only", 10),
                            ]
                        ],
                        {},
                    ),
                    12: ("wagtail.blocks.ListBlock", (11,), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 7), ("links", 12)]],
                        {"label": "Links"},
                    ),
                    14: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (),
                        {
                            "help_text": "Optionally pick a JudgeCollection snippet",
                            "label": "Judge Collection",
                            "required": False,
                            "target_model": "home.JudgeCollection",
                        },
                    ),
                    15: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 0),
                                ("h3", 1),
                                ("hr", 2),
                                ("h2WithAnchorTag", 5),
                                ("clickableButton", 6),
                                ("links", 13),
                                ("judgeCollection", 14),
                            ]
                        ],
                        {},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: ("wagtail.blocks.StructBlock", [[("column", 16)]], {}),
                },
                help_text="Add judge profiles or collections to display on this page",
            ),
        ),
    ]
