# Generated by Django 5.1.7 on 2025-06-05 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0051_alter_judgecollectionorderable_judge"),
        ("wagtaildocs", "0014_alter_document_file_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancyentry",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                help_text="Upload a PDF or Word doc of the vacancy",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtaildocs.document",
            ),
        ),
        migrations.AddField(
            model_name="vacancyentry",
            name="closing_date_text",
            field=models.CharField(
                blank=True,
                default="Until the position is filled",
                help_text='Text for closing date display, e.g., "June 30, 2025 or until filled"',
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vacancyentry",
            name="closing_date",
            field=models.DateField(
                blank=True, help_text="Closing date for the vacancy", null=True
            ),
        ),
        migrations.AlterField(
            model_name="vacancyentry",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Link to the vacancy announcement",
                max_length=255,
                null=True,
            ),
        ),
    ]
