# Generated by Django 5.1.7 on 2025-06-10 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0052_vacancyentry_attachment_and_more"),
        ("wagtaildocs", "0014_alter_document_file_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancyentry",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                help_text="Upload a PDF or Word doc of the vacancy (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtaildocs.document",
            ),
        ),
        migrations.AlterField(
            model_name="vacancyentry",
            name="closing_date",
            field=models.DateField(
                blank=True,
                help_text="Closing date that the vacancy will no longer appear on the Vacancy announcement page.",
                null=True,
            ),
        ),
    ]
