# Generated by Django 5.1.7 on 2025-06-26 02:49

from django.db import migrations


def fix_petitioner_about_page(apps, schema_editor):
    """Fix the petitioner about page by updating it through the proper model"""
    # Get models
    Page = apps.get_model("wagtailcore", "Page")

    # Updated questions with document links
    questions = [
        {
            "question": "What is the United States Tax Court?",
            "answer": "The United States Tax Court is a Federal trial court. Because it is a court of record, a record is made of all its proceedings. It is an independent judicial forum. It is not controlled by or connected with the Internal Revenue Service (IRS). Congress created the Tax Court as an independent judicial authority for taxpayers disputing certain IRS determinations. The Tax Court's authority to resolve these disputes is called its jurisdiction. Generally, a taxpayer may file a petition in the Tax Court in response to certain IRS determinations. A taxpayer who begins such a proceeding is known as the \"petitioner\", and the Commissioner of Internal Revenue is the \"respondent\". <br><br>The Tax Court is based in Washington, D.C. Its <strong><a href='/judges' title='Judges'>Judges</a></strong> and <strong><a href='/judges' title='Judges'>Special Trial Judges</a></strong> preside at trials in 74 U.S. <strong><a href='/dpt-cities' title='Places of Trial'>cities</a></strong>.",
            "anchortag": "ABOUT1",
        },
        {
            "question": "What are the Tax Court's hours of operation?",
            "answer": 'The Tax Court is open from 8 a.m. to 4:30 p.m. (EST) on all days except Saturdays, Sundays, and <strong><a href="/holidays" title="Legal holidays">legal holidays</a></strong> in the District of Columbia.',
            "anchortag": "ABOUT2",
        },
        {
            "question": "What is the life cycle of a Tax Court case?",
            "answer": 'A case in the Tax Court is commenced by the filing of a petition. The petition must be timely filed within the allowable time. The Court cannot extend the time for filing which is set by statute.<br><br>A $60 filing fee must be paid when the petition is filed. Once the petition is filed, payment of the underlying tax ordinarily is postponed until the case has been decided.<br><br>In certain tax disputes involving $50,000 or less, taxpayers may elect to have their case conducted under the Court\'s simplified <strong><a href="/files/documents/Petition_Kit.pdf" target="_blank" title="Petition Kit">small tax case procedure</a></strong>. Trials in small tax cases generally are less formal and result in a speedier disposition. However, decisions entered pursuant to small tax case procedures are not appealable.<br><br>Cases are calendared for trial as soon as practicable (on a first in/ first out basis) after the case becomes at issue. When a case is calendared, the parties are notified by the Court of the date, time, and place of trial. Trials are conducted before one judge, without a jury, and taxpayers are permitted to represent themselves if they desire. Taxpayers may be represented by practitioners admitted to the bar of the Tax Court.<br><br>Most cases are settled by mutual agreement without trial. However, if a trial is conducted, in due course a report is ordinarily issued by the presiding judge setting forth findings of fact and an opinion. The case is then closed in accordance with the judge\'s opinion by entry of a decision.',
            "anchortag": "ABOUT3",
        },
        {
            "question": "How can I obtain information about the history of the Tax Court?",
            "answer": 'The revised and expanded <strong><em><a href="/files/documents/Dubroff_Hellwig.pdf" target="_blank" title="The United States Tax Court: An Historical Analysis (Second Edition)">The United States Tax Court: An Historical Analysis (Second Edition)</a></em></strong> by Professors Harold Dubroff and Brant J. Hellwig is available as a <strong><a href="/files/documents/Dubroff_Hellwig.pdf" target="_blank"> PDF download</a></strong> (6MB) or at the <strong><a href="https://bookstore.gpo.gov/user/login?destination=node/10107" target="_blank" title="Government Printing Office bookstore">Government Printing Office bookstore</a></strong> in print and other e-pub formats.',
            "anchortag": "ABOUT4",
        },
    ]

    # Find the page by slug
    petitioner_page = Page.objects.filter(slug="petitioners-about").first()

    if petitioner_page:
        # Get the specific page model based on content_type
        content_type = petitioner_page.content_type
        model_class = apps.get_model(content_type.app_label, content_type.model)

        # Get the specific page instance
        specific_page = model_class.objects.get(page_ptr=petitioner_page)

        # Update the fields
        specific_page.body = [
            {"type": "h2", "value": "About the Court"},
            {"type": "questionanswers", "value": questions},
        ]
        specific_page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0056_judgecollection_expire_at_judgecollection_expired_and_more"),
        ("wagtailcore", "__latest__"),
    ]

    operations = [
        migrations.RunPython(
            code=fix_petitioner_about_page,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
