# Generated by Django 5.1.7 on 2025-06-25 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0056_fancycard_expire_at_fancycard_expired_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fancycard",
            name="expire_at",
        ),
        migrations.RemoveField(
            model_name="fancycard",
            name="expired",
        ),
        migrations.RemoveField(
            model_name="fancycard",
            name="first_published_at",
        ),
        migrations.RemoveField(
            model_name="fancycard",
            name="go_live_at",
        ),
        migrations.RemoveField(
            model_name="fancycard",
            name="has_unpublished_changes",
        ),
        migrations.RemoveField(
            model_name="fancycard",
            name="last_published_at",
        ),
        migrations.RemoveField(
            model_name="fancycard",
            name="latest_revision",
        ),
        migrations.RemoveField(
            model_name="fancycard",
            name="live",
        ),
        migrations.RemoveField(
            model_name="fancycard",
            name="live_revision",
        ),
        migrations.RemoveField(
            model_name="simplecard",
            name="expire_at",
        ),
        migrations.RemoveField(
            model_name="simplecard",
            name="expired",
        ),
        migrations.RemoveField(
            model_name="simplecard",
            name="first_published_at",
        ),
        migrations.RemoveField(
            model_name="simplecard",
            name="go_live_at",
        ),
        migrations.RemoveField(
            model_name="simplecard",
            name="has_unpublished_changes",
        ),
        migrations.RemoveField(
            model_name="simplecard",
            name="last_published_at",
        ),
        migrations.RemoveField(
            model_name="simplecard",
            name="latest_revision",
        ),
        migrations.RemoveField(
            model_name="simplecard",
            name="live",
        ),
        migrations.RemoveField(
            model_name="simplecard",
            name="live_revision",
        ),
    ]
