# Generated by Django 5.1.7 on 2025-06-25 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0057_remove_fancycard_expire_at_remove_fancycard_expired_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FancyCard",
            new_name="DawsonFancyCard",
        ),
        migrations.RenameModel(
            old_name="SimpleCard",
            new_name="DawsonSimpleCard",
        ),
    ]
