# Generated by Django 5.1.7 on 2025-07-07 19:13

from django.db import migrations
import re

tags_names = [
    "Review and approve all content",
    "Backup publisher",
    "All things technical",
    "Administrative Orders",
    "Cases Commenced in the Court of Appeals",
    "Citation and Style Manual",
    "Clinics",
    "DAWSON Training Guides",
    "Directory",
    "Discipline",
    "Engagement & Outreach",
    "Events and Webinars",
    "Fees & Charges",
    "Forms",
    "Guidance for Petitioners",
    "Guidance for Practitioners",
    "History",
    "Internship Programs",
    "Judges & Bios",
    "Judicial Conduct and Disability Procedures",
    "Law Clerk Programs",
    "LITC",
    "Mission Statement",
    "Pamphlets",
    "Press Releases",
    "Pro Bono Programs",
    "Records (Transcripts & Copies)",
    "DAWSON Release Notes",
    "Remote Proceedings",
    "Reports & Statistics",
    "Rules Comments and Suggestions",
    "Tax Court Reports",
    "Tax Court Rules",
    "Trial Sessions",
    "Vacancy Announcements",
]


def create_slug(name):
    name = name.lower()
    name = re.sub(r"\s+", "-", name)
    return name


def create_tags(apps, schema_editor):
    Tag = apps.get_model("taggit", "Tag")
    for tag_name in tags_names:
        slug = create_slug(tag_name)
        # Use the slug to check for existence, and provide the name as a default
        # for creation. This avoids the unique constraint error.
        Tag.objects.get_or_create(slug=slug, defaults={"name": tag_name})


def remove_tags(apps, schema_editor):
    Tag = apps.get_model("taggit", "Tag")
    # Create a list of slugs to safely identify the tags to be removed.
    slugs_to_remove = [create_slug(tag_name) for tag_name in tags_names]
    Tag.objects.filter(slug__in=slugs_to_remove).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0057_fix_petitioner_about_page"),
        ("taggit", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_tags, remove_tags),
    ]
