# Generated by Django 5.1.7 on 2025-07-07 19:13

from django.db import migrations
import re
from home.data.tag_and_collection_names import TAGS_AND_COLLECTION_NAMES


def create_slug(name):
    name = name.lower()
    name = re.sub(r"\s+", "-", name)
    return name


def create_tags(apps, schema_editor):
    Tag = apps.get_model("taggit", "Tag")
    for tag_name in TAGS_AND_COLLECTION_NAMES:
        slug = create_slug(tag_name)
        # Use the slug to check for existence, and provide the name as a default
        # for creation. This avoids the unique constraint error.
        Tag.objects.get_or_create(slug=slug, defaults={"name": tag_name})


def remove_tags(apps, schema_editor):
    Tag = apps.get_model("taggit", "Tag")
    # Create a list of slugs to safely identify the tags to be removed.
    slugs_to_remove = [create_slug(tag_name) for tag_name in TAGS_AND_COLLECTION_NAMES]
    Tag.objects.filter(slug__in=slugs_to_remove).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0058_fix_inline_pdf_links"),
        ("taggit", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_tags, remove_tags),
    ]
