# Generated by Django 5.1.7 on 2025-07-10 16:04

from django.db import migrations

collection_sorting_order = [
    "Press Releases",
    "Pamphlets",
    "Tax Court Reports",
    "Tax Court Rules",
    "DAWSON Training Guides",
    "Release Notes",
    "Vacancy Announcements",
    "Guidance for Petitioners",
    "Guidance for Practitioners",
    "Trial Sessions",
    "Judges & Bios",
    "Directory",
    "Law Clerk Programs",
    "Administrative Orders",
    "Cases Commenced in the Court of Appeals",
    "Citation and style manual",
    "Clinics",
    "Discipline",
    "Events and Webinars",
    "Fees & Charges",
    "Forms",
    "History",
    "Internship Programs",
    "Judicial Conduct and Disability Procedures",
    "LITC",
    "Mission Statement",
    "Pro Bono Programs",
    "Records (Transcripts & Copies)",
    "Remote Proceedings",
    "Engagement & Outreach",
    "Reports & Statistics",
    "Rules Comments and Suggestions",
]

document_tags_map = {
    "010301.pdf": {"tags": ["Press Releases"]},
    "010318.pdf": {"tags": ["Press Releases"]},
    "010501.pdf": {"tags": ["Press Releases"]},
    "011116.pdf": {"tags": ["Press Releases", "Rules Comments and Suggestions"]},
    "01112021.pdf": {"tags": ["Press Releases"]},
    "011207.pdf": {"tags": ["Press Releases", "Tax Court Rules"]},
    "01122022.pdf": {"tags": ["Press Releases"]},
    "011508.pdf": {"tags": ["Press Releases", "Tax Court Rules"]},
    "01152020.pdf": {"tags": ["Press Releases", "Tax Court Rules"]},
    "011607.pdf": {"tags": ["Press Releases"]},
    "011702.pdf": {"tags": ["Press Releases"]},
    "01222024.pdf": {"tags": ["Press Releases", "Rules Comments and Suggestions"]},
    "01242022.pdf": {"tags": ["Press Releases"]},
    "012619.pdf": {"tags": ["Press Releases"]},
    "01262022.pdf": {"tags": ["Press Releases"]},
    "012706.pdf": {"tags": ["Press Releases"]},
    "01282025.pdf": {"tags": ["Press Releases", "Guidance for Practitioners"]},
    "02012022.pdf": {"tags": ["Press Releases"]},
    "020419.pdf": {"tags": ["Press Releases"]},
    "021003.pdf": {"tags": ["Press Releases"]},
    "02122021.pdf": {"tags": ["Press Releases"]},
    "021607_release.pdf": {"tags": ["Press Releases"]},
    "02162024.pdf": {"tags": ["Press Releases"]},
    "021717.pdf": {"tags": ["Press Releases"]},
    "02182022.pdf": {"tags": ["Press Releases"]},
    "021916.pdf": {"tags": ["Press Releases"]},
    "02202024.pdf": {"tags": ["Press Releases"]},
    "02212020.pdf": {"tags": ["Press Releases"]},
    "02212025.pdf": {"tags": ["Press Releases"]},
    "022304.pdf": {"tags": ["Press Releases"]},
    "02232021.pdf": {"tags": ["Press Releases"]},
    "022415.pdf": {"tags": ["Press Releases"]},
    "02242020.pdf": {"tags": ["Press Releases"]},
    "022502.pdf": {"tags": ["Press Releases"]},
    "02252022.pdf": {"tags": ["Press Releases"]},
    "022618.pdf": {"tags": ["Press Releases"]},
    "022800.pdf": {"tags": ["Press Releases"]},
    "022806.pdf": {"tags": ["Press Releases"]},
    "022916.pdf": {"tags": ["Press Releases"]},
    "030612.pdf": {"tags": ["Press Releases"]},
    "03082022.pdf": {"tags": ["Press Releases"]},
    "03112020.pdf": {"tags": ["Press Releases"]},
    "03132020.pdf": {"tags": ["Press Releases"]},
    "03142024.pdf": {"tags": ["Press Releases"]},
    "031519.pdf": {"tags": ["Press Releases"]},
    "031811.pdf": {"tags": ["Press Releases"]},
    "03182020.pdf": {"tags": ["Press Releases"]},
    "032000.pdf": {"tags": ["Press Releases"]},
    "03202023.pdf": {
        "tags": ["Press Releases", "Rules Comments and Suggestions", "Tax Court Rules"]
    },
    "03232020.pdf": {"tags": ["Press Releases"]},
    "03232022.pdf": {"tags": ["Press Releases", "Rules Comments and Suggestions"]},
    "032416.pdf": {"tags": ["Press Releases"]},
    "032612.pdf": {"tags": ["Press Releases"]},
    "032709.pdf": {"tags": ["Press Releases"]},
    "032816.pdf": {"tags": ["Press Releases"]},
    "04012022.pdf": {"tags": ["Press Releases"]},
    "040307.pdf": {"tags": ["Press Releases", "Tax Court Rules"]},
    "040402.pdf": {"tags": ["Press Releases"]},
    "04052021.pdf": {"tags": ["Press Releases"]},
    "04072025.pdf": {"tags": ["Press Releases"]},
    "041300.pdf": {"tags": ["Press Releases"]},
    "041317.pdf": {"tags": ["Press Releases"]},
    "04162025.pdf": {"tags": ["Press Releases"]},
    "041712.pdf": {"tags": ["Press Releases"]},
    "041918.pdf": {"tags": ["Press Releases"]},
    "04212020_1.pdf": {"tags": ["Press Releases"]},
    "04212020_2.pdf": {"tags": ["Press Releases"]},
    "042203_Goeke.pdf": {"tags": ["Press Releases"]},
    "042203_Haines.pdf": {"tags": ["Press Releases"]},
    "042415.pdf": {"tags": ["Press Releases"]},
    "042514.pdf": {"tags": ["Press Releases"]},
    "04252024.pdf": {"tags": ["Press Releases"]},
    "042607.pdf": {"tags": ["Press Releases"]},
    "042700.pdf": {"tags": ["Press Releases"]},
    "042803_Wherry.pdf": {"tags": ["Press Releases"]},
    "04292025.pdf": {"tags": ["Press Releases", "Guidance for Practitioners"]},
    "043008.pdf": {"tags": ["Press Releases"]},
    "043012.pdf": {"tags": ["Press Releases"]},
    "050306.pdf": {"tags": ["Press Releases"]},
    "05042020.pdf": {"tags": ["Press Releases"]},
    "050511.pdf": {"tags": ["Press Releases", "Tax Court Rules"]},
    "05052010_exam.pdf": {"tags": ["Press Releases"]},
    "05052025.pdf": {"tags": ["Press Releases", "Guidance for Practitioners"]},
    "050616.pdf": {"tags": ["Press Releases"]},
    "050712.pdf": {"tags": ["Press Releases"]},
    "05072020.pdf": {"tags": ["Press Releases"]},
    "050812.pdf": {"tags": ["Press Releases"]},
    "050818.pdf": {"tags": ["Press Releases"]},
    "05082023.pdf": {"tags": ["Press Releases"]},
    "051019.pdf": {"tags": ["Press Releases"]},
    "051217.pdf": {"tags": ["Press Releases"]},
    "051314.pdf": {"tags": ["Press Releases"]},
    "051704_Electronic_Courtroom.pdf": {"tags": ["Press Releases"]},
    "051719.pdf": {"tags": ["Press Releases"]},
    "05172021.pdf": {"tags": ["Press Releases"]},
    "05182020.pdf": {"tags": ["Press Releases", "Rules Comments and Suggestions"]},
    "05212021.pdf": {"tags": ["Press Releases"]},
    "052915.pdf": {"tags": ["Press Releases"]},
    "05292020_copywork.pdf": {"tags": ["Press Releases"]},
    "05292020_proceedings.pdf": {"tags": ["Press Releases"]},
    "05302024.pdf": {"tags": ["Press Releases", "Guidance for Practitioners"]},
    "053116.pdf": {"tags": ["Press Releases"]},
    "060208.pdf": {"tags": ["Press Releases"]},
    "06032022.pdf": {"tags": ["Press Releases"]},
    "061119.pdf": {"tags": ["Press Releases"]},
    "061212.pdf": {"tags": ["Press Releases"]},
    "061416.pdf": {"tags": ["Press Releases"]},
    "061703_Kroupa.pdf": {"tags": ["Press Releases"]},
    "061711.pdf": {"tags": ["Press Releases"]},
    "06192020.pdf": {"tags": ["Press Releases"]},
    "062005.pdf": {"tags": ["Press Releases"]},
    "06222020.pdf": {"tags": ["Press Releases"]},
    "062304.pdf": {"tags": ["Press Releases"]},
    "06242020.pdf": {"tags": ["Press Releases"]},
    "06242022.pdf": {"tags": ["Press Releases"]},
    "062513.pdf": {"tags": ["Press Releases"]},
    "062612.pdf": {"tags": ["Press Releases"]},
    "063003.pdf": {"tags": ["Press Releases", "Tax Court Rules"]},
    "063003_Holmes.pdf": {"tags": ["Press Releases"]},
    "070115.pdf": {"tags": ["Press Releases"]},
    "070612.pdf": {"tags": ["Press Releases", "Tax Court Rules"]},
    "070705.pdf": {"tags": ["Press Releases"]},
    "071219.pdf": {"tags": ["Press Releases"]},
    "071312.pdf": {"tags": ["Press Releases"]},
    "071519.pdf": {
        "tags": ["Press Releases", "Rules Comments and Suggestions", "Tax Court Rules"]
    },
    "07172020.pdf": {"tags": ["Press Releases"]},
    "071814.pdf": {"tags": ["Press Releases"]},
    "071816.pdf": {"tags": ["Press Releases"]},
    "072018.pdf": {"tags": ["Press Releases"]},
    "07202020.pdf": {"tags": ["Press Releases"]},
    "07232021.pdf": {"tags": ["Press Releases"]},
    "080408_Gustafson.pdf": {"tags": ["Press Releases"]},
    "08042023.pdf": {"tags": ["Press Releases"]},
    "080615.pdf": {"tags": ["Press Releases"]},
    "08062020.pdf": {"tags": ["Press Releases"]},
    "08082024bv2.pdf": {"tags": ["Press Releases"]},
    "08082024v3.pdf": {
        "tags": ["Press Releases", "Rules Comments and Suggestions", "Tax Court Rules"]
    },
    "08162021.pdf": {"tags": ["Press Releases"]},
    "08172020.pdf": {"tags": ["Press Releases"]},
    "08232022.pdf": {"tags": ["Press Releases"]},
    "08252022.pdf": {"tags": ["Press Releases"]},
    "08272021.pdf": {"tags": ["Press Releases"]},
    "08282023.pdf": {"tags": ["Press Releases"]},
    "083007.pdf": {"tags": ["Press Releases"]},
    "083117.pdf": {"tags": ["Press Releases"]},
    "090105.pdf": {"tags": ["Press Releases"]},
    "090419.pdf": {"tags": ["Press Releases"]},
    "090514.pdf": {"tags": ["Press Releases"]},
    "090618.pdf": {"tags": ["Press Releases"]},
    "09092020.pdf": {"tags": ["Press Releases"]},
    "091112.pdf": {"tags": ["Press Releases"]},
    "091206.pdf": {"tags": ["Press Releases"]},
    "091517.pdf": {"tags": ["Press Releases"]},
    "091809.pdf": {"tags": ["Press Releases", "Tax Court Rules"]},
    "091812.pdf": {"tags": ["Press Releases"]},
    "092105.pdf": {"tags": ["Press Releases", "Tax Court Rules"]},
    "092319.pdf": {"tags": ["Press Releases"]},
    "09232024.pdf": {"tags": ["Press Releases", "Guidance for Practitioners"]},
    "092418.pdf": {"tags": ["Press Releases"]},
    "092518.pdf": {"tags": ["Press Releases"]},
    "093013.pdf": {"tags": ["Press Releases"]},
    "10012024.pdf": {"tags": ["Press Releases"]},
    "100308.pdf": {"tags": ["Tax Court Rules"]},
    "10042024.pdf": {"tags": ["Press Releases"]},
    "10052021.pdf": {"tags": ["Press Releases"]},
    "10062020.pdf": {"tags": ["Rules Comments and Suggestions", "Tax Court Rules"]},
    "10072020.pdf": {"tags": ["Press Releases"]},
    "100908_Morrison.pdf": {"tags": ["Press Releases"]},
    "101014.pdf": {"tags": ["Press Releases"]},
    "101216.pdf": {"tags": ["Press Releases"]},
    "101218.pdf": {"tags": ["Press Releases"]},
    "101317.pdf": {"tags": ["Press Releases"]},
    "10142021.pdf": {"tags": ["Press Releases"]},
    "10142022.pdf": {"tags": ["Press Releases"]},
    "101515.pdf": {"tags": ["Press Releases"]},
    "10162024.pdf": {"tags": ["Press Releases"]},
    "102005.pdf": {"tags": ["Press Releases"]},
    "10222024.pdf": {"tags": ["Press Releases", "Guidance for Practitioners"]},
    "10262022.pdf": {"tags": ["Press Releases"]},
    "10292020.pdf": {"tags": ["Press Releases"]},
    "110204.pdf": {"tags": ["Press Releases"]},
    "11122020.pdf": {"tags": ["Press Releases"]},
    "111414.pdf": {"tags": ["Press Releases"]},
    "11162020.pdf": {"tags": ["Press Releases"]},
    "11192021.pdf": {"tags": ["Press Releases"]},
    "112009.pdf": {"tags": ["Press Releases", "Tax Court Rules"]},
    "11202020.pdf": {"tags": ["Press Releases"]},
    "11212022.pdf": {"tags": ["Press Releases"]},
    "112219.pdf": {"tags": ["Press Releases"]},
    "112519.pdf": {"tags": ["Press Releases"]},
    "112707.pdf": {"tags": ["Press Releases"]},
    "112806.pdf": {"tags": ["Press Releases"]},
    "11282023.pdf": {"tags": ["Press Releases"]},
    "113018.pdf": {
        "tags": ["Press Releases", "Rules Comments and Suggestions", "Tax Court Rules"]
    },
    "113018_disciplinary_matters.pdf": {"tags": ["Press Releases"]},
    "11302020.pdf": {"tags": ["Press Releases"]},
    "120301.pdf": {"tags": ["Press Releases"]},
    "120605.pdf": {"tags": ["Press Releases"]},
    "12062021.pdf": {"tags": ["Press Releases"]},
    "12092021.pdf": {"tags": ["Press Releases"]},
    "12102020.pdf": {"tags": ["Press Releases"]},
    "121205_electronic_filing.pdf": {"tags": ["Press Releases"]},
    "12132024.pdf": {"tags": ["Press Releases"]},
    "12142021.pdf": {"tags": ["Press Releases"]},
    "121616.pdf": {"tags": ["Press Releases"]},
    "12162022.pdf": {"tags": ["Press Releases"]},
    "121815.pdf": {"tags": ["Press Releases"]},
    "12182020.pdf": {"tags": ["Press Releases"]},
    "121914.pdf": {"tags": ["Press Releases"]},
    "121918.pdf": {"tags": ["Press Releases", "Rules Comments and Suggestions"]},
    "122010.pdf": {"tags": ["Press Releases"]},
    "122013.pdf": {"tags": ["Press Releases"]},
    "122117.pdf": {"tags": ["Press Releases"]},
    "122310.pdf": {"tags": ["Press Releases"]},
    "122811.pdf": {"tags": ["Press Releases"]},
    "12282021.pdf": {"tags": ["Press Releases"]},
    "158_TC_1-98.pdf": {"tags": ["Pamphlets"]},
    "158_TC_99-199.pdf": {"tags": ["Pamphlets"]},
    "159_TC_1-27.pdf": {"tags": ["Pamphlets"]},
    "159_TC_28-75.pdf": {"tags": ["Pamphlets"]},
    "159_TC_75-80.pdf": {"tags": ["Pamphlets"]},
    "159_TC_80-183.pdf": {"tags": ["Pamphlets"]},
    "160_TC_1-49.pdf": {"tags": ["Pamphlets"]},
    "160_TC_389-399.pdf": {"tags": ["Pamphlets"]},
    "160_TC_399-470.pdf": {"tags": ["Pamphlets"]},
    "160_TC_470-557.pdf": {"tags": ["Pamphlets"]},
    "160_TC_50-388.pdf": {"tags": ["Pamphlets"]},
    "160_TC_557-690.pdf": {"tags": ["Pamphlets"]},
    "161_TC_112-328.pdf": {"tags": ["Pamphlets"]},
    "161_TC_1-9.pdf": {"tags": ["Pamphlets"]},
    "161_TC_58-112.pdf": {"tags": ["Pamphlets"]},
    "161_TC_9-58.pdf": {"tags": ["Pamphlets"]},
    "162_TC_1-35.pdf": {"tags": ["Pamphlets"]},
    "162_TC_148-199.pdf": {"tags": ["Pamphlets"]},
    "162_TC_199-242.pdf": {"tags": ["Pamphlets"]},
    "162_TC_243-260.pdf": {"tags": ["Pamphlets"]},
    "162_TC_35-98.pdf": {"tags": ["Pamphlets"]},
    "162_TC_98-148.pdf": {"tags": ["Pamphlets"]},
    "163_TC_1-45.pdf": {"tags": ["Pamphlets"]},
    "2018_Nonattorney_Exam.pdf": {"tags": ["Guidance for Practitioners"]},
    "2021_calendar_call_program_sample_letter.pdf": {"tags": ["Clinics"]},
    "2021_letter_to_CJ_academic_law_and_nonlaw.pdf": {"tags": ["Clinics"]},
    "2021_Nonattorney_Exam.pdf": {"tags": ["Guidance for Practitioners"]},
    "2023_Nonattorney_Exam.pdf": {"tags": ["Guidance for Practitioners"]},
    "ABA_Section_of_Taxation_05252022.pdf": {
        "tags": ["Rules Comments and Suggestions"]
    },
    "ABA_Tax_Section_10-3-18.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "ABA_Tax_Section_11-10-15.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "ABA_Tax_Section_2-10-16.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "ABA_Tax_Section_5-4-16.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "ABA_Tax_Section_Comments_on_Amendments_to_Rule_24_06012020.pdf": {
        "tags": ["Rules Comments and Suggestions"]
    },
    "Aderant_Cheryl-Siler_05162022.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "Administrative_Order_2020-01.pdf": {"tags": ["Administrative Orders"]},
    "Administrative_Order_2020-02.pdf": {"tags": ["Administrative Orders"]},
    "Administrative_Order_2020-03.pdf": {
        "tags": ["Guidance for Practitioners", "Administrative Orders"]
    },
    "Administrative_Order_2020-04.pdf": {"tags": ["Administrative Orders"]},
    "Administrative_Order_2020-05.pdf": {"tags": ["Administrative Orders"]},
    "Administrative_Order_2021-01.pdf": {"tags": ["Administrative Orders"]},
    "Administrative_Order_2021-02_REPEALED.pdf": {"tags": ["Administrative Orders"]},
    "Administrative_Order_2021-03_REPEALED.pdf": {"tags": ["Administrative Orders"]},
    "Administrative_Order_2022-01_Repealed.pdf": {"tags": ["Administrative Orders"]},
    "Administrative_Order_2023-01_Repealed.pdf": {"tags": ["Administrative Orders"]},
    "Administrative_Order_2023-02.pdf": {
        "tags": ["Press Releases", "Administrative Orders"]
    },
    "Administrative_Order_2024-01.pdf": {"tags": ["Administrative Orders"]},
    "Admissions_Information_Attorney_12212021.pdf": {
        "tags": ["Guidance for Practitioners"]
    },
    "AOTD_Form_15.pdf": {"tags": ["Forms", "Tax Court Rules"]},
    "appellate_report_april_2021.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_april_2022.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_april_2023.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_april_2024.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_april_2025.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_august_2020.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_august_2021.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_august_2022.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_august_2023.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_august_2024.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_december_2021.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_december_2022.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_december_2023.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_december_2024.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_february_2021.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_february_2022.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_february_2023.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_february_2024.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_february_2025.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_for_january_2022.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_january_2021.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_january_2023.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_january_2024.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_january_2025.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_july_2020.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_july_2021.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_july_2022.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_july_2023.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_july_2024.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_june_2021.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_june_2022.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_june_2023.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_june_2024.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_march_2021.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_march_2022.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_march_2023.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_march_2024.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_march_2025.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_may_2021.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_may_2022.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_may_2024.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_november_2020.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_november_2021.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_november_2022.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_november_2023.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_november_2024.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_october_2020.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_october_2021.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_october_2022.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_october_2023.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_october_2024.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_september_2020.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_september_2021.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_september_2022.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_september_2023.pdf": {"tags": ["Reports & Statistics"]},
    "appellate_report_september_2024.pdf": {"tags": ["Reports & Statistics"]},
    "Application_for_Admission_to_Practice_Attorney_Form_30.pdf": {
        "tags": ["Guidance for Practitioners"]
    },
    "Application_for_Waiver_of_Filing_Fee.pdf": {
        "tags": ["Forms", "Fees & Charges", "Guidance for Petitioners"]
    },
    "Baker_and_McKenzie_11-23-15.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "Carlton_M-_Smith_2-22-16.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "Carlton_M-_Smith_9-25-15.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "Center_for-Taxpayer_Rights_Nina_E_Olson_05252022.pdf": {
        "tags": ["Rules Comments and Suggestions"]
    },
    "Certificate_of_Service_Form_-9.pdf": {
        "tags": ["Guidance for Petitioners", "Forms", "Tax Court Rules"]
    },
    "Certificate_on_Return_of_Deposition_Form_16.pdf": {
        "tags": ["Forms", "Tax Court Rules"]
    },
    "clinics.pdf": {
        "tags": ["LITC", "Pro Bono Programs", "Guidance for Petitioners", "Clinics"]
    },
    "clinics_counsel_rooms.pdf": {"tags": ["Clinics"]},
    "CohnReznick_Dan_Wise_CPA_03242022.pdf": {
        "tags": ["Rules Comments and Suggestions"]
    },
    "Complete_Rules_of_Practice_and_Procedure_Amended_080824.pdf": {
        "tags": ["Tax Court Rules"]
    },
    "Corporate_Disclosure_Statement_Form.pdf": {
        "tags": ["Guidance for Petitioners", "Forms", "Tax Court Rules"]
    },
    "court_schedules_fall_2025_8z9kc5F.pdf": {"tags": ["Trial Sessions"]},
    "DAWSON_Petitioner_Training_Guide.pdf": {
        "tags": ["DAWSON Training Guides", "Guidance for Petitioners"]
    },
    "DAWSON_Practitioner_Training_Guide.pdf": {"tags": ["Guidance for Practitioners"]},
    "DAWSON_Reminders_for_Practitioners.pdf": {"tags": ["Guidance for Practitioners"]},
    "Discussion_of_Comments_March_2023.pdf": {
        "tags": ["Rules Comments and Suggestions"]
    },
    "documentary_evidence.pdf": {"tags": ["Remote Proceedings"]},
    "Dubroff_Hellwig.pdf": {"tags": ["History", "Guidance for Petitioners"]},
    "efiling_in_consolidated_cases.mp4": {"tags": ["DAWSON Training Guides"]},
    "EOA_Form_7.pdf": {"tags": ["Forms", "Tax Court Rules"]},
    "fee_schedule.pdf": {"tags": ["Fees & Charges"]},
    "Form_4_Statement_of_Taxpayer_Identification_Number.pdf": {
        "tags": ["Guidance for Petitioners", "Forms", "Tax Court Rules"]
    },
    "Form_5_Request_for_Place_of_Trial.pdf": {
        "tags": ["Guidance for Petitioners", "Forms", "Tax Court Rules"]
    },
    "FY_2021_Congressional_Budget_Justification.pdf": {
        "tags": ["Reports & Statistics"]
    },
    "FY_2022_Congressional_Budget_Justification.pdf": {
        "tags": ["Reports & Statistics"]
    },
    "FY_2023_Congressional_Budget_Justification.pdf": {
        "tags": ["Reports & Statistics"]
    },
    "FY_2024_Congressional_Budget_Justification.pdf": {
        "tags": ["Reports & Statistics"]
    },
    "FY_2025_Congressional_Budget_Justification.pdf": {
        "tags": ["Reports & Statistics"]
    },
    "FY_2026_Congressional_Budget_Justification.pdf": {
        "tags": ["Reports & Statistics"]
    },
    "GMT20201013-122947_Jessica-Ma_1600x900.mp4": {"tags": ["DAWSON Training Guides"]},
    "Guide_to_Rules_Amendments_and_Notes.pdf": {"tags": ["Tax Court Rules"]},
    "Harvard_10-30-15.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "Harvard-Clinic_Comment_re_Proposed-Amendment.pdf": {
        "tags": ["Rules Comments and Suggestions"]
    },
    "IRS_-2-12-16.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "IRS_3-1-19.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "IRS_-4-26-16.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "IRS_-9-11-15.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "IRS_Chief_Counsel_Drita_Tonuzi.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "jcd_complaint_form.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "jcd_rules.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "jcd_users_guide.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "John_H_Dies_10-30-15.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "Law_Office_of_Wm_Mark_Scott_PLLC_05252022.pdf": {
        "tags": ["Rules Comments and Suggestions"]
    },
    "lea_faq.pdf": {"tags": ["Guidance for Practitioners"]},
    "Legal_Services_Center_of_Harvard-Law_School_Keith_Fogg_05202022.pdf": {
        "tags": ["Rules Comments and Suggestions"]
    },
    "letter_to_cj_occ_student_practice.pdf": {"tags": ["Clinics"]},
    "Lewis_C_Taishoff.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "Lewis_C_Taishoff_9-28-15.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "Limited_Entry_of_Appearance.pdf": {"tags": ["Forms"]},
    "Motion_to_Proceed_Remotely.pdf": {"tags": ["Forms", "Guidance for Petitioners"]},
    "NOCOA_Form_10.pdf": {
        "tags": ["Guidance for Petitioners", "Forms", "Tax Court Rules"]
    },
    "NonAttorney_Exam_Statistics.pdf": {"tags": ["Guidance for Practitioners"]},
    "Nonattorney_Examination_Procedures_050322.pdf": {
        "tags": ["Guidance for Practitioners"]
    },
    "Notice_of_Appeal_Form_17.pdf": {"tags": ["Forms", "Tax Court Rules"]},
    "Notice_of_Election_to_Intervene_Form_11.pdf": {
        "tags": ["Forms", "Tax Court Rules"]
    },
    "Notice_of_Election_to_Participate_Form_12.pdf": {"tags": ["Forms"]},
    "Notice_of_Intervention_Form_13.pdf": {"tags": ["Forms", "Tax Court Rules"]},
    "Notice_of_Receipt_of_Petition.pdf": {"tags": ["Guidance for Petitioners"]},
    "Petition_for_Administrative_Costs_Form_3.pdf": {
        "tags": ["Forms", "Tax Court Rules"]
    },
    "Petition_Kit.pdf": {"tags": ["Forms", "Guidance for Petitioners"]},
    "Petition_Simplified_Form_2.pdf": {
        "tags": ["Forms", "Tax Court Rules", "Guidance for Petitioners"]
    },
    "Pretrial_Memorandum_Form.pdf": {"tags": ["Forms"]},
    "Pretrial_Memorandum_Form_old.pdf": {"tags": ["Guidance for Petitioners"]},
    "Privacy-_Notice.pdf": {"tags": ["Guidance for Petitioners"]},
    "Rule_13_Package-Discussion_of_Comments_Received_8-08-2024.pdf": {
        "tags": ["Rules Comments and Suggestions"]
    },
    "Rule-1_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-10_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-100.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-101.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-102.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-103_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-104.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-110_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-11superseded.pdf": {"tags": ["Fees & Charges", "Tax Court Rules"]},
    "Rule-120.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-121.pdf": {"tags": ["Guidance for Petitioners"]},
    "Rule-121_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-122.pdf": {"tags": ["Guidance for Petitioners", "Tax Court Rules"]},
    "Rule-123.pdf": {"tags": ["Guidance for Petitioners", "Tax Court Rules"]},
    "Rule-124.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-12superseded.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-13_amended_08082024.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-130.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-131.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-132.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-133_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-140_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-141_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-142.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-143amended.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-144.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-145.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-146.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-147.pdf": {"tags": ["Guidance for Petitioners"]},
    "Rule-147_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-148.pdf": {
        "tags": ["Guidance for Petitioners", "Fees & Charges", "Tax Court Rules"]
    },
    "Rule-149.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-150.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-151.pdf": {"tags": ["Guidance for Petitioners"]},
    "Rule-151_1_Amended_03202023.pdf": {"tags": ["Press Releases", "Tax Court Rules"]},
    "Rule-151_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-152_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-155.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-156.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-157.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-160.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-161_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-162.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-163.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-170_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-171_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-172.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-173.pdf": {"tags": ["Guidance for Petitioners", "Tax Court Rules"]},
    "Rule-174.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-180_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-181.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-182_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-183.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-190.pdf": {
        "tags": ["Guidance for Petitioners", "Fees & Charges", "Tax Court Rules"]
    },
    "Rule-191.pdf": {"tags": ["Guidance for Petitioners", "Tax Court Rules"]},
    "Rule-192.pdf": {"tags": ["Guidance for Petitioners", "Tax Court Rules"]},
    "Rule-193.pdf": {"tags": ["Guidance for Petitioners", "Tax Court Rules"]},
    "Rule-2.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-20_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-2002nd-amended.pdf": {
        "tags": ["Fees & Charges", "Guidance for Practitioners", "Tax Court Rules"]
    },
    "Rule-201.pdf": {"tags": ["Guidance for Practitioners", "Tax Court Rules"]},
    "Rule-202.pdf": {"tags": ["Guidance for Practitioners", "Tax Court Rules"]},
    "Rule-21.pdf": {"tags": ["DAWSON Training Guides"]},
    "Rule-21_Amended_03202023.pdf": {"tags": ["Forms", "Tax Court Rules"]},
    "Rule-210_amended_08082024.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-211.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-212.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-213_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-214.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-215.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-216.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-217_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-218.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-220_amended_08082024.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-221.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-222.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-223.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-224.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-225.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-226.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-227.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-228.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-229.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-229A.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-22amended.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-23_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-2302nd-amended.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-231_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-232.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-233_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-240_amended_08082024.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-241.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-242.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-243.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-244.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-245.pdf": {"tags": ["Forms", "Tax Court Rules"]},
    "Rule-246.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-247.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-248.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-249.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-24amended-Oct.-6-2020.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-25_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-250.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-251.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-255.1_amended_08082024.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-255.2New.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-255.3New.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-255.4New.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-255.5New.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-255.6New.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-255.7New.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-26_Amended_03202023.pdf": {
        "tags": ["DAWSON Training Guides", "Tax Court Rules"]
    },
    "Rule-260amended-Oct.-6-2020.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-261amended-Oct.-6-2020.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-262amended-Oct.-6-2020.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-27.pdf": {"tags": ["Guidance for Petitioners"]},
    "Rule-27_Amended_03202023.pdf": {"tags": ["Press Releases", "Tax Court Rules"]},
    "Rule-270_amended_08082024.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-271.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-272.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-273.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-274.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-280_amended_08082024.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-280amended.pdf": {"tags": ["Guidance for Petitioners"]},
    "Rule-281amended.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-282.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-283.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-284.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-290_amended_08082024.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-291.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-292.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-293.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-294.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-3_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-30.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-300_amended_08082024.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-301.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-302.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-303.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-304.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-305.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-31_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-310_amended_08082024.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-311.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-312.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-313.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-314.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-315.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-316.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-32_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-320.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-321.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-322.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-323.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-324.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-325.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-33_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-330.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-331.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-332.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-333.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-334.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-34_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-340.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-341.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-342.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-343.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-344.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-345.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-35_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-350.pdf": {"tags": ["Guidance for Petitioners", "Tax Court Rules"]},
    "Rule-351.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-352.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-353.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-354.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-36_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-37.pdf": {"tags": ["Guidance for Petitioners", "Tax Court Rules"]},
    "Rule-38amended.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-39.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-40.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-41_amended_08082024.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-50.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-51.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-52.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-53.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-54.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-55.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-56.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-57..pdf": {"tags": ["Tax Court Rules"]},
    "Rule-58.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-60amended.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-61_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-62_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-63_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-64_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-70_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-71.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-72.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-73.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-74_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-74amended.pdf": {"tags": ["Guidance for Petitioners"]},
    "Rule-80.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-81.pdf": {"tags": ["Guidance for Petitioners"]},
    "Rule-81_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-82.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-83.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-84.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-85.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-90_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-91_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-92_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "Rule-93_Amended_03202023.pdf": {"tags": ["Tax Court Rules"]},
    "sample_notice_setting_case_for_trial.pdf": {"tags": ["Remote Proceedings"]},
    "Sample_Notice_Setting_Case_for_Trial_R_cases.pdf": {
        "tags": ["Guidance for Petitioners"]
    },
    "Sample_Notice_Setting_Case_for_Trial_S_cases.pdf": {
        "tags": ["Guidance for Petitioners"]
    },
    "sample_pretrial_memorandum.pdf": {"tags": ["Remote Proceedings"]},
    "sample_standing_pretrial_order.pdf": {"tags": ["Remote Proceedings"]},
    "sample_standing_pretrial_order_small_tax_cases.pdf": {
        "tags": ["Remote Proceedings"]
    },
    "SOC_Form_8.pdf": {"tags": ["Forms", "Tax Court Rules"]},
    "SPTO_regular_sample.pdf": {"tags": ["Guidance for Petitioners"]},
    "SPTO_small_sample.pdf": {"tags": ["Guidance for Petitioners"]},
    "stuffer_notice.pdf": {"tags": []},
    "Subpoena_Appear_Testify_Hearing_Or_Trial.pdf": {
        "tags": ["Guidance for Petitioners", "Forms", "Tax Court Rules"]
    },
    "Subpoena_To_Testify_Deposition.pdf": {
        "tags": ["Guidance for Petitioners", "Forms", "Tax Court Rules"]
    },
    "subpoenas_for_remote_proceedings.pdf": {"tags": ["Remote Proceedings"]},
    "Suzanne_McCrory.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "Tax_Court_Rule_24_Comments_05272020.pdf": {
        "tags": ["Rules Comments and Suggestions"]
    },
    "Tax_Court_Rules_Amendments_1-22-24_-Chief_Counsel_Comments_Paul_Butler_3-21-24.pdf": {
        "tags": ["Rules Comments and Suggestions"]
    },
    "Tax_Section_State_Bar_of_Texas_10-30-15.pdf": {
        "tags": ["Rules Comments and Suggestions"]
    },
    "Tax_Section_State_Bar_of_Texas_11-6-18.pdf": {
        "tags": ["Rules Comments and Suggestions"]
    },
    "Tax_Section_State_Bar_of_Texas_2-8-16.pdf": {
        "tags": ["Rules Comments and Suggestions"]
    },
    "Tax_Section_State_Bar_of_Texas_4-27-16.pdf": {
        "tags": ["Rules Comments and Suggestions"]
    },
    "TC_RULE_24_Chief_Counsel_IRS_05292020.pdf": {
        "tags": ["Rules Comments and Suggestions"]
    },
    "TC-16-90001.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-16-90002.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-16-90002_2017-08-16_Council-Order.pdf": {
        "tags": ["Judicial Conduct and Disability Procedures"]
    },
    "TC-16-90003.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-16-90003_2017-08-16_Council-Order.pdf": {
        "tags": ["Judicial Conduct and Disability Procedures"]
    },
    "TC-16-90004.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-17-90001.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-17-900011.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-17-900012.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-17-900015.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-17-90002.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-17-90003.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-17-90003_2017-08-16_Council_Order.pdf": {
        "tags": ["Judicial Conduct and Disability Procedures"]
    },
    "TC-17-90004.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-17-90005.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-17-90005_2018-08.06_Council_Order.pdf": {
        "tags": ["Judicial Conduct and Disability Procedures"]
    },
    "TC-17-90006.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-17-90006_2018-08.06_Council_Order.pdf": {
        "tags": ["Judicial Conduct and Disability Procedures"]
    },
    "TC-17-90007.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-17-90008.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-17-90009.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-17-90010.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-17-90011_2018-08.06_Council_Order.pdf": {
        "tags": ["Judicial Conduct and Disability Procedures"]
    },
    "TC-17-90013.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-17-90014.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-17-90015_2018-08.06_Council_Order.pdf": {
        "tags": ["Judicial Conduct and Disability Procedures"]
    },
    "TC-18-90001.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-18-90001_2018-12.17_Council_Order.pdf": {
        "tags": ["Judicial Conduct and Disability Procedures"]
    },
    "TC-19-90001.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-19-90002.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-19-90003.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-20-90001.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-20-90002.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-21-90001.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-21-90002.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-21-90003.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-21-90004.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-21-90005.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-21-90006.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-21-90007.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-21-90008.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-21-90009.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-22-90001.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-23-90001.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-23-90002.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-24-90001-CJ-1.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-24-90001-CJ-2.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-24-90001-JCDC-1.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-24-90001-JCDC-2.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-24-90002.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-24-90003.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-24-90004.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-24-90005.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-24-90007.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "TC-24-90008.pdf": {"tags": ["Judicial Conduct and Disability Procedures"]},
    "Thomas_N_Thompson_10-5-15.pdf": {"tags": ["Rules Comments and Suggestions"]},
    "tou.pdf": {"tags": ["Guidance for Petitioners"]},
    "Trujillo_and_Rico_Public_Comment.pdf": {
        "tags": ["Rules Comments and Suggestions"]
    },
    "Unsworn_Declaration_Form_18.pdf": {
        "tags": ["Guidance for Petitioners", "Forms", "Tax Court Rules"]
    },
    "USTC_Citation_and_Style_Manual_modified_2024.09.pdf": {
        "tags": ["Citation and Style Manual"]
    },
    "USTC_IRA_Strategic_Plan_2024.pdf": {"tags": ["Reports & Statistics"]},
    "VA_Dep_Clerk_Admin_Svc_Final_20250424.pdf": {"tags": ["Vacancy Announcements"]},
    "zoomgov_faqs.pdf": {"tags": ["Remote Proceedings"]},
}


def assign_tags_to_documents(apps, schema_editor):
    Document = apps.get_model("wagtaildocs", "Document")
    Tag = apps.get_model("taggit", "Tag")
    TaggedItem = apps.get_model("taggit", "TaggedItem")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Collection = apps.get_model("wagtailcore", "Collection")

    doc_content_type = ContentType.objects.get(
        app_label="wagtaildocs", model="document"
    )

    for doc_name, data in document_tags_map.items():
        try:
            doc = Document.objects.get(title=doc_name)
        except Document.DoesNotExist:
            print(f"document with title '{doc_name}' Not found")
            continue
        tags = data.get("tags", [])
        # Assign tags
        for tag_name in tags:
            tag = Tag.objects.get(name=tag_name)
            if not TaggedItem.objects.filter(
                tag_id=tag.pk, object_id=doc.pk, content_type_id=doc_content_type.pk
            ).exists():
                TaggedItem.objects.create(
                    tag_id=tag.pk, object_id=doc.pk, content_type_id=doc_content_type.pk
                )
        # Assign collection
        collection_name = None
        for cname in collection_sorting_order:
            if cname in tags:
                collection_name = cname
                break
        if collection_name:
            try:
                collection = Collection.objects.get(name=collection_name)
                doc.collection = collection
                doc.save()
            except Collection.DoesNotExist:
                print(
                    f"Collection '{collection_name}' not found for document '{doc_name}'"
                )


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0059_add_initial_collections"),
        ("wagtaildocs", "0001_initial"),
        ("taggit", "0003_taggeditem_add_unique_index"),
    ]
    operations = [
        migrations.RunPython(assign_tags_to_documents),
    ]
