# Generated by Django 5.1.7 on 2025-07-08 16:04

from django.db import migrations

TAGS_AND_COLLECTION_NAMES = [
    "Administrative Orders",
    "Cases Commenced in the Court of Appeals",
    "Citation and Style Manual",
    "Clinics",
    "DAWSON Training Guides",
    "Directory",
    "Discipline",
    "Engagement & Outreach",
    "Events and Webinars",
    "Fees & Charges",
    "Forms",
    "Guidance for Petitioners",
    "Guidance for Practitioners",
    "History",
    "Internship Programs",
    "Judges & Bios",
    "Judicial Conduct and Disability Procedures",
    "Law Clerk Programs",
    "LITC",
    "Mission Statement",
    "Pamphlets",
    "Press Releases",
    "Pro Bono Programs",
    "Records (Transcripts & Copies)",
    "DAWSON Release Notes",
    "Remote Proceedings",
    "Reports & Statistics",
    "Rules Comments and Suggestions",
    "Tax Court Reports",
    "Tax Court Rules",
    "Trial Sessions",
    "Vacancy Announcements",
]


def get_next_collection_path(Collection, root):
    children = Collection.objects.filter(path__startswith=root.path, depth=2)
    if children.exists():
        max_segment = max(int(child.path[-4:]) for child in children)
        next_index = max_segment + 1
    else:
        next_index = 1
    segment = str(next_index).zfill(4)
    return root.path + segment


def create_collections(apps, schema_editor):
    Collection = apps.get_model("wagtailcore", "Collection")
    root = Collection.objects.get(name="Root")
    for name in TAGS_AND_COLLECTION_NAMES:
        path = get_next_collection_path(Collection, root)
        obj, created = Collection.objects.get_or_create(
            name=name, defaults={"path": path, "depth": 2, "numchild": 0}
        )
        if created:
            root.numchild += 1
            root.save()


def remove_collections(apps, schema_editor):
    Collection = apps.get_model("wagtailcore", "Collection")
    root = Collection.objects.get(depth=1)
    deleted_count, _ = Collection.objects.filter(
        name__in=TAGS_AND_COLLECTION_NAMES
    ).delete()
    root.numchild = max(0, root.numchild - len(TAGS_AND_COLLECTION_NAMES))
    root.save()


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0059_add_initial_tags"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]
    operations = [
        migrations.RunPython(create_collections, remove_collections),
    ]
