# Generated by Django 5.1.7 on 2025-07-10 16:04

from django.db import migrations
from home.data.document_tags_map import DOCUMENT_TAGS_MAP
from home.utils.document_collection_and_tag_assignment import (
    get_tags_for_document,
    get_collection_for_document,
)


def assign_tags_to_documents(apps, schema_editor):
    Document = apps.get_model("wagtaildocs", "Document")
    Tag = apps.get_model("taggit", "Tag")
    TaggedItem = apps.get_model("taggit", "TaggedItem")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Collection = apps.get_model("wagtailcore", "Collection")

    doc_content_type = ContentType.objects.get(
        app_label="wagtaildocs", model="document"
    )

    for doc_name, data in DOCUMENT_TAGS_MAP.items():
        try:
            doc = Document.objects.get(file=f"documents/{doc_name}")
        except Document.DoesNotExist:
            print(f"document with title '{doc_name}' Not found")
            continue

        document_tags = get_tags_for_document(doc_name)

        for tag_name in document_tags:
            tag = Tag.objects.get(name=tag_name)
            if not TaggedItem.objects.filter(
                tag_id=tag.pk, object_id=doc.pk, content_type_id=doc_content_type.pk
            ).exists():
                TaggedItem.objects.create(
                    tag_id=tag.pk, object_id=doc.pk, content_type_id=doc_content_type.pk
                )
        # Assign collection
        collection_name = get_collection_for_document(doc_name, document_tags)
        if collection_name:
            try:
                collection = Collection.objects.get(name=collection_name)
                doc.collection = collection
                doc.save()
            except Collection.DoesNotExist:
                print(
                    f"Collection '{collection_name}' not found for document '{doc_name}'"
                )


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0060_add_role_tags"),
        ("wagtaildocs", "0001_initial"),
        ("taggit", "__latest__"),
    ]
    operations = [
        migrations.RunPython(assign_tags_to_documents),
    ]
