# Generated by Django 5.1.7 on 2025-07-08 16:04

from django.db import migrations
from home.data.tag_and_collection_names import TAGS_AND_COLLECTION_NAMES


def get_next_collection_path(Collection, root):
    children = Collection.objects.filter(path__startswith=root.path, depth=2)
    if children.exists():
        max_segment = max(int(child.path[-4:]) for child in children)
        next_index = max_segment + 1
    else:
        next_index = 1
    segment = str(next_index).zfill(4)
    return root.path + segment


def create_collections(apps, schema_editor):
    Collection = apps.get_model("wagtailcore", "Collection")
    root = Collection.objects.get(name="Root")
    for name in TAGS_AND_COLLECTION_NAMES:
        path = get_next_collection_path(Collection, root)
        obj, created = Collection.objects.get_or_create(
            name=name, defaults={"path": path, "depth": 2, "numchild": 0}
        )
        if created:
            root.numchild += 1
            root.save()


def remove_collections(apps, schema_editor):
    Collection = apps.get_model("wagtailcore", "Collection")
    root = Collection.objects.get(depth=1)
    deleted_count, _ = Collection.objects.filter(
        name__in=TAGS_AND_COLLECTION_NAMES
    ).delete()
    root.numchild = max(0, root.numchild - len(TAGS_AND_COLLECTION_NAMES))
    root.save()


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0058_add_initial_tags"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]
    operations = [
        migrations.RunPython(create_collections, remove_collections),
    ]
