# Generated by Django 5.1.7 on 2025-07-10

from django.db import migrations
import re

ROLE_TAGS_NAMES = [
    "Role Content Manager",
    "Role Website Manager",
    "Role Chief Judge",
    "Role Dawson Contributor",
    "Role Public Affairs",
    "Role Clerk Office",
    "Role Hr Committee",
    "Role Pro Se Committee",
    "Role Rules Committee",
    "Role Admissions Committee",
    "Role Ethics Committee",
    "Role Disciplinary Committee",
    "Role Reporters Office",
    "Role Appellate Reports",
    "Role Case Services",
]


def create_slug(name):
    name = name.lower()
    name = re.sub(r"\s+", "-", name)
    return name


def create_role_tags(apps, schema_editor):
    Tag = apps.get_model("taggit", "Tag")
    for tag_name in ROLE_TAGS_NAMES:
        slug = create_slug(tag_name)
        # Use the slug to check for existence, and provide the name as a default
        # for creation. This avoids the unique constraint error.
        Tag.objects.get_or_create(slug=slug, defaults={"name": tag_name})


def remove_role_tags(apps, schema_editor):
    Tag = apps.get_model("taggit", "Tag")
    # Create a list of slugs to safely identify the tags to be removed.
    slugs_to_remove = [create_slug(tag_name) for tag_name in ROLE_TAGS_NAMES]
    Tag.objects.filter(slug__in=slugs_to_remove).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0060_add_initial_collections"),
        ("taggit", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_role_tags, remove_role_tags),
    ]
