# Generated by Django 5.1.7 on 2025-08-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0064_update_rules_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="commontext",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional deadline for review and moderation of this content.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enhancedstandardpage",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional deadline for review and moderation of this content.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="judgecollection",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional deadline for review and moderation of this content.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="judgeprofile",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional deadline for review and moderation of this content.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="judgerole",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional deadline for review and moderation of this content.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="navigationmenu",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional deadline for review and moderation of this content.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="navigationribbon",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional deadline for review and moderation of this content.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional deadline for review and moderation of this content.",
                null=True,
            ),
        ),
    ]
