# Generated by Django 5.2 on 2025-08-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0064_update_rules_documents"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostDeploymentScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "script_name",
                    models.CharField(
                        help_text="Filename of the script that was executed.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Script executed time."
                    ),
                ),
            ],
        ),
    ]
