# Generated by Django 5.1.7 on 2025-08-06 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0064_update_rules_documents"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomWorkflowState",
            fields=[
                (
                    "workflowstate_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.workflowstate",
                    ),
                ),
                (
                    "review_by_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publish Deadline2"
                    ),
                ),
                (
                    "publish_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional date/time when this item should be published by.",
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.workflowstate",),
        ),
        migrations.AddField(
            model_name="commontext",
            name="publish_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional deadline for publishing this content.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="commontext",
            name="review_by_date",
            field=models.DateTimeField(
                blank=True,
                help_text="item should be reviewed by.",
                null=True,
                verbose_name="Publish Deadline2",
            ),
        ),
        migrations.AddField(
            model_name="enhancedstandardpage",
            name="publish_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional deadline for publishing this content.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enhancedstandardpage",
            name="review_by_date",
            field=models.DateTimeField(
                blank=True,
                help_text="item should be reviewed by.",
                null=True,
                verbose_name="Publish Deadline2",
            ),
        ),
        migrations.AddField(
            model_name="judgecollection",
            name="publish_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for when this should be published",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="judgecollection",
            name="review_by_date",
            field=models.DateTimeField(
                blank=True,
                help_text="item should be reviewed by.",
                null=True,
                verbose_name="Publish Deadline2",
            ),
        ),
        migrations.AddField(
            model_name="judgeprofile",
            name="publish_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional deadline for publishing this content.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="judgeprofile",
            name="review_by_date",
            field=models.DateTimeField(
                blank=True,
                help_text="item should be reviewed by.",
                null=True,
                verbose_name="Publish Deadline2",
            ),
        ),
        migrations.AddField(
            model_name="judgerole",
            name="publish_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional deadline for publishing this content.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="judgerole",
            name="review_by_date",
            field=models.DateTimeField(
                blank=True,
                help_text="item should be reviewed by.",
                null=True,
                verbose_name="Publish Deadline2",
            ),
        ),
        migrations.AddField(
            model_name="navigationribbon",
            name="publish_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional deadline for publishing this content.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="navigationribbon",
            name="review_by_date",
            field=models.DateTimeField(
                blank=True,
                help_text="item should be reviewed by.",
                null=True,
                verbose_name="Publish Deadline2",
            ),
        ),
    ]
