# Generated by Django 5.2 on 2025-08-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0064_update_rules_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fancycard",
            name="text",
            field=models.CharField(
                blank=True,
                help_text="The text to appear next to the image in the light blue card.",
                null=True,
            ),
        ),
    ]
