# Generated by Django 5.2 on 2025-08-19 22:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0064_update_rules_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fancycard",
            name="text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="The text to appear next to the image in the light blue card.",
                null=True,
            ),
        ),
    ]
