# Generated by Django 5.2 on 2025-08-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0065_alter_fancycard_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fancycard",
            name="text",
            field=models.TextField(
                blank=True,
                help_text="The text to appear next to the image in the light blue card.",
                null=True,
            ),
        ),
    ]
