# Generated by Django 5.2 on 2025-08-13 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0065_newsitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecuteScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command_name",
                    models.CharField(
                        help_text="Name of the command to execute", max_length=255
                    ),
                ),
                (
                    "execution_type",
                    models.CharField(
                        choices=[("ONETIME", "One Time"), ("EVERYTIME", "Every Time")],
                        default="ONETIME",
                        help_text="How often this script should be executed",
                        max_length=20,
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time for script execution",
                        null=True,
                    ),
                ),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        help_text="Status of script execution",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_scripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
