# Generated by Django 5.1.7 on 2025-08-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0065_commontext_review_by_directoryindex_review_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commontext",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="directoryindex",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="enhancedstandardpage",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="externalredirectpage",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="judgecollection",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="judgeindex",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="judgeprofile",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="judgerole",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="navigationmenu",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="navigationribbon",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="placesoftrialpage",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
    ]
