# Generated by Django 5.2 on 2025-08-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0065_alter_fancycard_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="commontext",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="commontext",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for review and moderation of this content.",
                null=True,
                verbose_name="Review by date",
            ),
        ),
        migrations.AddField(
            model_name="directoryindex",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="directoryindex",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for review and moderation of this content.",
                null=True,
                verbose_name="Review by date",
            ),
        ),
        migrations.AddField(
            model_name="enhancedstandardpage",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="enhancedstandardpage",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for review and moderation of this content.",
                null=True,
                verbose_name="Review by date",
            ),
        ),
        migrations.AddField(
            model_name="externalredirectpage",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="externalredirectpage",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for review and moderation of this content.",
                null=True,
                verbose_name="Review by date",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for review and moderation of this content.",
                null=True,
                verbose_name="Review by date",
            ),
        ),
        migrations.AddField(
            model_name="judgecollection",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="judgecollection",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for review and moderation of this content.",
                null=True,
                verbose_name="Review by date",
            ),
        ),
        migrations.AddField(
            model_name="judgeindex",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="judgeindex",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for review and moderation of this content.",
                null=True,
                verbose_name="Review by date",
            ),
        ),
        migrations.AddField(
            model_name="judgeprofile",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="judgeprofile",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for review and moderation of this content.",
                null=True,
                verbose_name="Review by date",
            ),
        ),
        migrations.AddField(
            model_name="judgerole",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="judgerole",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for review and moderation of this content.",
                null=True,
                verbose_name="Review by date",
            ),
        ),
        migrations.AddField(
            model_name="navigationmenu",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="navigationmenu",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for review and moderation of this content.",
                null=True,
                verbose_name="Review by date",
            ),
        ),
        migrations.AddField(
            model_name="navigationribbon",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="navigationribbon",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for review and moderation of this content.",
                null=True,
                verbose_name="Review by date",
            ),
        ),
        migrations.AddField(
            model_name="placesoftrialpage",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="placesoftrialpage",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for review and moderation of this content.",
                null=True,
                verbose_name="Review by date",
            ),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for review and moderation of this content.",
                null=True,
                verbose_name="Review by date",
            ),
        ),
        migrations.AlterField(
            model_name="caserelatedformsentry",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="commontext",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="fancycard",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="footer",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="googleanalyticssettings",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="homepageimage",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="judgecollection",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="judgecollectionorderable",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="judgeprofile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="judgerole",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="navigationmenu",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="navigationribbon",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="navigationribbonlink",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pamphletentry",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pdfs",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="photodedication",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="relatedpage",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="simplecard",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="simplecardgroup",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="vacancyentry",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
