# Generated by Django 5.2 on 2025-08-13 20:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0066_executescript"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pressreleasepage",
            name="press_release_body",
            field=wagtail.fields.StreamField(
                [("button", 3), ("news_items", 4), ("press_releases", 10)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button link  (Can be relative or absolute)",
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary")],
                            "help_text": "Choose the button style",
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("href", 1), ("style", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[]], {}),
                    5: ("wagtail.blocks.DateBlock", (), {"required": False}),
                    6: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    7: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("description", 6), ("file", 7)]],
                        {"required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("release_date", 5), ("details", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                },
                null=True,
            ),
        ),
    ]
