# Generated by Django 5.2 on 2025-08-22 20:15

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0066_executescript_newsitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticTextCardGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Group title (optional)", max_length=255
                    ),
                ),
                (
                    "contents",
                    wagtail.fields.StreamField(
                        [("card", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Card title",
                                    "max_length": 2000,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Card content", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("body", 1)]],
                                {},
                            ),
                        },
                        help_text="Add multiple static text cards to this group",
                    ),
                ),
                (
                    "homepage",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="static_text_card_group",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
