# Generated by Django 5.2 on 2025-08-26 20:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0066_executescript_newsitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="static_text_cards",
            field=wagtail.fields.StreamField(
                [("card", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Card title",
                            "max_length": 2000,
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Card content", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.DateTimeBlock",
                        (),
                        {"help_text": "Start date for display", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.DateTimeBlock",
                        (),
                        {"help_text": "End date for display", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("body", 1),
                                ("start_date", 2),
                                ("end_date", 3),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Add multiple static text cards",
            ),
        ),
    ]
