# Generated by Django 5.2 on 2025-09-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0069_homepage_static_text_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note for moderators when submitting content for review.",
                null=True,
                verbose_name="Moderation note",
            ),
        ),
        migrations.AddField(
            model_name="newsitem",
            name="review_by",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for review and moderation of this content.",
                null=True,
                verbose_name="Review by date",
            ),
        ),
    ]
