# Generated by Django 5.2 on 2025-09-10 22:33

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0070_backfill_live_revisions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pamphletentry",
            options={"ordering": ["sort_order"]},
        ),
        migrations.RemoveField(
            model_name="pamphletentry",
            name="citation",
        ),
        migrations.RemoveField(
            model_name="pamphletentry",
            name="code",
        ),
        migrations.RemoveField(
            model_name="pamphletentry",
            name="volume_number",
        ),
        migrations.AddField(
            model_name="pamphletentry",
            name="cases",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Cases"),
        ),
        migrations.AddField(
            model_name="pamphletentry",
            name="page_range",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Page Range"
            ),
        ),
        migrations.AddField(
            model_name="pamphletentry",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
