# Generated by Django 5.2.7 on 2025-10-22 21:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0070_backfill_live_revisions"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefinitionsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "review_by",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for review and moderation of this content.",
                        null=True,
                        verbose_name="Review by date",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional note for moderators when submitting content for review.",
                        null=True,
                        verbose_name="Moderation note",
                    ),
                ),
                (
                    "definitions",
                    wagtail.fields.StreamField(
                        [("definition", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "The term being defined",
                                    "label": "Definition Name",
                                },
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "The definition of the term (supports rich text and links)",
                                    "label": "Definition",
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 0), ("answer", 1)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
