# Generated by Django 5.2 on 2025-09-12 18:41

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0071_newsitem_note_newsitem_review_by"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_background_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Background image for the hero section (recommended size: 3000x1200px)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_body",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="We are a national court that helps quickly resolve disputes between taxpayers and the IRS. Our online system, DAWSON allows users to file documents and track case status. The US Tax Court is an Article I federal trail court established by Congress under Article 1 of the U.S. Constitution, Section 8.",
                help_text="Welcome text displayed below the title in the hero section",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(
                default="Welcome to the United States Tax Court",
                help_text="Main welcome title displayed on the homepage hero section",
                max_length=255,
            ),
        ),
    ]
