# Generated by Django 5.2 on 2025-10-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0071_newsitem_note_newsitem_review_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="banner_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date/time when the banner should stop appearing",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="newsitem",
            name="banner_start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date/time when the banner should start appearing",
                null=True,
            ),
        ),
    ]
