# Generated by Django 5.2 on 2025-10-08 20:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0072_remove_homepageimage_image_remove_homepageimage_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_body",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="We are a national court that helps quickly resolve disputes between taxpayers and the IRS. Our online system, DAWSON allows users to file documents and track case status. The US Tax Court is an Article I federal trial court established by Congress under Article 1 of the U.S. Constitution, Section 8.",
                help_text="Welcome text displayed below the title in the hero section",
            ),
        ),
    ]
