# Generated by Django 5.2 on 2025-10-01 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0072_homepage_hero_background_image_homepage_hero_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepageimage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="homepageimage",
            name="page",
        ),
        migrations.DeleteModel(
            name="HomePageEntry",
        ),
        migrations.DeleteModel(
            name="HomePageImage",
        ),
    ]
