# Generated by Django 5.2 on 2025-10-06 15:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0073_alter_homepage_hero_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="quick_access_tiles",
            field=wagtail.fields.StreamField(
                [("tile", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tile text", "max_length": 255, "required": True},
                    ),
                    1: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    2: ("wagtail.blocks.PageChooserBlock", (), {"required": True}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 0),
                                ("icon", 1),
                                ("related_page", 2),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Add multiple quick access tiles",
            ),
        ),
    ]
