# Generated by Django 5.2 on 2025-10-03 20:59

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0073_alter_homepage_hero_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="banner_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date/time when the banner should stop appearing",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="newsitem",
            name="banner_start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date/time when the banner should start appearing",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_body",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="We are a national court that helps quickly resolve disputes between taxpayers and the IRS. Our online system, DAWSON allows users to file documents and track case status. The US Tax Court is an Article I federal trial court established by Congress under Article 1 of the U.S. Constitution, Section 8.",
                help_text="Welcome text displayed below the title in the hero section",
            ),
        ),
    ]
