# Generated by Django 5.2 on 2025-10-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0074_newsitem_banner_end_date_newsitem_banner_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="banner_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date/time when the banner should stop appearing (optional - leave blank for indefinite display until replaced by a new banner)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="newsitem",
            name="banner_start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date/time when the banner should start appearing (required for high and critical priority banners)",
                null=True,
            ),
        ),
    ]
