# Generated by Django 5.2 on 2025-10-06 18:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0074_homepage_quick_access_tiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="quick_access_tiles",
            field=wagtail.fields.StreamField(
                [("tile", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tile text", "max_length": 255, "required": True},
                    ),
                    1: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Select an SVG file."},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("svg_file", 1)]],
                        {"required": True},
                    ),
                    3: ("wagtail.blocks.PageChooserBlock", (), {"required": True}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 0),
                                ("icon", 2),
                                ("related_page", 3),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Add multiple quick access tiles",
            ),
        ),
    ]
