# Generated by Django 5.2 on 2025-10-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0075_alter_newsitem_banner_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="banner_options",
            field=models.CharField(
                choices=[
                    ("none", "No banner"),
                    ("high", "High priority (Yellow banner)"),
                    ("critical", "Critical (Red banner)"),
                ],
                default="none",
                help_text="Select the banner type for the news article",
                max_length=20,
            ),
        ),
    ]
