# Generated by Django 5.2 on 2025-10-14 15:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0076_alter_newsitem_banner_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="full_width_quick_access_tile",
            field=wagtail.fields.StreamField(
                [("tile", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tile text", "max_length": 255, "required": True},
                    ),
                    1: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Select an SVG file."},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("svg_file", 1)]],
                        {"required": True},
                    ),
                    3: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "External link URL", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 2),
                                ("related_page", 3),
                                ("external_url", 4),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Add one optional full-width quick access tile.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="quick_access_tiles",
            field=wagtail.fields.StreamField(
                [("tile", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Tile text", "max_length": 255, "required": True},
                    ),
                    1: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Select an SVG file."},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("svg_file", 1)]],
                        {"required": True},
                    ),
                    3: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "External link URL", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 0),
                                ("icon", 2),
                                ("related_page", 3),
                                ("external_url", 4),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Add multiple quick access tiles",
            ),
        ),
    ]
