# Generated by Django 5.2 on 2025-10-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0077_homepage_full_width_quick_access_tile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chief_judge",
                    models.CharField(
                        default="Patrick J. Urda, Chief Judge",
                        help_text="Name and title of the Chief Judge",
                        max_length=255,
                    ),
                ),
                (
                    "clerk_of_court",
                    models.CharField(
                        default="Charles G. Jeane, Clerk of the Court",
                        help_text="Name and title of the Clerk of the Court",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
