# Generated by Django 5.2 on 2025-10-20 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0077_homepage_full_width_quick_access_tile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footer",
            name="otherQuestions",
        ),
    ]
