# Generated by Django 5.2 on 2025-10-28 00:00

from django.db import migrations


def fix_trail_court_typo(apps, schema_editor):
    """Fix typo: 'trail court' -> 'trial court' in HomePage hero_body field"""
    HomePage = apps.get_model("home", "HomePage")

    # Find all HomePage instances with 'trail court' in hero_body
    for page in HomePage.objects.all():
        if page.hero_body and "trail court" in page.hero_body.lower():
            # Replace all occurrences (case-insensitive)
            original = page.hero_body
            # Handle different casings
            updated = original.replace("trail court", "trial court")
            updated = updated.replace("Trail court", "Trial court")
            updated = updated.replace("Trail Court", "Trial Court")
            updated = updated.replace("TRAIL COURT", "TRIAL COURT")

            if updated != original:
                page.hero_body = updated
                page.save()


def reverse_fix(apps, schema_editor):
    """Reverse the fix by changing 'trial court' back to 'trail court'"""
    HomePage = apps.get_model("home", "HomePage")

    # Find all HomePage instances with 'trial court' in hero_body
    for page in HomePage.objects.all():
        if page.hero_body and "trial court" in page.hero_body.lower():
            # Replace all occurrences (case-insensitive)
            original = page.hero_body
            # Handle different casings
            updated = original.replace("trial court", "trail court")
            updated = updated.replace("Trial court", "Trail court")
            updated = updated.replace("Trial Court", "Trail Court")
            updated = updated.replace("TRIAL COURT", "TRAIL COURT")

            if updated != original:
                page.hero_body = updated
                page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0079_remove_footer_otherquestions"),
    ]

    operations = [
        migrations.RunPython(
            code=fix_trail_court_typo,
            reverse_code=reverse_fix,
        ),
    ]
