# Generated by Django 5.2.7 on 2025-11-03 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0071_definitionspage"),
        ("home", "0080_fix_trail_court_typo"),
    ]

    operations = []
