# Generated by Django 5.2.8 on 2025-11-17 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0081_merge_0071_definitionspage_0080_fix_trail_court_typo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="hero_title",
            new_name="intro_text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="intro",
        ),
    ]
