# Generated by Django 5.2.7 on 2025-11-13 20:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0082_rename_hero_title_homepage_intro_text_and_more.py"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Summary of the news article",
                verbose_name="Summary",
            ),
        ),
    ]
