# Generated by Django 5.2.8 on 2025-11-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0082_rename_hero_title_homepage_intro_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caserelatedformspage",
            name="show_floating_definitions_button",
            field=models.BooleanField(
                default=False,
                help_text="Check to display the floating definitions button on this page.",
                verbose_name="Floating Definitions Button",
            ),
        ),
        migrations.AddField(
            model_name="enhancedstandardpage",
            name="show_floating_definitions_button",
            field=models.BooleanField(
                default=False,
                help_text="Check to display the floating definitions button on this page.",
                verbose_name="Floating Definitions Button",
            ),
        ),
    ]
