# Generated by Django 5.2.8 on 2025-12-18 17:48

import django.db.models.deletion
import wagtail.fields
import wagtail.models.workflows
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0085_alter_enhancedstandardpage_body"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtaildocs", "0014_alter_document_file_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsitem",
            name="banner_end_date",
        ),
        migrations.RemoveField(
            model_name="newsitem",
            name="banner_options",
        ),
        migrations.RemoveField(
            model_name="newsitem",
            name="banner_start_date",
        ),
        migrations.AddField(
            model_name="newsitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("news", "News Item"),
                    ("high", "High priority Announcement"),
                    ("critical", "Critical Anouncement"),
                ],
                default="news",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "live",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="live"
                    ),
                ),
                (
                    "has_unpublished_changes",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="has unpublished changes",
                    ),
                ),
                (
                    "first_published_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="first published at",
                    ),
                ),
                (
                    "last_published_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="last published at"
                    ),
                ),
                (
                    "go_live_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="go live date/time"
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expiry date/time"
                    ),
                ),
                (
                    "expired",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="expired"
                    ),
                ),
                (
                    "review_by",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for review and moderation of this content.",
                        null=True,
                        verbose_name="Review by date",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional note for moderators when submitting content for review.",
                        null=True,
                        verbose_name="Moderation note",
                    ),
                ),
                (
                    "banner_title",
                    models.CharField(
                        help_text="Character Limit 0f 115", max_length=115
                    ),
                ),
                ("description", wagtail.fields.RichTextField()),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("high", "High priority (Yellow banner)"),
                            ("critical", "Critical (Red banner)"),
                        ],
                        default="none",
                        help_text="Select the banner type for the news article",
                        max_length=20,
                    ),
                ),
                (
                    "banner_start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date/time when the banner should start appearing (required for high and critical priority banner)",
                        null=True,
                    ),
                ),
                (
                    "banner_end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date/time when the banner should stop appearing (optional - leave blank for indefinite display until replaced by a new banner)",
                        null=True,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                    ),
                ),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail.models.workflows.WorkflowMixin, models.Model),
        ),
    ]
