# Generated by Django 5.2.8 on 2025-12-11 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0085_remove_newsitem_banner_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="banner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="news_items",
                to="home.banner",
            ),
        ),
    ]
