# Generated by Django 5.2.8 on 2025-12-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0085_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleTagManagerSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gtm_container_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Tag Manager Container ID, e.g. GTM-XXXXXXX",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
