# Generated by Django 5.2.8 on 2025-12-22 21:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0085_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("snippet", 8),
                    ("button", 16),
                    ("hr", 17),
                    ("iframe", 21),
                    ("alert", 23),
                    ("image", 24),
                    ("photo_dedication", 29),
                    ("table", 30),
                    ("unstyled_table", 30),
                    ("list", 47),
                    ("links", 54),
                    ("questionanswers", 56),
                    ("columns", 65),
                    ("embedded_video", 67),
                    ("card", 72),
                    ("accordian", 78),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    9: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Optional: Button icon", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to"},
                    ),
                    12: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Enter an external URL"},
                    ),
                    13: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal_page", 11), ("external_url", 12)]],
                        {
                            "help_text": "Choose either an internal page or external URL",
                            "label": "URL",
                            "max_num": 1,
                            "min_num": 1,
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary")],
                            "help_text": "Choose the button style",
                        },
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect on button",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 9),
                                ("text", 10),
                                ("url", 13),
                                ("style", 14),
                                ("button_hover", 15),
                            ]
                        ],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    18: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    19: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    20: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("src", 18),
                                ("width", 19),
                                ("height", 19),
                                ("class", 20),
                                ("loading", 20),
                                ("data_delay", 20),
                                ("name", 20),
                                ("title", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success")]},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("alert_type", 22), ("content", 7)]],
                        {},
                    ),
                    24: ("wagtail.images.blocks.ImageBlock", [], {}),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    26: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {
                            "help_text": "Upload an image to display with this dedication"
                        },
                    ),
                    27: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Provide alternative text for the image for accessibility.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 25),
                                ("photo", 26),
                                ("paragraph_text", 27),
                                ("alt_text", 28),
                            ]
                        ],
                        {},
                    ),
                    30: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                            ],
                            "required": False,
                        },
                    ),
                    32: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 32), ("image", 24)]],
                        {"required": False},
                    ),
                    34: ("wagtail.blocks.ListBlock", (33,), {"default": []}),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 31), ("items", 34)]],
                        {"required": False},
                    ),
                    36: ("wagtail.blocks.ListBlock", (35,), {"default": []}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 32), ("image", 24), ("nested_list", 36)]],
                        {"required": False},
                    ),
                    38: ("wagtail.blocks.ListBlock", (37,), {"default": []}),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 31), ("items", 38)]],
                        {"required": False},
                    ),
                    40: ("wagtail.blocks.ListBlock", (39,), {"default": []}),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 32), ("image", 24), ("nested_list", 40)]],
                        {"required": False},
                    ),
                    42: ("wagtail.blocks.ListBlock", (41,), {"default": []}),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 31), ("items", 42)]],
                        {"required": False},
                    ),
                    44: ("wagtail.blocks.ListBlock", (43,), {"default": []}),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 32), ("image", 24), ("nested_list", 44)]],
                        {"required": False},
                    ),
                    46: ("wagtail.blocks.ListBlock", (45,), {"default": []}),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 31), ("items", 46)]],
                        {"required": False},
                    ),
                    48: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ],
                            "label": "List style",
                        },
                    ),
                    49: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    51: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 49),
                                ("document", 50),
                                ("video", 50),
                                ("url", 20),
                                ("text_only", 51),
                            ]
                        ],
                        {},
                    ),
                    53: ("wagtail.blocks.ListBlock", (52,), {"label": "Add Entry"}),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 48), ("links", 53)]],
                        {"label": "List of Links"},
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 20), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    56: (
                        "wagtail.blocks.ListBlock",
                        (55,),
                        {
                            "help_text": "Add a question and answer with anchor tag for linking",
                            "label": "Question and Answer",
                        },
                    ),
                    57: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 20)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 20)]],
                        {"label": "Clickable Button"},
                    ),
                    60: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    61: ("wagtail.blocks.ListBlock", (52,), {}),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 60), ("links", 61)]],
                        {"label": "Links"},
                    ),
                    63: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 4),
                                ("h3", 5),
                                ("hr", 57),
                                ("h2WithAnchorTag", 58),
                                ("clickableButton", 59),
                                ("links", 62),
                            ]
                        ],
                        {},
                    ),
                    64: ("wagtail.blocks.ListBlock", (63,), {}),
                    65: ("wagtail.blocks.StructBlock", [[("column", 64)]], {}),
                    66: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 20), ("description", 32), ("video_url", 66)]],
                        {},
                    ),
                    68: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ]
                        },
                    ),
                    69: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    70: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    71: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 68),
                                ("title", 19),
                                ("description", 69),
                                ("color", 70),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    72: ("wagtail.blocks.ListBlock", (71,), {"label": "Card Set"}),
                    73: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title user will see before opening",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    74: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of this special element",
                            "required": True,
                        },
                    ),
                    75: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "The paragraph content", "required": True},
                    ),
                    76: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 74), ("text", 75)]],
                        {},
                    ),
                    77: (
                        "wagtail.blocks.StreamBlock",
                        [[("prose", 7), ("callout", 76)]],
                        {
                            "help_text": "Add text or special elements to the body",
                            "required": True,
                        },
                    ),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 73), ("description", 77)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="pressreleasepage",
            name="press_release_body",
            field=wagtail.fields.StreamField(
                [("button", 7), ("press_releases", 13)],
                blank=True,
                block_lookup={
                    0: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Optional: Button icon", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to"},
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Enter an external URL"},
                    ),
                    4: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal_page", 2), ("external_url", 3)]],
                        {
                            "help_text": "Choose either an internal page or external URL",
                            "label": "URL",
                            "max_num": 1,
                            "min_num": 1,
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary")],
                            "help_text": "Choose the button style",
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect on button",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 0),
                                ("text", 1),
                                ("url", 4),
                                ("style", 5),
                                ("button_hover", 6),
                            ]
                        ],
                        {},
                    ),
                    8: ("wagtail.blocks.DateBlock", (), {"required": False}),
                    9: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    10: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("description", 9), ("file", 10)]],
                        {"required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("release_date", 8), ("details", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                },
                null=True,
            ),
        ),
    ]
