# Generated by Django 5.2.8 on 2026-01-12 19:18

import django.db.models.deletion
import wagtail.fields
import wagtail.models.workflows
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0086_alter_enhancedstandardpage_body"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtaildocs", "0014_alter_document_file_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsitem",
            name="banner_end_date",
        ),
        migrations.RemoveField(
            model_name="newsitem",
            name="banner_options",
        ),
        migrations.RemoveField(
            model_name="newsitem",
            name="banner_start_date",
        ),
        migrations.AddField(
            model_name="newsitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("news", "News Item"),
                    ("high", "High priority Announcement"),
                    ("critical", "Critical Announcement"),
                ],
                default="news",
                max_length=20,
            ),
        ),
        # NOTE: The following AlterField for enhancedstandardpage.body includes schema changes
        # (addition of 'callout' block type and updated callout_type field) that should have been
        # part of the callout story (already merged). These changes are included here to backfill
        # the omitted schema update and ensure consistency. This is not a mistake—it's a correction.
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("snippet", 8),
                    ("button", 12),
                    ("hr", 13),
                    ("iframe", 17),
                    ("alert", 19),
                    ("image", 20),
                    ("photo_dedication", 25),
                    ("table", 26),
                    ("unstyled_table", 26),
                    ("list", 43),
                    ("links", 50),
                    ("questionanswers", 52),
                    ("columns", 61),
                    ("embedded_video", 63),
                    ("card", 68),
                    ("accordion", 75),
                    ("callout", 73),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "required": True},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button link  (Can be relative or absolute)",
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary")],
                            "help_text": "Choose the button style",
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 9), ("href", 10), ("style", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    14: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    15: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    16: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("src", 14),
                                ("width", 15),
                                ("height", 15),
                                ("class", 16),
                                ("loading", 16),
                                ("data_delay", 16),
                                ("name", 16),
                                ("title", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success")]},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("alert_type", 18), ("content", 7)]],
                        {},
                    ),
                    20: ("wagtail.images.blocks.ImageBlock", [], {}),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    22: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {
                            "help_text": "Upload an image to display with this dedication"
                        },
                    ),
                    23: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Provide alternative text for the image for accessibility.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 21),
                                ("photo", 22),
                                ("paragraph_text", 23),
                                ("alt_text", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                            ],
                            "required": False,
                        },
                    ),
                    28: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 28), ("image", 20)]],
                        {"required": False},
                    ),
                    30: ("wagtail.blocks.ListBlock", (29,), {"default": []}),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 27), ("items", 30)]],
                        {"required": False},
                    ),
                    32: ("wagtail.blocks.ListBlock", (31,), {"default": []}),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 28), ("image", 20), ("nested_list", 32)]],
                        {"required": False},
                    ),
                    34: ("wagtail.blocks.ListBlock", (33,), {"default": []}),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 27), ("items", 34)]],
                        {"required": False},
                    ),
                    36: ("wagtail.blocks.ListBlock", (35,), {"default": []}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 28), ("image", 20), ("nested_list", 36)]],
                        {"required": False},
                    ),
                    38: ("wagtail.blocks.ListBlock", (37,), {"default": []}),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 27), ("items", 38)]],
                        {"required": False},
                    ),
                    40: ("wagtail.blocks.ListBlock", (39,), {"default": []}),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 28), ("image", 20), ("nested_list", 40)]],
                        {"required": False},
                    ),
                    42: ("wagtail.blocks.ListBlock", (41,), {"default": []}),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 27), ("items", 42)]],
                        {"required": False},
                    ),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ],
                            "label": "List style",
                        },
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    46: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    47: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 45),
                                ("document", 46),
                                ("video", 46),
                                ("url", 16),
                                ("text_only", 47),
                            ]
                        ],
                        {},
                    ),
                    49: ("wagtail.blocks.ListBlock", (48,), {"label": "Add Entry"}),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 44), ("links", 49)]],
                        {"label": "List of Links"},
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 16), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    52: (
                        "wagtail.blocks.ListBlock",
                        (51,),
                        {
                            "help_text": "Add a question and answer with anchor tag for linking",
                            "label": "Question and Answer",
                        },
                    ),
                    53: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 16)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 16)]],
                        {"label": "Clickable Button"},
                    ),
                    56: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    57: ("wagtail.blocks.ListBlock", (48,), {}),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 56), ("links", 57)]],
                        {"label": "Links"},
                    ),
                    59: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 4),
                                ("h3", 5),
                                ("hr", 53),
                                ("h2WithAnchorTag", 54),
                                ("clickableButton", 55),
                                ("links", 58),
                            ]
                        ],
                        {},
                    ),
                    60: ("wagtail.blocks.ListBlock", (59,), {}),
                    61: ("wagtail.blocks.StructBlock", [[("column", 60)]], {}),
                    62: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 16), ("description", 28), ("video_url", 62)]],
                        {},
                    ),
                    64: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ]
                        },
                    ),
                    65: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    66: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 64),
                                ("title", 15),
                                ("description", 65),
                                ("color", 66),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    68: ("wagtail.blocks.ListBlock", (67,), {"label": "Card Set"}),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title user will see before opening",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    70: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of this special element",
                            "required": True,
                        },
                    ),
                    71: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "The paragraph content", "required": True},
                    ),
                    72: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("success", "Success"),
                                ("error", "Error"),
                                ("emergency", "Emergency"),
                            ]
                        },
                    ),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 70), ("text", 71), ("callout_type", 72)]],
                        {},
                    ),
                    74: (
                        "wagtail.blocks.StreamBlock",
                        [[("prose", 7), ("callout", 73)]],
                        {
                            "help_text": "Add text or special elements to the body",
                            "required": True,
                        },
                    ),
                    75: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 69), ("description", 74)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "live",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="live"
                    ),
                ),
                (
                    "has_unpublished_changes",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="has unpublished changes",
                    ),
                ),
                (
                    "first_published_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="first published at",
                    ),
                ),
                (
                    "last_published_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="last published at"
                    ),
                ),
                (
                    "go_live_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="go live date/time"
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expiry date/time"
                    ),
                ),
                (
                    "expired",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="expired"
                    ),
                ),
                (
                    "review_by",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for review and moderation of this content.",
                        null=True,
                        verbose_name="Review by date",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional note for moderators when submitting content for review.",
                        null=True,
                        verbose_name="Moderation note",
                    ),
                ),
                (
                    "banner_title",
                    models.CharField(
                        help_text="Character Limit of 115", max_length=115
                    ),
                ),
                ("description", models.CharField()),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("high", "High priority (Yellow banner)"),
                            ("critical", "Critical (Red banner)"),
                        ],
                        default="none",
                        help_text="Select the banner type for the news article",
                        max_length=20,
                    ),
                ),
                (
                    "banner_start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date/time when the banner should start appearing (required for high and critical priority banner)",
                        null=True,
                    ),
                ),
                (
                    "banner_end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date/time when the banner should stop appearing (optional - leave blank for indefinite display until replaced by a new banner)",
                        null=True,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                    ),
                ),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail.models.workflows.WorkflowMixin, models.Model),
        ),
    ]
