# Generated by Django 5.2.8 on 2025-12-16 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0086_newsitem_banner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsitem",
            name="banner",
        ),
    ]
