# Generated by Django 5.2.8 on 2026-01-08 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0086_alter_enhancedstandardpage_body"),
        ("home", "0086_googletagmanagersettings"),
    ]

    operations = []
