# Generated by Django 5.2.8 on 2026-01-13 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0087_merge_20260108_0858"),
        ("home", "0087_remove_newsitem_banner_end_date_and_more"),
    ]

    operations = []
