# Generated by Django 5.2.8 on 2025-12-17 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0085_alter_enhancedstandardpage_body"),
        ("home", "0087_remove_newsitem_banner"),
    ]

    operations = []
