# Generated by Django 5.2.8 on 2026-01-15 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0088_alter_enhancedstandardpage_body"),
        ("home", "0088_merge_20260113_1621"),
    ]

    operations = []
