# Generated by Django 5.2.8 on 2026-01-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0088_merge_20260113_1621"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pamphletentry",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="pamphletentry",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
