# Generated by Django 5.2.8 on 2026-01-22 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0089_pamphlet_entry_orderable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pamphletentry",
            name="volume_number",
        ),
    ]
