# Generated by Django 5.2.8 on 2026-01-26 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0089_alter_enhancedstandardpage_body"),
        ("home", "0091_alter_enhancedstandardpage_body"),
    ]

    operations = []
