# Generated by Django 5.2.8 on 2026-01-27 21:04

from django.db import migrations


def create_subcollection_under_parent(apps, schema_editor):
    Collection = apps.get_model("wagtailcore", "Collection")

    parent_name = "News and Announcements"
    subcollection_name = "Home Page News Images"

    try:
        Collection.objects.get(name=parent_name)
    except Collection.DoesNotExist:
        raise RuntimeError(
            f"Parent collection '{parent_name}' does not exist. Migration aborted."
        )

    # Create subcollection if it doesn't already exist under this parent
    from wagtail.models import Collection as RealCollection

    try:
        # Use the real model to get the root and create the child
        parent_collection_real = RealCollection.objects.get(name=parent_name)
        if (
            not parent_collection_real.get_children()
            .filter(name=subcollection_name)
            .exists()
        ):
            parent_collection_real.add_child(name=subcollection_name)

    except Exception as e:
        raise RuntimeError(
            f"FATAL: Could not create subcollection '{subcollection_name}' under collection '{parent_name}'. Error: {e}"
        )


def delete_subcollection_under_parent(apps, schema_editor):
    Collection = apps.get_model("wagtailcore", "Collection")

    parent_name = "News and Announcements"
    subcollection_name = "Home Page News Images"

    try:
        Collection.objects.get(name=parent_name)
    except Collection.DoesNotExist:
        return  # Parent missing, nothing to delete

    from wagtail.models import Collection as RealCollection

    try:
        # Use the real model to get the root and create the child
        parent_collection_real = RealCollection.objects.get(name=parent_name)
        parent_collection_real.get_children().filter(name=subcollection_name).delete()

    except Exception as e:
        raise RuntimeError(
            f"FATAL: Could not create subcollection '{subcollection_name}' under collection '{parent_name}'. Error: {e}"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0091_auto_20260127_1550"),
    ]

    operations = [
        migrations.RunPython(
            create_subcollection_under_parent, delete_subcollection_under_parent
        ),
    ]
