# Generated by Django 5.2.8 on 2026-01-30 19:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0091_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("snippet", 8),
                    ("button", 17),
                    ("hr", 18),
                    ("iframe", 22),
                    ("alert", 24),
                    ("image", 25),
                    ("photo_dedication", 30),
                    ("table", 31),
                    ("unstyled_table", 31),
                    ("list", 48),
                    ("links", 55),
                    ("questionanswers", 57),
                    ("columns", 66),
                    ("embedded_video", 68),
                    ("card", 73),
                    ("accordion", 80),
                    ("callout", 78),
                    ("grid", 90),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    9: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Optional: Button icon", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to"},
                    ),
                    12: (
                        "home.blocks.PDFDocumentChooserBlock",
                        (),
                        {"help_text": "Select a PDF to link to"},
                    ),
                    13: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Enter an external URL"},
                    ),
                    14: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 11),
                                ("internal_pdf", 12),
                                ("external_url", 13),
                            ]
                        ],
                        {
                            "help_text": "Select exactly one: Internal Page, External URL, or PDF.",
                            "label": "URL",
                            "max_num": 1,
                            "min_num": 1,
                        },
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary")],
                            "help_text": "Choose the button style",
                        },
                    ),
                    16: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect on button",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 9),
                                ("text", 10),
                                ("url", 14),
                                ("style", 15),
                                ("button_hover", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    19: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    20: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    21: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("src", 19),
                                ("width", 20),
                                ("height", 20),
                                ("class", 21),
                                ("loading", 21),
                                ("data_delay", 21),
                                ("name", 21),
                                ("title", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success")]},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("alert_type", 23), ("content", 7)]],
                        {},
                    ),
                    25: ("wagtail.images.blocks.ImageBlock", [], {}),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    27: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {
                            "help_text": "Upload an image to display with this dedication"
                        },
                    ),
                    28: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Provide alternative text for the image for accessibility.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 26),
                                ("photo", 27),
                                ("paragraph_text", 28),
                                ("alt_text", 29),
                            ]
                        ],
                        {},
                    ),
                    31: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                            ],
                            "required": False,
                        },
                    ),
                    33: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 33), ("image", 25)]],
                        {"required": False},
                    ),
                    35: ("wagtail.blocks.ListBlock", (34,), {"default": []}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 32), ("items", 35)]],
                        {"required": False},
                    ),
                    37: ("wagtail.blocks.ListBlock", (36,), {"default": []}),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 33), ("image", 25), ("nested_list", 37)]],
                        {"required": False},
                    ),
                    39: ("wagtail.blocks.ListBlock", (38,), {"default": []}),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 32), ("items", 39)]],
                        {"required": False},
                    ),
                    41: ("wagtail.blocks.ListBlock", (40,), {"default": []}),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 33), ("image", 25), ("nested_list", 41)]],
                        {"required": False},
                    ),
                    43: ("wagtail.blocks.ListBlock", (42,), {"default": []}),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 32), ("items", 43)]],
                        {"required": False},
                    ),
                    45: ("wagtail.blocks.ListBlock", (44,), {"default": []}),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 33), ("image", 25), ("nested_list", 45)]],
                        {"required": False},
                    ),
                    47: ("wagtail.blocks.ListBlock", (46,), {"default": []}),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 32), ("items", 47)]],
                        {"required": False},
                    ),
                    49: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ],
                            "label": "List style",
                        },
                    ),
                    50: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    51: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    52: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 50),
                                ("document", 51),
                                ("video", 51),
                                ("url", 21),
                                ("text_only", 52),
                            ]
                        ],
                        {},
                    ),
                    54: ("wagtail.blocks.ListBlock", (53,), {"label": "Add Entry"}),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 49), ("links", 54)]],
                        {"label": "List of Links"},
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 21), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    57: (
                        "wagtail.blocks.ListBlock",
                        (56,),
                        {
                            "help_text": "Add a question and answer with anchor tag for linking",
                            "label": "Question and Answer",
                        },
                    ),
                    58: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 21)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 21)]],
                        {"label": "Clickable Button"},
                    ),
                    61: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    62: ("wagtail.blocks.ListBlock", (53,), {}),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 61), ("links", 62)]],
                        {"label": "Links"},
                    ),
                    64: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 4),
                                ("h3", 5),
                                ("hr", 58),
                                ("h2WithAnchorTag", 59),
                                ("clickableButton", 60),
                                ("links", 63),
                            ]
                        ],
                        {},
                    ),
                    65: ("wagtail.blocks.ListBlock", (64,), {}),
                    66: ("wagtail.blocks.StructBlock", [[("column", 65)]], {}),
                    67: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    68: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 21), ("description", 33), ("video_url", 67)]],
                        {},
                    ),
                    69: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ]
                        },
                    ),
                    70: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    71: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 69),
                                ("title", 20),
                                ("description", 70),
                                ("color", 71),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    73: ("wagtail.blocks.ListBlock", (72,), {"label": "Card Set"}),
                    74: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title user will see before opening",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of this special element",
                            "required": True,
                        },
                    ),
                    76: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "The paragraph content", "required": True},
                    ),
                    77: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("success", "Success"),
                                ("error", "Error"),
                                ("emergency", "Emergency"),
                            ]
                        },
                    ),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 75), ("text", 76), ("callout_type", 77)]],
                        {},
                    ),
                    79: (
                        "wagtail.blocks.StreamBlock",
                        [[("prose", 7), ("callout", 78)]],
                        {
                            "help_text": "Add text or special elements to the body",
                            "required": True,
                        },
                    ),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 74), ("description", 79)]],
                        {},
                    ),
                    81: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [(1, 1), (2, 2), (3, 3), (4, 4)],
                            "help_text": "Max number of columns in the grid (1-4)",
                        },
                    ),
                    82: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("full", "Full Width")],
                            "help_text": "Maximum width of the grid",
                        },
                    ),
                    83: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("styled", "Styled"), ("unstyled", "Unstyled")],
                            "help_text": "Style of the grid",
                        },
                    ),
                    84: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional header for this grid cell",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    85: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional caption for this grid cell (links allowed)",
                            "required": False,
                        },
                    ),
                    86: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Make the caption text italic",
                            "required": False,
                        },
                    ),
                    87: (
                        "wagtail.blocks.StreamBlock",
                        [[("prose", 7), ("callout", 78)]],
                        {
                            "help_text": "Add text or special elements to the cell body",
                            "required": True,
                        },
                    ),
                    88: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 84),
                                ("caption", 85),
                                ("italic_caption", 86),
                                ("body", 87),
                            ]
                        ],
                        {},
                    ),
                    89: (
                        "wagtail.blocks.ListBlock",
                        (88,),
                        {
                            "help_text": "Add cells to the grid. Cells will fill row-by-row based on the number of columns selected."
                        },
                    ),
                    90: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("columns", 81),
                                ("width", 82),
                                ("gridStyle", 83),
                                ("cells", 89),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
