# Generated by Django 5.2.8 on 2026-02-06 18:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0092_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("snippet", 8),
                    ("button", 17),
                    ("hr", 18),
                    ("iframe", 22),
                    ("alert", 24),
                    ("image", 25),
                    ("photo_dedication", 30),
                    ("table", 31),
                    ("unstyled_table", 31),
                    ("enhanced_table", 44),
                    ("list", 61),
                    ("links", 68),
                    ("questionanswers", 70),
                    ("columns", 79),
                    ("embedded_video", 81),
                    ("card", 86),
                    ("accordian", 38),
                    ("callout", 35),
                    ("grid", 96),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    9: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Optional: Button icon", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to"},
                    ),
                    12: (
                        "home.blocks.PDFDocumentChooserBlock",
                        (),
                        {"help_text": "Select a PDF to link to"},
                    ),
                    13: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Enter an external URL"},
                    ),
                    14: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 11),
                                ("internal_pdf", 12),
                                ("external_url", 13),
                            ]
                        ],
                        {
                            "help_text": "Select exactly one: Internal Page, External URL, or PDF.",
                            "label": "URL",
                            "max_num": 1,
                            "min_num": 1,
                        },
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary")],
                            "help_text": "Choose the button style",
                        },
                    ),
                    16: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect on button",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 9),
                                ("text", 10),
                                ("url", 14),
                                ("style", 15),
                                ("button_hover", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    19: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    20: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    21: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("src", 19),
                                ("width", 20),
                                ("height", 20),
                                ("class", 21),
                                ("loading", 21),
                                ("data_delay", 21),
                                ("name", 21),
                                ("title", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success")]},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("alert_type", 23), ("content", 7)]],
                        {},
                    ),
                    25: ("wagtail.images.blocks.ImageBlock", [], {}),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    27: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {
                            "help_text": "Upload an image to display with this dedication"
                        },
                    ),
                    28: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Provide alternative text for the image for accessibility.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 26),
                                ("photo", 27),
                                ("paragraph_text", 28),
                                ("alt_text", 29),
                            ]
                        ],
                        {},
                    ),
                    31: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of this special element",
                            "required": True,
                        },
                    ),
                    33: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "The paragraph content", "required": True},
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("success", "Success"),
                                ("error", "Error"),
                                ("emergency", "Emergency"),
                            ]
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 32), ("text", 33), ("callout_type", 34)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title user will see before opening",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    37: (
                        "wagtail.blocks.StreamBlock",
                        [[("prose", 7), ("callout", 35)]],
                        {
                            "help_text": "Add text or special elements to the body",
                            "required": True,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 36), ("description", 37)]],
                        {},
                    ),
                    39: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 7),
                                ("callout", 35),
                                ("accordian", 38),
                                ("button", 17),
                            ]
                        ],
                        {},
                    ),
                    40: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("components", 39)]],
                        {},
                    ),
                    41: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("top", "Top"), ("bottom", "Bottom")]},
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("styled", "Styled Table"),
                                ("borderlessUnstyled", "Borderless Unstyled Table"),
                                ("unstyled", "Unstyled Table"),
                            ]
                        },
                    ),
                    43: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to set table layout to fixed width.",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("table", 40),
                                ("caption_location", 41),
                                ("style", 42),
                                ("fixed", 43),
                            ]
                        ],
                        {},
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                            ],
                            "required": False,
                        },
                    ),
                    46: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 46), ("image", 25)]],
                        {"required": False},
                    ),
                    48: ("wagtail.blocks.ListBlock", (47,), {"default": []}),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 45), ("items", 48)]],
                        {"required": False},
                    ),
                    50: ("wagtail.blocks.ListBlock", (49,), {"default": []}),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 46), ("image", 25), ("nested_list", 50)]],
                        {"required": False},
                    ),
                    52: ("wagtail.blocks.ListBlock", (51,), {"default": []}),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 45), ("items", 52)]],
                        {"required": False},
                    ),
                    54: ("wagtail.blocks.ListBlock", (53,), {"default": []}),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 46), ("image", 25), ("nested_list", 54)]],
                        {"required": False},
                    ),
                    56: ("wagtail.blocks.ListBlock", (55,), {"default": []}),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 45), ("items", 56)]],
                        {"required": False},
                    ),
                    58: ("wagtail.blocks.ListBlock", (57,), {"default": []}),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 46), ("image", 25), ("nested_list", 58)]],
                        {"required": False},
                    ),
                    60: ("wagtail.blocks.ListBlock", (59,), {"default": []}),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 45), ("items", 60)]],
                        {"required": False},
                    ),
                    62: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ],
                            "label": "List style",
                        },
                    ),
                    63: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    64: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    65: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 63),
                                ("document", 64),
                                ("video", 64),
                                ("url", 21),
                                ("text_only", 65),
                            ]
                        ],
                        {},
                    ),
                    67: ("wagtail.blocks.ListBlock", (66,), {"label": "Add Entry"}),
                    68: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 62), ("links", 67)]],
                        {"label": "List of Links"},
                    ),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 21), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    70: (
                        "wagtail.blocks.ListBlock",
                        (69,),
                        {
                            "help_text": "Add a question and answer with anchor tag for linking",
                            "label": "Question and Answer",
                        },
                    ),
                    71: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 21)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 21)]],
                        {"label": "Clickable Button"},
                    ),
                    74: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    75: ("wagtail.blocks.ListBlock", (66,), {}),
                    76: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 74), ("links", 75)]],
                        {"label": "Links"},
                    ),
                    77: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 4),
                                ("h3", 5),
                                ("hr", 71),
                                ("h2WithAnchorTag", 72),
                                ("clickableButton", 73),
                                ("links", 76),
                            ]
                        ],
                        {},
                    ),
                    78: ("wagtail.blocks.ListBlock", (77,), {}),
                    79: ("wagtail.blocks.StructBlock", [[("column", 78)]], {}),
                    80: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    81: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 21), ("description", 46), ("video_url", 80)]],
                        {},
                    ),
                    82: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ]
                        },
                    ),
                    83: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    84: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 82),
                                ("title", 20),
                                ("description", 83),
                                ("color", 84),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    86: ("wagtail.blocks.ListBlock", (85,), {"label": "Card Set"}),
                    87: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [(1, 1), (2, 2), (3, 3), (4, 4)],
                            "help_text": "Max number of columns in the grid (1-4)",
                        },
                    ),
                    88: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("full", "Full Width")],
                            "help_text": "Maximum width of the grid",
                        },
                    ),
                    89: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("styled", "Styled"), ("unstyled", "Unstyled")],
                            "help_text": "Style of the grid",
                        },
                    ),
                    90: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional header for this grid cell",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    91: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional caption for this grid cell (links allowed)",
                            "required": False,
                        },
                    ),
                    92: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Make the caption text italic",
                            "required": False,
                        },
                    ),
                    93: (
                        "wagtail.blocks.StreamBlock",
                        [[("prose", 7), ("callout", 35)]],
                        {
                            "help_text": "Add text or special elements to the cell body",
                            "required": True,
                        },
                    ),
                    94: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 90),
                                ("caption", 91),
                                ("italic_caption", 92),
                                ("body", 93),
                            ]
                        ],
                        {},
                    ),
                    95: (
                        "wagtail.blocks.ListBlock",
                        (94,),
                        {
                            "help_text": "Add cells to the grid. Cells will fill row-by-row based on the number of columns selected."
                        },
                    ),
                    96: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("columns", 87),
                                ("width", 88),
                                ("gridStyle", 89),
                                ("cells", 95),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
