# Generated by Django 5.2.8 on 2026-01-30 23:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0090_remove_pamphletentry_volume_number"),
        ("home", "0092_alter_enhancedstandardpage_body"),
    ]

    operations = []
