# Generated by Django 5.2.8 on 2026-02-06 10:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0092_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("indented_paragraph", 8),
                    ("snippet", 9),
                    ("button", 18),
                    ("hr", 19),
                    ("iframe", 23),
                    ("alert", 25),
                    ("image", 26),
                    ("photo_dedication", 31),
                    ("table", 32),
                    ("unstyled_table", 32),
                    ("list", 49),
                    ("links", 56),
                    ("questionanswers", 58),
                    ("columns", 67),
                    ("embedded_video", 69),
                    ("card", 74),
                    ("accordian", 81),
                    ("callout", 79),
                    ("card_tiles", 95),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Paragraph with left indentation for alignment with list items",
                            "label": "Indented Paragraph",
                        },
                    ),
                    9: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    10: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Optional: Button icon", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to"},
                    ),
                    13: (
                        "home.blocks.PDFDocumentChooserBlock",
                        (),
                        {"help_text": "Select a PDF to link to"},
                    ),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Enter an external URL"},
                    ),
                    15: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 12),
                                ("internal_pdf", 13),
                                ("external_url", 14),
                            ]
                        ],
                        {
                            "help_text": "Select exactly one: Internal Page, External URL, or PDF.",
                            "label": "URL",
                            "max_num": 1,
                            "min_num": 1,
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary")],
                            "help_text": "Choose the button style",
                        },
                    ),
                    17: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect on button",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 10),
                                ("text", 11),
                                ("url", 15),
                                ("style", 16),
                                ("button_hover", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    20: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    21: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    22: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("src", 20),
                                ("width", 21),
                                ("height", 21),
                                ("class", 22),
                                ("loading", 22),
                                ("data_delay", 22),
                                ("name", 22),
                                ("title", 22),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success")]},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("alert_type", 24), ("content", 7)]],
                        {},
                    ),
                    26: ("wagtail.images.blocks.ImageBlock", [], {}),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    28: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {
                            "help_text": "Upload an image to display with this dedication"
                        },
                    ),
                    29: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Provide alternative text for the image for accessibility.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 27),
                                ("photo", 28),
                                ("paragraph_text", 29),
                                ("alt_text", 30),
                            ]
                        ],
                        {},
                    ),
                    32: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                            ],
                            "required": False,
                        },
                    ),
                    34: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 34), ("image", 26)]],
                        {"required": False},
                    ),
                    36: ("wagtail.blocks.ListBlock", (35,), {"default": []}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 33), ("items", 36)]],
                        {"required": False},
                    ),
                    38: ("wagtail.blocks.ListBlock", (37,), {"default": []}),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 34), ("image", 26), ("nested_list", 38)]],
                        {"required": False},
                    ),
                    40: ("wagtail.blocks.ListBlock", (39,), {"default": []}),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 33), ("items", 40)]],
                        {"required": False},
                    ),
                    42: ("wagtail.blocks.ListBlock", (41,), {"default": []}),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 34), ("image", 26), ("nested_list", 42)]],
                        {"required": False},
                    ),
                    44: ("wagtail.blocks.ListBlock", (43,), {"default": []}),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 33), ("items", 44)]],
                        {"required": False},
                    ),
                    46: ("wagtail.blocks.ListBlock", (45,), {"default": []}),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 34), ("image", 26), ("nested_list", 46)]],
                        {"required": False},
                    ),
                    48: ("wagtail.blocks.ListBlock", (47,), {"default": []}),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 33), ("items", 48)]],
                        {"required": False},
                    ),
                    50: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ],
                            "label": "List style",
                        },
                    ),
                    51: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    52: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    53: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 51),
                                ("document", 52),
                                ("video", 52),
                                ("url", 22),
                                ("text_only", 53),
                            ]
                        ],
                        {},
                    ),
                    55: ("wagtail.blocks.ListBlock", (54,), {"label": "Add Entry"}),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 50), ("links", 55)]],
                        {"label": "List of Links"},
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 22), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    58: (
                        "wagtail.blocks.ListBlock",
                        (57,),
                        {
                            "help_text": "Add a question and answer with anchor tag for linking",
                            "label": "Question and Answer",
                        },
                    ),
                    59: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 22)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 22)]],
                        {"label": "Clickable Button"},
                    ),
                    62: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    63: ("wagtail.blocks.ListBlock", (54,), {}),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 62), ("links", 63)]],
                        {"label": "Links"},
                    ),
                    65: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 4),
                                ("h3", 5),
                                ("hr", 59),
                                ("h2WithAnchorTag", 60),
                                ("clickableButton", 61),
                                ("links", 64),
                            ]
                        ],
                        {},
                    ),
                    66: ("wagtail.blocks.ListBlock", (65,), {}),
                    67: ("wagtail.blocks.StructBlock", [[("column", 66)]], {}),
                    68: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 22), ("description", 34), ("video_url", 68)]],
                        {},
                    ),
                    70: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ]
                        },
                    ),
                    71: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    72: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 70),
                                ("title", 21),
                                ("description", 71),
                                ("color", 72),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    74: ("wagtail.blocks.ListBlock", (73,), {"label": "Card Set"}),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title user will see before opening",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    76: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of this special element",
                            "required": True,
                        },
                    ),
                    77: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "The paragraph content", "required": True},
                    ),
                    78: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("success", "Success"),
                                ("error", "Error"),
                                ("emergency", "Emergency"),
                            ]
                        },
                    ),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 76), ("text", 77), ("callout_type", 78)]],
                        {},
                    ),
                    80: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 3), ("prose", 7), ("callout", 79)]],
                        {
                            "help_text": "Add text or special elements to the body",
                            "required": True,
                        },
                    ),
                    81: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 75), ("description", 80)]],
                        {},
                    ),
                    82: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Card Icon", "required": True},
                    ),
                    83: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("right", "Right"),
                                ("bottom", "Bottom"),
                                ("left", "Left"),
                            ],
                            "help_text": "Icon placement, e.g. Top, Right, Bottom, Left. Default is Top.",
                            "required": False,
                        },
                    ),
                    84: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Displays the card title", "required": True},
                    ),
                    85: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "required": True},
                    ),
                    86: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 3),
                                ("h2", 4),
                                ("h3", 5),
                                ("h4", 6),
                                ("paragraph", 7),
                                ("indented_paragraph", 8),
                                ("snippet", 9),
                                ("button", 18),
                                ("hr", 19),
                                ("iframe", 23),
                                ("alert", 25),
                                ("image", 26),
                                ("photo_dedication", 31),
                                ("table", 32),
                                ("unstyled_table", 32),
                                ("list", 49),
                                ("links", 56),
                                ("questionanswers", 58),
                                ("columns", 67),
                                ("embedded_video", 69),
                                ("card", 74),
                                ("accordian", 81),
                                ("callout", 79),
                            ]
                        ],
                        {"required": False},
                    ),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [[("breadcrumb_title", 85), ("body", 86)]],
                        {},
                    ),
                    88: ("wagtail.blocks.PageChooserBlock", (), {}),
                    89: ("wagtail.blocks.URLBlock", (), {}),
                    90: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("anchor_page", 87),
                                ("internal_page", 88),
                                ("external_url", 89),
                            ]
                        ],
                        {"max_num": 1, "min_num": 1},
                    ),
                    91: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect",
                            "required": False,
                        },
                    ),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 82),
                                ("icon_direction", 83),
                                ("card_header", 84),
                                ("link", 90),
                                ("card_hover", 91),
                            ]
                        ],
                        {},
                    ),
                    93: (
                        "wagtail.blocks.ListBlock",
                        (92,),
                        {
                            "help_text": "Add up to 4 card tiles. They will display responsively based on screen size.",
                            "max_num": 4,
                            "min_num": 1,
                        },
                    ),
                    94: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 3),
                                ("h2", 4),
                                ("h3", 5),
                                ("h4", 6),
                                ("paragraph", 7),
                                ("indented_paragraph", 8),
                                ("snippet", 9),
                                ("button", 18),
                                ("hr", 19),
                                ("iframe", 23),
                                ("alert", 25),
                                ("image", 26),
                                ("photo_dedication", 31),
                                ("table", 32),
                                ("unstyled_table", 32),
                                ("list", 49),
                                ("links", 56),
                                ("questionanswers", 58),
                                ("columns", 67),
                                ("embedded_video", 69),
                                ("card", 74),
                                ("accordian", 81),
                                ("callout", 79),
                            ]
                        ],
                        {
                            "help_text": "Default content to display when no card is selected",
                            "required": False,
                        },
                    ),
                    95: (
                        "wagtail.blocks.StructBlock",
                        [[("tiles", 93), ("default_content", 94)]],
                        {},
                    ),
                },
            ),
        ),
    ]
