# Generated by Django 5.2.8 on 2026-01-27 20:50

from django.db import migrations


def rename_collection_to_new_name(apps, schema_editor):
    Collection = apps.get_model("wagtailcore", "Collection")

    old_collection_name = "Press Releases"
    new_collection_name = "News and Announcements"

    try:
        coll = Collection.objects.get(name=old_collection_name)
    except Collection.DoesNotExist:
        raise RuntimeError(
            f"Old collection '{old_collection_name}' does not exist. Migration aborted."
        )

    # Rename collection if it exists
    coll.name = new_collection_name
    coll.save(update_fields=["name"])


def rename_collection_back_to_old_name(apps, schema_editor):
    Collection = apps.get_model("wagtailcore", "Collection")

    current_collection_name = "News and Announcements"
    previous_collection_name = "Press Releases"

    try:
        coll = Collection.objects.get(name=current_collection_name)
    except Collection.DoesNotExist:
        raise RuntimeError(
            f"Old collection '{current_collection_name}' does not exist. Migration aborted."
        )

    # Rename collection if it exists
    coll.name = previous_collection_name
    coll.save(update_fields=["name"])


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0092_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.RunPython(
            rename_collection_to_new_name, rename_collection_back_to_old_name
        ),
    ]
