# Generated by Django 5.2.8 on 2026-01-27 20:50

from django.db import migrations


# Updates the name of the tag with the name of [old_tag_name] to [new_tag_name]
def update_tag_name(apps, schema_editor, old_tag_name, new_tag_name):
    Tag = apps.get_model("taggit", "Tag")
    tag = Tag.objects.get(name=old_tag_name)
    tag.name = new_tag_name
    tag.save()


# Updates the "Press Releases" collection and tag to be named "News and Announcements"
def rename_collection_and_tag_to_new_name(apps, schema_editor):
    Collection = apps.get_model("wagtailcore", "Collection")

    old_collection_name = "Press Releases"
    new_collection_name = "News and Announcements"

    try:
        coll = Collection.objects.get(name=old_collection_name)
    except Collection.DoesNotExist:
        raise RuntimeError(
            f"Old collection '{old_collection_name}' does not exist. Migration aborted."
        )

    # Rename collection if it exists
    coll.name = new_collection_name
    coll.save(update_fields=["name"])

    try:
        update_tag_name(apps, schema_editor, old_collection_name, new_collection_name)
    except Exception as e:
        raise RuntimeError(
            f"Error while checking updating tag '{old_collection_name}' to '{new_collection_name}'. Migration aborted. Error: {e}"
        )


# Updates the "News and Collection" collection and tag to be named "Press Releases"
def rename_tag_and_collection_back_to_old_name(apps, schema_editor):
    Collection = apps.get_model("wagtailcore", "Collection")

    current_collection_name = "News and Announcements"
    previous_collection_name = "Press Releases"

    try:
        update_tag_name(
            apps, schema_editor, current_collection_name, previous_collection_name
        )
    except Exception as e:
        raise RuntimeError(
            f"Error while checking updating tag '{current_collection_name}' to '{previous_collection_name}'. Migration aborted. Error: {e}"
        )

    try:
        coll = Collection.objects.get(name=current_collection_name)
    except Collection.DoesNotExist:
        raise RuntimeError(
            f"Old collection '{current_collection_name}' does not exist. Migration aborted."
        )

    # Rename collection if it exists
    coll.name = previous_collection_name
    coll.save(update_fields=["name"])


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0092_alter_enhancedstandardpage_body"),
        ("taggit", "__latest__"),
    ]

    operations = [
        migrations.RunPython(
            rename_collection_and_tag_to_new_name,
            rename_tag_and_collection_back_to_old_name,
        ),
    ]
