# Generated by Django 5.2.8 on 2026-01-30 23:06

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0093_merge_20260130_1805"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pamphletentry",
            name="citation",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Cases"),
        ),
        migrations.AlterField(
            model_name="pamphletentry",
            name="code",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Page Range"
            ),
        ),
        migrations.AlterField(
            model_name="pamphletentry",
            name="date_range",
            field=models.CharField(max_length=255, verbose_name="Date Range"),
        ),
    ]
