# Generated by Django 5.2.8 on 2026-02-04 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0093_litcpage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="litcpage",
            old_name="low_income_taxpayer_clinic",
            new_name="low_income_taxpayer_clinics",
        ),
    ]
