# Generated by Django 5.2.8 on 2026-02-17 14:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0096_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("indented_paragraph", 8),
                    ("snippet", 9),
                    ("button", 18),
                    ("hr", 19),
                    ("iframe", 23),
                    ("alert", 25),
                    ("image", 26),
                    ("photo_dedication", 31),
                    ("table", 32),
                    ("unstyled_table", 32),
                    ("enhanced_table", 45),
                    ("list", 62),
                    ("links", 69),
                    ("questionanswers", 71),
                    ("columns", 80),
                    ("embedded_video", 82),
                    ("card", 87),
                    ("accordian", 39),
                    ("callout", 36),
                    ("card_tiles", 101),
                    ("quick_access_tiles", 112),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Paragraph with left indentation for alignment with list items",
                            "label": "Indented Paragraph",
                        },
                    ),
                    9: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    10: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Optional: Button icon", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to"},
                    ),
                    13: (
                        "home.blocks.PDFDocumentChooserBlock",
                        (),
                        {"help_text": "Select a PDF to link to"},
                    ),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Enter an external URL"},
                    ),
                    15: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 12),
                                ("internal_pdf", 13),
                                ("external_url", 14),
                            ]
                        ],
                        {
                            "help_text": "Select exactly one: Internal Page, External URL, or PDF.",
                            "label": "URL",
                            "max_num": 1,
                            "min_num": 1,
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary")],
                            "help_text": "Choose the button style",
                        },
                    ),
                    17: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect on button",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 10),
                                ("text", 11),
                                ("url", 15),
                                ("style", 16),
                                ("button_hover", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    20: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    21: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    22: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("src", 20),
                                ("width", 21),
                                ("height", 21),
                                ("class", 22),
                                ("loading", 22),
                                ("data_delay", 22),
                                ("name", 22),
                                ("title", 22),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success")]},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("alert_type", 24), ("content", 7)]],
                        {},
                    ),
                    26: ("wagtail.images.blocks.ImageBlock", [], {}),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    28: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {
                            "help_text": "Upload an image to display with this dedication"
                        },
                    ),
                    29: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Provide alternative text for the image for accessibility.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 27),
                                ("photo", 28),
                                ("paragraph_text", 29),
                                ("alt_text", 30),
                            ]
                        ],
                        {},
                    ),
                    32: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of this special element",
                            "required": True,
                        },
                    ),
                    34: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "The paragraph content", "required": True},
                    ),
                    35: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("success", "Success"),
                                ("error", "Error"),
                                ("emergency", "Emergency"),
                            ]
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 33), ("text", 34), ("callout_type", 35)]],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title user will see before opening",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 3), ("prose", 7), ("callout", 36)]],
                        {
                            "help_text": "Add text or special elements to the body",
                            "required": True,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 37), ("description", 38)]],
                        {},
                    ),
                    40: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 7),
                                ("callout", 36),
                                ("accordian", 39),
                                ("button", 18),
                            ]
                        ],
                        {"required": False},
                    ),
                    41: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("components", 40)]],
                        {},
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("top", "Top"), ("bottom", "Bottom")]},
                    ),
                    43: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("styled", "Styled Table"),
                                ("borderlessUnstyled", "Borderless Unstyled Table"),
                                ("unstyled", "Unstyled Table"),
                            ]
                        },
                    ),
                    44: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to set table layout to fixed width.",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("table", 41),
                                ("caption_location", 42),
                                ("style", 43),
                                ("fixed", 44),
                            ]
                        ],
                        {},
                    ),
                    46: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                            ],
                            "required": False,
                        },
                    ),
                    47: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 47), ("image", 26)]],
                        {"required": False},
                    ),
                    49: ("wagtail.blocks.ListBlock", (48,), {"default": []}),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 46), ("items", 49)]],
                        {"required": False},
                    ),
                    51: ("wagtail.blocks.ListBlock", (50,), {"default": []}),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 47), ("image", 26), ("nested_list", 51)]],
                        {"required": False},
                    ),
                    53: ("wagtail.blocks.ListBlock", (52,), {"default": []}),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 46), ("items", 53)]],
                        {"required": False},
                    ),
                    55: ("wagtail.blocks.ListBlock", (54,), {"default": []}),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 47), ("image", 26), ("nested_list", 55)]],
                        {"required": False},
                    ),
                    57: ("wagtail.blocks.ListBlock", (56,), {"default": []}),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 46), ("items", 57)]],
                        {"required": False},
                    ),
                    59: ("wagtail.blocks.ListBlock", (58,), {"default": []}),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 47), ("image", 26), ("nested_list", 59)]],
                        {"required": False},
                    ),
                    61: ("wagtail.blocks.ListBlock", (60,), {"default": []}),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 46), ("items", 61)]],
                        {"required": False},
                    ),
                    63: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ],
                            "label": "List style",
                        },
                    ),
                    64: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    65: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    66: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 64),
                                ("document", 65),
                                ("video", 65),
                                ("url", 22),
                                ("text_only", 66),
                            ]
                        ],
                        {},
                    ),
                    68: ("wagtail.blocks.ListBlock", (67,), {"label": "Add Entry"}),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 63), ("links", 68)]],
                        {"label": "List of Links"},
                    ),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 22), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    71: (
                        "wagtail.blocks.ListBlock",
                        (70,),
                        {
                            "help_text": "Add a question and answer with anchor tag for linking",
                            "label": "Question and Answer",
                        },
                    ),
                    72: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 22)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 22)]],
                        {"label": "Clickable Button"},
                    ),
                    75: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    76: ("wagtail.blocks.ListBlock", (67,), {}),
                    77: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 75), ("links", 76)]],
                        {"label": "Links"},
                    ),
                    78: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 4),
                                ("h3", 5),
                                ("hr", 72),
                                ("h2WithAnchorTag", 73),
                                ("clickableButton", 74),
                                ("links", 77),
                            ]
                        ],
                        {},
                    ),
                    79: ("wagtail.blocks.ListBlock", (78,), {}),
                    80: ("wagtail.blocks.StructBlock", [[("column", 79)]], {}),
                    81: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 22), ("description", 47), ("video_url", 81)]],
                        {},
                    ),
                    83: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ]
                        },
                    ),
                    84: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    85: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 83),
                                ("title", 21),
                                ("description", 84),
                                ("color", 85),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    87: ("wagtail.blocks.ListBlock", (86,), {"label": "Card Set"}),
                    88: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Card Icon", "required": True},
                    ),
                    89: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("right", "Right"),
                                ("bottom", "Bottom"),
                                ("left", "Left"),
                            ],
                            "help_text": "Icon placement, e.g. Top, Right, Bottom, Left. Default is Top.",
                            "required": False,
                        },
                    ),
                    90: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Displays the card title", "required": True},
                    ),
                    91: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "required": True},
                    ),
                    92: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 3),
                                ("h2", 4),
                                ("h3", 5),
                                ("h4", 6),
                                ("paragraph", 7),
                                ("indented_paragraph", 8),
                                ("snippet", 9),
                                ("button", 18),
                                ("hr", 19),
                                ("iframe", 23),
                                ("alert", 25),
                                ("image", 26),
                                ("photo_dedication", 31),
                                ("table", 32),
                                ("unstyled_table", 32),
                                ("enhanced_table", 45),
                                ("list", 62),
                                ("links", 69),
                                ("questionanswers", 71),
                                ("columns", 80),
                                ("embedded_video", 82),
                                ("card", 87),
                                ("accordian", 39),
                                ("callout", 36),
                            ]
                        ],
                        {"required": False},
                    ),
                    93: (
                        "wagtail.blocks.StructBlock",
                        [[("breadcrumb_title", 91), ("body", 92)]],
                        {},
                    ),
                    94: ("wagtail.blocks.PageChooserBlock", (), {}),
                    95: ("wagtail.blocks.URLBlock", (), {}),
                    96: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("anchor_page", 93),
                                ("internal_page", 94),
                                ("external_url", 95),
                            ]
                        ],
                        {"max_num": 1, "min_num": 1},
                    ),
                    97: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect",
                            "required": False,
                        },
                    ),
                    98: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 88),
                                ("icon_direction", 89),
                                ("card_header", 90),
                                ("link", 96),
                                ("card_hover", 97),
                            ]
                        ],
                        {},
                    ),
                    99: (
                        "wagtail.blocks.ListBlock",
                        (98,),
                        {
                            "help_text": "Add up to 4 card tiles. They will display responsively based on screen size.",
                            "max_num": 4,
                            "min_num": 1,
                        },
                    ),
                    100: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 3),
                                ("h2", 4),
                                ("h3", 5),
                                ("h4", 6),
                                ("paragraph", 7),
                                ("indented_paragraph", 8),
                                ("snippet", 9),
                                ("button", 18),
                                ("hr", 19),
                                ("iframe", 23),
                                ("alert", 25),
                                ("image", 26),
                                ("photo_dedication", 31),
                                ("table", 32),
                                ("unstyled_table", 32),
                                ("enhanced_table", 45),
                                ("list", 62),
                                ("links", 69),
                                ("questionanswers", 71),
                                ("columns", 80),
                                ("embedded_video", 82),
                                ("card", 87),
                                ("accordian", 39),
                                ("callout", 36),
                            ]
                        ],
                        {
                            "help_text": "Default content to display when no card is selected",
                            "required": False,
                        },
                    ),
                    101: (
                        "wagtail.blocks.StructBlock",
                        [[("tiles", 99), ("default_content", 100)]],
                        {},
                    ),
                    102: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "If checked, hover treatment is enabled for ALL tiles in this set.",
                            "required": False,
                        },
                    ),
                    103: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "desktop_top_mobile_left",
                                    "Desktop-Top / Mobile-Left",
                                ),
                                (
                                    "desktop_bottom_mobile_right",
                                    "Desktop-Bottom / Mobile-Right",
                                ),
                            ],
                            "help_text": "Applies to ALL tiles in this set (keeps icon placement uniform).",
                        },
                    ),
                    104: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Card header (H2)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    105: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional body text",
                            "required": False,
                        },
                    ),
                    106: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Select an SVG file."},
                    ),
                    107: (
                        "wagtail.blocks.StructBlock",
                        [[("svg_file", 106)]],
                        {"required": True},
                    ),
                    108: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center"),
                                ("left", "Left"),
                                ("right", "Right"),
                            ],
                            "help_text": "Desktop text alignment (tablet/mobile will be left-aligned per design).",
                        },
                    ),
                    109: (
                        "wagtail.blocks.StreamBlock",
                        [[("related_page", 94), ("external_url", 95)]],
                        {
                            "help_text": "Choose where this tile should link.",
                            "min_num": 1,
                            "required": False,
                        },
                    ),
                    110: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 104),
                                ("description", 105),
                                ("icon", 107),
                                ("content_alignment", 108),
                                ("link", 109),
                            ]
                        ],
                        {},
                    ),
                    111: (
                        "wagtail.blocks.ListBlock",
                        (110,),
                        {
                            "help_text": "Add, reorder, duplicate, or remove tiles. Responsive grid: 3 desktop / 2 tablet / 1 mobile.",
                            "required": False,
                        },
                    ),
                    112: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles_hover_enabled", 102),
                                ("icon_position", 103),
                                ("tiles", 111),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
