# Generated by Django 5.2.8 on 2026-02-10 12:55

import django.db.models.deletion
import home.models.snippets.news_item
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0096_alter_newsitem_image"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsitem",
            name="image",
            field=models.ForeignKey(
                default=home.models.snippets.news_item.get_random_news_item_image_pk,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
