# Generated by Django 5.2.8 on 2026-02-20 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0093_litcpage"),
        ("home", "0097_alter_enhancedstandardpage_body"),
    ]

    operations = []
