# Generated by Django 5.2.8 on 2026-02-25 22:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0098_alter_enhancedstandardpage_body"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LITCPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "review_by",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for review and moderation of this content.",
                        null=True,
                        verbose_name="Review by date",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional note for moderators when submitting content for review.",
                        null=True,
                        verbose_name="Moderation note",
                    ),
                ),
                (
                    "low_income_taxpayer_clinics",
                    wagtail.fields.StreamField(
                        [("state", 9)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Indicates if the clinic handles only small cases",
                                    "required": False,
                                },
                            ),
                            2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            3: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            4: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 0),
                                        ("address", 2),
                                        ("phone", 2),
                                        ("website", 3),
                                        ("email", 4),
                                        ("small_case_procedures_only", 1),
                                    ]
                                ],
                                {},
                            ),
                            6: ("wagtail.blocks.ListBlock", (5,), {}),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 0),
                                        ("small_cases_only", 1),
                                        ("clinics", 6),
                                    ]
                                ],
                                {},
                            ),
                            8: ("wagtail.blocks.ListBlock", (7,), {}),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("state", 0), ("cities", 8)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
