# Generated by Django 5.2.8 on 2026-02-20 16:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0098_merge_20260220_1116"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="litcpage",
            name="body",
        ),
        migrations.AlterField(
            model_name="litcpage",
            name="low_income_taxpayer_clinics",
            field=wagtail.fields.StreamField(
                [("state", 9)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Indicates if the clinic handles only small cases",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    4: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 0),
                                ("address", 2),
                                ("phone", 2),
                                ("website", 3),
                                ("email", 4),
                                ("small_case_procedures_only", 1),
                            ]
                        ],
                        {},
                    ),
                    6: ("wagtail.blocks.ListBlock", (5,), {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("small_cases_only", 1), ("clinics", 6)]],
                        {},
                    ),
                    8: ("wagtail.blocks.ListBlock", (7,), {}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("state", 0), ("cities", 8)]],
                        {},
                    ),
                },
            ),
        ),
    ]
