# Generated by Django 5.2.8 on 2026-02-26 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0098_alter_pressreleasepage_options"),
        ("home", "0099_litcpage"),
    ]

    operations = []
