# Generated by Django 5.2.8 on 2026-02-27 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0100_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsitem",
            name="category",
        ),
    ]
