# Generated by Django 5.2.8 on 2026-02-27 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0100_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pressreleasepage",
            options={"verbose_name": "News and Announcements Page"},
        ),
    ]
