# Generated by Django 5.2.8 on 2026-03-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0101_remove_newsitem_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustedSites",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trusted_sites",
                    models.TextField(
                        blank=True, help_text="List of trusted sites, one per line."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
