# Generated by Django 5.2.8 on 2026-02-27 18:16

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0101_remove_newsitem_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pamphletentry",
            options={"ordering": ["sort_order"]},
        ),
        migrations.RemoveField(
            model_name="pamphletentry",
            name="volume_number",
        ),
        migrations.AddField(
            model_name="pamphletentry",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="pamphletentry",
            name="citation",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Cases"),
        ),
        migrations.AlterField(
            model_name="pamphletentry",
            name="code",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Page Range"
            ),
        ),
        migrations.AlterField(
            model_name="pamphletentry",
            name="date_range",
            field=models.CharField(max_length=255, verbose_name="Date Range"),
        ),
    ]
