# Generated by Django 5.2.8 on 2026-03-03 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0101_remove_newsitem_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pressreleasepage",
            options={"verbose_name": "News and Announcements Page"},
        ),
    ]
