# Generated by Django 5.2.8 on 2026-03-12 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0105_migrate_photo_dedication_data"),
    ]

    operations = []
