# Generated by Django 5.2.8 on 2026-03-12 20:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0105_migrate_photo_dedication_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("indented_paragraph", 8),
                    ("snippet", 9),
                    ("button", 18),
                    ("hr", 19),
                    ("iframe", 23),
                    ("alert", 25),
                    ("image", 26),
                    ("photo_dedication", 32),
                    ("table", 33),
                    ("unstyled_table", 33),
                    ("enhanced_table", 48),
                    ("list", 65),
                    ("links", 72),
                    ("questionanswers", 74),
                    ("columns", 83),
                    ("embedded_video", 85),
                    ("card", 90),
                    ("accordian", 45),
                    ("callout", 42),
                    ("grid", 101),
                    ("card_tiles", 115),
                    ("quick_access_tiles", 126),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Paragraph with left indentation for alignment with list items",
                            "label": "Indented Paragraph",
                        },
                    ),
                    9: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    10: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Optional: Button icon", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to"},
                    ),
                    13: (
                        "home.blocks.PDFDocumentChooserBlock",
                        (),
                        {"help_text": "Select a PDF to link to"},
                    ),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Enter an external URL"},
                    ),
                    15: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 12),
                                ("internal_pdf", 13),
                                ("external_url", 14),
                            ]
                        ],
                        {
                            "help_text": "Select exactly one: Internal Page, External URL, or PDF.",
                            "label": "URL",
                            "max_num": 1,
                            "min_num": 1,
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary")],
                            "help_text": "Choose the button style",
                        },
                    ),
                    17: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect on button",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 10),
                                ("text", 11),
                                ("url", 15),
                                ("style", 16),
                                ("button_hover", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    20: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    21: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    22: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("src", 20),
                                ("width", 21),
                                ("height", 21),
                                ("class", 22),
                                ("loading", 22),
                                ("data_delay", 22),
                                ("name", 22),
                                ("title", 22),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success")]},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("alert_type", 24), ("content", 7)]],
                        {},
                    ),
                    26: ("wagtail.images.blocks.ImageBlock", [], {}),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Before"), ("right", "After")],
                            "help_text": "Place the image before (left on desktop) or after (right on desktop) the text.",
                        },
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional heading displayed above the photo and text.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Upload an image to display with this dedication",
                            "required": True,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Describe the image for a visually impaired person.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    31: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image_position", 27),
                                ("title", 28),
                                ("photo", 29),
                                ("alt_text", 30),
                                ("paragraph_text", 31),
                            ]
                        ],
                        {},
                    ),
                    33: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title displayed above the table (rendered as H2).",
                            "label": "Header",
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "A caption displayed above or below the table depending on Caption Location.",
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("top", "Top"), ("bottom", "Bottom")]},
                    ),
                    37: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("styled", "Styled Table"),
                                ("borderlessUnstyled", "Borderless Unstyled Table"),
                                ("unstyled", "Unstyled Table"),
                            ]
                        },
                    ),
                    38: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to set table layout to fixed width.",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of this special element",
                            "required": True,
                        },
                    ),
                    40: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "The paragraph content", "required": True},
                    ),
                    41: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("success", "Success"),
                                ("error", "Error"),
                                ("emergency", "Emergency"),
                            ]
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 39), ("text", 40), ("callout_type", 41)]],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title user will see before opening",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    44: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 3), ("prose", 7), ("callout", 42)]],
                        {
                            "help_text": "Add text or special elements to the body",
                            "required": True,
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 43), ("description", 44)]],
                        {},
                    ),
                    46: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 7),
                                ("callout", 42),
                                ("accordian", 45),
                                ("button", 18),
                            ]
                        ],
                        {"required": False},
                    ),
                    47: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("components", 46)]],
                        {},
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 34),
                                ("caption", 35),
                                ("caption_location", 36),
                                ("style", 37),
                                ("fixed", 38),
                                ("table", 47),
                            ]
                        ],
                        {},
                    ),
                    49: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                            ],
                            "required": False,
                        },
                    ),
                    50: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 50), ("image", 26)]],
                        {"required": False},
                    ),
                    52: ("wagtail.blocks.ListBlock", (51,), {"default": []}),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 49), ("items", 52)]],
                        {"required": False},
                    ),
                    54: ("wagtail.blocks.ListBlock", (53,), {"default": []}),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 50), ("image", 26), ("nested_list", 54)]],
                        {"required": False},
                    ),
                    56: ("wagtail.blocks.ListBlock", (55,), {"default": []}),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 49), ("items", 56)]],
                        {"required": False},
                    ),
                    58: ("wagtail.blocks.ListBlock", (57,), {"default": []}),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 50), ("image", 26), ("nested_list", 58)]],
                        {"required": False},
                    ),
                    60: ("wagtail.blocks.ListBlock", (59,), {"default": []}),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 49), ("items", 60)]],
                        {"required": False},
                    ),
                    62: ("wagtail.blocks.ListBlock", (61,), {"default": []}),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 50), ("image", 26), ("nested_list", 62)]],
                        {"required": False},
                    ),
                    64: ("wagtail.blocks.ListBlock", (63,), {"default": []}),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 49), ("items", 64)]],
                        {"required": False},
                    ),
                    66: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ],
                            "label": "List style",
                        },
                    ),
                    67: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    68: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    69: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 67),
                                ("document", 68),
                                ("video", 68),
                                ("url", 22),
                                ("text_only", 69),
                            ]
                        ],
                        {},
                    ),
                    71: ("wagtail.blocks.ListBlock", (70,), {"label": "Add Entry"}),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 66), ("links", 71)]],
                        {"label": "List of Links"},
                    ),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 22), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    74: (
                        "wagtail.blocks.ListBlock",
                        (73,),
                        {
                            "help_text": "Add a question and answer with anchor tag for linking",
                            "label": "Question and Answer",
                        },
                    ),
                    75: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    76: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 22)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    77: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 22)]],
                        {"label": "Clickable Button"},
                    ),
                    78: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    79: ("wagtail.blocks.ListBlock", (70,), {}),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 78), ("links", 79)]],
                        {"label": "Links"},
                    ),
                    81: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 4),
                                ("h3", 5),
                                ("hr", 75),
                                ("h2WithAnchorTag", 76),
                                ("clickableButton", 77),
                                ("links", 80),
                            ]
                        ],
                        {},
                    ),
                    82: ("wagtail.blocks.ListBlock", (81,), {}),
                    83: ("wagtail.blocks.StructBlock", [[("column", 82)]], {}),
                    84: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 22), ("description", 50), ("video_url", 84)]],
                        {},
                    ),
                    86: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ]
                        },
                    ),
                    87: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    88: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 86),
                                ("title", 21),
                                ("description", 87),
                                ("color", 88),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    90: ("wagtail.blocks.ListBlock", (89,), {"label": "Card Set"}),
                    91: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [(1, 1), (2, 2), (3, 3), (4, 4)],
                            "help_text": "Max number of columns in the grid (1-4)",
                        },
                    ),
                    92: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("full", "Full Width")],
                            "help_text": "Maximum width of the grid",
                        },
                    ),
                    93: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("styled", "Styled"), ("unstyled", "Unstyled")],
                            "help_text": "Style of the grid",
                        },
                    ),
                    94: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional header for this grid cell",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    95: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("#f1f9fc", "Default"), ("#DEEAF0", "Blue-Gray")]},
                    ),
                    96: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional caption for this grid cell (links allowed)",
                            "required": False,
                        },
                    ),
                    97: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Make the caption text italic",
                            "required": False,
                        },
                    ),
                    98: (
                        "wagtail.blocks.StreamBlock",
                        [[("prose", 7), ("callout", 42)]],
                        {
                            "help_text": "Add text or special elements to the cell body",
                            "required": True,
                        },
                    ),
                    99: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 94),
                                ("header_color", 95),
                                ("caption", 96),
                                ("italic_caption", 97),
                                ("body", 98),
                            ]
                        ],
                        {},
                    ),
                    100: (
                        "wagtail.blocks.ListBlock",
                        (99,),
                        {
                            "help_text": "Add cells to the grid. Cells will fill row-by-row based on the number of columns selected."
                        },
                    ),
                    101: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("columns", 91),
                                ("width", 92),
                                ("gridStyle", 93),
                                ("cells", 100),
                            ]
                        ],
                        {},
                    ),
                    102: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Card Icon", "required": True},
                    ),
                    103: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("right", "Right"),
                                ("bottom", "Bottom"),
                                ("left", "Left"),
                            ],
                            "help_text": "Icon placement, e.g. Top, Right, Bottom, Left. Default is Top.",
                            "required": False,
                        },
                    ),
                    104: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Displays the card title", "required": True},
                    ),
                    105: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "required": True},
                    ),
                    106: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 3),
                                ("h2", 4),
                                ("h3", 5),
                                ("h4", 6),
                                ("paragraph", 7),
                                ("indented_paragraph", 8),
                                ("snippet", 9),
                                ("button", 18),
                                ("hr", 19),
                                ("iframe", 23),
                                ("alert", 25),
                                ("image", 26),
                                ("photo_dedication", 32),
                                ("table", 33),
                                ("unstyled_table", 33),
                                ("enhanced_table", 48),
                                ("list", 65),
                                ("links", 72),
                                ("questionanswers", 74),
                                ("columns", 83),
                                ("embedded_video", 85),
                                ("card", 90),
                                ("accordian", 45),
                                ("callout", 42),
                                ("grid", 101),
                            ]
                        ],
                        {"required": False},
                    ),
                    107: (
                        "wagtail.blocks.StructBlock",
                        [[("breadcrumb_title", 105), ("body", 106)]],
                        {},
                    ),
                    108: ("wagtail.blocks.PageChooserBlock", (), {}),
                    109: ("wagtail.blocks.URLBlock", (), {}),
                    110: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("anchor_page", 107),
                                ("internal_page", 108),
                                ("external_url", 109),
                            ]
                        ],
                        {"max_num": 1, "min_num": 1},
                    ),
                    111: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect",
                            "required": False,
                        },
                    ),
                    112: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 102),
                                ("icon_direction", 103),
                                ("card_header", 104),
                                ("link", 110),
                                ("card_hover", 111),
                            ]
                        ],
                        {},
                    ),
                    113: (
                        "wagtail.blocks.ListBlock",
                        (112,),
                        {
                            "help_text": "Add up to 4 card tiles. They will display responsively based on screen size.",
                            "max_num": 4,
                            "min_num": 1,
                        },
                    ),
                    114: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 3),
                                ("h2", 4),
                                ("h3", 5),
                                ("h4", 6),
                                ("paragraph", 7),
                                ("indented_paragraph", 8),
                                ("snippet", 9),
                                ("button", 18),
                                ("hr", 19),
                                ("iframe", 23),
                                ("alert", 25),
                                ("image", 26),
                                ("photo_dedication", 32),
                                ("table", 33),
                                ("unstyled_table", 33),
                                ("enhanced_table", 48),
                                ("list", 65),
                                ("links", 72),
                                ("questionanswers", 74),
                                ("columns", 83),
                                ("embedded_video", 85),
                                ("card", 90),
                                ("accordian", 45),
                                ("callout", 42),
                                ("grid", 101),
                            ]
                        ],
                        {
                            "help_text": "Default content to display when no card is selected",
                            "required": False,
                        },
                    ),
                    115: (
                        "wagtail.blocks.StructBlock",
                        [[("tiles", 113), ("default_content", 114)]],
                        {},
                    ),
                    116: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "If checked, hover treatment is enabled for ALL tiles in this set.",
                            "required": False,
                        },
                    ),
                    117: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "desktop_top_mobile_left",
                                    "Desktop-Top / Mobile-Left",
                                ),
                                (
                                    "desktop_bottom_mobile_right",
                                    "Desktop-Bottom / Mobile-Right",
                                ),
                            ],
                            "help_text": "Applies to ALL tiles in this set (keeps icon placement uniform).",
                        },
                    ),
                    118: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Card header (H2)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    119: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional body text",
                            "required": False,
                        },
                    ),
                    120: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Select an SVG file."},
                    ),
                    121: (
                        "wagtail.blocks.StructBlock",
                        [[("svg_file", 120)]],
                        {"required": True},
                    ),
                    122: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center"),
                                ("left", "Left"),
                                ("right", "Right"),
                            ],
                            "help_text": "Desktop text alignment (tablet/mobile will be left-aligned per design).",
                        },
                    ),
                    123: (
                        "wagtail.blocks.StreamBlock",
                        [[("related_page", 108), ("external_url", 109)]],
                        {
                            "help_text": "Choose where this tile should link.",
                            "min_num": 1,
                            "required": False,
                        },
                    ),
                    124: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 118),
                                ("description", 119),
                                ("icon", 121),
                                ("content_alignment", 122),
                                ("link", 123),
                            ]
                        ],
                        {},
                    ),
                    125: (
                        "wagtail.blocks.ListBlock",
                        (124,),
                        {
                            "help_text": "Add, reorder, duplicate, or remove tiles. Responsive grid: 3 desktop / 2 tablet / 1 mobile.",
                            "required": False,
                        },
                    ),
                    126: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles_hover_enabled", 116),
                                ("icon_position", 117),
                                ("tiles", 125),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
