# Generated by Django 5.2.8 on 2026-03-18 17:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0106_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="litcpage",
            name="introductory_paragraph",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="The Low-Income Taxpayer Clinics (LITCs) listed are not part of the Internal Revenue Service (IRS) or the United States Tax Court. The Tax Court does not endorse or recommend any specific tax clinic or organization. LITCs located next to the State and City/Place of Trial are available to assist eligible taxpayers.",
                help_text="Optional introductory paragraph for the page.",
            ),
        ),
    ]
