# Generated by Django 5.2.8 on 2026-03-19 17:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0107_litcpage_introductory_paragraph"),
    ]

    operations = [
        migrations.AddField(
            model_name="litcpage",
            name="asterisks_notice",
            field=wagtail.fields.StreamField(
                [("asterisk_notice", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("", "None"), ("*", "*"), ("**", "**")],
                            "help_text": "Set the number of asterisks to display (0, 1 or 2).",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Write your explanation text here."},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("asterisks_count", 0), ("text", 1)]],
                        {"icon": "info-circle", "label": "Asterisk Notice"},
                    ),
                },
                default=[
                    (
                        "asterisk_notice",
                        {
                            "asterisks_count": "*",
                            "text": "Indicates the city only holds trials for small tax cases.",
                        },
                    ),
                    (
                        "asterisk_notice",
                        {
                            "asterisks_count": "**",
                            "text": "Indicates the clinic only represents taxpayers who have elected the small tax case procedure.",
                        },
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="litcpage",
            name="introductory_paragraph",
            field=wagtail.fields.StreamField(
                [("paragraph", 0)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "The Low-Income Taxpayer Clinics (LITCs) listed are not part of the Internal Revenue Service (IRS) or the United States Tax Court. The Tax Court does not endorse or recommend any specific tax clinic or organization. LITCs located next to the State and City/Place of Trial are available to assist eligible taxpayers.",
                            "help_text": "Write your paragraph here.",
                        },
                    )
                },
                default=[
                    (
                        "paragraph",
                        "<p>The Low-Income Taxpayer Clinics (LITCs) listed are not part of the Internal Revenue Service (IRS) or the United States Tax Court. The Tax Court does not endorse or recommend any specific tax clinic or organization. LITCs located next to the State and City/Place of Trial are available to assist eligible taxpayers.</p>",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="litcpage",
            name="low_income_taxpayer_clinics",
            field=wagtail.fields.StreamField(
                [("state", 10)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Indicates the city only holds small case trials.",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    4: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Indicates the clinic only represents taxpayers who have elected the small tax case procedures.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 0),
                                ("address", 2),
                                ("phone", 2),
                                ("website", 3),
                                ("email", 4),
                                ("small_case_procedures_only", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("wagtail.blocks.ListBlock", (6,), {}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("small_cases_only", 1), ("clinics", 7)]],
                        {},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("state", 0), ("cities", 9)]],
                        {},
                    ),
                },
            ),
        ),
    ]
