# Generated by Django 5.2.8 on 2026-03-18 18:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0107_litcpage_introductory_paragraph"),
    ]

    operations = [
        migrations.AlterField(
            model_name="litcpage",
            name="introductory_paragraph",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Optional introductory paragraph for the page."
            ),
        ),
    ]
