# Generated by Django 5.2.13 on 2026-04-22 18:10

from django.db import migrations
from django.conf import settings

"""Data migration: Create the TEXT CONFIGURATION required to have PostgreSQL not split on
hyphens in titles, body, and autocomplete that Wagtail searches on"""


def get_env():
    return getattr(settings, "ENVIRONMENT", "local")


def create_configuration_if_not_exists(apps, schema_editor):
    """Only run if environment is not local (i.e., is running in AWS and is using PostgresSQL)"""
    if get_env() != "local":
        """Use raw SQL to check if the configuration exists and to create it if it doesn't"""
        connection = schema_editor.connection
        cursor = connection.cursor()

        cursor.execute(
            "SELECT cfgname from pg_catalog.pg_ts_config where cfgname = 'english_hyphen'"
        )
        rows = cursor.fetchall()

        for cfgname in rows:
            if cfgname:
                continue

            cursor.execute(
                "CREATE TEXT SEARCH CONFIGURATION public.english_hyphen (COPY = pg_catalog.english)"
            )
            cursor.execute(
                "ALTER TEXT SEARCH CONFIGURATION public.english_hyphen ALTER MAPPING FOR asciiword, asciihword, hword_asciipart WITH simple"
            )


def reverse_migration(apps, schema_editor):
    """Only run if environment is not local (i.e., is running in AWS and is using PostgresSQL)"""
    if get_env() != "local":
        """Use raw SQL to check if the configuration exists and to delete it if it does"""
        connection = schema_editor.connection
        cursor = connection.cursor()

        cursor.execute(
            "SELECT cfgname from pg_catalog.pg_ts_config where cfgname = 'english_hyphen'"
        )
        rows = cursor.fetchall()

        for cfgname in rows:
            if not cfgname:
                continue

            cursor.execute("DROP TEXT SEARCH CONFIGURATION public.english_hyphen")


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0111_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.RunPython(create_configuration_if_not_exists, reverse_migration),
    ]
