# Generated by Django 5.2.13 on 2026-05-04 14:05

from django.db import migrations
from wagtail.contrib.redirects.models import Redirect
from wagtail.contrib.redirects.base_formats import XLSX
from django.utils.encoding import force_str
import os
import logging

logger = logging.getLogger(__name__)


def create_redirects_from_dataset(dataset, config):
    errors = []
    successes = 0
    total = 0

    for row in dataset:
        total += 1

        try:
            from_link = row[config["from_index"]]
            to_link = row[config["to_index"]]

            Redirect.objects.create(
                old_path=from_link,
                redirect_link=to_link,
                is_permanent=config["permanent"],
                site=config["site"],
            )
            successes += 1
        except Exception as e:
            logger.error(
                f"  -> ERROR: An unexpected error occurred for redirect '{from_link}' -> '{to_link}': {e}"
            )
            errors.append(
                f"  -> ERROR: An unexpected error occurred for redirect '{from_link}' -> '{to_link}': {e}"
            )

    return {
        "errors": errors,
        "successes": successes,
        "total": total,
    }


class Migration(migrations.Migration):
    # This logic is based on the code found in apply_document_updates_from_csv(...) in 0064_update_rules_documents and
    # create_redirects_from_dataset(...) found in Wagtail's contrib/redirects/views.py file. This function is unable
    # to use the create_redirects_from_dataset method because of the URL validation that the RedirectForm model does
    # on the redirect_links in the spreadsheet.
    def create_redirects_for_broken_pdf_links(apps, schema_editor):
        from_encoding = "utf-8"
        input_format = XLSX()

        migration_dir = os.path.dirname(__file__)
        xlsx_filename = os.path.basename(__file__).replace(".py", ".xlsx")
        update_xlsx_path = os.path.join(migration_dir, xlsx_filename)
        with open(update_xlsx_path, mode=input_format.get_read_mode()) as file:
            data = file.read()
            if not input_format.is_binary() and from_encoding:
                data = force_str(data, from_encoding)
            dataset = input_format.create_dataset(data)
            import_summary = create_redirects_from_dataset(
                dataset,
                {
                    "from_index": 0,
                    "to_index": 1,
                    "permanent": True,
                    "site": None,
                },
            )
            logger.info("--- Redirect import process complete ---")
            logger.info(
                f"Summary: {import_summary['successes']} redirects imported, {import_summary['total']} attempted."
            )
            for err in import_summary["errors"]:
                logger.info(f"  {err}")

    dependencies = [
        ("home", "0115_alter_enhancedstandardpage_body"),
        (
            "wagtailredirects",
            "0008_add_verbose_name_plural",
        ),
    ]

    operations = [
        migrations.RunPython(
            create_redirects_for_broken_pdf_links,
        ),
    ]
