# Generated by Django 5.2.8 on 2026-05-18 23:19

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0117_alter_enhancedstandardpage_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgeindex",
            name="body",
        ),
        migrations.AddField(
            model_name="judgeindex",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="See the Judge's biography by clicking on the cards.",
                help_text="Introductory text displayed below the page title.",
            ),
        ),
        migrations.AlterField(
            model_name="judgeprofile",
            name="title",
            field=models.CharField(
                choices=[
                    ("Judge", "Judge"),
                    ("Senior Judge", "Senior Judge"),
                    ("Special Trial Judge", "Special Trial Judge"),
                    ("Senior Special Trial Judge", "Senior Special Trial Judge"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="PrivateSeminarDisclosure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program_provider",
                    models.CharField(help_text="Program Provider", max_length=255),
                ),
                (
                    "program_title",
                    models.CharField(help_text="Program Title", max_length=255),
                ),
                ("date", models.DateField(help_text="Date of the program")),
                (
                    "location",
                    models.CharField(
                        help_text="Location of the program", max_length=255
                    ),
                ),
                (
                    "program_topics",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Program topics (may be bulleted)"
                    ),
                ),
                (
                    "supporter",
                    models.CharField(
                        blank=True, help_text="Supporter (if any)", max_length=255
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        help_text="The judge associated with this disclosure",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seminar_disclosures",
                        to="home.judgeprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Private Seminar Disclosure",
                "verbose_name_plural": "Private Seminar Disclosures",
                "ordering": ["-date", "judge__last_name"],
            },
        ),
    ]
