# Generated by Django 5.2.13 on 2026-05-29 14:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0118_remove_judgeindex_body_judgeindex_intro_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgeindex",
            name="bottom_tiles",
            field=wagtail.fields.StreamField(
                [("quick_access_tiles", 12)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "If checked, hover treatment is enabled for ALL tiles in this set.",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "desktop_top_mobile_left",
                                    "Desktop-Top / Mobile-Left",
                                ),
                                (
                                    "desktop_bottom_mobile_right",
                                    "Desktop-Bottom / Mobile-Right",
                                ),
                            ],
                            "help_text": "Applies to ALL tiles in this set (keeps icon placement uniform).",
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Card header (H2)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic"],
                            "help_text": "Optional body text",
                            "required": False,
                        },
                    ),
                    4: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Select an SVG file."},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("svg_file", 4)]],
                        {"required": True},
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center"),
                                ("left", "Left"),
                                ("right", "Right"),
                            ],
                            "help_text": "Desktop text alignment (tablet/mobile will be left-aligned per design).",
                        },
                    ),
                    7: ("wagtail.blocks.PageChooserBlock", (), {}),
                    8: ("wagtail.blocks.URLBlock", (), {}),
                    9: (
                        "wagtail.blocks.StreamBlock",
                        [[("related_page", 7), ("external_url", 8)]],
                        {
                            "help_text": "Choose where this tile should link.",
                            "max_num": 1,
                            "min_num": 1,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 2),
                                ("description", 3),
                                ("icon", 5),
                                ("content_alignment", 6),
                                ("link", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {
                            "help_text": "Add, reorder, duplicate, or remove tiles. Responsive grid: 3 desktop / 2 tablet / 1 mobile.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles_hover_enabled", 0),
                                ("icon_position", 1),
                                ("tiles", 11),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Quick-access tiles rendered below the judge card grid.",
            ),
        ),
    ]
