# Generated by Django 5.2.13 on 2026-05-27 19:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0119_judgeindex_seminar_text_and_disclosure_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privateseminardisclosure",
            name="judge",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seminar_disclosures",
                to="home.judgeprofile",
            ),
        ),
    ]
