# Generated by Django 5.2.13 on 2026-06-09 15:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0125_fix_jcdp_page_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgeindex",
            name="seminar_intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p>The following are private seminar disclosures submitted by judges of the United States Tax Court.</p><p>Below is the Running list of Tax Court Disclosures:</p>",
                help_text="Introductory text shown at the top of the Private Seminar Disclosures page (hidden automatically when there are no disclosures to display). Includes the 'Below is...' line by default so editors can change it without code changes.",
            ),
        ),
    ]
