# Generated by Django 5.2.13 on 2026-06-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0125_fix_jcdp_page_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="navigationribbonlink",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="navigationribbonlink",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.RunSQL(
            sql="""WITH new_values as (SELECT id, RANK() over (PARTITION BY navigation_ribbon_id ORDER BY id) as new_sort_order FROM home_navigationribbonlink) UPDATE home_navigationribbonlink SET sort_order = (SELECT new_sort_order-1 FROM new_values WHERE new_values.id = home_navigationribbonlink.id);""",
            reverse_sql="""UPDATE home_navigationribbonlink SET sort_order = null;""",
        ),
    ]
