# Generated by Django 5.2.13 on 2026-07-21 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0127_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pressreleasepage",
            name="press_release_body",
        ),
    ]
