# Generated by Django 5.2.15 on 2026-07-27 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0128_remove_pressreleasepage_press_release_body"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""UPDATE home_enhancedstandardpage set body = replace(body, 'accordian', 'accordion');""",
            reverse_sql="""UPDATE home_enhancedstandardpage set body = replace(body, 'accordion', 'accordian');""",
        ),
    ]
