# Generated by Django 5.2.13 on 2026-06-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0131_delete_stray_pluralized_judge_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privateseminardisclosure",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
