# Generated by Django 5.2.16 on 2026-08-17 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0132_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetititonerExperiencePage",
            fields=[
                (
                    "enhancedstandardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.enhancedstandardpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Petitioner Experience Page",
            },
            bases=("home.enhancedstandardpage",),
        ),
    ]
