# Generated by Django 5.2.15 on 2026-07-29 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0129_alter_enhancedstandardpage_body"),
        ("home", "0132_alter_enhancedstandardpage_body"),
    ]

    operations = []
