# Generated by Django 5.2.16 on 2026-08-18 18:26

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0133_set_sort_order_of_administrative_order_pdfs"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetitionerExperiencePage",
            fields=[
                (
                    "enhancedstandardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.enhancedstandardpage",
                    ),
                ),
                (
                    "introductory_text",
                    wagtail.fields.RichTextField(
                        help_text="Text to be displayed at the top of the page under the page's title."
                    ),
                ),
            ],
            options={
                "verbose_name": "Petitioner Experience Page",
            },
            bases=("home.enhancedstandardpage",),
        ),
    ]
