# Generated by Django 5.2.15 on 2026-07-29 16:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0133_merge_20260729_1212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("indented_paragraph", 8),
                    ("snippet", 9),
                    ("button", 18),
                    ("hr", 19),
                    ("iframe", 23),
                    ("alert", 25),
                    ("image", 28),
                    ("photo_dedication", 34),
                    ("table", 35),
                    ("unstyled_table", 35),
                    ("enhanced_table", 51),
                    ("list", 71),
                    ("links", 78),
                    ("questionanswers", 80),
                    ("columns", 89),
                    ("embedded_video", 92),
                    ("card", 97),
                    ("accordion", 48),
                    ("callout", 44),
                    ("grid", 108),
                    ("card_tiles", 133),
                    ("quick_access_tiles", 125),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Paragraph with left indentation for alignment with list items",
                            "label": "Indented Paragraph",
                        },
                    ),
                    9: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    10: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Optional: Button icon", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to"},
                    ),
                    13: (
                        "home.blocks.PDFDocumentChooserBlock",
                        (),
                        {"help_text": "Select a PDF to link to"},
                    ),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Enter an external URL"},
                    ),
                    15: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 12),
                                ("internal_pdf", 13),
                                ("external_url", 14),
                            ]
                        ],
                        {
                            "help_text": "Select exactly one: Internal Page, External URL, or PDF.",
                            "label": "URL",
                            "max_num": 1,
                            "min_num": 1,
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary")],
                            "help_text": "Choose the button style",
                        },
                    ),
                    17: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect on button",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 10),
                                ("text", 11),
                                ("url", 15),
                                ("style", 16),
                                ("button_hover", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    20: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    21: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    22: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("src", 20),
                                ("width", 21),
                                ("height", 21),
                                ("class", 22),
                                ("loading", 22),
                                ("data_delay", 22),
                                ("name", 22),
                                ("title", 22),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success")]},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("alert_type", 24), ("content", 7)]],
                        {},
                    ),
                    26: ("wagtail.images.blocks.ImageBlock", [], {}),
                    27: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 12),
                                ("internal_pdf", 13),
                                ("external_url", 14),
                            ]
                        ],
                        {
                            "help_text": "Optional: add a link to make the image clickable.",
                            "max_num": 1,
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 26), ("link", 27)]],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Before"), ("right", "After")],
                            "help_text": "Place the image before (left on desktop) or after (right on desktop) the text.",
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional heading displayed above the photo and text.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Upload an image to display with this dedication",
                            "required": True,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Describe the image for a visually impaired person.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    33: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image_position", 29),
                                ("title", 30),
                                ("photo", 31),
                                ("alt_text", 32),
                                ("paragraph_text", 33),
                                ("link", 27),
                            ]
                        ],
                        {},
                    ),
                    35: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title displayed above the table (rendered as H2).",
                            "label": "Header",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "A caption displayed above or below the table depending on Caption Location.",
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("top", "Top"), ("bottom", "Bottom")]},
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("styled", "Styled Table"),
                                ("borderlessUnstyled", "Borderless Unstyled Table"),
                                ("unstyled", "Unstyled Table"),
                            ]
                        },
                    ),
                    40: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to set table layout to fixed width.",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of this special element",
                            "required": True,
                        },
                    ),
                    42: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "The paragraph content", "required": True},
                    ),
                    43: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("success", "Success"),
                                ("error", "Error"),
                                ("emergency", "Emergency"),
                            ]
                        },
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 41), ("text", 42), ("callout_type", 43)]],
                        {},
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title user will see before opening",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    46: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 3), ("prose", 7), ("callout", 44)]],
                        {
                            "help_text": "Add text or special elements to the body",
                            "required": True,
                        },
                    ),
                    47: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to have the accordion open by default when the page loads.",
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 45), ("description", 46), ("default_to_open", 47)]],
                        {},
                    ),
                    49: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 7),
                                ("callout", 44),
                                ("accordion", 48),
                                ("button", 18),
                            ]
                        ],
                        {"required": False},
                    ),
                    50: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("components", 49)]],
                        {},
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 36),
                                ("caption", 37),
                                ("caption_location", 38),
                                ("style", 39),
                                ("fixed", 40),
                                ("table", 50),
                            ]
                        ],
                        {},
                    ),
                    52: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                                ("checkbox", "Checkbox List"),
                                ("checkbox_with_subtext", "Checkbox with Subtext"),
                            ],
                            "required": False,
                        },
                    ),
                    53: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    54: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Always render this checkbox as disabled, regardless of other checkboxes.",
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: a short id for this checkbox (e.g. 'agree'). Other checkboxes in this list can require it via their 'Requires checkbox checked' field.",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: enter another checkbox's Condition Key from this list. This checkbox stays disabled until that one is checked by the visitor.",
                            "label": "Requires checkbox checked",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 53),
                                ("subtext", 53),
                                ("disabled", 54),
                                ("condition_key", 55),
                                ("requires_checked", 56),
                                ("image", 26),
                            ]
                        ],
                        {"required": False},
                    ),
                    58: ("wagtail.blocks.ListBlock", (57,), {"default": []}),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 52), ("items", 58)]],
                        {"required": False},
                    ),
                    60: ("wagtail.blocks.ListBlock", (59,), {"default": []}),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 53),
                                ("subtext", 53),
                                ("disabled", 54),
                                ("condition_key", 55),
                                ("requires_checked", 56),
                                ("image", 26),
                                ("nested_list", 60),
                            ]
                        ],
                        {"required": False},
                    ),
                    62: ("wagtail.blocks.ListBlock", (61,), {"default": []}),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 52), ("items", 62)]],
                        {"required": False},
                    ),
                    64: ("wagtail.blocks.ListBlock", (63,), {"default": []}),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 53),
                                ("subtext", 53),
                                ("disabled", 54),
                                ("condition_key", 55),
                                ("requires_checked", 56),
                                ("image", 26),
                                ("nested_list", 64),
                            ]
                        ],
                        {"required": False},
                    ),
                    66: ("wagtail.blocks.ListBlock", (65,), {"default": []}),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 52), ("items", 66)]],
                        {"required": False},
                    ),
                    68: ("wagtail.blocks.ListBlock", (67,), {"default": []}),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 53),
                                ("subtext", 53),
                                ("disabled", 54),
                                ("condition_key", 55),
                                ("requires_checked", 56),
                                ("image", 26),
                                ("nested_list", 68),
                            ]
                        ],
                        {"required": False},
                    ),
                    70: ("wagtail.blocks.ListBlock", (69,), {"default": []}),
                    71: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 52), ("items", 70)]],
                        {"required": False},
                    ),
                    72: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ],
                            "label": "List style",
                        },
                    ),
                    73: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    74: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    75: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    76: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 73),
                                ("document", 74),
                                ("video", 74),
                                ("url", 22),
                                ("text_only", 75),
                            ]
                        ],
                        {},
                    ),
                    77: ("wagtail.blocks.ListBlock", (76,), {"label": "Add Entry"}),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 72), ("links", 77)]],
                        {"label": "List of Links"},
                    ),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 22), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    80: (
                        "wagtail.blocks.ListBlock",
                        (79,),
                        {
                            "help_text": "Add a question and answer with anchor tag for linking",
                            "label": "Question and Answer",
                        },
                    ),
                    81: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 22)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    83: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 22)]],
                        {"label": "Clickable Button"},
                    ),
                    84: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    85: ("wagtail.blocks.ListBlock", (76,), {}),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 84), ("links", 85)]],
                        {"label": "Links"},
                    ),
                    87: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 4),
                                ("h3", 5),
                                ("hr", 81),
                                ("h2WithAnchorTag", 82),
                                ("clickableButton", 83),
                                ("links", 86),
                            ]
                        ],
                        {},
                    ),
                    88: ("wagtail.blocks.ListBlock", (87,), {}),
                    89: ("wagtail.blocks.StructBlock", [[("column", 88)]], {}),
                    90: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use the YouTube embed URL (e.g. https://www.youtube.com/embed/VIDEO_ID), not the watch URL.",
                            "required": True,
                        },
                    ),
                    91: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("below", "Below"), ("right-of", "Right")]},
                    ),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 22),
                                ("description", 53),
                                ("video_url", 90),
                                ("text_location", 91),
                            ]
                        ],
                        {},
                    ),
                    93: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ]
                        },
                    ),
                    94: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    95: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    96: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 93),
                                ("title", 21),
                                ("description", 94),
                                ("color", 95),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    97: ("wagtail.blocks.ListBlock", (96,), {"label": "Card Set"}),
                    98: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [(1, 1), (2, 2), (3, 3), (4, 4)],
                            "help_text": "Max number of columns in the grid (1-4)",
                        },
                    ),
                    99: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("full", "Full Width")],
                            "help_text": "Maximum width of the grid",
                        },
                    ),
                    100: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("styled", "Styled"), ("unstyled", "Unstyled")],
                            "help_text": "Style of the grid",
                        },
                    ),
                    101: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional header for this grid cell",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    102: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("#f1f9fc", "Default"), ("#DEEAF0", "Blue-Gray")]},
                    ),
                    103: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional caption for this grid cell (links allowed)",
                            "required": False,
                        },
                    ),
                    104: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Make the caption text italic",
                            "required": False,
                        },
                    ),
                    105: (
                        "wagtail.blocks.StreamBlock",
                        [[("prose", 7), ("callout", 44)]],
                        {
                            "help_text": "Add text or special elements to the cell body",
                            "required": True,
                        },
                    ),
                    106: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 101),
                                ("header_color", 102),
                                ("caption", 103),
                                ("italic_caption", 104),
                                ("body", 105),
                            ]
                        ],
                        {},
                    ),
                    107: (
                        "wagtail.blocks.ListBlock",
                        (106,),
                        {
                            "help_text": "Add cells to the grid. Cells will fill row-by-row based on the number of columns selected."
                        },
                    ),
                    108: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("columns", 98),
                                ("width", 99),
                                ("gridStyle", 100),
                                ("cells", 107),
                            ]
                        ],
                        {},
                    ),
                    109: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Card Icon", "required": True},
                    ),
                    110: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("right", "Right"),
                                ("bottom", "Bottom"),
                                ("left", "Left"),
                            ],
                            "help_text": "Icon placement, e.g. Top, Right, Bottom, Left. Default is Top.",
                            "required": False,
                        },
                    ),
                    111: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Displays the card title", "required": True},
                    ),
                    112: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "required": True},
                    ),
                    113: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "If checked, hover treatment is enabled for ALL tiles in this set.",
                            "required": False,
                        },
                    ),
                    114: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "desktop_top_mobile_left",
                                    "Desktop-Top / Mobile-Left",
                                ),
                                (
                                    "desktop_bottom_mobile_right",
                                    "Desktop-Bottom / Mobile-Right",
                                ),
                            ],
                            "help_text": "Applies to ALL tiles in this set (keeps icon placement uniform).",
                        },
                    ),
                    115: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Card header (H2)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    116: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic"],
                            "help_text": "Optional body text",
                            "required": False,
                        },
                    ),
                    117: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Select an SVG file."},
                    ),
                    118: (
                        "wagtail.blocks.StructBlock",
                        [[("svg_file", 117)]],
                        {"required": True},
                    ),
                    119: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center"),
                                ("left", "Left"),
                                ("right", "Right"),
                            ],
                            "help_text": "Desktop text alignment (tablet/mobile will be left-aligned per design).",
                        },
                    ),
                    120: ("wagtail.blocks.PageChooserBlock", (), {}),
                    121: ("wagtail.blocks.URLBlock", (), {}),
                    122: (
                        "wagtail.blocks.StreamBlock",
                        [[("related_page", 120), ("external_url", 121)]],
                        {
                            "help_text": "Choose where this tile should link.",
                            "max_num": 1,
                            "min_num": 1,
                            "required": False,
                        },
                    ),
                    123: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 115),
                                ("description", 116),
                                ("icon", 118),
                                ("content_alignment", 119),
                                ("link", 122),
                            ]
                        ],
                        {},
                    ),
                    124: (
                        "wagtail.blocks.ListBlock",
                        (123,),
                        {
                            "help_text": "Add, reorder, duplicate, or remove tiles. Responsive grid: 3 desktop / 2 tablet / 1 mobile.",
                            "required": False,
                        },
                    ),
                    125: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles_hover_enabled", 113),
                                ("icon_position", 114),
                                ("tiles", 124),
                            ]
                        ],
                        {},
                    ),
                    126: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 3),
                                ("h2", 4),
                                ("h3", 5),
                                ("h4", 6),
                                ("paragraph", 7),
                                ("indented_paragraph", 8),
                                ("snippet", 9),
                                ("button", 18),
                                ("hr", 19),
                                ("iframe", 23),
                                ("alert", 25),
                                ("image", 28),
                                ("photo_dedication", 34),
                                ("table", 35),
                                ("unstyled_table", 35),
                                ("enhanced_table", 51),
                                ("list", 71),
                                ("links", 78),
                                ("questionanswers", 80),
                                ("columns", 89),
                                ("embedded_video", 92),
                                ("card", 97),
                                ("accordion", 48),
                                ("callout", 44),
                                ("grid", 108),
                                ("quick_access_tiles", 125),
                            ]
                        ],
                        {"required": False},
                    ),
                    127: (
                        "wagtail.blocks.StructBlock",
                        [[("breadcrumb_title", 112), ("body", 126)]],
                        {},
                    ),
                    128: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("anchor_page", 127),
                                ("internal_page", 120),
                                ("external_url", 121),
                            ]
                        ],
                        {"max_num": 1, "min_num": 1},
                    ),
                    129: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect",
                            "required": False,
                        },
                    ),
                    130: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 109),
                                ("icon_direction", 110),
                                ("card_header", 111),
                                ("link", 128),
                                ("card_hover", 129),
                            ]
                        ],
                        {},
                    ),
                    131: (
                        "wagtail.blocks.ListBlock",
                        (130,),
                        {
                            "help_text": "Add up to 4 card tiles. They will display responsively based on screen size.",
                            "max_num": 4,
                            "min_num": 1,
                        },
                    ),
                    132: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 3),
                                ("h2", 4),
                                ("h3", 5),
                                ("h4", 6),
                                ("paragraph", 7),
                                ("indented_paragraph", 8),
                                ("snippet", 9),
                                ("button", 18),
                                ("hr", 19),
                                ("iframe", 23),
                                ("alert", 25),
                                ("image", 28),
                                ("photo_dedication", 34),
                                ("table", 35),
                                ("unstyled_table", 35),
                                ("enhanced_table", 51),
                                ("list", 71),
                                ("links", 78),
                                ("questionanswers", 80),
                                ("columns", 89),
                                ("embedded_video", 92),
                                ("card", 97),
                                ("accordion", 48),
                                ("callout", 44),
                                ("grid", 108),
                            ]
                        ],
                        {
                            "help_text": "Default content to display when no card is selected",
                            "required": False,
                        },
                    ),
                    133: (
                        "wagtail.blocks.StructBlock",
                        [[("tiles", 131), ("default_content", 132)]],
                        {},
                    ),
                },
            ),
        ),
    ]
