# Generated by Django 5.2.13 on 2026-08-14 13:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0133_set_sort_order_of_administrative_order_pdfs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="litcpage",
            name="city_asterisk_notice",
        ),
        migrations.AlterField(
            model_name="litcpage",
            name="low_income_taxpayer_clinics",
            field=wagtail.fields.StreamField(
                [("state", 9)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Indicates the clinic only represents taxpayers who have elected the small tax case procedures.",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 0),
                                ("address", 1),
                                ("phone", 1),
                                ("website", 2),
                                ("email", 3),
                                ("small_case_procedures_only", 4),
                            ]
                        ],
                        {},
                    ),
                    6: ("wagtail.blocks.ListBlock", (5,), {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("clinics", 6)]],
                        {},
                    ),
                    8: ("wagtail.blocks.ListBlock", (7,), {}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("state", 0), ("cities", 8)]],
                        {},
                    ),
                },
            ),
        ),
    ]
