# Generated by Django 5.2.13 on 2026-08-20 14:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0134_remove_litcpage_city_asterisk_notice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="litcpage",
            name="remote_clinics",
            field=wagtail.fields.StreamField(
                [("remote", 10)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bottom", "Bottom (after all states)"),
                                ("top", "Top (before all states)"),
                            ],
                            "help_text": "Where the Remote banner appears relative to the state list.",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Don’t see a clinic in your area? This clinic operates across all geographic boundaries",
                            "help_text": "The text shown in the blue Remote banner.",
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Low Income Taxpayer Clinic",
                            "help_text": 'The category label shown above the clinic name on the card (e.g. "Low Income Taxpayer Clinic" or "Pro Bono Program").',
                        },
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {}),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    6: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Indicates the clinic only represents taxpayers who have elected the small tax case procedures.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("clinic_type", 2),
                                ("name", 3),
                                ("address", 4),
                                ("phone", 4),
                                ("website", 5),
                                ("email", 6),
                                ("small_case_procedures_only", 7),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("position", 0), ("text", 1), ("clinics", 9)]],
                        {},
                    ),
                },
                help_text="Clinics that operate across geographic boundaries rather than in a specific state/city. Renders as its own banner above or below all states on the front end, based on the Position field below. If no clinics are added here, the Remote banner will not be shown.",
            ),
        ),
    ]
