# Generated by Django 5.2.16 on 2026-08-21 18:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0134_remove_litcpage_city_asterisk_notice_and_more"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("indented_paragraph", 8),
                    ("snippet", 9),
                    ("button", 19),
                    ("hr", 20),
                    ("iframe", 24),
                    ("alert", 26),
                    ("image", 29),
                    ("photo_dedication", 35),
                    ("table", 36),
                    ("unstyled_table", 36),
                    ("enhanced_table", 52),
                    ("list", 69),
                    ("links", 76),
                    ("questionanswers", 78),
                    ("columns", 87),
                    ("embedded_video", 90),
                    ("card", 95),
                    ("accordion", 49),
                    ("callout", 45),
                    ("grid", 106),
                    ("card_tiles", 133),
                    ("quick_access_tiles", 123),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Paragraph with left indentation for alignment with list items",
                            "label": "Indented Paragraph",
                        },
                    ),
                    9: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    10: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Optional: Button icon", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("before", "Before Text"),
                                ("after", "After Text"),
                            ],
                            "help_text": "Choose the location of the icon relative to the text, if icon is selected.",
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    13: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to"},
                    ),
                    14: (
                        "home.blocks.PDFDocumentChooserBlock",
                        (),
                        {"help_text": "Select a PDF to link to"},
                    ),
                    15: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Enter an external URL"},
                    ),
                    16: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 13),
                                ("internal_pdf", 14),
                                ("external_url", 15),
                            ]
                        ],
                        {
                            "help_text": "Select exactly one: Internal Page, External URL, or PDF.",
                            "label": "URL",
                            "max_num": 1,
                            "min_num": 1,
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("inverted-primary", "Inverted Primary"),
                            ],
                            "help_text": "Choose the button style",
                        },
                    ),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect on button",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 10),
                                ("icon_location", 11),
                                ("text", 12),
                                ("url", 16),
                                ("style", 17),
                                ("button_hover", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    21: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    22: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    23: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("src", 21),
                                ("width", 22),
                                ("height", 22),
                                ("class", 23),
                                ("loading", 23),
                                ("data_delay", 23),
                                ("name", 23),
                                ("title", 23),
                            ]
                        ],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success")]},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("alert_type", 25), ("content", 7)]],
                        {},
                    ),
                    27: ("wagtail.images.blocks.ImageBlock", [], {}),
                    28: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 13),
                                ("internal_pdf", 14),
                                ("external_url", 15),
                            ]
                        ],
                        {
                            "help_text": "Optional: add a link to make the image clickable.",
                            "max_num": 1,
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 27), ("link", 28)]],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Before"), ("right", "After")],
                            "help_text": "Place the image before (left on desktop) or after (right on desktop) the text.",
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional heading displayed above the photo and text.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Upload an image to display with this dedication",
                            "required": True,
                        },
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Describe the image for a visually impaired person.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    34: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image_position", 30),
                                ("title", 31),
                                ("photo", 32),
                                ("alt_text", 33),
                                ("paragraph_text", 34),
                                ("link", 28),
                            ]
                        ],
                        {},
                    ),
                    36: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title displayed above the table (rendered as H2).",
                            "label": "Header",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "A caption displayed above or below the table depending on Caption Location.",
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("top", "Top"), ("bottom", "Bottom")]},
                    ),
                    40: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("styled", "Styled Table"),
                                ("borderlessUnstyled", "Borderless Unstyled Table"),
                                ("unstyled", "Unstyled Table"),
                            ]
                        },
                    ),
                    41: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to set table layout to fixed width.",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of this special element",
                            "required": True,
                        },
                    ),
                    43: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "The paragraph content", "required": True},
                    ),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("success", "Success"),
                                ("error", "Error"),
                                ("emergency", "Emergency"),
                            ]
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 42), ("text", 43), ("callout_type", 44)]],
                        {},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title user will see before opening",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    47: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 3), ("prose", 7), ("callout", 45)]],
                        {
                            "help_text": "Add text or special elements to the body",
                            "required": True,
                        },
                    ),
                    48: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to have the accordion open by default when the page loads.",
                            "required": False,
                        },
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 46), ("description", 47), ("default_to_open", 48)]],
                        {},
                    ),
                    50: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 7),
                                ("callout", 45),
                                ("accordion", 49),
                                ("button", 19),
                            ]
                        ],
                        {"required": False},
                    ),
                    51: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("components", 50)]],
                        {},
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 37),
                                ("caption", 38),
                                ("caption_location", 39),
                                ("style", 40),
                                ("fixed", 41),
                                ("table", 51),
                            ]
                        ],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                                ("checkbox", "Checkbox List"),
                                ("checkbox_with_subtext", "Checkbox with Subtext"),
                            ],
                            "required": False,
                        },
                    ),
                    54: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 54), ("subtext", 54), ("image", 27)]],
                        {"required": False},
                    ),
                    56: ("wagtail.blocks.ListBlock", (55,), {"default": []}),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 53), ("items", 56)]],
                        {"required": False},
                    ),
                    58: ("wagtail.blocks.ListBlock", (57,), {"default": []}),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 54),
                                ("subtext", 54),
                                ("image", 27),
                                ("nested_list", 58),
                            ]
                        ],
                        {"required": False},
                    ),
                    60: ("wagtail.blocks.ListBlock", (59,), {"default": []}),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 53), ("items", 60)]],
                        {"required": False},
                    ),
                    62: ("wagtail.blocks.ListBlock", (61,), {"default": []}),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 54),
                                ("subtext", 54),
                                ("image", 27),
                                ("nested_list", 62),
                            ]
                        ],
                        {"required": False},
                    ),
                    64: ("wagtail.blocks.ListBlock", (63,), {"default": []}),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 53), ("items", 64)]],
                        {"required": False},
                    ),
                    66: ("wagtail.blocks.ListBlock", (65,), {"default": []}),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 54),
                                ("subtext", 54),
                                ("image", 27),
                                ("nested_list", 66),
                            ]
                        ],
                        {"required": False},
                    ),
                    68: ("wagtail.blocks.ListBlock", (67,), {"default": []}),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 53), ("items", 68)]],
                        {"required": False},
                    ),
                    70: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ],
                            "label": "List style",
                        },
                    ),
                    71: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    72: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    73: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 71),
                                ("document", 72),
                                ("video", 72),
                                ("url", 23),
                                ("text_only", 73),
                            ]
                        ],
                        {},
                    ),
                    75: ("wagtail.blocks.ListBlock", (74,), {"label": "Add Entry"}),
                    76: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 70), ("links", 75)]],
                        {"label": "List of Links"},
                    ),
                    77: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 23), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    78: (
                        "wagtail.blocks.ListBlock",
                        (77,),
                        {
                            "help_text": "Add a question and answer with anchor tag for linking",
                            "label": "Question and Answer",
                        },
                    ),
                    79: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 23)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    81: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 23)]],
                        {"label": "Clickable Button"},
                    ),
                    82: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    83: ("wagtail.blocks.ListBlock", (74,), {}),
                    84: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 82), ("links", 83)]],
                        {"label": "Links"},
                    ),
                    85: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 4),
                                ("h3", 5),
                                ("hr", 79),
                                ("h2WithAnchorTag", 80),
                                ("clickableButton", 81),
                                ("links", 84),
                            ]
                        ],
                        {},
                    ),
                    86: ("wagtail.blocks.ListBlock", (85,), {}),
                    87: ("wagtail.blocks.StructBlock", [[("column", 86)]], {}),
                    88: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use the YouTube embed URL (e.g. https://www.youtube.com/embed/VIDEO_ID), not the watch URL.",
                            "required": True,
                        },
                    ),
                    89: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("below", "Below"), ("right-of", "Right")]},
                    ),
                    90: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 23),
                                ("description", 54),
                                ("video_url", 88),
                                ("text_location", 89),
                            ]
                        ],
                        {},
                    ),
                    91: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ]
                        },
                    ),
                    92: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    93: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    94: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 91),
                                ("title", 22),
                                ("description", 92),
                                ("color", 93),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    95: ("wagtail.blocks.ListBlock", (94,), {"label": "Card Set"}),
                    96: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [(1, 1), (2, 2), (3, 3), (4, 4)],
                            "help_text": "Max number of columns in the grid (1-4)",
                        },
                    ),
                    97: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("full", "Full Width")],
                            "help_text": "Maximum width of the grid",
                        },
                    ),
                    98: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("styled", "Styled"), ("unstyled", "Unstyled")],
                            "help_text": "Style of the grid",
                        },
                    ),
                    99: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional header for this grid cell",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    100: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("#f1f9fc", "Default"), ("#DEEAF0", "Blue-Gray")]},
                    ),
                    101: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional caption for this grid cell (links allowed)",
                            "required": False,
                        },
                    ),
                    102: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Make the caption text italic",
                            "required": False,
                        },
                    ),
                    103: (
                        "wagtail.blocks.StreamBlock",
                        [[("prose", 7), ("callout", 45)]],
                        {
                            "help_text": "Add text or special elements to the cell body",
                            "required": True,
                        },
                    ),
                    104: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 99),
                                ("header_color", 100),
                                ("caption", 101),
                                ("italic_caption", 102),
                                ("body", 103),
                            ]
                        ],
                        {},
                    ),
                    105: (
                        "wagtail.blocks.ListBlock",
                        (104,),
                        {
                            "help_text": "Add cells to the grid. Cells will fill row-by-row based on the number of columns selected."
                        },
                    ),
                    106: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("columns", 96),
                                ("width", 97),
                                ("gridStyle", 98),
                                ("cells", 105),
                            ]
                        ],
                        {},
                    ),
                    107: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Card Icon", "required": True},
                    ),
                    108: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("right", "Right"),
                                ("bottom", "Bottom"),
                                ("left", "Left"),
                            ],
                            "help_text": "Icon placement, e.g. Top, Right, Bottom, Left. Default is Top.",
                            "required": False,
                        },
                    ),
                    109: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Displays the card title", "required": True},
                    ),
                    110: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "required": True},
                    ),
                    111: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "If checked, hover treatment is enabled for ALL tiles in this set.",
                            "required": False,
                        },
                    ),
                    112: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "desktop_top_mobile_left",
                                    "Desktop-Top / Mobile-Left",
                                ),
                                (
                                    "desktop_bottom_mobile_right",
                                    "Desktop-Bottom / Mobile-Right",
                                ),
                            ],
                            "help_text": "Applies to ALL tiles in this set (keeps icon placement uniform).",
                        },
                    ),
                    113: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Card header (H2)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    114: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic"],
                            "help_text": "Optional body text",
                            "required": False,
                        },
                    ),
                    115: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Select an SVG file."},
                    ),
                    116: (
                        "wagtail.blocks.StructBlock",
                        [[("svg_file", 115)]],
                        {"required": True},
                    ),
                    117: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center"),
                                ("left", "Left"),
                                ("right", "Right"),
                            ],
                            "help_text": "Desktop text alignment (tablet/mobile will be left-aligned per design).",
                        },
                    ),
                    118: ("wagtail.blocks.PageChooserBlock", (), {}),
                    119: ("wagtail.blocks.URLBlock", (), {}),
                    120: (
                        "wagtail.blocks.StreamBlock",
                        [[("related_page", 118), ("external_url", 119)]],
                        {
                            "help_text": "Choose where this tile should link.",
                            "max_num": 1,
                            "min_num": 1,
                            "required": False,
                        },
                    ),
                    121: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 113),
                                ("description", 114),
                                ("icon", 116),
                                ("content_alignment", 117),
                                ("link", 120),
                            ]
                        ],
                        {},
                    ),
                    122: (
                        "wagtail.blocks.ListBlock",
                        (121,),
                        {
                            "help_text": "Add, reorder, duplicate, or remove tiles. Responsive grid: 3 desktop / 2 tablet / 1 mobile.",
                            "required": False,
                        },
                    ),
                    123: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles_hover_enabled", 111),
                                ("icon_position", 112),
                                ("tiles", 122),
                            ]
                        ],
                        {},
                    ),
                    124: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 3),
                                ("h2", 4),
                                ("h3", 5),
                                ("h4", 6),
                                ("paragraph", 7),
                                ("indented_paragraph", 8),
                                ("snippet", 9),
                                ("button", 19),
                                ("hr", 20),
                                ("iframe", 24),
                                ("alert", 26),
                                ("image", 29),
                                ("photo_dedication", 35),
                                ("table", 36),
                                ("unstyled_table", 36),
                                ("enhanced_table", 52),
                                ("list", 69),
                                ("links", 76),
                                ("questionanswers", 78),
                                ("columns", 87),
                                ("embedded_video", 90),
                                ("card", 95),
                                ("accordion", 49),
                                ("callout", 45),
                                ("grid", 106),
                                ("quick_access_tiles", 123),
                            ]
                        ],
                        {"required": False},
                    ),
                    125: (
                        "wagtail.blocks.StructBlock",
                        [[("breadcrumb_title", 110), ("body", 124)]],
                        {},
                    ),
                    126: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("anchor_page", 125),
                                ("internal_page", 118),
                                ("external_url", 119),
                            ]
                        ],
                        {"max_num": 1, "min_num": 1},
                    ),
                    127: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect",
                            "required": False,
                        },
                    ),
                    128: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 107),
                                ("icon_direction", 108),
                                ("card_header", 109),
                                ("link", 126),
                                ("card_hover", 127),
                            ]
                        ],
                        {},
                    ),
                    129: (
                        "wagtail.blocks.ListBlock",
                        (128,),
                        {
                            "help_text": "Add up to 4 card tiles. They will display responsively based on screen size.",
                            "max_num": 4,
                            "min_num": 1,
                        },
                    ),
                    130: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 3),
                                ("h2", 4),
                                ("h3", 5),
                                ("h4", 6),
                                ("paragraph", 7),
                                ("indented_paragraph", 8),
                                ("snippet", 9),
                                ("button", 19),
                                ("hr", 20),
                                ("iframe", 24),
                                ("alert", 26),
                                ("image", 29),
                                ("photo_dedication", 35),
                                ("table", 36),
                                ("unstyled_table", 36),
                                ("enhanced_table", 52),
                                ("list", 69),
                                ("links", 76),
                                ("questionanswers", 78),
                                ("columns", 87),
                                ("embedded_video", 90),
                                ("card", 95),
                                ("accordion", 49),
                                ("callout", 45),
                                ("grid", 106),
                            ]
                        ],
                        {
                            "help_text": "Default content to display when no card is selected",
                            "required": False,
                        },
                    ),
                    131: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Display a back button when a card tile is selected (e.g. p/a, p/b). Hidden on the default view showing all card tiles. If checked, Back Button Text is required.",
                            "required": False,
                        },
                    ),
                    132: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text shown on the back button. Required if 'Show back button' is checked.",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    133: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles", 129),
                                ("default_content", 130),
                                ("show_back_button", 131),
                                ("back_button_text", 132),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.CreateModel(
            name="CallToActionBox",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "live",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="live"
                    ),
                ),
                (
                    "has_unpublished_changes",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="has unpublished changes",
                    ),
                ),
                (
                    "first_published_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="first published at",
                    ),
                ),
                (
                    "last_published_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="last published at"
                    ),
                ),
                (
                    "go_live_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="go live date/time"
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expiry date/time"
                    ),
                ),
                (
                    "expired",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="expired"
                    ),
                ),
                (
                    "review_by",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for review and moderation of this content.",
                        null=True,
                        verbose_name="Review by date",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional note for moderators when submitting content for review.",
                        null=True,
                        verbose_name="Moderation note",
                    ),
                ),
                (
                    "header",
                    models.CharField(
                        help_text="Header to display in the Call to Action Box",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Content to display in the Call to Action Box",
                        null=True,
                    ),
                ),
                (
                    "buttons",
                    wagtail.fields.StreamField(
                        [("button", 9)],
                        block_lookup={
                            0: (
                                "home.blocks.SVGDocumentChooserBlock",
                                (),
                                {
                                    "help_text": "Optional: Button icon",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("before", "Before Text"),
                                        ("after", "After Text"),
                                    ],
                                    "help_text": "Choose the location of the icon relative to the text, if icon is selected.",
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Button text",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            3: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"help_text": "Select a page to link to"},
                            ),
                            4: (
                                "home.blocks.PDFDocumentChooserBlock",
                                (),
                                {"help_text": "Select a PDF to link to"},
                            ),
                            5: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"help_text": "Enter an external URL"},
                            ),
                            6: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("internal_page", 3),
                                        ("internal_pdf", 4),
                                        ("external_url", 5),
                                    ]
                                ],
                                {
                                    "help_text": "Select exactly one: Internal Page, External URL, or PDF.",
                                    "label": "URL",
                                    "max_num": 1,
                                    "min_num": 1,
                                },
                            ),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("inverted-primary", "Inverted Primary"),
                                    ],
                                    "help_text": "Choose the button style",
                                },
                            ),
                            8: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Enable hover effect on button",
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 0),
                                        ("icon_location", 1),
                                        ("text", 2),
                                        ("url", 6),
                                        ("style", 7),
                                        ("button_hover", 8),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Buttons to display at the bottom of the Call to Action Box",
                    ),
                ),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call to Action Box",
                "verbose_name_plural": "Call to Action Boxes",
            },
        ),
        migrations.CreateModel(
            name="PetitionerExperiencePage",
            fields=[
                (
                    "enhancedstandardpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.enhancedstandardpage",
                    ),
                ),
                (
                    "introductory_text",
                    wagtail.fields.RichTextField(
                        help_text="Text to be displayed at the top of the page under the page's title."
                    ),
                ),
                (
                    "call_to_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="home.calltoactionbox",
                    ),
                ),
            ],
            options={
                "verbose_name": "Petitioner Experience Page",
            },
            bases=("home.enhancedstandardpage",),
        ),
    ]
