# Generated by Django 5.2.13 on 2026-08-26 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0135_alter_enhancedrawhtmlpage_raw_html_body_and_more"),
        ("home", "0135_alter_enhancedstandardpage_body_calltoactionbox_and_more"),
    ]

    operations = []
