# Generated by Django 5.2.16 on 2026-08-24 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0134_petitionerexperiencepage"),
        ("home", "0135_alter_enhancedrawhtmlpage_raw_html_body_and_more"),
    ]

    operations = []
