# Generated by Django 5.2.13 on 2026-09-02 15:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0135_litcpage_remote_clinics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 3),
                    ("h2", 4),
                    ("h3", 5),
                    ("h4", 6),
                    ("paragraph", 7),
                    ("indented_paragraph", 8),
                    ("snippet", 9),
                    ("button", 18),
                    ("hr", 19),
                    ("iframe", 23),
                    ("alert", 25),
                    ("image", 28),
                    ("photo_dedication", 34),
                    ("table", 35),
                    ("unstyled_table", 35),
                    ("enhanced_table", 51),
                    ("list", 68),
                    ("links", 75),
                    ("questionanswers", 77),
                    ("columns", 86),
                    ("embedded_video", 89),
                    ("card", 100),
                    ("accordion", 48),
                    ("callout", 44),
                    ("grid", 111),
                    ("card_tiles", 138),
                    ("quick_access_tiles", 128),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1), ("id", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    7: ("wagtail.blocks.RichTextBlock", (), {}),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Paragraph with left indentation for alignment with list items",
                            "label": "Indented Paragraph",
                        },
                    ),
                    9: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    10: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Optional: Button icon", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to"},
                    ),
                    13: (
                        "home.blocks.PDFDocumentChooserBlock",
                        (),
                        {"help_text": "Select a PDF to link to"},
                    ),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Enter an external URL"},
                    ),
                    15: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 12),
                                ("internal_pdf", 13),
                                ("external_url", 14),
                            ]
                        ],
                        {
                            "help_text": "Select exactly one: Internal Page, External URL, or PDF.",
                            "label": "URL",
                            "max_num": 1,
                            "min_num": 1,
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("primary", "Primary")],
                            "help_text": "Choose the button style",
                        },
                    ),
                    17: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect on button",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 10),
                                ("text", 11),
                                ("url", 15),
                                ("style", 16),
                                ("button_hover", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    20: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    21: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    22: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("src", 20),
                                ("width", 21),
                                ("height", 21),
                                ("class", 22),
                                ("loading", 22),
                                ("data_delay", 22),
                                ("name", 22),
                                ("title", 22),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success")]},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("alert_type", 24), ("content", 7)]],
                        {},
                    ),
                    26: ("wagtail.images.blocks.ImageBlock", [], {}),
                    27: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 12),
                                ("internal_pdf", 13),
                                ("external_url", 14),
                            ]
                        ],
                        {
                            "help_text": "Optional: add a link to make the image clickable.",
                            "max_num": 1,
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 26), ("link", 27)]],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Before"), ("right", "After")],
                            "help_text": "Place the image before (left on desktop) or after (right on desktop) the text.",
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional heading displayed above the photo and text.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Upload an image to display with this dedication",
                            "required": True,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Describe the image for a visually impaired person.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    33: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image_position", 29),
                                ("title", 30),
                                ("photo", 31),
                                ("alt_text", 32),
                                ("paragraph_text", 33),
                                ("link", 27),
                            ]
                        ],
                        {},
                    ),
                    35: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 7)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title displayed above the table (rendered as H2).",
                            "label": "Header",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "A caption displayed above or below the table depending on Caption Location.",
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("top", "Top"), ("bottom", "Bottom")]},
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("styled", "Styled Table"),
                                ("borderlessUnstyled", "Borderless Unstyled Table"),
                                ("unstyled", "Unstyled Table"),
                            ]
                        },
                    ),
                    40: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to set table layout to fixed width.",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of this special element",
                            "required": True,
                        },
                    ),
                    42: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "The paragraph content", "required": True},
                    ),
                    43: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("success", "Success"),
                                ("error", "Error"),
                                ("emergency", "Emergency"),
                            ]
                        },
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 41), ("text", 42), ("callout_type", 43)]],
                        {},
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title user will see before opening",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    46: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 3), ("prose", 7), ("callout", 44)]],
                        {
                            "help_text": "Add text or special elements to the body",
                            "required": True,
                        },
                    ),
                    47: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to have the accordion open by default when the page loads.",
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 45), ("description", 46), ("default_to_open", 47)]],
                        {},
                    ),
                    49: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 7),
                                ("callout", 44),
                                ("accordion", 48),
                                ("button", 18),
                            ]
                        ],
                        {"required": False},
                    ),
                    50: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("components", 49)]],
                        {},
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 36),
                                ("caption", 37),
                                ("caption_location", 38),
                                ("style", 39),
                                ("fixed", 40),
                                ("table", 50),
                            ]
                        ],
                        {},
                    ),
                    52: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                                ("checkbox", "Checkbox List"),
                                ("checkbox_with_subtext", "Checkbox with Subtext"),
                            ],
                            "required": False,
                        },
                    ),
                    53: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 53), ("subtext", 53), ("image", 26)]],
                        {"required": False},
                    ),
                    55: ("wagtail.blocks.ListBlock", (54,), {"default": []}),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 52), ("items", 55)]],
                        {"required": False},
                    ),
                    57: ("wagtail.blocks.ListBlock", (56,), {"default": []}),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 53),
                                ("subtext", 53),
                                ("image", 26),
                                ("nested_list", 57),
                            ]
                        ],
                        {"required": False},
                    ),
                    59: ("wagtail.blocks.ListBlock", (58,), {"default": []}),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 52), ("items", 59)]],
                        {"required": False},
                    ),
                    61: ("wagtail.blocks.ListBlock", (60,), {"default": []}),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 53),
                                ("subtext", 53),
                                ("image", 26),
                                ("nested_list", 61),
                            ]
                        ],
                        {"required": False},
                    ),
                    63: ("wagtail.blocks.ListBlock", (62,), {"default": []}),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 52), ("items", 63)]],
                        {"required": False},
                    ),
                    65: ("wagtail.blocks.ListBlock", (64,), {"default": []}),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 53),
                                ("subtext", 53),
                                ("image", 26),
                                ("nested_list", 65),
                            ]
                        ],
                        {"required": False},
                    ),
                    67: ("wagtail.blocks.ListBlock", (66,), {"default": []}),
                    68: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 52), ("items", 67)]],
                        {"required": False},
                    ),
                    69: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ],
                            "label": "List style",
                        },
                    ),
                    70: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    71: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    72: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("icon", 70),
                                ("document", 71),
                                ("video", 71),
                                ("url", 22),
                                ("text_only", 72),
                            ]
                        ],
                        {},
                    ),
                    74: ("wagtail.blocks.ListBlock", (73,), {"label": "Add Entry"}),
                    75: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 69), ("links", 74)]],
                        {"label": "List of Links"},
                    ),
                    76: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 22), ("answer", 7), ("anchortag", 0)]],
                        {},
                    ),
                    77: (
                        "wagtail.blocks.ListBlock",
                        (76,),
                        {
                            "help_text": "Add a question and answer with anchor tag for linking",
                            "label": "Question and Answer",
                        },
                    ),
                    78: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("anchortag", 22)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 22)]],
                        {"label": "Clickable Button"},
                    ),
                    81: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    82: ("wagtail.blocks.ListBlock", (73,), {}),
                    83: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 81), ("links", 82)]],
                        {"label": "Links"},
                    ),
                    84: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 4),
                                ("h3", 5),
                                ("hr", 78),
                                ("h2WithAnchorTag", 79),
                                ("clickableButton", 80),
                                ("links", 83),
                            ]
                        ],
                        {},
                    ),
                    85: ("wagtail.blocks.ListBlock", (84,), {}),
                    86: ("wagtail.blocks.StructBlock", [[("column", 85)]], {}),
                    87: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use the YouTube embed URL (e.g. https://www.youtube.com/embed/VIDEO_ID), not the watch URL.",
                            "required": True,
                        },
                    ),
                    88: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("below", "Below"), ("right-of", "Right")]},
                    ),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 22),
                                ("description", 53),
                                ("video_url", 87),
                                ("text_location", 88),
                            ]
                        ],
                        {},
                    ),
                    90: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("gray", "Gray"),
                                ("dark-primary", "Dark-Primary"),
                                ("green", "Green"),
                                ("yellow", "Yellow"),
                            ],
                            "label": "Card Color",
                        },
                    ),
                    91: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-1", "One"),
                                ("fa-solid fa-2", "Two"),
                                ("fa-solid fa-3", "Three"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-exclamation", "Exclamation"),
                            ],
                            "help_text": "Optional numbered or status icon displayed on the card.",
                            "label": "Numbered Icon",
                            "required": False,
                        },
                    ),
                    92: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "help_text": "Only applies when Numbered Icon is not 'None'.",
                            "label": "Numbered Icon Alignment",
                            "required": False,
                        },
                    ),
                    93: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {
                            "help_text": "Optional: any SVG uploaded as a Wagtail Document.",
                            "label": "Title Icon",
                            "required": False,
                        },
                    ),
                    94: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank if the Title Icon is purely decorative. Fill in if it conveys meaning not already in the Card Title (e.g. distinguishing icons for different options).",
                            "label": "Title Icon Alt Text",
                            "required": False,
                        },
                    ),
                    95: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Displays the card sub title",
                            "label": "Card Sub-title",
                            "required": False,
                        },
                    ),
                    96: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Displays the card title",
                            "label": "Card Title",
                            "required": False,
                        },
                    ),
                    97: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Displays the text that goes under the header",
                            "label": "Body Text",
                            "required": False,
                        },
                    ),
                    98: (
                        "wagtail.blocks.ListBlock",
                        (18,),
                        {
                            "label": "Buttons",
                            "max_num": 1,
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    99: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("color", 90),
                                ("numbered_icon", 91),
                                ("numbered_icon_alignment", 92),
                                ("title_icon", 93),
                                ("title_icon_alt_text", 94),
                                ("subtitle", 95),
                                ("title", 96),
                                ("description", 97),
                                ("buttons", 98),
                            ]
                        ],
                        {"label": "Card", "label_format": "Card: {title}"},
                    ),
                    100: (
                        "wagtail.blocks.ListBlock",
                        (99,),
                        {
                            "help_text": "Add up to 3 cards. They display in a single row on desktop/tablet and stack in a single column on mobile.",
                            "label": "Card Set",
                            "max_num": 3,
                        },
                    ),
                    101: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [(1, 1), (2, 2), (3, 3), (4, 4)],
                            "help_text": "Max number of columns in the grid (1-4)",
                        },
                    ),
                    102: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("full", "Full Width")],
                            "help_text": "Maximum width of the grid",
                        },
                    ),
                    103: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("styled", "Styled"), ("unstyled", "Unstyled")],
                            "help_text": "Style of the grid",
                        },
                    ),
                    104: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional header for this grid cell",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    105: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("#f1f9fc", "Default"), ("#DEEAF0", "Blue-Gray")]},
                    ),
                    106: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional caption for this grid cell (links allowed)",
                            "required": False,
                        },
                    ),
                    107: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Make the caption text italic",
                            "required": False,
                        },
                    ),
                    108: (
                        "wagtail.blocks.StreamBlock",
                        [[("prose", 7), ("callout", 44)]],
                        {
                            "help_text": "Add text or special elements to the cell body",
                            "required": True,
                        },
                    ),
                    109: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 104),
                                ("header_color", 105),
                                ("caption", 106),
                                ("italic_caption", 107),
                                ("body", 108),
                            ]
                        ],
                        {},
                    ),
                    110: (
                        "wagtail.blocks.ListBlock",
                        (109,),
                        {
                            "help_text": "Add cells to the grid. Cells will fill row-by-row based on the number of columns selected."
                        },
                    ),
                    111: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("columns", 101),
                                ("width", 102),
                                ("gridStyle", 103),
                                ("cells", 110),
                            ]
                        ],
                        {},
                    ),
                    112: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Card Icon", "required": True},
                    ),
                    113: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("right", "Right"),
                                ("bottom", "Bottom"),
                                ("left", "Left"),
                            ],
                            "help_text": "Icon placement, e.g. Top, Right, Bottom, Left. Default is Top.",
                            "required": False,
                        },
                    ),
                    114: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Displays the card title", "required": True},
                    ),
                    115: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "required": True},
                    ),
                    116: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "If checked, hover treatment is enabled for ALL tiles in this set.",
                            "required": False,
                        },
                    ),
                    117: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "desktop_top_mobile_left",
                                    "Desktop-Top / Mobile-Left",
                                ),
                                (
                                    "desktop_bottom_mobile_right",
                                    "Desktop-Bottom / Mobile-Right",
                                ),
                            ],
                            "help_text": "Applies to ALL tiles in this set (keeps icon placement uniform).",
                        },
                    ),
                    118: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Card header (H2)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    119: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic"],
                            "help_text": "Optional body text",
                            "required": False,
                        },
                    ),
                    120: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Select an SVG file."},
                    ),
                    121: (
                        "wagtail.blocks.StructBlock",
                        [[("svg_file", 120)]],
                        {"required": True},
                    ),
                    122: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center"),
                                ("left", "Left"),
                                ("right", "Right"),
                            ],
                            "help_text": "Desktop text alignment (tablet/mobile will be left-aligned per design).",
                        },
                    ),
                    123: ("wagtail.blocks.PageChooserBlock", (), {}),
                    124: ("wagtail.blocks.URLBlock", (), {}),
                    125: (
                        "wagtail.blocks.StreamBlock",
                        [[("related_page", 123), ("external_url", 124)]],
                        {
                            "help_text": "Choose where this tile should link.",
                            "max_num": 1,
                            "min_num": 1,
                            "required": False,
                        },
                    ),
                    126: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 118),
                                ("description", 119),
                                ("icon", 121),
                                ("content_alignment", 122),
                                ("link", 125),
                            ]
                        ],
                        {},
                    ),
                    127: (
                        "wagtail.blocks.ListBlock",
                        (126,),
                        {
                            "help_text": "Add, reorder, duplicate, or remove tiles. Responsive grid: 3 desktop / 2 tablet / 1 mobile.",
                            "required": False,
                        },
                    ),
                    128: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles_hover_enabled", 116),
                                ("icon_position", 117),
                                ("tiles", 127),
                            ]
                        ],
                        {},
                    ),
                    129: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 3),
                                ("h2", 4),
                                ("h3", 5),
                                ("h4", 6),
                                ("paragraph", 7),
                                ("indented_paragraph", 8),
                                ("snippet", 9),
                                ("button", 18),
                                ("hr", 19),
                                ("iframe", 23),
                                ("alert", 25),
                                ("image", 28),
                                ("photo_dedication", 34),
                                ("table", 35),
                                ("unstyled_table", 35),
                                ("enhanced_table", 51),
                                ("list", 68),
                                ("links", 75),
                                ("questionanswers", 77),
                                ("columns", 86),
                                ("embedded_video", 89),
                                ("card", 100),
                                ("accordion", 48),
                                ("callout", 44),
                                ("grid", 111),
                                ("quick_access_tiles", 128),
                            ]
                        ],
                        {"required": False},
                    ),
                    130: (
                        "wagtail.blocks.StructBlock",
                        [[("breadcrumb_title", 115), ("body", 129)]],
                        {},
                    ),
                    131: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("anchor_page", 130),
                                ("internal_page", 123),
                                ("external_url", 124),
                            ]
                        ],
                        {"max_num": 1, "min_num": 1},
                    ),
                    132: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect",
                            "required": False,
                        },
                    ),
                    133: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 112),
                                ("icon_direction", 113),
                                ("card_header", 114),
                                ("link", 131),
                                ("card_hover", 132),
                            ]
                        ],
                        {},
                    ),
                    134: (
                        "wagtail.blocks.ListBlock",
                        (133,),
                        {
                            "help_text": "Add up to 4 card tiles. They will display responsively based on screen size.",
                            "max_num": 4,
                            "min_num": 1,
                        },
                    ),
                    135: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 3),
                                ("h2", 4),
                                ("h3", 5),
                                ("h4", 6),
                                ("paragraph", 7),
                                ("indented_paragraph", 8),
                                ("snippet", 9),
                                ("button", 18),
                                ("hr", 19),
                                ("iframe", 23),
                                ("alert", 25),
                                ("image", 28),
                                ("photo_dedication", 34),
                                ("table", 35),
                                ("unstyled_table", 35),
                                ("enhanced_table", 51),
                                ("list", 68),
                                ("links", 75),
                                ("questionanswers", 77),
                                ("columns", 86),
                                ("embedded_video", 89),
                                ("card", 100),
                                ("accordion", 48),
                                ("callout", 44),
                                ("grid", 111),
                            ]
                        ],
                        {
                            "help_text": "Default content to display when no card is selected",
                            "required": False,
                        },
                    ),
                    136: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Display a back button when a card tile is selected (e.g. p/a, p/b). Hidden on the default view showing all card tiles. If checked, Back Button Text is required.",
                            "required": False,
                        },
                    ),
                    137: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text shown on the back button. Required if 'Show back button' is checked.",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    138: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles", 134),
                                ("default_content", 135),
                                ("show_back_button", 136),
                                ("back_button_text", 137),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
