# Generated by Django 5.2.16 on 2026-09-01 15:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0138_alter_enhancedstandardpage_body_pe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petitionerexperiencepage",
            name="introductory_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Text to be displayed at the top of the page under the page's title.",
            ),
        ),
    ]
