# Generated by Django 5.2.15 on 2026-09-03 17:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0139_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("icon_header", 3),
                    ("heading", 7),
                    ("h2", 8),
                    ("h3", 9),
                    ("h4", 10),
                    ("paragraph", 11),
                    ("indented_paragraph", 12),
                    ("snippet", 13),
                    ("button", 23),
                    ("hr", 24),
                    ("iframe", 28),
                    ("alert", 30),
                    ("image", 33),
                    ("photo_dedication", 39),
                    ("table", 40),
                    ("unstyled_table", 40),
                    ("enhanced_table", 56),
                    ("list", 73),
                    ("links", 80),
                    ("questionanswers", 83),
                    ("columns", 92),
                    ("embedded_video", 95),
                    ("card", 100),
                    ("accordion", 53),
                    ("callout", 49),
                    ("grid", 111),
                    ("summary_timeline", 117),
                    ("card_tiles", 144),
                    ("quick_access_tiles", 134),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "label": "Icon",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Header Text", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ],
                            "label": "Heading Level",
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 0), ("text", 1), ("level", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {}),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 4), ("level", 5), ("id", 6)]],
                        {},
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    9: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    10: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    11: ("wagtail.blocks.RichTextBlock", (), {}),
                    12: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Paragraph with left indentation for alignment with list items",
                            "label": "Indented Paragraph",
                        },
                    ),
                    13: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    14: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Optional: Button icon", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("before", "Before Text"),
                                ("after", "After Text"),
                            ],
                            "help_text": "Choose the location of the icon relative to the text, if icon is selected.",
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    17: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to"},
                    ),
                    18: (
                        "home.blocks.PDFDocumentChooserBlock",
                        (),
                        {"help_text": "Select a PDF to link to"},
                    ),
                    19: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Enter an external URL"},
                    ),
                    20: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 17),
                                ("internal_pdf", 18),
                                ("external_url", 19),
                            ]
                        ],
                        {
                            "help_text": "Select exactly one: Internal Page, External URL, or PDF.",
                            "label": "URL",
                            "max_num": 1,
                            "min_num": 1,
                        },
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("inverted-primary", "Inverted Primary"),
                            ],
                            "help_text": "Choose the button style",
                        },
                    ),
                    22: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect on button",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 14),
                                ("icon_location", 15),
                                ("text", 16),
                                ("url", 20),
                                ("style", 21),
                                ("button_hover", 22),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    25: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    26: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    27: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("src", 25),
                                ("width", 26),
                                ("height", 26),
                                ("class", 27),
                                ("loading", 27),
                                ("data_delay", 27),
                                ("name", 27),
                                ("title", 27),
                            ]
                        ],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success")]},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("alert_type", 29), ("content", 11)]],
                        {},
                    ),
                    31: ("wagtail.images.blocks.ImageBlock", [], {}),
                    32: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 17),
                                ("internal_pdf", 18),
                                ("external_url", 19),
                            ]
                        ],
                        {
                            "help_text": "Optional: add a link to make the image clickable.",
                            "max_num": 1,
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 31), ("link", 32)]],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Before"), ("right", "After")],
                            "help_text": "Place the image before (left on desktop) or after (right on desktop) the text.",
                        },
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional heading displayed above the photo and text.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Upload an image to display with this dedication",
                            "required": True,
                        },
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Describe the image for a visually impaired person.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    38: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image_position", 34),
                                ("title", 35),
                                ("photo", 36),
                                ("alt_text", 37),
                                ("paragraph_text", 38),
                                ("link", 32),
                            ]
                        ],
                        {},
                    ),
                    40: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 11)]],
                        {},
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title displayed above the table (rendered as H2).",
                            "label": "Header",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "A caption displayed above or below the table depending on Caption Location.",
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("top", "Top"), ("bottom", "Bottom")]},
                    ),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("styled", "Styled Table"),
                                ("borderlessUnstyled", "Borderless Unstyled Table"),
                                ("unstyled", "Unstyled Table"),
                            ]
                        },
                    ),
                    45: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to set table layout to fixed width.",
                            "required": False,
                        },
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of this special element",
                            "required": True,
                        },
                    ),
                    47: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "The paragraph content", "required": True},
                    ),
                    48: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("success", "Success"),
                                ("error", "Error"),
                                ("emergency", "Emergency"),
                            ]
                        },
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 46), ("text", 47), ("callout_type", 48)]],
                        {},
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title user will see before opening",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    51: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 7), ("prose", 11), ("callout", 49)]],
                        {
                            "help_text": "Add text or special elements to the body",
                            "required": True,
                        },
                    ),
                    52: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to have the accordion open by default when the page loads.",
                            "required": False,
                        },
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 50), ("description", 51), ("default_to_open", 52)]],
                        {},
                    ),
                    54: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 11),
                                ("callout", 49),
                                ("accordion", 53),
                                ("button", 23),
                            ]
                        ],
                        {"required": False},
                    ),
                    55: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("components", 54)]],
                        {},
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 41),
                                ("caption", 42),
                                ("caption_location", 43),
                                ("style", 44),
                                ("fixed", 45),
                                ("table", 55),
                            ]
                        ],
                        {},
                    ),
                    57: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                                ("checkbox", "Checkbox List"),
                                ("checkbox_with_subtext", "Checkbox with Subtext"),
                            ],
                            "required": False,
                        },
                    ),
                    58: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 58), ("subtext", 58), ("image", 31)]],
                        {"required": False},
                    ),
                    60: ("wagtail.blocks.ListBlock", (59,), {"default": []}),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 57), ("items", 60)]],
                        {"required": False},
                    ),
                    62: ("wagtail.blocks.ListBlock", (61,), {"default": []}),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 58),
                                ("subtext", 58),
                                ("image", 31),
                                ("nested_list", 62),
                            ]
                        ],
                        {"required": False},
                    ),
                    64: ("wagtail.blocks.ListBlock", (63,), {"default": []}),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 57), ("items", 64)]],
                        {"required": False},
                    ),
                    66: ("wagtail.blocks.ListBlock", (65,), {"default": []}),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 58),
                                ("subtext", 58),
                                ("image", 31),
                                ("nested_list", 66),
                            ]
                        ],
                        {"required": False},
                    ),
                    68: ("wagtail.blocks.ListBlock", (67,), {"default": []}),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 57), ("items", 68)]],
                        {"required": False},
                    ),
                    70: ("wagtail.blocks.ListBlock", (69,), {"default": []}),
                    71: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 58),
                                ("subtext", 58),
                                ("image", 31),
                                ("nested_list", 70),
                            ]
                        ],
                        {"required": False},
                    ),
                    72: ("wagtail.blocks.ListBlock", (71,), {"default": []}),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 57), ("items", 72)]],
                        {"required": False},
                    ),
                    74: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ],
                            "label": "List style",
                        },
                    ),
                    75: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    76: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    77: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 4),
                                ("icon", 75),
                                ("document", 76),
                                ("video", 76),
                                ("url", 27),
                                ("text_only", 77),
                            ]
                        ],
                        {},
                    ),
                    79: ("wagtail.blocks.ListBlock", (78,), {"label": "Add Entry"}),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 74), ("links", 79)]],
                        {"label": "List of Links"},
                    ),
                    81: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("filing", "Filing"),
                                ("deadlines", "Deadlines"),
                                ("representation", "Representation"),
                                ("forms-documents", "Forms & Documents"),
                                ("trial-process", "Trial Process"),
                                ("fees-costs", "Fees & Costs"),
                                ("after-decision", "After Decision"),
                            ],
                            "label": "FilterTag",
                        },
                    ),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("question", 27),
                                ("answer", 11),
                                ("anchortag", 4),
                                ("filtertag", 81),
                            ]
                        ],
                        {},
                    ),
                    83: (
                        "wagtail.blocks.ListBlock",
                        (82,),
                        {
                            "help_text": "Add a question and answer. Link the anchor tag number. Select the FAQ FilterTag type in the dropdown.",
                            "label": "Question and Answer",
                        },
                    ),
                    84: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 4), ("anchortag", 27)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 4), ("url", 27)]],
                        {"label": "Clickable Button"},
                    ),
                    87: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    88: ("wagtail.blocks.ListBlock", (78,), {}),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 87), ("links", 88)]],
                        {"label": "Links"},
                    ),
                    90: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 8),
                                ("h3", 9),
                                ("hr", 84),
                                ("h2WithAnchorTag", 85),
                                ("clickableButton", 86),
                                ("links", 89),
                            ]
                        ],
                        {},
                    ),
                    91: ("wagtail.blocks.ListBlock", (90,), {}),
                    92: ("wagtail.blocks.StructBlock", [[("column", 91)]], {}),
                    93: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use the YouTube embed URL (e.g. https://www.youtube.com/embed/VIDEO_ID), not the watch URL.",
                            "required": True,
                        },
                    ),
                    94: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("below", "Below"), ("right-of", "Right")]},
                    ),
                    95: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 27),
                                ("description", 58),
                                ("video_url", 93),
                                ("text_location", 94),
                            ]
                        ],
                        {},
                    ),
                    96: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ]
                        },
                    ),
                    97: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    98: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    99: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 96),
                                ("title", 26),
                                ("description", 97),
                                ("color", 98),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    100: ("wagtail.blocks.ListBlock", (99,), {"label": "Card Set"}),
                    101: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [(1, 1), (2, 2), (3, 3), (4, 4)],
                            "help_text": "Max number of columns in the grid (1-4)",
                        },
                    ),
                    102: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("full", "Full Width")],
                            "help_text": "Maximum width of the grid",
                        },
                    ),
                    103: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("styled", "Styled"), ("unstyled", "Unstyled")],
                            "help_text": "Style of the grid",
                        },
                    ),
                    104: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional header for this grid cell",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    105: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("#f1f9fc", "Default"), ("#DEEAF0", "Blue-Gray")]},
                    ),
                    106: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional caption for this grid cell (links allowed)",
                            "required": False,
                        },
                    ),
                    107: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Make the caption text italic",
                            "required": False,
                        },
                    ),
                    108: (
                        "wagtail.blocks.StreamBlock",
                        [[("prose", 11), ("callout", 49)]],
                        {
                            "help_text": "Add text or special elements to the cell body",
                            "required": True,
                        },
                    ),
                    109: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 104),
                                ("header_color", 105),
                                ("caption", 106),
                                ("italic_caption", 107),
                                ("body", 108),
                            ]
                        ],
                        {},
                    ),
                    110: (
                        "wagtail.blocks.ListBlock",
                        (109,),
                        {
                            "help_text": "Add cells to the grid. Cells will fill row-by-row based on the number of columns selected."
                        },
                    ),
                    111: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("columns", 101),
                                ("width", 102),
                                ("gridStyle", 103),
                                ("cells", 110),
                            ]
                        ],
                        {},
                    ),
                    112: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the beginning of the timeline.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    113: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the beginning of the phase.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    114: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the end of the phase.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    115: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 113), ("date_range", 114)]],
                        {},
                    ),
                    116: (
                        "wagtail.blocks.ListBlock",
                        (115,),
                        {
                            "blank": True,
                            "help_text": "Phases to be displayed in the timeline.",
                        },
                    ),
                    117: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 112), ("phases", 116)]],
                        {},
                    ),
                    118: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Card Icon", "required": True},
                    ),
                    119: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("right", "Right"),
                                ("bottom", "Bottom"),
                                ("left", "Left"),
                            ],
                            "help_text": "Icon placement, e.g. Top, Right, Bottom, Left. Default is Top.",
                            "required": False,
                        },
                    ),
                    120: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Displays the card title", "required": True},
                    ),
                    121: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "required": True},
                    ),
                    122: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "If checked, hover treatment is enabled for ALL tiles in this set.",
                            "required": False,
                        },
                    ),
                    123: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "desktop_top_mobile_left",
                                    "Desktop-Top / Mobile-Left",
                                ),
                                (
                                    "desktop_bottom_mobile_right",
                                    "Desktop-Bottom / Mobile-Right",
                                ),
                            ],
                            "help_text": "Applies to ALL tiles in this set (keeps icon placement uniform).",
                        },
                    ),
                    124: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Card header (H2)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    125: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic"],
                            "help_text": "Optional body text",
                            "required": False,
                        },
                    ),
                    126: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Select an SVG file."},
                    ),
                    127: (
                        "wagtail.blocks.StructBlock",
                        [[("svg_file", 126)]],
                        {"required": True},
                    ),
                    128: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center"),
                                ("left", "Left"),
                                ("right", "Right"),
                            ],
                            "help_text": "Desktop text alignment (tablet/mobile will be left-aligned per design).",
                        },
                    ),
                    129: ("wagtail.blocks.PageChooserBlock", (), {}),
                    130: ("wagtail.blocks.URLBlock", (), {}),
                    131: (
                        "wagtail.blocks.StreamBlock",
                        [[("related_page", 129), ("external_url", 130)]],
                        {
                            "help_text": "Choose where this tile should link.",
                            "max_num": 1,
                            "min_num": 1,
                            "required": False,
                        },
                    ),
                    132: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 124),
                                ("description", 125),
                                ("icon", 127),
                                ("content_alignment", 128),
                                ("link", 131),
                            ]
                        ],
                        {},
                    ),
                    133: (
                        "wagtail.blocks.ListBlock",
                        (132,),
                        {
                            "help_text": "Add, reorder, duplicate, or remove tiles. Responsive grid: 3 desktop / 2 tablet / 1 mobile.",
                            "required": False,
                        },
                    ),
                    134: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles_hover_enabled", 122),
                                ("icon_position", 123),
                                ("tiles", 133),
                            ]
                        ],
                        {},
                    ),
                    135: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("icon_header", 3),
                                ("heading", 7),
                                ("h2", 8),
                                ("h3", 9),
                                ("h4", 10),
                                ("paragraph", 11),
                                ("indented_paragraph", 12),
                                ("snippet", 13),
                                ("button", 23),
                                ("hr", 24),
                                ("iframe", 28),
                                ("alert", 30),
                                ("image", 33),
                                ("photo_dedication", 39),
                                ("table", 40),
                                ("unstyled_table", 40),
                                ("enhanced_table", 56),
                                ("list", 73),
                                ("links", 80),
                                ("questionanswers", 83),
                                ("columns", 92),
                                ("embedded_video", 95),
                                ("card", 100),
                                ("accordion", 53),
                                ("callout", 49),
                                ("grid", 111),
                                ("summary_timeline", 117),
                                ("quick_access_tiles", 134),
                            ]
                        ],
                        {"required": False},
                    ),
                    136: (
                        "wagtail.blocks.StructBlock",
                        [[("breadcrumb_title", 121), ("body", 135)]],
                        {},
                    ),
                    137: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("anchor_page", 136),
                                ("internal_page", 129),
                                ("external_url", 130),
                            ]
                        ],
                        {"max_num": 1, "min_num": 1},
                    ),
                    138: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect",
                            "required": False,
                        },
                    ),
                    139: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 118),
                                ("icon_direction", 119),
                                ("card_header", 120),
                                ("link", 137),
                                ("card_hover", 138),
                            ]
                        ],
                        {},
                    ),
                    140: (
                        "wagtail.blocks.ListBlock",
                        (139,),
                        {
                            "help_text": "Add up to 4 card tiles. They will display responsively based on screen size.",
                            "max_num": 4,
                            "min_num": 1,
                        },
                    ),
                    141: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("icon_header", 3),
                                ("heading", 7),
                                ("h2", 8),
                                ("h3", 9),
                                ("h4", 10),
                                ("paragraph", 11),
                                ("indented_paragraph", 12),
                                ("snippet", 13),
                                ("button", 23),
                                ("hr", 24),
                                ("iframe", 28),
                                ("alert", 30),
                                ("image", 33),
                                ("photo_dedication", 39),
                                ("table", 40),
                                ("unstyled_table", 40),
                                ("enhanced_table", 56),
                                ("list", 73),
                                ("links", 80),
                                ("questionanswers", 83),
                                ("columns", 92),
                                ("embedded_video", 95),
                                ("card", 100),
                                ("accordion", 53),
                                ("callout", 49),
                                ("grid", 111),
                                ("summary_timeline", 117),
                            ]
                        ],
                        {
                            "help_text": "Default content to display when no card is selected",
                            "required": False,
                        },
                    ),
                    142: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Display a back button when a card tile is selected (e.g. p/a, p/b). Hidden on the default view showing all card tiles. If checked, Back Button Text is required.",
                            "required": False,
                        },
                    ),
                    143: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text shown on the back button. Required if 'Show back button' is checked.",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    144: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles", 140),
                                ("default_content", 141),
                                ("show_back_button", 142),
                                ("back_button_text", 143),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
