# Generated by Django 5.2.15 on 2026-09-04 12:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0140_alter_enhancedstandardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("icon_header", 2),
                    ("heading", 6),
                    ("h2", 7),
                    ("h3", 8),
                    ("h4", 9),
                    ("paragraph", 10),
                    ("indented_paragraph", 11),
                    ("snippet", 12),
                    ("button", 22),
                    ("hr", 23),
                    ("iframe", 27),
                    ("alert", 29),
                    ("image", 32),
                    ("photo_dedication", 38),
                    ("table", 39),
                    ("unstyled_table", 39),
                    ("enhanced_table", 55),
                    ("list", 72),
                    ("links", 79),
                    ("questionanswers", 82),
                    ("columns", 91),
                    ("embedded_video", 94),
                    ("card", 99),
                    ("accordion", 52),
                    ("callout", 48),
                    ("grid", 110),
                    ("summary_timeline", 116),
                    ("card_tiles", 143),
                    ("quick_access_tiles", 133),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "label": "Icon",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Header Text", "required": True},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("icon", 0), ("text", 1)]], {}),
                    3: ("wagtail.blocks.CharBlock", (), {}),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("level", 4), ("id", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    8: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    9: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    10: ("wagtail.blocks.RichTextBlock", (), {}),
                    11: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Paragraph with left indentation for alignment with list items",
                            "label": "Indented Paragraph",
                        },
                    ),
                    12: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    13: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Optional: Button icon", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("before", "Before Text"),
                                ("after", "After Text"),
                            ],
                            "help_text": "Choose the location of the icon relative to the text, if icon is selected.",
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    16: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to"},
                    ),
                    17: (
                        "home.blocks.PDFDocumentChooserBlock",
                        (),
                        {"help_text": "Select a PDF to link to"},
                    ),
                    18: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Enter an external URL"},
                    ),
                    19: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 16),
                                ("internal_pdf", 17),
                                ("external_url", 18),
                            ]
                        ],
                        {
                            "help_text": "Select exactly one: Internal Page, External URL, or PDF.",
                            "label": "URL",
                            "max_num": 1,
                            "min_num": 1,
                        },
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("inverted-primary", "Inverted Primary"),
                            ],
                            "help_text": "Choose the button style",
                        },
                    ),
                    21: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect on button",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 13),
                                ("icon_location", 14),
                                ("text", 15),
                                ("url", 19),
                                ("style", 20),
                                ("button_hover", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    24: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    25: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    26: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("src", 24),
                                ("width", 25),
                                ("height", 25),
                                ("class", 26),
                                ("loading", 26),
                                ("data_delay", 26),
                                ("name", 26),
                                ("title", 26),
                            ]
                        ],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success")]},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("alert_type", 28), ("content", 10)]],
                        {},
                    ),
                    30: ("wagtail.images.blocks.ImageBlock", [], {}),
                    31: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 16),
                                ("internal_pdf", 17),
                                ("external_url", 18),
                            ]
                        ],
                        {
                            "help_text": "Optional: add a link to make the image clickable.",
                            "max_num": 1,
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 30), ("link", 31)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Before"), ("right", "After")],
                            "help_text": "Place the image before (left on desktop) or after (right on desktop) the text.",
                        },
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional heading displayed above the photo and text.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Upload an image to display with this dedication",
                            "required": True,
                        },
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Describe the image for a visually impaired person.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    37: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image_position", 33),
                                ("title", 34),
                                ("photo", 35),
                                ("alt_text", 36),
                                ("paragraph_text", 37),
                                ("link", 31),
                            ]
                        ],
                        {},
                    ),
                    39: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 10)]],
                        {},
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title displayed above the table (rendered as H2).",
                            "label": "Header",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "A caption displayed above or below the table depending on Caption Location.",
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("top", "Top"), ("bottom", "Bottom")]},
                    ),
                    43: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("styled", "Styled Table"),
                                ("borderlessUnstyled", "Borderless Unstyled Table"),
                                ("unstyled", "Unstyled Table"),
                            ]
                        },
                    ),
                    44: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to set table layout to fixed width.",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of this special element",
                            "required": True,
                        },
                    ),
                    46: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "The paragraph content", "required": True},
                    ),
                    47: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("success", "Success"),
                                ("error", "Error"),
                                ("emergency", "Emergency"),
                            ]
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 45), ("text", 46), ("callout_type", 47)]],
                        {},
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title user will see before opening",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    50: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 6), ("prose", 10), ("callout", 48)]],
                        {
                            "help_text": "Add text or special elements to the body",
                            "required": True,
                        },
                    ),
                    51: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to have the accordion open by default when the page loads.",
                            "required": False,
                        },
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 49), ("description", 50), ("default_to_open", 51)]],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 10),
                                ("callout", 48),
                                ("accordion", 52),
                                ("button", 22),
                            ]
                        ],
                        {"required": False},
                    ),
                    54: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("components", 53)]],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 40),
                                ("caption", 41),
                                ("caption_location", 42),
                                ("style", 43),
                                ("fixed", 44),
                                ("table", 54),
                            ]
                        ],
                        {},
                    ),
                    56: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                                ("checkbox", "Checkbox List"),
                                ("checkbox_with_subtext", "Checkbox with Subtext"),
                            ],
                            "required": False,
                        },
                    ),
                    57: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 57), ("subtext", 57), ("image", 30)]],
                        {"required": False},
                    ),
                    59: ("wagtail.blocks.ListBlock", (58,), {"default": []}),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 56), ("items", 59)]],
                        {"required": False},
                    ),
                    61: ("wagtail.blocks.ListBlock", (60,), {"default": []}),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 57),
                                ("subtext", 57),
                                ("image", 30),
                                ("nested_list", 61),
                            ]
                        ],
                        {"required": False},
                    ),
                    63: ("wagtail.blocks.ListBlock", (62,), {"default": []}),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 56), ("items", 63)]],
                        {"required": False},
                    ),
                    65: ("wagtail.blocks.ListBlock", (64,), {"default": []}),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 57),
                                ("subtext", 57),
                                ("image", 30),
                                ("nested_list", 65),
                            ]
                        ],
                        {"required": False},
                    ),
                    67: ("wagtail.blocks.ListBlock", (66,), {"default": []}),
                    68: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 56), ("items", 67)]],
                        {"required": False},
                    ),
                    69: ("wagtail.blocks.ListBlock", (68,), {"default": []}),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 57),
                                ("subtext", 57),
                                ("image", 30),
                                ("nested_list", 69),
                            ]
                        ],
                        {"required": False},
                    ),
                    71: ("wagtail.blocks.ListBlock", (70,), {"default": []}),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 56), ("items", 71)]],
                        {"required": False},
                    ),
                    73: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ],
                            "label": "List style",
                        },
                    ),
                    74: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ],
                            "required": False,
                        },
                    ),
                    75: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    76: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    77: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("icon", 74),
                                ("document", 75),
                                ("video", 75),
                                ("url", 26),
                                ("text_only", 76),
                            ]
                        ],
                        {},
                    ),
                    78: ("wagtail.blocks.ListBlock", (77,), {"label": "Add Entry"}),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 73), ("links", 78)]],
                        {"label": "List of Links"},
                    ),
                    80: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("filing", "Filing"),
                                ("deadlines", "Deadlines"),
                                ("representation", "Representation"),
                                ("forms-documents", "Forms & Documents"),
                                ("trial-process", "Trial Process"),
                                ("fees-costs", "Fees & Costs"),
                                ("after-decision", "After Decision"),
                            ],
                            "label": "FilterTag",
                        },
                    ),
                    81: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("question", 26),
                                ("answer", 10),
                                ("anchortag", 3),
                                ("filtertag", 80),
                            ]
                        ],
                        {},
                    ),
                    82: (
                        "wagtail.blocks.ListBlock",
                        (81,),
                        {
                            "help_text": "Add a question and answer. Link the anchor tag number. Select the FAQ FilterTag type in the dropdown.",
                            "label": "Question and Answer",
                        },
                    ),
                    83: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    84: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("anchortag", 26)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("url", 26)]],
                        {"label": "Clickable Button"},
                    ),
                    86: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    87: ("wagtail.blocks.ListBlock", (77,), {}),
                    88: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 86), ("links", 87)]],
                        {"label": "Links"},
                    ),
                    89: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 7),
                                ("h3", 8),
                                ("hr", 83),
                                ("h2WithAnchorTag", 84),
                                ("clickableButton", 85),
                                ("links", 88),
                            ]
                        ],
                        {},
                    ),
                    90: ("wagtail.blocks.ListBlock", (89,), {}),
                    91: ("wagtail.blocks.StructBlock", [[("column", 90)]], {}),
                    92: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use the YouTube embed URL (e.g. https://www.youtube.com/embed/VIDEO_ID), not the watch URL.",
                            "required": True,
                        },
                    ),
                    93: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("below", "Below"), ("right-of", "Right")]},
                    ),
                    94: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 26),
                                ("description", 57),
                                ("video_url", 92),
                                ("text_location", 93),
                            ]
                        ],
                        {},
                    ),
                    95: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("fa-solid fa-book", "Book"),
                                ("fa-solid fa-building-columns", "Building Bank"),
                                ("fa-solid fa-calendar", "Calendar Month"),
                                ("fa-solid fa-chevron-right", "Chevron Right"),
                                ("fa-solid fa-file", "File"),
                                ("fa-solid fa-gavel", "Hammer"),
                                ("fa-solid fa-circle-info", "Info"),
                                ("fa-solid fa-check", "Check"),
                                ("fa-solid fa-link", "Link"),
                                ("fa-solid fa-exclamation", "Exclamation Mark"),
                                ("fa-solid fa-file-pdf", "Pdf"),
                                ("fa-solid fa-scale-balanced", "Scale"),
                                ("fa-solid fa-user", "User"),
                                ("fa-solid fa-video", "Video"),
                                ("fa-solid fa-gear", "Settings"),
                                ("fa-solid fa-briefcase", "Briefcase"),
                                ("fa-solid fa-magnifying-glass", "Search"),
                            ]
                        },
                    ),
                    96: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    97: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("green", "Green"), ("yellow", "Yellow")]},
                    ),
                    98: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 95),
                                ("title", 25),
                                ("description", 96),
                                ("color", 97),
                            ]
                        ],
                        {"label": "Card"},
                    ),
                    99: ("wagtail.blocks.ListBlock", (98,), {"label": "Card Set"}),
                    100: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [(1, 1), (2, 2), (3, 3), (4, 4)],
                            "help_text": "Max number of columns in the grid (1-4)",
                        },
                    ),
                    101: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("full", "Full Width")],
                            "help_text": "Maximum width of the grid",
                        },
                    ),
                    102: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("styled", "Styled"), ("unstyled", "Unstyled")],
                            "help_text": "Style of the grid",
                        },
                    ),
                    103: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional header for this grid cell",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    104: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("#f1f9fc", "Default"), ("#DEEAF0", "Blue-Gray")]},
                    ),
                    105: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional caption for this grid cell (links allowed)",
                            "required": False,
                        },
                    ),
                    106: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Make the caption text italic",
                            "required": False,
                        },
                    ),
                    107: (
                        "wagtail.blocks.StreamBlock",
                        [[("prose", 10), ("callout", 48)]],
                        {
                            "help_text": "Add text or special elements to the cell body",
                            "required": True,
                        },
                    ),
                    108: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 103),
                                ("header_color", 104),
                                ("caption", 105),
                                ("italic_caption", 106),
                                ("body", 107),
                            ]
                        ],
                        {},
                    ),
                    109: (
                        "wagtail.blocks.ListBlock",
                        (108,),
                        {
                            "help_text": "Add cells to the grid. Cells will fill row-by-row based on the number of columns selected."
                        },
                    ),
                    110: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("columns", 100),
                                ("width", 101),
                                ("gridStyle", 102),
                                ("cells", 109),
                            ]
                        ],
                        {},
                    ),
                    111: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the beginning of the timeline.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    112: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the beginning of the phase.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    113: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the end of the phase.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    114: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 112), ("date_range", 113)]],
                        {},
                    ),
                    115: (
                        "wagtail.blocks.ListBlock",
                        (114,),
                        {
                            "blank": True,
                            "help_text": "Phases to be displayed in the timeline.",
                        },
                    ),
                    116: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 111), ("phases", 115)]],
                        {},
                    ),
                    117: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Card Icon", "required": True},
                    ),
                    118: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("right", "Right"),
                                ("bottom", "Bottom"),
                                ("left", "Left"),
                            ],
                            "help_text": "Icon placement, e.g. Top, Right, Bottom, Left. Default is Top.",
                            "required": False,
                        },
                    ),
                    119: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Displays the card title", "required": True},
                    ),
                    120: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "required": True},
                    ),
                    121: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "If checked, hover treatment is enabled for ALL tiles in this set.",
                            "required": False,
                        },
                    ),
                    122: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "desktop_top_mobile_left",
                                    "Desktop-Top / Mobile-Left",
                                ),
                                (
                                    "desktop_bottom_mobile_right",
                                    "Desktop-Bottom / Mobile-Right",
                                ),
                            ],
                            "help_text": "Applies to ALL tiles in this set (keeps icon placement uniform).",
                        },
                    ),
                    123: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Card header (H2)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    124: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic"],
                            "help_text": "Optional body text",
                            "required": False,
                        },
                    ),
                    125: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Select an SVG file."},
                    ),
                    126: (
                        "wagtail.blocks.StructBlock",
                        [[("svg_file", 125)]],
                        {"required": True},
                    ),
                    127: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center"),
                                ("left", "Left"),
                                ("right", "Right"),
                            ],
                            "help_text": "Desktop text alignment (tablet/mobile will be left-aligned per design).",
                        },
                    ),
                    128: ("wagtail.blocks.PageChooserBlock", (), {}),
                    129: ("wagtail.blocks.URLBlock", (), {}),
                    130: (
                        "wagtail.blocks.StreamBlock",
                        [[("related_page", 128), ("external_url", 129)]],
                        {
                            "help_text": "Choose where this tile should link.",
                            "max_num": 1,
                            "min_num": 1,
                            "required": False,
                        },
                    ),
                    131: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 123),
                                ("description", 124),
                                ("icon", 126),
                                ("content_alignment", 127),
                                ("link", 130),
                            ]
                        ],
                        {},
                    ),
                    132: (
                        "wagtail.blocks.ListBlock",
                        (131,),
                        {
                            "help_text": "Add, reorder, duplicate, or remove tiles. Responsive grid: 3 desktop / 2 tablet / 1 mobile.",
                            "required": False,
                        },
                    ),
                    133: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles_hover_enabled", 121),
                                ("icon_position", 122),
                                ("tiles", 132),
                            ]
                        ],
                        {},
                    ),
                    134: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("icon_header", 2),
                                ("heading", 6),
                                ("h2", 7),
                                ("h3", 8),
                                ("h4", 9),
                                ("paragraph", 10),
                                ("indented_paragraph", 11),
                                ("snippet", 12),
                                ("button", 22),
                                ("hr", 23),
                                ("iframe", 27),
                                ("alert", 29),
                                ("image", 32),
                                ("photo_dedication", 38),
                                ("table", 39),
                                ("unstyled_table", 39),
                                ("enhanced_table", 55),
                                ("list", 72),
                                ("links", 79),
                                ("questionanswers", 82),
                                ("columns", 91),
                                ("embedded_video", 94),
                                ("card", 99),
                                ("accordion", 52),
                                ("callout", 48),
                                ("grid", 110),
                                ("summary_timeline", 116),
                                ("quick_access_tiles", 133),
                            ]
                        ],
                        {"required": False},
                    ),
                    135: (
                        "wagtail.blocks.StructBlock",
                        [[("breadcrumb_title", 120), ("body", 134)]],
                        {},
                    ),
                    136: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("anchor_page", 135),
                                ("internal_page", 128),
                                ("external_url", 129),
                            ]
                        ],
                        {"max_num": 1, "min_num": 1},
                    ),
                    137: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect",
                            "required": False,
                        },
                    ),
                    138: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 117),
                                ("icon_direction", 118),
                                ("card_header", 119),
                                ("link", 136),
                                ("card_hover", 137),
                            ]
                        ],
                        {},
                    ),
                    139: (
                        "wagtail.blocks.ListBlock",
                        (138,),
                        {
                            "help_text": "Add up to 4 card tiles. They will display responsively based on screen size.",
                            "max_num": 4,
                            "min_num": 1,
                        },
                    ),
                    140: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("icon_header", 2),
                                ("heading", 6),
                                ("h2", 7),
                                ("h3", 8),
                                ("h4", 9),
                                ("paragraph", 10),
                                ("indented_paragraph", 11),
                                ("snippet", 12),
                                ("button", 22),
                                ("hr", 23),
                                ("iframe", 27),
                                ("alert", 29),
                                ("image", 32),
                                ("photo_dedication", 38),
                                ("table", 39),
                                ("unstyled_table", 39),
                                ("enhanced_table", 55),
                                ("list", 72),
                                ("links", 79),
                                ("questionanswers", 82),
                                ("columns", 91),
                                ("embedded_video", 94),
                                ("card", 99),
                                ("accordion", 52),
                                ("callout", 48),
                                ("grid", 110),
                                ("summary_timeline", 116),
                            ]
                        ],
                        {
                            "help_text": "Default content to display when no card is selected",
                            "required": False,
                        },
                    ),
                    141: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Display a back button when a card tile is selected (e.g. p/a, p/b). Hidden on the default view showing all card tiles. If checked, Back Button Text is required.",
                            "required": False,
                        },
                    ),
                    142: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text shown on the back button. Required if 'Show back button' is checked.",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    143: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles", 139),
                                ("default_content", 140),
                                ("show_back_button", 141),
                                ("back_button_text", 142),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
