# Generated by Django 5.2.15 on 2026-09-15 23:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0138_alter_enhancedstandardpage_body"),
        ("home", "0139_alter_petitionerexperiencepage_introductory_text_pe"),
        ("home", "0141_alter_enhancedstandardpage_body_pe"),
        ("home", "0142_alter_enhancedstandardpage_body"),
    ]

    operations = []
