# Generated by Django 5.2.13 on 2026-09-15 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0141_alter_enhancedstandardpage_body_pe"),
        ("home", "0142_split_oversized_card_sets_pe"),
    ]

    operations = []
