# Generated by Django 5.2.17 on 2026-09-16 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0139_alter_enhancedstandardpage_body"),
        ("home", "0142_alter_enhancedstandardpage_body_pe"),
    ]

    operations = []
