# Generated by Django 5.2.13 on 2026-09-16 00:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0142_alter_enhancedstandardpage_body_pe"),
        ("home", "0145_alter_enhancedstandardpage_body_pe"),
    ]

    operations = []
