# Generated by Django 5.2.17 on 2026-09-18 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0144_alter_enhancedstandardpage_body"),
        ("home", "0146_strip_phantom_card_button_pe"),
    ]

    operations = []
