# Generated by Django 5.2.17 on 2026-09-18 23:21

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0148_migrate_fa_icon_to_md_icon_pe"),
    ]

    operations = [
        migrations.CreateModel(
            name="SideCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("book_3", "Book"),
                            ("account_balance", "Building Bank"),
                            ("calendar_today", "Calendar Month"),
                            ("chevron_right", "Chevron Right"),
                            ("draft", "File"),
                            ("gavel", "Hammer"),
                            ("info", "Info"),
                            ("check", "Check"),
                            ("link_2", "Link"),
                            ("exclamation", "Exclamation Mark"),
                            ("description", "Pdf"),
                            ("balance", "Scale"),
                            ("person", "User"),
                            ("videocam", "Video"),
                            ("settings", "Settings"),
                            ("work", "Briefcase"),
                            ("search", "Search"),
                            ("signpost", "Signpost"),
                            ("timeline", "Timeline"),
                            ("note_stack", "Notes"),
                            ("article", "Forms"),
                            ("help", "Help"),
                            ("dawson", "Dawson"),
                        ],
                        default="",
                        help_text="Optional icon for this side card.",
                        max_length=200,
                    ),
                ),
                ("header_title", models.CharField(max_length=255)),
                ("introductory_text", wagtail.fields.RichTextField()),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("gray", "Gray"),
                            ("dark-primary", "Dark-Primary"),
                            ("green", "Green"),
                            ("yellow", "Yellow"),
                        ],
                        default="white",
                        max_length=20,
                    ),
                ),
                (
                    "links",
                    wagtail.fields.StreamField(
                        [("button", 9)],
                        blank=True,
                        block_lookup={
                            0: (
                                "home.blocks.SVGDocumentChooserBlock",
                                (),
                                {
                                    "help_text": "Optional: Button icon",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("before", "Before Text"),
                                        ("after", "After Text"),
                                    ],
                                    "help_text": "Choose the location of the icon relative to the text, if icon is selected.",
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Button text",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            3: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"help_text": "Select a page to link to"},
                            ),
                            4: (
                                "home.blocks.PDFDocumentChooserBlock",
                                (),
                                {"help_text": "Select a PDF to link to"},
                            ),
                            5: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"help_text": "Enter an external URL"},
                            ),
                            6: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("internal_page", 3),
                                        ("internal_pdf", 4),
                                        ("external_url", 5),
                                    ]
                                ],
                                {
                                    "help_text": "Select exactly one: Internal Page, External URL, or PDF.",
                                    "label": "URL",
                                    "max_num": 1,
                                    "min_num": 1,
                                },
                            ),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("inverted-primary", "Inverted Primary"),
                                    ],
                                    "help_text": "Choose the button style",
                                },
                            ),
                            8: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Enable hover effect on button",
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 0),
                                        ("icon_location", 1),
                                        ("text", 2),
                                        ("url", 6),
                                        ("style", 7),
                                        ("button_hover", 8),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Informational blocks/buttons for this side card.",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="side_cards",
                        to="home.petitionerexperiencepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
