# Generated by Django 5.2.15 on 2026-09-21 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0148_alter_enhancedstandardpage_body"),
        ("home", "0148_migrate_fa_icon_to_md_icon_pe"),
    ]

    operations = []
