# Generated by Django 5.2.17 on 2026-09-21 02:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0150_sidecard_link_display_style_pe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sidecard",
            name="introductory_text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
