# Generated by Django 5.2.17 on 2026-09-23 17:26

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0150_alter_directoryindex_body_and_more_pe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directoryindex",
            name="body",
            field=wagtail.fields.StreamField(
                [("directory", 18)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {}),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("anchortag", 4)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("url", 4)]],
                        {"label": "Clickable Button"},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("book_3", "Book"),
                                ("account_balance", "Building Bank"),
                                ("calendar_today", "Calendar Month"),
                                ("chevron_right", "Chevron Right"),
                                ("draft", "File"),
                                ("gavel", "Hammer"),
                                ("info", "Info"),
                                ("check", "Check"),
                                ("link_2", "Link"),
                                ("exclamation", "Exclamation Mark"),
                                ("description", "Pdf"),
                                ("balance", "Scale"),
                                ("person", "User"),
                                ("videocam", "Video"),
                                ("settings", "Settings"),
                                ("work", "Briefcase"),
                                ("search", "Search"),
                                ("signpost", "Signpost"),
                                ("timeline", "Timeline"),
                                ("note_stack", "Notes"),
                                ("article", "Forms"),
                                ("help", "Help"),
                                ("dawson", "Dawson"),
                                ("select_check_box", "Select Check Box"),
                                ("outbound", "Outbound"),
                            ],
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    10: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("icon", 8),
                                ("document", 9),
                                ("video", 9),
                                ("url", 4),
                                ("text_only", 10),
                            ]
                        ],
                        {},
                    ),
                    12: ("wagtail.blocks.ListBlock", (11,), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 7), ("links", 12)]],
                        {"label": "Links"},
                    ),
                    14: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (),
                        {
                            "help_text": "Optionally pick a JudgeCollection snippet",
                            "label": "Judge Collection",
                            "required": False,
                            "target_model": "home.JudgeCollection",
                        },
                    ),
                    15: ("wagtail.blocks.RichTextBlock", (), {}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("description", 15), ("phone_number", 3)]],
                        {},
                    ),
                    17: ("wagtail.blocks.ListBlock", (16,), {}),
                    18: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 0),
                                ("h3", 1),
                                ("hr", 2),
                                ("h2WithAnchorTag", 5),
                                ("clickableButton", 6),
                                ("links", 13),
                                ("JudgeCollection", 14),
                                ("DirectoryEntry", 17),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Directory entries or judge profiles",
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("icon_header", 2),
                    ("heading", 6),
                    ("h2", 7),
                    ("h3", 8),
                    ("h4", 9),
                    ("paragraph", 10),
                    ("indented_paragraph", 11),
                    ("snippet", 12),
                    ("button", 22),
                    ("hr", 23),
                    ("iframe", 27),
                    ("alert", 29),
                    ("image", 32),
                    ("photo_dedication", 38),
                    ("table", 39),
                    ("unstyled_table", 39),
                    ("enhanced_table", 55),
                    ("list", 72),
                    ("links", 79),
                    ("questionanswers", 82),
                    ("columns", 91),
                    ("embedded_video", 94),
                    ("card", 105),
                    ("accordion", 52),
                    ("callout", 48),
                    ("grid", 116),
                    ("summary_timeline", 122),
                    ("detailed_timeline", 137),
                    ("hero_section", 142),
                    ("printable_section", 147),
                    ("card_tiles", 174),
                    ("quick_access_tiles", 164),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("book_3", "Book"),
                                ("account_balance", "Building Bank"),
                                ("calendar_today", "Calendar Month"),
                                ("chevron_right", "Chevron Right"),
                                ("draft", "File"),
                                ("gavel", "Hammer"),
                                ("info", "Info"),
                                ("check", "Check"),
                                ("link_2", "Link"),
                                ("exclamation", "Exclamation Mark"),
                                ("description", "Pdf"),
                                ("balance", "Scale"),
                                ("person", "User"),
                                ("videocam", "Video"),
                                ("settings", "Settings"),
                                ("work", "Briefcase"),
                                ("search", "Search"),
                                ("signpost", "Signpost"),
                                ("timeline", "Timeline"),
                                ("note_stack", "Notes"),
                                ("article", "Forms"),
                                ("help", "Help"),
                                ("dawson", "Dawson"),
                                ("select_check_box", "Select Check Box"),
                                ("outbound", "Outbound"),
                            ],
                            "label": "Icon",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Header Text", "required": True},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("icon", 0), ("text", 1)]], {}),
                    3: ("wagtail.blocks.CharBlock", (), {}),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("level", 4), ("id", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    8: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    9: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    10: ("wagtail.blocks.RichTextBlock", (), {}),
                    11: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Paragraph with left indentation for alignment with list items",
                            "label": "Indented Paragraph",
                        },
                    ),
                    12: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    13: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Optional: Button icon", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("before", "Before Text"),
                                ("after", "After Text"),
                            ],
                            "help_text": "Choose the location of the icon relative to the text, if icon is selected.",
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    16: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to"},
                    ),
                    17: (
                        "home.blocks.PDFDocumentChooserBlock",
                        (),
                        {"help_text": "Select a PDF to link to"},
                    ),
                    18: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Enter an external URL"},
                    ),
                    19: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 16),
                                ("internal_pdf", 17),
                                ("external_url", 18),
                            ]
                        ],
                        {
                            "help_text": "Select exactly one: Internal Page, External URL, or PDF.",
                            "label": "URL",
                            "max_num": 1,
                            "min_num": 1,
                        },
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("inverted-primary", "Inverted Primary"),
                            ],
                            "help_text": "Choose the button style",
                        },
                    ),
                    21: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect on button",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 13),
                                ("icon_location", 14),
                                ("text", 15),
                                ("url", 19),
                                ("style", 20),
                                ("button_hover", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    24: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    25: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    26: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("src", 24),
                                ("width", 25),
                                ("height", 25),
                                ("class", 26),
                                ("loading", 26),
                                ("data_delay", 26),
                                ("name", 26),
                                ("title", 26),
                            ]
                        ],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success")]},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("alert_type", 28), ("content", 10)]],
                        {},
                    ),
                    30: ("wagtail.images.blocks.ImageBlock", [], {}),
                    31: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 16),
                                ("internal_pdf", 17),
                                ("external_url", 18),
                            ]
                        ],
                        {
                            "help_text": "Optional: add a link to make the image clickable.",
                            "max_num": 1,
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 30), ("link", 31)]],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Before"), ("right", "After")],
                            "help_text": "Place the image before (left on desktop) or after (right on desktop) the text.",
                        },
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional heading displayed above the photo and text.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Upload an image to display with this dedication",
                            "required": True,
                        },
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Describe the image for a visually impaired person.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    37: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image_position", 33),
                                ("title", 34),
                                ("photo", 35),
                                ("alt_text", 36),
                                ("paragraph_text", 37),
                                ("link", 31),
                            ]
                        ],
                        {},
                    ),
                    39: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 10)]],
                        {},
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title displayed above the table (rendered as H2).",
                            "label": "Header",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "A caption displayed above or below the table depending on Caption Location.",
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("top", "Top"), ("bottom", "Bottom")]},
                    ),
                    43: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("styled", "Styled Table"),
                                ("borderlessUnstyled", "Borderless Unstyled Table"),
                                ("unstyled", "Unstyled Table"),
                            ]
                        },
                    ),
                    44: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to set table layout to fixed width.",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of this special element",
                            "required": True,
                        },
                    ),
                    46: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "The paragraph content", "required": True},
                    ),
                    47: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("success", "Success"),
                                ("error", "Error"),
                                ("emergency", "Emergency"),
                            ]
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 45), ("text", 46), ("callout_type", 47)]],
                        {},
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title user will see before opening",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    50: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 6), ("prose", 10), ("callout", 48)]],
                        {
                            "help_text": "Add text or special elements to the body",
                            "required": True,
                        },
                    ),
                    51: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to have the accordion open by default when the page loads.",
                            "required": False,
                        },
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 49), ("description", 50), ("default_to_open", 51)]],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 10),
                                ("callout", 48),
                                ("accordion", 52),
                                ("button", 22),
                            ]
                        ],
                        {"required": False},
                    ),
                    54: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("components", 53)]],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 40),
                                ("caption", 41),
                                ("caption_location", 42),
                                ("style", 43),
                                ("fixed", 44),
                                ("table", 54),
                            ]
                        ],
                        {},
                    ),
                    56: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                                ("checkbox", "Checkbox List"),
                                ("checkbox_with_subtext", "Checkbox with Subtext"),
                            ],
                            "required": False,
                        },
                    ),
                    57: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 57), ("subtext", 57), ("image", 30)]],
                        {"required": False},
                    ),
                    59: ("wagtail.blocks.ListBlock", (58,), {"default": []}),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 56), ("items", 59)]],
                        {"required": False},
                    ),
                    61: ("wagtail.blocks.ListBlock", (60,), {"default": []}),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 57),
                                ("subtext", 57),
                                ("image", 30),
                                ("nested_list", 61),
                            ]
                        ],
                        {"required": False},
                    ),
                    63: ("wagtail.blocks.ListBlock", (62,), {"default": []}),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 56), ("items", 63)]],
                        {"required": False},
                    ),
                    65: ("wagtail.blocks.ListBlock", (64,), {"default": []}),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 57),
                                ("subtext", 57),
                                ("image", 30),
                                ("nested_list", 65),
                            ]
                        ],
                        {"required": False},
                    ),
                    67: ("wagtail.blocks.ListBlock", (66,), {"default": []}),
                    68: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 56), ("items", 67)]],
                        {"required": False},
                    ),
                    69: ("wagtail.blocks.ListBlock", (68,), {"default": []}),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 57),
                                ("subtext", 57),
                                ("image", 30),
                                ("nested_list", 69),
                            ]
                        ],
                        {"required": False},
                    ),
                    71: ("wagtail.blocks.ListBlock", (70,), {"default": []}),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 56), ("items", 71)]],
                        {"required": False},
                    ),
                    73: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ],
                            "label": "List style",
                        },
                    ),
                    74: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("book_3", "Book"),
                                ("account_balance", "Building Bank"),
                                ("calendar_today", "Calendar Month"),
                                ("chevron_right", "Chevron Right"),
                                ("draft", "File"),
                                ("gavel", "Hammer"),
                                ("info", "Info"),
                                ("check", "Check"),
                                ("link_2", "Link"),
                                ("exclamation", "Exclamation Mark"),
                                ("description", "Pdf"),
                                ("balance", "Scale"),
                                ("person", "User"),
                                ("videocam", "Video"),
                                ("settings", "Settings"),
                                ("work", "Briefcase"),
                                ("search", "Search"),
                                ("signpost", "Signpost"),
                                ("timeline", "Timeline"),
                                ("note_stack", "Notes"),
                                ("article", "Forms"),
                                ("help", "Help"),
                                ("dawson", "Dawson"),
                                ("select_check_box", "Select Check Box"),
                                ("outbound", "Outbound"),
                            ],
                            "required": False,
                        },
                    ),
                    75: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    76: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    77: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("icon", 74),
                                ("document", 75),
                                ("video", 75),
                                ("url", 26),
                                ("text_only", 76),
                            ]
                        ],
                        {},
                    ),
                    78: ("wagtail.blocks.ListBlock", (77,), {"label": "Add Entry"}),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 73), ("links", 78)]],
                        {"label": "List of Links"},
                    ),
                    80: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("filing", "Filing"),
                                ("deadlines", "Deadlines"),
                                ("representation", "Representation"),
                                ("forms-documents", "Forms & Documents"),
                                ("trial-process", "Trial Process"),
                                ("fees-costs", "Fees & Costs"),
                                ("after-decision", "After Decision"),
                            ],
                            "label": "FilterTag",
                        },
                    ),
                    81: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("question", 26),
                                ("answer", 10),
                                ("anchortag", 3),
                                ("filtertag", 80),
                            ]
                        ],
                        {},
                    ),
                    82: (
                        "wagtail.blocks.ListBlock",
                        (81,),
                        {
                            "help_text": "Add a question and answer. Link the anchor tag number. Select the FAQ FilterTag type in the dropdown.",
                            "label": "Question and Answer",
                        },
                    ),
                    83: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    84: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("anchortag", 26)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("url", 26)]],
                        {"label": "Clickable Button"},
                    ),
                    86: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    87: ("wagtail.blocks.ListBlock", (77,), {}),
                    88: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 86), ("links", 87)]],
                        {"label": "Links"},
                    ),
                    89: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 7),
                                ("h3", 8),
                                ("hr", 83),
                                ("h2WithAnchorTag", 84),
                                ("clickableButton", 85),
                                ("links", 88),
                            ]
                        ],
                        {},
                    ),
                    90: ("wagtail.blocks.ListBlock", (89,), {}),
                    91: ("wagtail.blocks.StructBlock", [[("column", 90)]], {}),
                    92: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use the YouTube embed URL (e.g. https://www.youtube.com/embed/VIDEO_ID), not the watch URL.",
                            "required": True,
                        },
                    ),
                    93: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("below", "Below"), ("right-of", "Right")]},
                    ),
                    94: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 26),
                                ("description", 57),
                                ("video_url", 92),
                                ("text_location", 93),
                            ]
                        ],
                        {},
                    ),
                    95: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("gray", "Gray"),
                                ("dark-primary", "Dark-Primary"),
                                ("green", "Green"),
                                ("yellow", "Yellow"),
                            ],
                            "label": "Card Color",
                        },
                    ),
                    96: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("1", "One"),
                                ("2", "Two"),
                                ("3", "Three"),
                                ("check", "Check"),
                                ("exclamation", "Exclamation"),
                            ],
                            "help_text": "Optional numbered or status icon displayed on the card.",
                            "label": "Numbered Icon",
                            "required": False,
                        },
                    ),
                    97: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "help_text": "Only applies when Numbered Icon is not 'None'.",
                            "label": "Numbered Icon Alignment",
                        },
                    ),
                    98: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {
                            "help_text": "Optional: any SVG uploaded as a Wagtail Document.",
                            "label": "Title Icon",
                            "required": False,
                        },
                    ),
                    99: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank if the Title Icon is purely decorative. Fill in if it conveys meaning not already in the Card Title (e.g. distinguishing icons for different options).",
                            "label": "Title Icon Alt Text",
                            "required": False,
                        },
                    ),
                    100: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Displays the card sub title",
                            "label": "Card Sub-title",
                            "required": False,
                        },
                    ),
                    101: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Displays the card title",
                            "label": "Card Title",
                            "required": False,
                        },
                    ),
                    102: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Displays the text that goes under the header",
                            "label": "Body Text",
                            "required": False,
                        },
                    ),
                    103: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {
                            "default": [],
                            "label": "Buttons",
                            "max_num": 1,
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    104: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("color", 95),
                                ("numbered_icon", 96),
                                ("numbered_icon_alignment", 97),
                                ("title_icon", 98),
                                ("title_icon_alt_text", 99),
                                ("subtitle", 100),
                                ("title", 101),
                                ("description", 102),
                                ("buttons", 103),
                            ]
                        ],
                        {"label": "Card", "label_format": "Card: {title}"},
                    ),
                    105: (
                        "wagtail.blocks.ListBlock",
                        (104,),
                        {
                            "help_text": "Add up to 3 cards. They display in a single row on desktop, wrap 2-up on tablet, and stack in a single column on mobile.",
                            "label": "Card Set",
                            "max_num": 3,
                        },
                    ),
                    106: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [(1, 1), (2, 2), (3, 3), (4, 4)],
                            "help_text": "Max number of columns in the grid (1-4)",
                        },
                    ),
                    107: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("full", "Full Width")],
                            "help_text": "Maximum width of the grid",
                        },
                    ),
                    108: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("styled", "Styled"), ("unstyled", "Unstyled")],
                            "help_text": "Style of the grid",
                        },
                    ),
                    109: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional header for this grid cell",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    110: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("#f1f9fc", "Default"), ("#DEEAF0", "Blue-Gray")]},
                    ),
                    111: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional caption for this grid cell (links allowed)",
                            "required": False,
                        },
                    ),
                    112: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Make the caption text italic",
                            "required": False,
                        },
                    ),
                    113: (
                        "wagtail.blocks.StreamBlock",
                        [[("prose", 10), ("callout", 48)]],
                        {
                            "help_text": "Add text or special elements to the cell body",
                            "required": True,
                        },
                    ),
                    114: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 109),
                                ("header_color", 110),
                                ("caption", 111),
                                ("italic_caption", 112),
                                ("body", 113),
                            ]
                        ],
                        {},
                    ),
                    115: (
                        "wagtail.blocks.ListBlock",
                        (114,),
                        {
                            "help_text": "Add cells to the grid. Cells will fill row-by-row based on the number of columns selected."
                        },
                    ),
                    116: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("columns", 106),
                                ("width", 107),
                                ("gridStyle", 108),
                                ("cells", 115),
                            ]
                        ],
                        {},
                    ),
                    117: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the beginning of the timeline.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    118: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the beginning of the phase.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    119: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the end of the phase.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    120: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 118), ("date_range", 119)]],
                        {},
                    ),
                    121: (
                        "wagtail.blocks.ListBlock",
                        (120,),
                        {
                            "blank": True,
                            "help_text": "Phases to be displayed in the timeline.",
                        },
                    ),
                    122: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 117), ("phases", 121)]],
                        {},
                    ),
                    123: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the beginning of the detailed timeline.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    124: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Text to be displayed under the detailed timeline's title.",
                            "required": True,
                        },
                    ),
                    125: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the end of the phase.",
                            "label": "Date Range",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    126: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Text to be shown at the top of the phase when it is expanded.",
                            "required": True,
                        },
                    ),
                    127: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    128: (
                        "wagtail.blocks.StructBlock",
                        [[("Text", 127), ("Subtext", 57)]],
                        {"label": "Task Item"},
                    ),
                    129: (
                        "wagtail.blocks.ListBlock",
                        (128,),
                        {
                            "default": [],
                            "help_text": "Tasks to be completed during this phase.",
                            "label": "Your Tasks",
                            "required": False,
                        },
                    ),
                    130: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("outbound", "Action"), ("help", "Question")],
                            "help_text": "Choose the icon to be displayed in front of the text.",
                            "label": "Icon",
                        },
                    ),
                    131: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Helpful Information text",
                            "label": "Information",
                        },
                    ),
                    132: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Helpful Information subtext",
                            "label": "Information Subtext",
                            "required": False,
                        },
                    ),
                    133: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("Icon", 130),
                                ("Information", 131),
                                ("InformationSubtext", 132),
                            ]
                        ],
                        {"label": "Helpful Information Item"},
                    ),
                    134: (
                        "wagtail.blocks.ListBlock",
                        (133,),
                        {
                            "default": [],
                            "help_text": "Helpful information to be displayed at the bottom of the phase when expanded.",
                            "label": "Helpful Information",
                            "required": False,
                        },
                    ),
                    135: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 118),
                                ("date_range", 125),
                                ("instructions", 126),
                                ("your_tasks", 129),
                                ("helpful_information", 134),
                            ]
                        ],
                        {},
                    ),
                    136: (
                        "wagtail.blocks.StreamBlock",
                        [[("phase", 135)]],
                        {
                            "blank": True,
                            "help_text": "Phases to be displayed in the detailed timeline.",
                        },
                    ),
                    137: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 123), ("introduction", 124), ("phases", 136)]],
                        {},
                    ),
                    138: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title displayed at the top of the hero section.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    139: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Introductory text displayed beneath the title in the hero section.",
                            "max_length": 512,
                            "required": True,
                        },
                    ),
                    140: (
                        "wagtail.blocks.StreamBlock",
                        [[("block", 48)]],
                        {
                            "blank": True,
                            "help_text": "Callout block displayed underneath the introductory text in the hero section.",
                            "max_num": 1,
                            "min_num": 0,
                            "required": False,
                            "use_json_field": True,
                        },
                    ),
                    141: (
                        "wagtail.blocks.StreamBlock",
                        [[("button", 22)]],
                        {
                            "blank": True,
                            "help_text": "Buttons to display at the bottom of the hero section.",
                            "max_num": 3,
                            "min_num": 0,
                            "required": False,
                            "use_json_field": True,
                        },
                    ),
                    142: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 138),
                                ("introductory_text", 139),
                                ("callout_block", 140),
                                ("buttons", 141),
                            ]
                        ],
                        {},
                    ),
                    143: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("book_3", "Book"),
                                ("account_balance", "Building Bank"),
                                ("calendar_today", "Calendar Month"),
                                ("chevron_right", "Chevron Right"),
                                ("draft", "File"),
                                ("gavel", "Hammer"),
                                ("info", "Info"),
                                ("check", "Check"),
                                ("link_2", "Link"),
                                ("exclamation", "Exclamation Mark"),
                                ("description", "Pdf"),
                                ("balance", "Scale"),
                                ("person", "User"),
                                ("videocam", "Video"),
                                ("settings", "Settings"),
                                ("work", "Briefcase"),
                                ("search", "Search"),
                                ("signpost", "Signpost"),
                                ("timeline", "Timeline"),
                                ("note_stack", "Notes"),
                                ("article", "Forms"),
                                ("help", "Help"),
                                ("dawson", "Dawson"),
                                ("select_check_box", "Select Check Box"),
                                ("outbound", "Outbound"),
                            ]
                        },
                    ),
                    144: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    145: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("level", 4), ("id", 26)]],
                        {},
                    ),
                    146: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 145), ("list", 72), ("paragraph", 10)]],
                        {"required": True},
                    ),
                    147: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 143), ("title", 25), ("intro", 144), ("body", 146)]],
                        {},
                    ),
                    148: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Card Icon", "required": True},
                    ),
                    149: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("right", "Right"),
                                ("bottom", "Bottom"),
                                ("left", "Left"),
                            ],
                            "help_text": "Icon placement, e.g. Top, Right, Bottom, Left. Default is Top.",
                            "required": False,
                        },
                    ),
                    150: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Displays the card title", "required": True},
                    ),
                    151: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "required": True},
                    ),
                    152: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "If checked, hover treatment is enabled for ALL tiles in this set.",
                            "required": False,
                        },
                    ),
                    153: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "desktop_top_mobile_left",
                                    "Desktop-Top / Mobile-Left",
                                ),
                                (
                                    "desktop_bottom_mobile_right",
                                    "Desktop-Bottom / Mobile-Right",
                                ),
                            ],
                            "help_text": "Applies to ALL tiles in this set (keeps icon placement uniform).",
                        },
                    ),
                    154: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Card header (H2)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    155: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic"],
                            "help_text": "Optional body text",
                            "required": False,
                        },
                    ),
                    156: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Select an SVG file."},
                    ),
                    157: (
                        "wagtail.blocks.StructBlock",
                        [[("svg_file", 156)]],
                        {"required": True},
                    ),
                    158: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center"),
                                ("left", "Left"),
                                ("right", "Right"),
                            ],
                            "help_text": "Desktop text alignment (tablet/mobile will be left-aligned per design).",
                        },
                    ),
                    159: ("wagtail.blocks.PageChooserBlock", (), {}),
                    160: ("wagtail.blocks.URLBlock", (), {}),
                    161: (
                        "wagtail.blocks.StreamBlock",
                        [[("related_page", 159), ("external_url", 160)]],
                        {
                            "help_text": "Choose where this tile should link.",
                            "max_num": 1,
                            "min_num": 1,
                            "required": False,
                        },
                    ),
                    162: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 154),
                                ("description", 155),
                                ("icon", 157),
                                ("content_alignment", 158),
                                ("link", 161),
                            ]
                        ],
                        {},
                    ),
                    163: (
                        "wagtail.blocks.ListBlock",
                        (162,),
                        {
                            "help_text": "Add, reorder, duplicate, or remove tiles. Responsive grid: 3 desktop / 2 tablet / 1 mobile.",
                            "required": False,
                        },
                    ),
                    164: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles_hover_enabled", 152),
                                ("icon_position", 153),
                                ("tiles", 163),
                            ]
                        ],
                        {},
                    ),
                    165: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("icon_header", 2),
                                ("heading", 6),
                                ("h2", 7),
                                ("h3", 8),
                                ("h4", 9),
                                ("paragraph", 10),
                                ("indented_paragraph", 11),
                                ("snippet", 12),
                                ("button", 22),
                                ("hr", 23),
                                ("iframe", 27),
                                ("alert", 29),
                                ("image", 32),
                                ("photo_dedication", 38),
                                ("table", 39),
                                ("unstyled_table", 39),
                                ("enhanced_table", 55),
                                ("list", 72),
                                ("links", 79),
                                ("questionanswers", 82),
                                ("columns", 91),
                                ("embedded_video", 94),
                                ("card", 105),
                                ("accordion", 52),
                                ("callout", 48),
                                ("grid", 116),
                                ("summary_timeline", 122),
                                ("detailed_timeline", 137),
                                ("hero_section", 142),
                                ("printable_section", 147),
                                ("quick_access_tiles", 164),
                            ]
                        ],
                        {"required": False},
                    ),
                    166: (
                        "wagtail.blocks.StructBlock",
                        [[("breadcrumb_title", 151), ("body", 165)]],
                        {},
                    ),
                    167: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("anchor_page", 166),
                                ("internal_page", 159),
                                ("external_url", 160),
                            ]
                        ],
                        {"max_num": 1, "min_num": 1},
                    ),
                    168: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect",
                            "required": False,
                        },
                    ),
                    169: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 148),
                                ("icon_direction", 149),
                                ("card_header", 150),
                                ("link", 167),
                                ("card_hover", 168),
                            ]
                        ],
                        {},
                    ),
                    170: (
                        "wagtail.blocks.ListBlock",
                        (169,),
                        {
                            "help_text": "Add up to 4 card tiles. They will display responsively based on screen size.",
                            "max_num": 4,
                            "min_num": 1,
                        },
                    ),
                    171: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("icon_header", 2),
                                ("heading", 6),
                                ("h2", 7),
                                ("h3", 8),
                                ("h4", 9),
                                ("paragraph", 10),
                                ("indented_paragraph", 11),
                                ("snippet", 12),
                                ("button", 22),
                                ("hr", 23),
                                ("iframe", 27),
                                ("alert", 29),
                                ("image", 32),
                                ("photo_dedication", 38),
                                ("table", 39),
                                ("unstyled_table", 39),
                                ("enhanced_table", 55),
                                ("list", 72),
                                ("links", 79),
                                ("questionanswers", 82),
                                ("columns", 91),
                                ("embedded_video", 94),
                                ("card", 105),
                                ("accordion", 52),
                                ("callout", 48),
                                ("grid", 116),
                                ("summary_timeline", 122),
                                ("detailed_timeline", 137),
                                ("hero_section", 142),
                                ("printable_section", 147),
                            ]
                        ],
                        {
                            "help_text": "Default content to display when no card is selected",
                            "required": False,
                        },
                    ),
                    172: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Display a back button when a card tile is selected (e.g. p/a, p/b). Hidden on the default view showing all card tiles. If checked, Back Button Text is required.",
                            "required": False,
                        },
                    ),
                    173: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text shown on the back button. Required if 'Show back button' is checked.",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    174: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles", 170),
                                ("default_content", 171),
                                ("show_back_button", 172),
                                ("back_button_text", 173),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="navigationribbonlink",
            name="icon",
            field=models.CharField(
                choices=[
                    ("", "None"),
                    ("book_3", "Book"),
                    ("account_balance", "Building Bank"),
                    ("calendar_today", "Calendar Month"),
                    ("chevron_right", "Chevron Right"),
                    ("draft", "File"),
                    ("gavel", "Hammer"),
                    ("info", "Info"),
                    ("check", "Check"),
                    ("link_2", "Link"),
                    ("exclamation", "Exclamation Mark"),
                    ("description", "Pdf"),
                    ("balance", "Scale"),
                    ("person", "User"),
                    ("videocam", "Video"),
                    ("settings", "Settings"),
                    ("work", "Briefcase"),
                    ("search", "Search"),
                    ("signpost", "Signpost"),
                    ("timeline", "Timeline"),
                    ("note_stack", "Notes"),
                    ("article", "Forms"),
                    ("help", "Help"),
                    ("dawson", "Dawson"),
                    ("select_check_box", "Select Check Box"),
                    ("outbound", "Outbound"),
                ],
                max_length=200,
            ),
        ),
    ]
