# Generated by Django 5.2.17 on 2026-09-25 15:17

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0151_sidecard_pe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directoryindex",
            name="body",
            field=wagtail.fields.StreamField(
                [("directory", 18)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {}),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("anchortag", 4)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("url", 4)]],
                        {"label": "Clickable Button"},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("book_3", "Book"),
                                ("account_balance", "Building Bank"),
                                ("calendar_today", "Calendar Month"),
                                ("chevron_right", "Chevron Right"),
                                ("draft", "File"),
                                ("gavel", "Hammer"),
                                ("info", "Info"),
                                ("check", "Check"),
                                ("link_2", "Link"),
                                ("exclamation", "Exclamation Mark"),
                                ("description", "Pdf"),
                                ("balance", "Scale"),
                                ("person", "User"),
                                ("videocam", "Video"),
                                ("settings", "Settings"),
                                ("work", "Briefcase"),
                                ("search", "Search"),
                                ("signpost", "Signpost"),
                                ("timeline", "Timeline"),
                                ("note_stack", "Notes"),
                                ("article", "Forms"),
                                ("help", "Help"),
                                ("dawson", "Dawson"),
                                ("mail", "Mail"),
                                ("call", "Call"),
                                ("open_in_new", "Open In New"),
                                ("select_check_box", "Select Check Box"),
                                ("outbound", "Outbound"),
                            ],
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    10: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("icon", 8),
                                ("document", 9),
                                ("video", 9),
                                ("url", 4),
                                ("text_only", 10),
                            ]
                        ],
                        {},
                    ),
                    12: ("wagtail.blocks.ListBlock", (11,), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 7), ("links", 12)]],
                        {"label": "Links"},
                    ),
                    14: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        (),
                        {
                            "help_text": "Optionally pick a JudgeCollection snippet",
                            "label": "Judge Collection",
                            "required": False,
                            "target_model": "home.JudgeCollection",
                        },
                    ),
                    15: ("wagtail.blocks.RichTextBlock", (), {}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("description", 15), ("phone_number", 3)]],
                        {},
                    ),
                    17: ("wagtail.blocks.ListBlock", (16,), {}),
                    18: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 0),
                                ("h3", 1),
                                ("hr", 2),
                                ("h2WithAnchorTag", 5),
                                ("clickableButton", 6),
                                ("links", 13),
                                ("JudgeCollection", 14),
                                ("DirectoryEntry", 17),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Directory entries or judge profiles",
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("icon_header", 2),
                    ("heading", 6),
                    ("h2", 7),
                    ("h3", 8),
                    ("h4", 9),
                    ("paragraph", 10),
                    ("indented_paragraph", 11),
                    ("snippet", 12),
                    ("button", 25),
                    ("hr", 26),
                    ("iframe", 30),
                    ("alert", 32),
                    ("image", 35),
                    ("photo_dedication", 41),
                    ("table", 42),
                    ("unstyled_table", 42),
                    ("enhanced_table", 58),
                    ("list", 75),
                    ("links", 82),
                    ("questionanswers", 85),
                    ("columns", 94),
                    ("embedded_video", 97),
                    ("card", 108),
                    ("accordion", 55),
                    ("callout", 51),
                    ("grid", 119),
                    ("summary_timeline", 125),
                    ("detailed_timeline", 140),
                    ("hero_section", 145),
                    ("printable_section", 150),
                    ("card_tiles", 177),
                    ("quick_access_tiles", 167),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("book_3", "Book"),
                                ("account_balance", "Building Bank"),
                                ("calendar_today", "Calendar Month"),
                                ("chevron_right", "Chevron Right"),
                                ("draft", "File"),
                                ("gavel", "Hammer"),
                                ("info", "Info"),
                                ("check", "Check"),
                                ("link_2", "Link"),
                                ("exclamation", "Exclamation Mark"),
                                ("description", "Pdf"),
                                ("balance", "Scale"),
                                ("person", "User"),
                                ("videocam", "Video"),
                                ("settings", "Settings"),
                                ("work", "Briefcase"),
                                ("search", "Search"),
                                ("signpost", "Signpost"),
                                ("timeline", "Timeline"),
                                ("note_stack", "Notes"),
                                ("article", "Forms"),
                                ("help", "Help"),
                                ("dawson", "Dawson"),
                                ("mail", "Mail"),
                                ("call", "Call"),
                                ("open_in_new", "Open In New"),
                                ("select_check_box", "Select Check Box"),
                                ("outbound", "Outbound"),
                            ],
                            "label": "Icon",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Header Text", "required": True},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("icon", 0), ("text", 1)]], {}),
                    3: ("wagtail.blocks.CharBlock", (), {}),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("level", 4), ("id", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    8: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    9: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    10: ("wagtail.blocks.RichTextBlock", (), {}),
                    11: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Paragraph with left indentation for alignment with list items",
                            "label": "Indented Paragraph",
                        },
                    ),
                    12: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    13: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Optional: Button icon", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("before", "Before Text"),
                                ("after", "After Text"),
                            ],
                            "help_text": "Choose the location of the icon relative to the text, if icon is selected.",
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    16: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to"},
                    ),
                    17: (
                        "home.blocks.PDFDocumentChooserBlock",
                        (),
                        {"help_text": "Select a PDF to link to"},
                    ),
                    18: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Enter an external URL"},
                    ),
                    19: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Enter an email address"},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter a phone number, e.g. (202) 521-0700",
                            "max_length": 20,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 16),
                                ("internal_pdf", 17),
                                ("external_url", 18),
                                ("email", 19),
                                ("phone", 20),
                            ]
                        ],
                        {
                            "help_text": "Select exactly one: Internal Page, External URL, PDF, Email, or Phone.",
                            "label": "URL",
                            "max_num": 1,
                            "min_num": 1,
                        },
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("inverted-primary", "Inverted Primary"),
                            ],
                            "help_text": "Choose the button style",
                        },
                    ),
                    23: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect on button",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional secondary line displayed under the button/link text (e.g. business hours).",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 13),
                                ("icon_location", 14),
                                ("text", 15),
                                ("url", 21),
                                ("style", 22),
                                ("button_hover", 23),
                                ("helper_text", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    27: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    28: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    29: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("src", 27),
                                ("width", 28),
                                ("height", 28),
                                ("class", 29),
                                ("loading", 29),
                                ("data_delay", 29),
                                ("name", 29),
                                ("title", 29),
                            ]
                        ],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success")]},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("alert_type", 31), ("content", 10)]],
                        {},
                    ),
                    33: ("wagtail.images.blocks.ImageBlock", [], {}),
                    34: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 16),
                                ("internal_pdf", 17),
                                ("external_url", 18),
                            ]
                        ],
                        {
                            "help_text": "Optional: add a link to make the image clickable.",
                            "max_num": 1,
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 33), ("link", 34)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Before"), ("right", "After")],
                            "help_text": "Place the image before (left on desktop) or after (right on desktop) the text.",
                        },
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional heading displayed above the photo and text.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Upload an image to display with this dedication",
                            "required": True,
                        },
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Describe the image for a visually impaired person.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    40: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image_position", 36),
                                ("title", 37),
                                ("photo", 38),
                                ("alt_text", 39),
                                ("paragraph_text", 40),
                                ("link", 34),
                            ]
                        ],
                        {},
                    ),
                    42: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 10)]],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title displayed above the table (rendered as H2).",
                            "label": "Header",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "A caption displayed above or below the table depending on Caption Location.",
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("top", "Top"), ("bottom", "Bottom")]},
                    ),
                    46: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("styled", "Styled Table"),
                                ("borderlessUnstyled", "Borderless Unstyled Table"),
                                ("unstyled", "Unstyled Table"),
                            ]
                        },
                    ),
                    47: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to set table layout to fixed width.",
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of this special element",
                            "required": True,
                        },
                    ),
                    49: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "The paragraph content", "required": True},
                    ),
                    50: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("success", "Success"),
                                ("error", "Error"),
                                ("emergency", "Emergency"),
                            ]
                        },
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 48), ("text", 49), ("callout_type", 50)]],
                        {},
                    ),
                    52: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title user will see before opening",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    53: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 6), ("prose", 10), ("callout", 51)]],
                        {
                            "help_text": "Add text or special elements to the body",
                            "required": True,
                        },
                    ),
                    54: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to have the accordion open by default when the page loads.",
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 52), ("description", 53), ("default_to_open", 54)]],
                        {},
                    ),
                    56: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 10),
                                ("callout", 51),
                                ("accordion", 55),
                                ("button", 25),
                            ]
                        ],
                        {"required": False},
                    ),
                    57: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("components", 56)]],
                        {},
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 43),
                                ("caption", 44),
                                ("caption_location", 45),
                                ("style", 46),
                                ("fixed", 47),
                                ("table", 57),
                            ]
                        ],
                        {},
                    ),
                    59: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                                ("checkbox", "Checkbox List"),
                                ("checkbox_with_subtext", "Checkbox with Subtext"),
                            ],
                            "required": False,
                        },
                    ),
                    60: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 60), ("subtext", 60), ("image", 33)]],
                        {"required": False},
                    ),
                    62: ("wagtail.blocks.ListBlock", (61,), {"default": []}),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 59), ("items", 62)]],
                        {"required": False},
                    ),
                    64: ("wagtail.blocks.ListBlock", (63,), {"default": []}),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 60),
                                ("subtext", 60),
                                ("image", 33),
                                ("nested_list", 64),
                            ]
                        ],
                        {"required": False},
                    ),
                    66: ("wagtail.blocks.ListBlock", (65,), {"default": []}),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 59), ("items", 66)]],
                        {"required": False},
                    ),
                    68: ("wagtail.blocks.ListBlock", (67,), {"default": []}),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 60),
                                ("subtext", 60),
                                ("image", 33),
                                ("nested_list", 68),
                            ]
                        ],
                        {"required": False},
                    ),
                    70: ("wagtail.blocks.ListBlock", (69,), {"default": []}),
                    71: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 59), ("items", 70)]],
                        {"required": False},
                    ),
                    72: ("wagtail.blocks.ListBlock", (71,), {"default": []}),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 60),
                                ("subtext", 60),
                                ("image", 33),
                                ("nested_list", 72),
                            ]
                        ],
                        {"required": False},
                    ),
                    74: ("wagtail.blocks.ListBlock", (73,), {"default": []}),
                    75: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 59), ("items", 74)]],
                        {"required": False},
                    ),
                    76: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ],
                            "label": "List style",
                        },
                    ),
                    77: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("book_3", "Book"),
                                ("account_balance", "Building Bank"),
                                ("calendar_today", "Calendar Month"),
                                ("chevron_right", "Chevron Right"),
                                ("draft", "File"),
                                ("gavel", "Hammer"),
                                ("info", "Info"),
                                ("check", "Check"),
                                ("link_2", "Link"),
                                ("exclamation", "Exclamation Mark"),
                                ("description", "Pdf"),
                                ("balance", "Scale"),
                                ("person", "User"),
                                ("videocam", "Video"),
                                ("settings", "Settings"),
                                ("work", "Briefcase"),
                                ("search", "Search"),
                                ("signpost", "Signpost"),
                                ("timeline", "Timeline"),
                                ("note_stack", "Notes"),
                                ("article", "Forms"),
                                ("help", "Help"),
                                ("dawson", "Dawson"),
                                ("mail", "Mail"),
                                ("call", "Call"),
                                ("open_in_new", "Open In New"),
                                ("select_check_box", "Select Check Box"),
                                ("outbound", "Outbound"),
                            ],
                            "required": False,
                        },
                    ),
                    78: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    79: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("icon", 77),
                                ("document", 78),
                                ("video", 78),
                                ("url", 29),
                                ("text_only", 79),
                            ]
                        ],
                        {},
                    ),
                    81: ("wagtail.blocks.ListBlock", (80,), {"label": "Add Entry"}),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 76), ("links", 81)]],
                        {"label": "List of Links"},
                    ),
                    83: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("filing", "Filing"),
                                ("deadlines", "Deadlines"),
                                ("representation", "Representation"),
                                ("forms-documents", "Forms & Documents"),
                                ("trial-process", "Trial Process"),
                                ("fees-costs", "Fees & Costs"),
                                ("after-decision", "After Decision"),
                            ],
                            "label": "FilterTag",
                        },
                    ),
                    84: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("question", 29),
                                ("answer", 10),
                                ("anchortag", 3),
                                ("filtertag", 83),
                            ]
                        ],
                        {},
                    ),
                    85: (
                        "wagtail.blocks.ListBlock",
                        (84,),
                        {
                            "help_text": "Add a question and answer. Link the anchor tag number. Select the FAQ FilterTag type in the dropdown.",
                            "label": "Question and Answer",
                        },
                    ),
                    86: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("anchortag", 29)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    88: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("url", 29)]],
                        {"label": "Clickable Button"},
                    ),
                    89: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    90: ("wagtail.blocks.ListBlock", (80,), {}),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 89), ("links", 90)]],
                        {"label": "Links"},
                    ),
                    92: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 7),
                                ("h3", 8),
                                ("hr", 86),
                                ("h2WithAnchorTag", 87),
                                ("clickableButton", 88),
                                ("links", 91),
                            ]
                        ],
                        {},
                    ),
                    93: ("wagtail.blocks.ListBlock", (92,), {}),
                    94: ("wagtail.blocks.StructBlock", [[("column", 93)]], {}),
                    95: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use the YouTube embed URL (e.g. https://www.youtube.com/embed/VIDEO_ID), not the watch URL.",
                            "required": True,
                        },
                    ),
                    96: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("below", "Below"), ("right-of", "Right")]},
                    ),
                    97: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 29),
                                ("description", 60),
                                ("video_url", 95),
                                ("text_location", 96),
                            ]
                        ],
                        {},
                    ),
                    98: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("gray", "Gray"),
                                ("dark-primary", "Dark-Primary"),
                                ("green", "Green"),
                                ("yellow", "Yellow"),
                            ],
                            "label": "Card Color",
                        },
                    ),
                    99: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("1", "One"),
                                ("2", "Two"),
                                ("3", "Three"),
                                ("check", "Check"),
                                ("exclamation", "Exclamation"),
                            ],
                            "help_text": "Optional numbered or status icon displayed on the card.",
                            "label": "Numbered Icon",
                            "required": False,
                        },
                    ),
                    100: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "help_text": "Only applies when Numbered Icon is not 'None'.",
                            "label": "Numbered Icon Alignment",
                        },
                    ),
                    101: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {
                            "help_text": "Optional: any SVG uploaded as a Wagtail Document.",
                            "label": "Title Icon",
                            "required": False,
                        },
                    ),
                    102: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank if the Title Icon is purely decorative. Fill in if it conveys meaning not already in the Card Title (e.g. distinguishing icons for different options).",
                            "label": "Title Icon Alt Text",
                            "required": False,
                        },
                    ),
                    103: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Displays the card sub title",
                            "label": "Card Sub-title",
                            "required": False,
                        },
                    ),
                    104: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Displays the card title",
                            "label": "Card Title",
                            "required": False,
                        },
                    ),
                    105: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Displays the text that goes under the header",
                            "label": "Body Text",
                            "required": False,
                        },
                    ),
                    106: (
                        "wagtail.blocks.ListBlock",
                        (25,),
                        {
                            "default": [],
                            "label": "Buttons",
                            "max_num": 1,
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    107: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("color", 98),
                                ("numbered_icon", 99),
                                ("numbered_icon_alignment", 100),
                                ("title_icon", 101),
                                ("title_icon_alt_text", 102),
                                ("subtitle", 103),
                                ("title", 104),
                                ("description", 105),
                                ("buttons", 106),
                            ]
                        ],
                        {"label": "Card", "label_format": "Card: {title}"},
                    ),
                    108: (
                        "wagtail.blocks.ListBlock",
                        (107,),
                        {
                            "help_text": "Add up to 3 cards. They display in a single row on desktop, wrap 2-up on tablet, and stack in a single column on mobile.",
                            "label": "Card Set",
                            "max_num": 3,
                        },
                    ),
                    109: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [(1, 1), (2, 2), (3, 3), (4, 4)],
                            "help_text": "Max number of columns in the grid (1-4)",
                        },
                    ),
                    110: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("full", "Full Width")],
                            "help_text": "Maximum width of the grid",
                        },
                    ),
                    111: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("styled", "Styled"), ("unstyled", "Unstyled")],
                            "help_text": "Style of the grid",
                        },
                    ),
                    112: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional header for this grid cell",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    113: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("#f1f9fc", "Default"), ("#DEEAF0", "Blue-Gray")]},
                    ),
                    114: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional caption for this grid cell (links allowed)",
                            "required": False,
                        },
                    ),
                    115: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Make the caption text italic",
                            "required": False,
                        },
                    ),
                    116: (
                        "wagtail.blocks.StreamBlock",
                        [[("prose", 10), ("callout", 51)]],
                        {
                            "help_text": "Add text or special elements to the cell body",
                            "required": True,
                        },
                    ),
                    117: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 112),
                                ("header_color", 113),
                                ("caption", 114),
                                ("italic_caption", 115),
                                ("body", 116),
                            ]
                        ],
                        {},
                    ),
                    118: (
                        "wagtail.blocks.ListBlock",
                        (117,),
                        {
                            "help_text": "Add cells to the grid. Cells will fill row-by-row based on the number of columns selected."
                        },
                    ),
                    119: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("columns", 109),
                                ("width", 110),
                                ("gridStyle", 111),
                                ("cells", 118),
                            ]
                        ],
                        {},
                    ),
                    120: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the beginning of the timeline.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    121: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the beginning of the phase.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    122: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the end of the phase.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    123: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 121), ("date_range", 122)]],
                        {},
                    ),
                    124: (
                        "wagtail.blocks.ListBlock",
                        (123,),
                        {
                            "blank": True,
                            "help_text": "Phases to be displayed in the timeline.",
                        },
                    ),
                    125: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 120), ("phases", 124)]],
                        {},
                    ),
                    126: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the beginning of the detailed timeline.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    127: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Text to be displayed under the detailed timeline's title.",
                            "required": True,
                        },
                    ),
                    128: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the end of the phase.",
                            "label": "Date Range",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    129: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Text to be shown at the top of the phase when it is expanded.",
                            "required": True,
                        },
                    ),
                    130: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    131: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 130), ("subtext", 60)]],
                        {"label": "Task Item"},
                    ),
                    132: (
                        "wagtail.blocks.ListBlock",
                        (131,),
                        {
                            "default": [],
                            "help_text": "Tasks to be completed during this phase.",
                            "label": "Your Tasks",
                            "required": False,
                        },
                    ),
                    133: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("outbound", "Action"), ("help", "Question")],
                            "help_text": "Choose the icon to be displayed in front of the text.",
                            "label": "Icon",
                        },
                    ),
                    134: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Helpful Information text",
                            "label": "Information",
                        },
                    ),
                    135: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Helpful Information subtext",
                            "label": "Information Subtext",
                            "required": False,
                        },
                    ),
                    136: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 133),
                                ("information", 134),
                                ("information_subtext", 135),
                            ]
                        ],
                        {"label": "Helpful Information Item"},
                    ),
                    137: (
                        "wagtail.blocks.ListBlock",
                        (136,),
                        {
                            "default": [],
                            "help_text": "Helpful information to be displayed at the bottom of the phase when expanded.",
                            "label": "Helpful Information",
                            "required": False,
                        },
                    ),
                    138: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 121),
                                ("date_range", 128),
                                ("instructions", 129),
                                ("your_tasks", 132),
                                ("helpful_information", 137),
                            ]
                        ],
                        {},
                    ),
                    139: (
                        "wagtail.blocks.StreamBlock",
                        [[("phase", 138)]],
                        {
                            "blank": True,
                            "help_text": "Phases to be displayed in the detailed timeline.",
                        },
                    ),
                    140: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 126), ("introduction", 127), ("phases", 139)]],
                        {},
                    ),
                    141: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title displayed at the top of the hero section.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    142: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Introductory text displayed beneath the title in the hero section.",
                            "max_length": 512,
                            "required": True,
                        },
                    ),
                    143: (
                        "wagtail.blocks.StreamBlock",
                        [[("block", 51)]],
                        {
                            "blank": True,
                            "help_text": "Callout block displayed underneath the introductory text in the hero section.",
                            "max_num": 1,
                            "min_num": 0,
                            "required": False,
                            "use_json_field": True,
                        },
                    ),
                    144: (
                        "wagtail.blocks.StreamBlock",
                        [[("button", 25)]],
                        {
                            "blank": True,
                            "help_text": "Buttons to display at the bottom of the hero section.",
                            "max_num": 3,
                            "min_num": 0,
                            "required": False,
                            "use_json_field": True,
                        },
                    ),
                    145: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 141),
                                ("introductory_text", 142),
                                ("callout_block", 143),
                                ("buttons", 144),
                            ]
                        ],
                        {},
                    ),
                    146: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("book_3", "Book"),
                                ("account_balance", "Building Bank"),
                                ("calendar_today", "Calendar Month"),
                                ("chevron_right", "Chevron Right"),
                                ("draft", "File"),
                                ("gavel", "Hammer"),
                                ("info", "Info"),
                                ("check", "Check"),
                                ("link_2", "Link"),
                                ("exclamation", "Exclamation Mark"),
                                ("description", "Pdf"),
                                ("balance", "Scale"),
                                ("person", "User"),
                                ("videocam", "Video"),
                                ("settings", "Settings"),
                                ("work", "Briefcase"),
                                ("search", "Search"),
                                ("signpost", "Signpost"),
                                ("timeline", "Timeline"),
                                ("note_stack", "Notes"),
                                ("article", "Forms"),
                                ("help", "Help"),
                                ("dawson", "Dawson"),
                                ("mail", "Mail"),
                                ("call", "Call"),
                                ("open_in_new", "Open In New"),
                                ("select_check_box", "Select Check Box"),
                                ("outbound", "Outbound"),
                            ]
                        },
                    ),
                    147: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    148: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 3), ("level", 4), ("id", 29)]],
                        {},
                    ),
                    149: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 148), ("list", 75), ("paragraph", 10)]],
                        {"required": True},
                    ),
                    150: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 146), ("title", 28), ("intro", 147), ("body", 149)]],
                        {},
                    ),
                    151: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Card Icon", "required": True},
                    ),
                    152: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("right", "Right"),
                                ("bottom", "Bottom"),
                                ("left", "Left"),
                            ],
                            "help_text": "Icon placement, e.g. Top, Right, Bottom, Left. Default is Top.",
                            "required": False,
                        },
                    ),
                    153: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Displays the card title", "required": True},
                    ),
                    154: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "required": True},
                    ),
                    155: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "If checked, hover treatment is enabled for ALL tiles in this set.",
                            "required": False,
                        },
                    ),
                    156: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "desktop_top_mobile_left",
                                    "Desktop-Top / Mobile-Left",
                                ),
                                (
                                    "desktop_bottom_mobile_right",
                                    "Desktop-Bottom / Mobile-Right",
                                ),
                            ],
                            "help_text": "Applies to ALL tiles in this set (keeps icon placement uniform).",
                        },
                    ),
                    157: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Card header (H2)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    158: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic"],
                            "help_text": "Optional body text",
                            "required": False,
                        },
                    ),
                    159: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Select an SVG file."},
                    ),
                    160: (
                        "wagtail.blocks.StructBlock",
                        [[("svg_file", 159)]],
                        {"required": True},
                    ),
                    161: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center"),
                                ("left", "Left"),
                                ("right", "Right"),
                            ],
                            "help_text": "Desktop text alignment (tablet/mobile will be left-aligned per design).",
                        },
                    ),
                    162: ("wagtail.blocks.PageChooserBlock", (), {}),
                    163: ("wagtail.blocks.URLBlock", (), {}),
                    164: (
                        "wagtail.blocks.StreamBlock",
                        [[("related_page", 162), ("external_url", 163)]],
                        {
                            "help_text": "Choose where this tile should link.",
                            "max_num": 1,
                            "min_num": 1,
                            "required": False,
                        },
                    ),
                    165: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 157),
                                ("description", 158),
                                ("icon", 160),
                                ("content_alignment", 161),
                                ("link", 164),
                            ]
                        ],
                        {},
                    ),
                    166: (
                        "wagtail.blocks.ListBlock",
                        (165,),
                        {
                            "help_text": "Add, reorder, duplicate, or remove tiles. Responsive grid: 3 desktop / 2 tablet / 1 mobile.",
                            "required": False,
                        },
                    ),
                    167: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles_hover_enabled", 155),
                                ("icon_position", 156),
                                ("tiles", 166),
                            ]
                        ],
                        {},
                    ),
                    168: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("icon_header", 2),
                                ("heading", 6),
                                ("h2", 7),
                                ("h3", 8),
                                ("h4", 9),
                                ("paragraph", 10),
                                ("indented_paragraph", 11),
                                ("snippet", 12),
                                ("button", 25),
                                ("hr", 26),
                                ("iframe", 30),
                                ("alert", 32),
                                ("image", 35),
                                ("photo_dedication", 41),
                                ("table", 42),
                                ("unstyled_table", 42),
                                ("enhanced_table", 58),
                                ("list", 75),
                                ("links", 82),
                                ("questionanswers", 85),
                                ("columns", 94),
                                ("embedded_video", 97),
                                ("card", 108),
                                ("accordion", 55),
                                ("callout", 51),
                                ("grid", 119),
                                ("summary_timeline", 125),
                                ("detailed_timeline", 140),
                                ("hero_section", 145),
                                ("printable_section", 150),
                                ("quick_access_tiles", 167),
                            ]
                        ],
                        {"required": False},
                    ),
                    169: (
                        "wagtail.blocks.StructBlock",
                        [[("breadcrumb_title", 154), ("body", 168)]],
                        {},
                    ),
                    170: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("anchor_page", 169),
                                ("internal_page", 162),
                                ("external_url", 163),
                            ]
                        ],
                        {"max_num": 1, "min_num": 1},
                    ),
                    171: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect",
                            "required": False,
                        },
                    ),
                    172: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 151),
                                ("icon_direction", 152),
                                ("card_header", 153),
                                ("link", 170),
                                ("card_hover", 171),
                            ]
                        ],
                        {},
                    ),
                    173: (
                        "wagtail.blocks.ListBlock",
                        (172,),
                        {
                            "help_text": "Add up to 4 card tiles. They will display responsively based on screen size.",
                            "max_num": 4,
                            "min_num": 1,
                        },
                    ),
                    174: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("icon_header", 2),
                                ("heading", 6),
                                ("h2", 7),
                                ("h3", 8),
                                ("h4", 9),
                                ("paragraph", 10),
                                ("indented_paragraph", 11),
                                ("snippet", 12),
                                ("button", 25),
                                ("hr", 26),
                                ("iframe", 30),
                                ("alert", 32),
                                ("image", 35),
                                ("photo_dedication", 41),
                                ("table", 42),
                                ("unstyled_table", 42),
                                ("enhanced_table", 58),
                                ("list", 75),
                                ("links", 82),
                                ("questionanswers", 85),
                                ("columns", 94),
                                ("embedded_video", 97),
                                ("card", 108),
                                ("accordion", 55),
                                ("callout", 51),
                                ("grid", 119),
                                ("summary_timeline", 125),
                                ("detailed_timeline", 140),
                                ("hero_section", 145),
                                ("printable_section", 150),
                            ]
                        ],
                        {
                            "help_text": "Default content to display when no card is selected",
                            "required": False,
                        },
                    ),
                    175: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Display a back button when a card tile is selected (e.g. p/a, p/b). Hidden on the default view showing all card tiles. If checked, Back Button Text is required.",
                            "required": False,
                        },
                    ),
                    176: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text shown on the back button. Required if 'Show back button' is checked.",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    177: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles", 173),
                                ("default_content", 174),
                                ("show_back_button", 175),
                                ("back_button_text", 176),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="navigationribbonlink",
            name="icon",
            field=models.CharField(
                choices=[
                    ("", "None"),
                    ("book_3", "Book"),
                    ("account_balance", "Building Bank"),
                    ("calendar_today", "Calendar Month"),
                    ("chevron_right", "Chevron Right"),
                    ("draft", "File"),
                    ("gavel", "Hammer"),
                    ("info", "Info"),
                    ("check", "Check"),
                    ("link_2", "Link"),
                    ("exclamation", "Exclamation Mark"),
                    ("description", "Pdf"),
                    ("balance", "Scale"),
                    ("person", "User"),
                    ("videocam", "Video"),
                    ("settings", "Settings"),
                    ("work", "Briefcase"),
                    ("search", "Search"),
                    ("signpost", "Signpost"),
                    ("timeline", "Timeline"),
                    ("note_stack", "Notes"),
                    ("article", "Forms"),
                    ("help", "Help"),
                    ("dawson", "Dawson"),
                    ("mail", "Mail"),
                    ("call", "Call"),
                    ("open_in_new", "Open In New"),
                    ("select_check_box", "Select Check Box"),
                    ("outbound", "Outbound"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sidecard",
            name="icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("book_3", "Book"),
                    ("account_balance", "Building Bank"),
                    ("calendar_today", "Calendar Month"),
                    ("chevron_right", "Chevron Right"),
                    ("draft", "File"),
                    ("gavel", "Hammer"),
                    ("info", "Info"),
                    ("check", "Check"),
                    ("link_2", "Link"),
                    ("exclamation", "Exclamation Mark"),
                    ("description", "Pdf"),
                    ("balance", "Scale"),
                    ("person", "User"),
                    ("videocam", "Video"),
                    ("settings", "Settings"),
                    ("work", "Briefcase"),
                    ("search", "Search"),
                    ("signpost", "Signpost"),
                    ("timeline", "Timeline"),
                    ("note_stack", "Notes"),
                    ("article", "Forms"),
                    ("help", "Help"),
                    ("dawson", "Dawson"),
                    ("mail", "Mail"),
                    ("call", "Call"),
                    ("open_in_new", "Open In New"),
                    ("select_check_box", "Select Check Box"),
                    ("outbound", "Outbound"),
                ],
                default="",
                help_text="Optional icon for this side card.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sidecard",
            name="links",
            field=wagtail.fields.StreamField(
                [("side_card_link", 12)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("book_3", "Book"),
                                ("account_balance", "Building Bank"),
                                ("calendar_today", "Calendar Month"),
                                ("chevron_right", "Chevron Right"),
                                ("draft", "File"),
                                ("gavel", "Hammer"),
                                ("info", "Info"),
                                ("check", "Check"),
                                ("link_2", "Link"),
                                ("exclamation", "Exclamation Mark"),
                                ("description", "Pdf"),
                                ("balance", "Scale"),
                                ("person", "User"),
                                ("videocam", "Video"),
                                ("settings", "Settings"),
                                ("work", "Briefcase"),
                                ("search", "Search"),
                                ("signpost", "Signpost"),
                                ("timeline", "Timeline"),
                                ("note_stack", "Notes"),
                                ("article", "Forms"),
                                ("help", "Help"),
                                ("dawson", "Dawson"),
                                ("mail", "Mail"),
                                ("call", "Call"),
                                ("open_in_new", "Open In New"),
                                ("select_check_box", "Select Check Box"),
                                ("outbound", "Outbound"),
                            ],
                            "help_text": "Optional icon for this link.",
                            "label": "Icon",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("before", "Before Text"),
                                ("after", "After Text"),
                            ],
                            "help_text": "Choose the location of the icon relative to the text, if icon is selected.",
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Link text", "max_length": 64, "required": True},
                    ),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to"},
                    ),
                    4: (
                        "home.blocks.PDFDocumentChooserBlock",
                        (),
                        {"help_text": "Select a PDF to link to"},
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Enter an external URL"},
                    ),
                    6: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Enter an email address"},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter a phone number, e.g. (202) 521-0700",
                            "max_length": 20,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 3),
                                ("internal_pdf", 4),
                                ("external_url", 5),
                                ("email", 6),
                                ("phone", 7),
                            ]
                        ],
                        {
                            "help_text": "Select exactly one: Internal Page, External URL, PDF, Email, or Phone.",
                            "label": "URL",
                            "max_num": 1,
                            "min_num": 1,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("inverted-primary", "Inverted Primary"),
                            ],
                            "help_text": "Choose the button style (used when the card's link display style is 'button').",
                        },
                    ),
                    10: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect on button",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional secondary line displayed under the link text (e.g. business hours).",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 0),
                                ("icon_location", 1),
                                ("text", 2),
                                ("url", 8),
                                ("style", 9),
                                ("button_hover", 10),
                                ("helper_text", 11),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Informational blocks/buttons for this side card.",
            ),
        ),
    ]
