# Generated by Django 5.2.17 on 2026-09-29 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0153_alter_enhancedstandardpage_body"),
        ("home", "0154_seed_faq_filter_tags"),
    ]

    operations = []
