# Generated by Django 5.2.17 on 2026-10-08 19:16

# Deleting redirects for paths ending in ".html" managed by
# home.management.commands.redirects.RedirectInitalizer so they
# can be recreated the next time "make updatepages" is called.

from django.db import migrations

LEGACY_URLS = [
    "/administrative_orders.html",
    "/case_procedure.html",
    "/case_related_forms.html",
    "/citation_and_style_manual.html",
    "/clinics.html",
    "/clinics_academic.html",
    "/clinics_academic_non_law_school.html",
    "/clinics_calendar_call.html",
    "/clinics_chief_counsel.html",
    "/clinics_nonacademic.html",
    "/dashboard.html",
    "/dawson.html",
    "/dawson_account_petitioner.html",
    "/dawson_account_practitioner.html",
    "/dawson_faqs_account_management.html",
    "/dawson_faqs_basics.html",
    "/dawson_faqs_case_management.html",
    "/dawson_faqs_login.html",
    "/dawson_faqs_searches_public_access.html",
    "/dawson_faqs_training_and_support.html",
    "/dawson_tou.html",
    "/dawson_user_guides.html",
    "/definitions.html",
    "/directory.html",
    "/documents_eligible_for_efiling.html",
    "/dpt_cities.html",
    "/efile_a_petition.html",
    "/employment.html",
    "/fees_and_charges.html",
    "/find_a_case.html",
    "/find_an_opinion.html",
    "/find_an_order.html",
    "/forms_instructions.html",
    "/history.html",
    "/holidays.html",
    "/judges.html",
    "/jcdp.html",
    "/jcdp_orders_issued.html",
    "/merging_files.html",
    "/mission.html",
    "/notice_regarding_privacy.html",
    "/notices_of_rule_amendments.html",
    "/pamphlets.html",
    "/pay_filing_fee.html",
    "/petitioners.html",
    "/petitioners_about.html",
    "/petitioners_after.html",
    "/petitioners_before.html",
    "/petitioners_during.html",
    "/petitioners_glossary.html",
    "/petitioners_start.html",
    "/practitioners.html",
    "/press_releases.html",
    "/release_notes.html",
    "/remote_proceedings.html",
    "/reports_and_statistics.html",
    "/rules.html",
    "/rules_comments.html",
    "/transcripts_and_copies.html",
    "/trial_sessions.html",
    "/update_contact_information.html",
    "/zoomgov.html",
    "/zoomgov_getting_ready.html",
    "/zoomgov_the_basics.html",
    "/zoomgov_zoomgov_proceedings.html",
    "/taxpayers_start.html",  # this was redirecting to "/petitioners-start/", the slash at the end will be removed by this migration
]


def delete_redirect_if_exists(apps, schema_editor):
    Redirect = apps.get_model("wagtailredirects", "redirect")
    for old_path in LEGACY_URLS:
        try:
            redirect_obj = Redirect.objects.get(old_path=old_path)
            if redirect_obj and redirect_obj.redirect_link[-1:] == "/":
                redirect_obj.redirect_link = redirect_obj.redirect_link[:-1]
                redirect_obj.save()
        except Redirect.DoesNotExist:
            continue


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0155_alter_enhancedstandardpage_body_pe"),
        (
            "wagtailredirects",
            "0008_add_verbose_name_plural",
        ),
    ]

    operations = [
        migrations.RunPython(delete_redirect_if_exists, migrations.RunPython.noop)
    ]
