# Generated by Django 5.2.17 on 2026-10-09 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0156_alter_enhancedstandardpage_body_pe"),
        ("home", "0156_data_delete_html_redirects_pe"),
    ]

    operations = []
