# Generated by Django 5.2.17 on 2026-10-09 15:02

import home.models.snippets.faq_filter_tag  # noqa: no-direct-model-imports-in-migrations — Django-generated reference to the FilterTag choices callable, not a live model
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0157_data_wrap_questionanswers_pe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedstandardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("icon_header", 2),
                    ("section_header", 6),
                    ("heading", 10),
                    ("h2", 11),
                    ("h3", 12),
                    ("h4", 13),
                    ("paragraph", 14),
                    ("indented_paragraph", 15),
                    ("snippet", 16),
                    ("button", 29),
                    ("hr", 30),
                    ("iframe", 34),
                    ("alert", 36),
                    ("image", 39),
                    ("photo_dedication", 45),
                    ("table", 46),
                    ("unstyled_table", 46),
                    ("enhanced_table", 62),
                    ("list", 79),
                    ("links", 86),
                    ("questionanswers", 91),
                    ("columns", 100),
                    ("embedded_video", 103),
                    ("card", 114),
                    ("accordion", 59),
                    ("callout", 55),
                    ("grid", 125),
                    ("summary_timeline", 131),
                    ("detailed_timeline", 146),
                    ("hero_section", 151),
                    ("printable_section", 156),
                    ("card_tiles", 183),
                    ("quick_access_tiles", 173),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("book_3", "Book"),
                                ("account_balance", "Building Bank"),
                                ("calendar_today", "Calendar Month"),
                                ("chevron_right", "Chevron Right"),
                                ("draft", "File"),
                                ("gavel", "Hammer"),
                                ("info", "Info"),
                                ("check", "Check"),
                                ("link_2", "Link"),
                                ("exclamation", "Exclamation Mark"),
                                ("description", "Pdf"),
                                ("balance", "Scale"),
                                ("person", "User"),
                                ("videocam", "Video"),
                                ("settings", "Settings"),
                                ("work", "Briefcase"),
                                ("search", "Search"),
                                ("signpost", "Signpost"),
                                ("timeline", "Timeline"),
                                ("note_stack", "Notes"),
                                ("article", "Forms"),
                                ("help", "Help"),
                                ("dawson", "Dawson"),
                                ("mail", "Mail"),
                                ("call", "Call"),
                                ("open_in_new", "Open In New"),
                                ("select_check_box", "Select Check Box"),
                                ("outbound", "Outbound"),
                            ],
                            "label": "Icon",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Header Text", "required": True},
                    ),
                    2: ("wagtail.blocks.StructBlock", [[("icon", 0), ("text", 1)]], {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Heading", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "required": True},
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link URL", "required": True},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 3), ("link_text", 4), ("link_url", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {}),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h2", "Heading 2"),
                                ("h3", "Heading 3"),
                                ("h4", "Heading 4"),
                                ("h5", "Heading 5"),
                            ]
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional ID for linking to this heading",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("level", 8), ("id", 9)]],
                        {},
                    ),
                    11: ("wagtail.blocks.CharBlock", (), {"label": "Heading 2"}),
                    12: ("wagtail.blocks.CharBlock", (), {"label": "Heading 3"}),
                    13: ("wagtail.blocks.CharBlock", (), {"label": "Heading 4"}),
                    14: ("wagtail.blocks.RichTextBlock", (), {}),
                    15: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Paragraph with left indentation for alignment with list items",
                            "label": "Indented Paragraph",
                        },
                    ),
                    16: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("home.CommonText",),
                        {},
                    ),
                    17: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Optional: Button icon", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("before", "Before Text"),
                                ("after", "After Text"),
                            ],
                            "help_text": "Choose the location of the icon relative to the text, if icon is selected.",
                        },
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text",
                            "max_length": 64,
                            "required": True,
                        },
                    ),
                    20: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select a page to link to"},
                    ),
                    21: (
                        "home.blocks.PDFDocumentChooserBlock",
                        (),
                        {"help_text": "Select a PDF to link to"},
                    ),
                    22: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Enter an external URL"},
                    ),
                    23: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Enter an email address"},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter a phone number, e.g. (202) 521-0700",
                            "max_length": 20,
                        },
                    ),
                    25: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 20),
                                ("internal_pdf", 21),
                                ("external_url", 22),
                                ("email", 23),
                                ("phone", 24),
                            ]
                        ],
                        {
                            "help_text": "Select exactly one: Internal Page, External URL, PDF, Email, or Phone.",
                            "label": "URL",
                            "max_num": 1,
                            "min_num": 1,
                        },
                    ),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("inverted-primary", "Inverted Primary"),
                            ],
                            "help_text": "Choose the button style",
                        },
                    ),
                    27: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect on button",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional secondary line displayed under the button/link text (e.g. business hours).",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 17),
                                ("icon_location", 18),
                                ("text", 19),
                                ("url", 25),
                                ("style", 26),
                                ("button_hover", 27),
                                ("helper_text", 28),
                            ]
                        ],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add 'Horizontal Rule'.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    31: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    32: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    33: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("src", 31),
                                ("width", 32),
                                ("height", 32),
                                ("class", 33),
                                ("loading", 33),
                                ("data_delay", 33),
                                ("name", 33),
                                ("title", 33),
                            ]
                        ],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("info", "Info"), ("success", "Success")]},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("alert_type", 35), ("content", 14)]],
                        {},
                    ),
                    37: ("wagtail.images.blocks.ImageBlock", [], {}),
                    38: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("internal_page", 20),
                                ("internal_pdf", 21),
                                ("external_url", 22),
                            ]
                        ],
                        {
                            "help_text": "Optional: add a link to make the image clickable.",
                            "max_num": 1,
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 37), ("link", 38)]],
                        {},
                    ),
                    40: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Before"), ("right", "After")],
                            "help_text": "Place the image before (left on desktop) or after (right on desktop) the text.",
                        },
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional heading displayed above the photo and text.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Upload an image to display with this dedication",
                            "required": True,
                        },
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Describe the image for a visually impaired person.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    44: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the main paragraph text for the dedication section",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image_position", 40),
                                ("title", 41),
                                ("photo", 42),
                                ("alt_text", 43),
                                ("paragraph_text", 44),
                                ("link", 38),
                            ]
                        ],
                        {},
                    ),
                    46: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("text", 14)]],
                        {},
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title displayed above the table (rendered as H2).",
                            "label": "Header",
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "A caption displayed above or below the table depending on Caption Location.",
                            "label": "Caption",
                            "required": False,
                        },
                    ),
                    49: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("top", "Top"), ("bottom", "Bottom")]},
                    ),
                    50: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("styled", "Styled Table"),
                                ("borderlessUnstyled", "Borderless Unstyled Table"),
                                ("unstyled", "Unstyled Table"),
                            ]
                        },
                    ),
                    51: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to set table layout to fixed width.",
                            "required": False,
                        },
                    ),
                    52: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title of this special element",
                            "required": True,
                        },
                    ),
                    53: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "The paragraph content", "required": True},
                    ),
                    54: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("info", "Info"),
                                ("warning", "Warning"),
                                ("success", "Success"),
                                ("error", "Error"),
                                ("emergency", "Emergency"),
                            ]
                        },
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 52), ("text", 53), ("callout_type", 54)]],
                        {},
                    ),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title user will see before opening",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    57: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 10), ("prose", 14), ("callout", 55)]],
                        {
                            "help_text": "Add text or special elements to the body",
                            "required": True,
                        },
                    ),
                    58: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Check to have the accordion open by default when the page loads.",
                            "required": False,
                        },
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 56), ("description", 57), ("default_to_open", 58)]],
                        {},
                    ),
                    60: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("text", 14),
                                ("callout", 55),
                                ("accordion", 59),
                                ("button", 29),
                            ]
                        ],
                        {"required": False},
                    ),
                    61: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("components", 60)]],
                        {},
                    ),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 47),
                                ("caption", 48),
                                ("caption_location", 49),
                                ("style", 50),
                                ("fixed", 51),
                                ("table", 61),
                            ]
                        ],
                        {},
                    ),
                    63: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("ordered", "Ordered List"),
                                ("unordered", "Unordered List"),
                                ("checkbox", "Checkbox List"),
                                ("checkbox_with_subtext", "Checkbox with Subtext"),
                            ],
                            "required": False,
                        },
                    ),
                    64: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 64), ("subtext", 64), ("image", 37)]],
                        {"label": "Item", "required": False},
                    ),
                    66: ("wagtail.blocks.ListBlock", (65,), {"default": []}),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 63), ("items", 66)]],
                        {"required": False},
                    ),
                    68: ("wagtail.blocks.ListBlock", (67,), {"default": []}),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 64),
                                ("subtext", 64),
                                ("image", 37),
                                ("nested_list", 68),
                            ]
                        ],
                        {"label": "Item", "required": False},
                    ),
                    70: ("wagtail.blocks.ListBlock", (69,), {"default": []}),
                    71: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 63), ("items", 70)]],
                        {"required": False},
                    ),
                    72: ("wagtail.blocks.ListBlock", (71,), {"default": []}),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 64),
                                ("subtext", 64),
                                ("image", 37),
                                ("nested_list", 72),
                            ]
                        ],
                        {"label": "Item", "required": False},
                    ),
                    74: ("wagtail.blocks.ListBlock", (73,), {"default": []}),
                    75: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 63), ("items", 74)]],
                        {"required": False},
                    ),
                    76: ("wagtail.blocks.ListBlock", (75,), {"default": []}),
                    77: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 64),
                                ("subtext", 64),
                                ("image", 37),
                                ("nested_list", 76),
                            ]
                        ],
                        {"label": "Item", "required": False},
                    ),
                    78: ("wagtail.blocks.ListBlock", (77,), {"default": []}),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 63), ("items", 78)]],
                        {"required": False},
                    ),
                    80: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "indented"),
                                ("unindented", "unindented"),
                            ],
                            "label": "List style",
                        },
                    ),
                    81: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("book_3", "Book"),
                                ("account_balance", "Building Bank"),
                                ("calendar_today", "Calendar Month"),
                                ("chevron_right", "Chevron Right"),
                                ("draft", "File"),
                                ("gavel", "Hammer"),
                                ("info", "Info"),
                                ("check", "Check"),
                                ("link_2", "Link"),
                                ("exclamation", "Exclamation Mark"),
                                ("description", "Pdf"),
                                ("balance", "Scale"),
                                ("person", "User"),
                                ("videocam", "Video"),
                                ("settings", "Settings"),
                                ("work", "Briefcase"),
                                ("search", "Search"),
                                ("signpost", "Signpost"),
                                ("timeline", "Timeline"),
                                ("note_stack", "Notes"),
                                ("article", "Forms"),
                                ("help", "Help"),
                                ("dawson", "Dawson"),
                                ("mail", "Mail"),
                                ("call", "Call"),
                                ("open_in_new", "Open In New"),
                                ("select_check_box", "Select Check Box"),
                                ("outbound", "Outbound"),
                            ],
                            "required": False,
                        },
                    ),
                    82: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    83: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    84: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 7),
                                ("icon", 81),
                                ("document", 82),
                                ("video", 82),
                                ("url", 33),
                                ("text_only", 83),
                            ]
                        ],
                        {},
                    ),
                    85: ("wagtail.blocks.ListBlock", (84,), {"label": "Add Entry"}),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [[("style", 80), ("links", 85)]],
                        {},
                    ),
                    87: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show FilterTag buttons above the questions and display each question as an accordion.",
                            "label": "Display Filter Section",
                            "required": False,
                        },
                    ),
                    88: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": home.models.snippets.faq_filter_tag.get_faq_filter_tag_choices,
                            "label": "FilterTag",
                        },
                    ),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("question", 33),
                                ("answer", 14),
                                ("anchortag", 7),
                                ("filtertag", 88),
                            ]
                        ],
                        {},
                    ),
                    90: (
                        "wagtail.blocks.ListBlock",
                        (89,),
                        {
                            "help_text": "Add a question and answer. Link the anchor tag number. Select the FAQ FilterTag type in the dropdown.",
                            "label": "Questions",
                        },
                    ),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [[("display_filter_section", 87), ("questions", 90)]],
                        {},
                    ),
                    92: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Add Horizontal Rule.",
                            "label": "Horizontal Rule",
                        },
                    ),
                    93: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("anchortag", 33)]],
                        {
                            "help_text": "Heading 2 with optional anchor tag for linking",
                            "label": "Heading 2 with Anchor Tag",
                        },
                    ),
                    94: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("url", 33)]],
                        {"label": "Clickable Button"},
                    ),
                    95: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("indented", "Indented"),
                                ("unindented", "Unindented"),
                            ]
                        },
                    ),
                    96: ("wagtail.blocks.ListBlock", (84,), {}),
                    97: (
                        "wagtail.blocks.StructBlock",
                        [[("class", 95), ("links", 96)]],
                        {"label": "Links"},
                    ),
                    98: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("h2", 11),
                                ("h3", 12),
                                ("hr", 92),
                                ("h2WithAnchorTag", 93),
                                ("clickableButton", 94),
                                ("links", 97),
                            ]
                        ],
                        {},
                    ),
                    99: ("wagtail.blocks.ListBlock", (98,), {}),
                    100: ("wagtail.blocks.StructBlock", [[("column", 99)]], {}),
                    101: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use the YouTube embed URL (e.g. https://www.youtube.com/embed/VIDEO_ID), not the watch URL.",
                            "required": True,
                        },
                    ),
                    102: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("below", "Below"), ("right-of", "Right")]},
                    ),
                    103: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 33),
                                ("description", 64),
                                ("video_url", 101),
                                ("text_location", 102),
                            ]
                        ],
                        {},
                    ),
                    104: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("gray", "Gray"),
                                ("dark-primary", "Dark-Primary"),
                                ("green", "Green"),
                                ("yellow", "Yellow"),
                            ],
                            "label": "Card Color",
                        },
                    ),
                    105: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("1", "One"),
                                ("2", "Two"),
                                ("3", "Three"),
                                ("check", "Check"),
                                ("exclamation", "Exclamation"),
                            ],
                            "help_text": "Optional numbered or status icon displayed on the card.",
                            "label": "Numbered Icon",
                            "required": False,
                        },
                    ),
                    106: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "help_text": "Only applies when Numbered Icon is not 'None'.",
                            "label": "Numbered Icon Alignment",
                        },
                    ),
                    107: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {
                            "help_text": "Optional: any SVG uploaded as a Wagtail Document.",
                            "label": "Title Icon",
                            "required": False,
                        },
                    ),
                    108: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank if the Title Icon is purely decorative. Fill in if it conveys meaning not already in the Card Title (e.g. distinguishing icons for different options).",
                            "label": "Title Icon Alt Text",
                            "required": False,
                        },
                    ),
                    109: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Displays the card sub title",
                            "label": "Card Sub-title",
                            "required": False,
                        },
                    ),
                    110: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Displays the card title",
                            "label": "Card Title",
                            "required": False,
                        },
                    ),
                    111: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Displays the text that goes under the header",
                            "label": "Body Text",
                            "required": False,
                        },
                    ),
                    112: (
                        "wagtail.blocks.ListBlock",
                        (29,),
                        {
                            "default": [],
                            "label": "Buttons",
                            "max_num": 1,
                            "min_num": 0,
                            "required": False,
                        },
                    ),
                    113: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("color", 104),
                                ("numbered_icon", 105),
                                ("numbered_icon_alignment", 106),
                                ("title_icon", 107),
                                ("title_icon_alt_text", 108),
                                ("subtitle", 109),
                                ("title", 110),
                                ("description", 111),
                                ("buttons", 112),
                            ]
                        ],
                        {"label": "Card", "label_format": "Card: {title}"},
                    ),
                    114: (
                        "wagtail.blocks.ListBlock",
                        (113,),
                        {
                            "help_text": "Add up to 3 cards. They display in a single row on desktop, wrap 2-up on tablet, and stack in a single column on mobile.",
                            "label": "Card Set",
                            "max_num": 3,
                        },
                    ),
                    115: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [(1, 1), (2, 2), (3, 3), (4, 4)],
                            "help_text": "Max number of columns in the grid (1-4)",
                        },
                    ),
                    116: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("full", "Full Width")],
                            "help_text": "Maximum width of the grid",
                        },
                    ),
                    117: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("styled", "Styled"), ("unstyled", "Unstyled")],
                            "help_text": "Style of the grid",
                        },
                    ),
                    118: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional header for this grid cell",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    119: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("#f1f9fc", "Default"), ("#DEEAF0", "Blue-Gray")]},
                    ),
                    120: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional caption for this grid cell (links allowed)",
                            "required": False,
                        },
                    ),
                    121: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Make the caption text italic",
                            "required": False,
                        },
                    ),
                    122: (
                        "wagtail.blocks.StreamBlock",
                        [[("prose", 14), ("callout", 55)]],
                        {
                            "help_text": "Add text or special elements to the cell body",
                            "required": True,
                        },
                    ),
                    123: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header", 118),
                                ("header_color", 119),
                                ("caption", 120),
                                ("italic_caption", 121),
                                ("body", 122),
                            ]
                        ],
                        {},
                    ),
                    124: (
                        "wagtail.blocks.ListBlock",
                        (123,),
                        {
                            "help_text": "Add cells to the grid. Cells will fill row-by-row based on the number of columns selected."
                        },
                    ),
                    125: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("columns", 115),
                                ("width", 116),
                                ("gridStyle", 117),
                                ("cells", 124),
                            ]
                        ],
                        {},
                    ),
                    126: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the beginning of the timeline.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    127: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the beginning of the phase.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    128: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the end of the phase.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    129: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 127), ("date_range", 128)]],
                        {},
                    ),
                    130: (
                        "wagtail.blocks.ListBlock",
                        (129,),
                        {
                            "blank": True,
                            "help_text": "Phases to be displayed in the timeline.",
                        },
                    ),
                    131: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 126), ("phases", 130)]],
                        {},
                    ),
                    132: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the beginning of the detailed timeline.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    133: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Text to be displayed under the detailed timeline's title.",
                            "required": True,
                        },
                    ),
                    134: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to be displayed at the end of the phase.",
                            "label": "Date Range",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    135: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Text to be shown at the top of the phase when it is expanded.",
                            "required": True,
                        },
                    ),
                    136: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    137: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 136), ("subtext", 64)]],
                        {"label": "Task Item"},
                    ),
                    138: (
                        "wagtail.blocks.ListBlock",
                        (137,),
                        {
                            "default": [],
                            "help_text": "Tasks to be completed during this phase.",
                            "label": "Your Tasks",
                            "required": False,
                        },
                    ),
                    139: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("outbound", "Action"), ("help", "Question")],
                            "help_text": "Choose the icon to be displayed in front of the text.",
                            "label": "Icon",
                        },
                    ),
                    140: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Helpful Information text",
                            "label": "Information",
                        },
                    ),
                    141: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Helpful Information subtext",
                            "label": "Information Subtext",
                            "required": False,
                        },
                    ),
                    142: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 139),
                                ("information", 140),
                                ("information_subtext", 141),
                            ]
                        ],
                        {"label": "Helpful Information Item"},
                    ),
                    143: (
                        "wagtail.blocks.ListBlock",
                        (142,),
                        {
                            "default": [],
                            "help_text": "Helpful information to be displayed at the bottom of the phase when expanded.",
                            "label": "Helpful Information",
                            "required": False,
                        },
                    ),
                    144: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 127),
                                ("date_range", 134),
                                ("instructions", 135),
                                ("your_tasks", 138),
                                ("helpful_information", 143),
                            ]
                        ],
                        {},
                    ),
                    145: (
                        "wagtail.blocks.StreamBlock",
                        [[("phase", 144)]],
                        {
                            "blank": True,
                            "help_text": "Phases to be displayed in the detailed timeline.",
                        },
                    ),
                    146: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 132), ("introduction", 133), ("phases", 145)]],
                        {},
                    ),
                    147: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title displayed at the top of the hero section.",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    148: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Introductory text displayed beneath the title in the hero section.",
                            "max_length": 512,
                            "required": True,
                        },
                    ),
                    149: (
                        "wagtail.blocks.StreamBlock",
                        [[("block", 55)]],
                        {
                            "blank": True,
                            "help_text": "Callout block displayed underneath the introductory text in the hero section.",
                            "max_num": 1,
                            "min_num": 0,
                            "required": False,
                            "use_json_field": True,
                        },
                    ),
                    150: (
                        "wagtail.blocks.StreamBlock",
                        [[("button", 29)]],
                        {
                            "blank": True,
                            "help_text": "Buttons to display at the bottom of the hero section.",
                            "max_num": 3,
                            "min_num": 0,
                            "required": False,
                            "use_json_field": True,
                        },
                    ),
                    151: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 147),
                                ("introductory_text", 148),
                                ("callout_block", 149),
                                ("buttons", 150),
                            ]
                        ],
                        {},
                    ),
                    152: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "None"),
                                ("book_3", "Book"),
                                ("account_balance", "Building Bank"),
                                ("calendar_today", "Calendar Month"),
                                ("chevron_right", "Chevron Right"),
                                ("draft", "File"),
                                ("gavel", "Hammer"),
                                ("info", "Info"),
                                ("check", "Check"),
                                ("link_2", "Link"),
                                ("exclamation", "Exclamation Mark"),
                                ("description", "Pdf"),
                                ("balance", "Scale"),
                                ("person", "User"),
                                ("videocam", "Video"),
                                ("settings", "Settings"),
                                ("work", "Briefcase"),
                                ("search", "Search"),
                                ("signpost", "Signpost"),
                                ("timeline", "Timeline"),
                                ("note_stack", "Notes"),
                                ("article", "Forms"),
                                ("help", "Help"),
                                ("dawson", "Dawson"),
                                ("mail", "Mail"),
                                ("call", "Call"),
                                ("open_in_new", "Open In New"),
                                ("select_check_box", "Select Check Box"),
                                ("outbound", "Outbound"),
                            ]
                        },
                    ),
                    153: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": False},
                    ),
                    154: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("level", 8), ("id", 33)]],
                        {},
                    ),
                    155: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 154), ("list", 79), ("paragraph", 14)]],
                        {"required": True},
                    ),
                    156: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 152), ("title", 32), ("intro", 153), ("body", 155)]],
                        {},
                    ),
                    157: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Card Icon", "required": True},
                    ),
                    158: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("right", "Right"),
                                ("bottom", "Bottom"),
                                ("left", "Left"),
                            ],
                            "help_text": "Icon placement, e.g. Top, Right, Bottom, Left. Default is Top.",
                            "required": False,
                        },
                    ),
                    159: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Displays the card title", "required": True},
                    ),
                    160: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "required": True},
                    ),
                    161: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "If checked, hover treatment is enabled for ALL tiles in this set.",
                            "required": False,
                        },
                    ),
                    162: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (
                                    "desktop_top_mobile_left",
                                    "Desktop-Top / Mobile-Left",
                                ),
                                (
                                    "desktop_bottom_mobile_right",
                                    "Desktop-Bottom / Mobile-Right",
                                ),
                            ],
                            "help_text": "Applies to ALL tiles in this set (keeps icon placement uniform).",
                        },
                    ),
                    163: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Card header (H2)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    164: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic"],
                            "help_text": "Optional body text",
                            "required": False,
                        },
                    ),
                    165: (
                        "home.blocks.SVGDocumentChooserBlock",
                        (),
                        {"help_text": "Select an SVG file."},
                    ),
                    166: (
                        "wagtail.blocks.StructBlock",
                        [[("svg_file", 165)]],
                        {"required": True},
                    ),
                    167: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center"),
                                ("left", "Left"),
                                ("right", "Right"),
                            ],
                            "help_text": "Desktop text alignment (tablet/mobile will be left-aligned per design).",
                        },
                    ),
                    168: ("wagtail.blocks.PageChooserBlock", (), {}),
                    169: ("wagtail.blocks.URLBlock", (), {}),
                    170: (
                        "wagtail.blocks.StreamBlock",
                        [[("related_page", 168), ("external_url", 169)]],
                        {
                            "help_text": "Choose where this tile should link.",
                            "max_num": 1,
                            "min_num": 1,
                            "required": False,
                        },
                    ),
                    171: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 163),
                                ("description", 164),
                                ("icon", 166),
                                ("content_alignment", 167),
                                ("link", 170),
                            ]
                        ],
                        {},
                    ),
                    172: (
                        "wagtail.blocks.ListBlock",
                        (171,),
                        {
                            "help_text": "Add, reorder, duplicate, or remove tiles. Responsive grid: 3 desktop / 2 tablet / 1 mobile.",
                            "required": False,
                        },
                    ),
                    173: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles_hover_enabled", 161),
                                ("icon_position", 162),
                                ("tiles", 172),
                            ]
                        ],
                        {},
                    ),
                    174: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("icon_header", 2),
                                ("section_header", 6),
                                ("heading", 10),
                                ("h2", 11),
                                ("h3", 12),
                                ("h4", 13),
                                ("paragraph", 14),
                                ("indented_paragraph", 15),
                                ("snippet", 16),
                                ("button", 29),
                                ("hr", 30),
                                ("iframe", 34),
                                ("alert", 36),
                                ("image", 39),
                                ("photo_dedication", 45),
                                ("table", 46),
                                ("unstyled_table", 46),
                                ("enhanced_table", 62),
                                ("list", 79),
                                ("links", 86),
                                ("questionanswers", 91),
                                ("columns", 100),
                                ("embedded_video", 103),
                                ("card", 114),
                                ("accordion", 59),
                                ("callout", 55),
                                ("grid", 125),
                                ("summary_timeline", 131),
                                ("detailed_timeline", 146),
                                ("hero_section", 151),
                                ("printable_section", 156),
                                ("quick_access_tiles", 173),
                            ]
                        ],
                        {"required": False},
                    ),
                    175: (
                        "wagtail.blocks.StructBlock",
                        [[("breadcrumb_title", 160), ("body", 174)]],
                        {},
                    ),
                    176: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("anchor_page", 175),
                                ("internal_page", 168),
                                ("external_url", 169),
                            ]
                        ],
                        {"max_num": 1, "min_num": 1},
                    ),
                    177: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable hover effect",
                            "required": False,
                        },
                    ),
                    178: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 157),
                                ("icon_direction", 158),
                                ("card_header", 159),
                                ("link", 176),
                                ("card_hover", 177),
                            ]
                        ],
                        {},
                    ),
                    179: (
                        "wagtail.blocks.ListBlock",
                        (178,),
                        {
                            "help_text": "Add up to 4 card tiles. They will display responsively based on screen size.",
                            "max_num": 4,
                            "min_num": 1,
                        },
                    ),
                    180: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("icon_header", 2),
                                ("section_header", 6),
                                ("heading", 10),
                                ("h2", 11),
                                ("h3", 12),
                                ("h4", 13),
                                ("paragraph", 14),
                                ("indented_paragraph", 15),
                                ("snippet", 16),
                                ("button", 29),
                                ("hr", 30),
                                ("iframe", 34),
                                ("alert", 36),
                                ("image", 39),
                                ("photo_dedication", 45),
                                ("table", 46),
                                ("unstyled_table", 46),
                                ("enhanced_table", 62),
                                ("list", 79),
                                ("links", 86),
                                ("questionanswers", 91),
                                ("columns", 100),
                                ("embedded_video", 103),
                                ("card", 114),
                                ("accordion", 59),
                                ("callout", 55),
                                ("grid", 125),
                                ("summary_timeline", 131),
                                ("detailed_timeline", 146),
                                ("hero_section", 151),
                                ("printable_section", 156),
                            ]
                        ],
                        {
                            "help_text": "Default content to display when no card is selected",
                            "required": False,
                        },
                    ),
                    181: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Display a back button when a card tile is selected (e.g. p/a, p/b). Hidden on the default view showing all card tiles. If checked, Back Button Text is required.",
                            "required": False,
                        },
                    ),
                    182: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text shown on the back button. Required if 'Show back button' is checked.",
                            "max_length": 64,
                            "required": False,
                        },
                    ),
                    183: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tiles", 179),
                                ("default_content", 180),
                                ("show_back_button", 181),
                                ("back_button_text", 182),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
