# Generated by Django 5.2.17 on 2026-10-09 14:28

"""
Data migration: updates the ``class`` property in the ``body`` field of List of Links
to ``style``.

0158 changed the EnhancedStandardPage ``links`` block from a bare list of
links to a struct defined by ListOfLinksBlock. Since ``class`` is a reserved word in
Python, the ``class`` property of links was renamed to ``style``. This migration script
rewrites saved content to match this change.
"""

import json

from django.db import migrations
from django.db.models import F, JSONField
from django.db.models.functions import Cast
from wagtail.blocks import StreamValue

LIST_OF_LINKS_BLOCK_TYPE = "links"
CHUNK_SIZE = 500


def change_list_of_links_class_to_style(node):
    """Changes list of links' class to style."""
    changed = False
    if isinstance(node, dict):
        if node.get("type") == LIST_OF_LINKS_BLOCK_TYPE and isinstance(
            node.get("value"), dict
        ):
            value = node["value"]
            if "class" in value:
                value["style"] = value.pop("class")
                changed = True
        for value in node.values():
            changed = change_list_of_links_class_to_style(value)[1] or changed
    elif isinstance(node, list):
        for value in node:
            changed = change_list_of_links_class_to_style(value)[1] or changed
    return node, changed


def change_list_of_links_style_to_class(node):
    """Inverse of ``change_list_of_links_class_to_style``; changes list of links' style to class."""
    changed = False
    if isinstance(node, dict):
        if node.get("type") == LIST_OF_LINKS_BLOCK_TYPE and isinstance(
            node.get("value"), dict
        ):
            value = node["value"]
            if "style" in value:
                value["class"] = value.pop("style")
                changed = True
        for value in node.values():
            changed = change_list_of_links_style_to_class(value)[1] or changed
    elif isinstance(node, list):
        for value in node:
            changed = change_list_of_links_style_to_class(value)[1] or changed
    return node, changed


def _transform_pages(apps, transform):
    EnhancedStandardPage = apps.get_model("home", "EnhancedStandardPage")
    stream_block = EnhancedStandardPage._meta.get_field("body").stream_block
    pages = EnhancedStandardPage.objects.annotate(
        raw_body=Cast(F("body"), JSONField())
    ).values_list("pk", "raw_body")
    for pk, raw_body in pages.iterator(chunk_size=CHUNK_SIZE):
        raw_body, changed = transform(raw_body)
        if changed:
            EnhancedStandardPage.objects.filter(pk=pk).update(
                body=StreamValue(stream_block, raw_body, is_lazy=True)
            )


def _transform_revisions(apps, transform):
    EnhancedStandardPage = apps.get_model("home", "EnhancedStandardPage")
    Revision = apps.get_model("wagtailcore", "Revision")
    page_ids = [
        str(pk) for pk in EnhancedStandardPage.objects.values_list("pk", flat=True)
    ]
    revisions = Revision.objects.filter(
        base_content_type__app_label="wagtailcore",
        base_content_type__model="page",
        object_id__in=page_ids,
    )
    buffer = []
    for revision in revisions.iterator(chunk_size=CHUNK_SIZE):
        body = revision.content.get("body")
        if not isinstance(body, str) or LIST_OF_LINKS_BLOCK_TYPE not in body:
            continue
        data, changed = transform(json.loads(body))
        if changed:
            revision.content["body"] = json.dumps(data)
            buffer.append(revision)
        if len(buffer) >= CHUNK_SIZE:
            Revision.objects.bulk_update(buffer, ["content"])
            buffer = []
    if buffer:
        Revision.objects.bulk_update(buffer, ["content"])


def forwards(apps, schema_editor):
    _transform_pages(apps, change_list_of_links_class_to_style)
    _transform_revisions(apps, change_list_of_links_class_to_style)


def backwards(apps, schema_editor):
    _transform_pages(apps, change_list_of_links_style_to_class)
    _transform_revisions(apps, change_list_of_links_style_to_class)


class Migration(migrations.Migration):
    dependencies = [("home", "0158_alter_directoryindex_body_and_more_pe")]

    operations = [migrations.RunPython(forwards, backwards)]
