# Generated by Django 5.2.8 on 2025-12-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DefinitionsQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_string", models.CharField(max_length=255, unique=True)),
                ("number_of_hits", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Definition Search Query",
                "verbose_name_plural": "Definition Search Queries",
            },
        ),
    ]
