# Generated by Django 5.2.8 on 2025-12-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="definitionsquery",
            name="number_of_hits",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="definitionsquery",
            name="query_string",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
