name: Deploy

on:
  push:
    branches:
      - development

jobs:
  deploy:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6

      - name: Set up Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          python3 --version
          pip3 --version

      - name: Apply Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd infra
          ./setup-tf-buckets.sh
          ./deploy.sh
          echo "bastion_public_ip=$(terraform output -raw bastion_public_ip)" >> $GITHUB_OUTPUT
          echo "database_endpoint=$(terraform output -raw database_endpoint)" >> $GITHUB_OUTPUT

      - name: Run Migrations
        env:
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          BASTION_HOST_IP: ${{ steps.tf_outputs.outputs.bastion_public_ip }}
          DATABASE_HOSTNAME: ${{ steps.tf_outputs.outputs.database_endpoint }}
        run: |
          cd website
          ssh -L 5432:${DATABASE_HOSTNAME}:5432 -N -i .ssh/id_rsa ubuntu@${BASTION_HOST_IP} &
          pip3 install -r requirements.txt
          export DATABASE_URL="postgresql://admin:${DATABASE_PASSWORD}@localhost:5432/postgres"
          python3 manage.py migrate

      - name: Manually Deploy ECS Task (Post-Migration)
        run: |
          aws ecs update-service \
            --cluster website-cluster \
            --service website-service \
            --desired-count 1 \
            --region us-east-1
