name: PRODUCTION Deploy

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to deploy'
        required: true
        type: string

jobs:
  production-deploy:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 45

    steps:

      - name: Set Environment
        id: set_env
        run: |
          echo "ENVIRONMENT=production" >> $GITHUB_ENV

      - name: Checkout specific commit
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - name: Configure AWS credentials from Prod account
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-workflow-deployer
          aws-region: us-east-1

      - name: Verify AWS Deployer Role (Poll for Policy Attachment)
        run: |
          while true; do
            if ! ATTACHED_POLICIES=$(aws iam list-attached-role-policies --role-name github-workflow-deployer 2>/dev/null); then
              echo "⏳ Waiting for IAM/role: github-workflow-deployer to be granted with policy: deployer-policy."
            else
              if echo "$ATTACHED_POLICIES" | jq -r '.["AttachedPolicies"][].PolicyName' | grep -q "^deployer-policy$"; then
                echo "✅ Policy change on user has propagated. Good to proceed with deployment."
                break
              fi
            fi
            sleep 15
          done

      - name: Set up Terraform
        uses: ./.github/actions/setup-terraform

      - name: Set up Python
        uses: ./.github/actions/setup-python

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Build USWDS
        run: |
          cd website
          make setup

      - name: Apply Terraform
        id: tf_outputs
        run: |
          cd infra
          ./setup-tf-buckets.sh

          export TF_VAR_github_sha=${{ github.event.inputs.commit_sha }}

          ./deploy.sh

          bastion_ip=$(terraform output -raw bastion_public_ip)
          echo "bastion_public_ip=${bastion_ip}" >> $GITHUB_OUTPUT

          db_endpoint=$(terraform output -raw database_endpoint)
          echo "database_endpoint=${db_endpoint}" >> $GITHUB_OUTPUT

          bucket_name=$(terraform output -raw bucket_name)
          echo "bucket_name=${bucket_name}" >> $GITHUB_OUTPUT

          deployment_notifications_topic_arn=$(terraform output -raw deployment_notifications_topic_arn)
          echo "deployment_notifications_topic_arn=${deployment_notifications_topic_arn}" >> $GITHUB_OUTPUT

      - name: Notify SNS of deployment start
        env:
          AWS_REGION: "us-east-1"
          SNS_TOPIC_ARN: ${{ steps.tf_outputs.outputs.deployment_notifications_topic_arn }}
        run: |
          timestamp=$(TZ="America/New_York" date "+%Y-%m-%d %H:%M:%S %Z")
          subject="Production deployment started by ${GITHUB_ACTOR} at $timestamp"
          commit_sha="${{ github.event.inputs.commit_sha || github.sha }}"
          message=$(echo -e "Deployment Notification STARTED\n\n\
          Environment: Production\n\
          Status:STARTED\n\
          Actor: ${GITHUB_ACTOR}\n\
          Time: ${timestamp}\n\
          Commit SHA: ${commit_sha}\n\n\
            —\n\
            This is an automated message from the CI/CD pipeline.")

          aws sns publish \
            --topic-arn "$SNS_TOPIC_ARN" \
            --subject "$subject" \
            --message "$message" \
            --region "$AWS_REGION"

      - name: Set up SSH Key
        run: |
          cd infra
          . ./load-secrets.sh
          cd ..
          echo "DOMAIN_NAME=$DOMAIN_NAME" >> $GITHUB_ENV
          echo "::add-mask::${DOMAIN_NAME}"
          echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> $GITHUB_ENV
          echo "::add-mask::${DATABASE_PASSWORD}"
          echo "DJANGO_SUPERUSER_PASSWORD=$DJANGO_SUPERUSER_PASSWORD" >> $GITHUB_ENV
          echo "::add-mask::${DJANGO_SUPERUSER_PASSWORD}"
          echo "SECRET_KEY=$SECRET_KEY" >> $GITHUB_ENV
          echo "::add-mask::${SECRET_KEY}"
          mkdir -p .ssh
          echo "${BASTION_PRIVATE_KEY}" | base64 --decode > .ssh/id_rsa
          chmod 600 .ssh/id_rsa

      - name: Perform Production Checks
        env:
          BASTION_HOST_IP: ${{ steps.tf_outputs.outputs.bastion_public_ip }}
          DATABASE_HOSTNAME: ${{ steps.tf_outputs.outputs.database_endpoint }}
          AWS_STORAGE_BUCKET_NAME: ${{ steps.tf_outputs.outputs.bucket_name }}
        run: |
          cd website
          # setup the tunnel so that we can run django commands into the env database
          set -e
          ssh-keyscan -H ${BASTION_HOST_IP} > /tmp/known_hosts
          ssh -o UserKnownHostsFile=/tmp/known_hosts -L 5432:${DATABASE_HOSTNAME} -N -i ../.ssh/id_rsa ubuntu@${BASTION_HOST_IP} &
          export DATABASE_URL="postgresql://master:${DATABASE_PASSWORD}@localhost:5432/postgres"
          make production-checks settings="app.settings.${ENVIRONMENT}"

      - name: Run Migrations
        env:
          BASTION_HOST_IP: ${{ steps.tf_outputs.outputs.bastion_public_ip }}
          DATABASE_HOSTNAME: ${{ steps.tf_outputs.outputs.database_endpoint }}
          AWS_STORAGE_BUCKET_NAME: ${{ steps.tf_outputs.outputs.bucket_name }}
        run: |
          cd website
          set -e

          if [ -z "${DJANGO_SUPERUSER_PASSWORD}" ]; then
            echo "ERROR: DJANGO_SUPERUSER_PASSWORD is not set or empty."
            exit 1
          fi

          ssh-keyscan -H ${BASTION_HOST_IP} > /tmp/known_hosts
          ssh -o UserKnownHostsFile=/tmp/known_hosts -L 5432:${DATABASE_HOSTNAME} -N -i ../.ssh/id_rsa ubuntu@${BASTION_HOST_IP} &
          export DATABASE_URL="postgresql://master:${DATABASE_PASSWORD}@localhost:5432/postgres"
          make migrate
          make superuser settings="app.settings.${ENVIRONMENT}" password=${DJANGO_SUPERUSER_PASSWORD} || echo "user already exists, skipping"
          make preregisterusers settings="app.settings.${ENVIRONMENT}"
          make preregistersuperusers settings="app.settings.${ENVIRONMENT}"
          make setupwagtaillroles settings="app.settings.${ENVIRONMENT}"
          make updateindex settings="app.settings.${ENVIRONMENT}"
          make cmd c="python manage.py update_search" settings="app.settings.${ENVIRONMENT}"
          make setupses settings="app.settings.${ENVIRONMENT}"
          make updatepages settings="app.settings.${ENVIRONMENT}"

      - name: Manually Deploy ECS Task (Post-Migration)
        run: |
          taskArn=$(aws ecs list-task-definitions \
            --family-prefix "${ENVIRONMENT}-website-tasks" \
            --sort DESC \
            --region us-east-1 \
            --query 'taskDefinitionArns[0]' \
            --output text
          )

          # Set desired count for production
          desired_count=2

          aws ecs update-service \
            --cluster "${ENVIRONMENT}-website-cluster" \
            --service "${ENVIRONMENT}-website-service" \
            --task-definition "${taskArn}" \
            --desired-count "${desired_count}" \
            --force-new-deployment \
            --region us-east-1

      - name: Wait for ECS Service to Stabilize
        run: |
          echo "Waiting for ECS service to stabilize..."
          aws ecs wait services-stable \
            --cluster "${ENVIRONMENT}-website-cluster" \
            --services "${ENVIRONMENT}-website-service" \
            --region us-east-1

      - name: Terminate Bastion Host
        run: |
          cd infra
          ./disable-bastion-host.sh

      - name: Invalidate CloudFront Distribution
        run: |
          # Get the CloudFront distribution ID for the environment
          distribution_id=$(aws cloudfront list-distributions \
            --query "DistributionList.Items[?contains(Origins.Items[0].DomainName, '${ENVIRONMENT}')].Id" \
            --output text)

          if [ -z "$distribution_id" ]; then
            echo "Error: Could not find CloudFront distribution for environment ${ENVIRONMENT}"
            exit 1
          fi

          echo "Invalidating CloudFront distribution: $distribution_id"
          aws cloudfront create-invalidation \
            --distribution-id "$distribution_id" \
            --paths "/*"

      - name: Cleanup Policy Attachment
        if: always() # Always runs, even if deployment fails
        run: |
          echo "Detaching deployer policy as a cleanup step..."
            aws iam detach-role-policy \
            --role-name github-workflow-deployer \
            --policy-arn arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:policy/deployer-policy || echo "Policy was not attached or already detached."
          echo "... Completed."

      # - name: Deploy to Training Environment
      #   run: |
      #     git config user.name "GitHub Actions"
      #     git config user.email "github-actions@github.com"
      #     git tag train
      #     git push --force origin train

      - name: Notify SNS of deployment outcome
        if: always()
        env:
          AWS_REGION: "us-east-1"
          SNS_TOPIC_ARN: ${{ steps.tf_outputs.outputs.deployment_notifications_topic_arn }}
        run: |
          # 1. Set status based on the job's outcome
          if [[ "${{ job.status }}" == "success" ]]; then
            STATUS="SUCCEEDED"
          else
            STATUS="FAILED"
          fi

          # 2. Prepare notification content
          timestamp=$(TZ="America/New_York" date "+%Y-%m-%d %H:%M:%S %Z")
          subject="Production deployment $STATUS by ${GITHUB_ACTOR} at $timestamp"
          commit_sha="${{ github.event.inputs.commit_sha || github.sha }}"
          message=$(echo -e "Deployment Notification $STATUS\n\n\
          Environment: Production\n\
          Status: $STATUS\n\
          Actor: ${GITHUB_ACTOR}\n\
          Time: ${timestamp}\n\
          Commit SHA: ${commit_sha}\n\n\
            —\n\
            This is an automated message from the CI/CD pipeline.")

          # 3. Publish to SNS
          aws sns publish \
            --topic-arn "$SNS_TOPIC_ARN" \
            --subject "$subject" \
            --message "$message" \
            --region "$AWS_REGION"
