name: Run all pull requests checks

on:
    push:
        branches:
          - main
    pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: ./.github/actions/setup-python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Run pre-commit hooks
      run: pre-commit run --all-files

    - name: Run Unit Tests
      run: |
        cd website
        set -e
        make setup
        make pytest
