name: QA Destroy

on:
  push:
    tags:
      - 'qa-destroy'
  workflow_dispatch:

jobs:
  destroy:
    environment: qa
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - name: Set Environment
        id: set_env
        run: |
          echo "ENVIRONMENT=qa" >> $GITHUB_ENV
      - name: Checkout qa tag
        uses: actions/checkout@v7
        with:
          ref: qa # Always check out the qa tag

      - name: Set up Terraform
        uses: ./.github/actions/setup-terraform

      - name: Apply Terraform destructive plan
        id: tf_outputs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd infra
          echo "Y" | ./destroy.sh

      - name: Reset qa branch to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin main
          git push origin origin/main:refs/heads/qa --force
